### ISSUE TITLE
Clicking on the Upper Screen puts input on the Bottom Screen (Latest Builds on Github)

### ISSUE THREAD

**Issue by Priestyle** [Arisotura/melonDS#1010]
Hi, this issue is for the latest build on github. So whenever I click on the upper-half of the screen of MelonDS window, the input goes to the bottom-half of the screen. As an example, for games like Pokemon HeartGold & SoulSilver, clicking on the top-half of the screen makes it touch the menu buttons on the lower screen. This didn't happen on the latest stable release (9.1) and previous builds from the official website. Calibrating the touchscreen didn't help.

**Comment by RSDuck** [comment]
which screen settings do you use?

**Comment by Priestyle** [comment]
Video Settings:
![20210222101229_melonDS_UWUoHIJUfU](https://user-images.githubusercontent.com/52426313/108645618-cae95c00-74f6-11eb-9df0-77df984fd224.png)

Screen Size: 1x
Screen Rotation: 0°
Screen Gap: 0 px
Screen Layout: Natural
Screen Sizing: Even
Aspect Ratio: Top 4:3 (Native) & Bottom 4:3 (Native)
Screen Filtering: ON
Show OSD: ON

(I'm not sure if this was what you were talking about)
These settings seem to be the same with the previous builds that didn't have the problem.

**Comment by RSDuck** [comment]
hm I can't reproduce your issue

**Comment by RSDuck** [comment]
ah I can reproduce it now

**Comment by Priestyle** [comment]
Also, I just tried switching to OpenGL to see if it fixes the problem but as soon as I click on OpenGL, melonds crashes. This is, again, an issue on the latest build from github, not the stable release from the website.

**Comment by RSDuck** [comment]
you're using the builds of https://github.com/Arisotura/melonDS/pull/1009 aren't you?

**Comment by Priestyle** [comment]
Yes, I'm using that build

**Comment by RSDuck** [comment]
I doubt the touchscreen issue is related, though the crashing with the OpenGL renderer probably is. Next time please mention this right from the start.

**Comment by Priestyle** [comment]
Okay, sorry haha
