### ISSUE TITLE
Better place for/hide timewarp.mln?

### ISSUE THREAD

**Issue by Tatsh** [Arisotura/melonDS#1025]
https://github.com/Arisotura/melonDS/blob/6a3aa551da43569e9e5d9b3f5b5ceaf0008bb5bf/src/frontend/Util_ROM.cpp#L654

This path is relative and eventually hits `QFile::QFile()`. The behaviour is that when the app is run from the .desktop file on Linux, it writes to `~`. This is because the desktop file doesn't specify a path so `xdg-open` (or most things) will start in `~`. The [documentation](https://doc.qt.io/qt-5/qfile.html#setFileName) states:

>If the file name has no path or a relative path, the path used will be the application's current directory path at the time of the open() call.

Can this file go somewhere like `~/.local/share/melonDS` (`XDG_DATA_HOME`, Qt: `GenericDataLocation`) or similar? Or perhaps have `SaveState` call `Platform::OpenLocalFile()` instead of `Platform::OpenFile()`? I could add a new function to the `Platform` to save to `GenericDataLocation` if desired.

I can make a PR for this.

**Comment by RSDuck** [comment]
yeah it should be OpenLocalFile
