### ISSUE TITLE
[Feature Request] Frame step hotkey

### ISSUE THREAD

**Issue by Tatsuya79** [Arisotura/melonDS#1030]
It seems there's no "next frame" key at the moment.

We noticed there's some frames of lag when using the gl renderer in the libretro core that aren't there in software mode.
I was wondering if it was there in your source project or not, but I can't tell without frame step (keeping a direction pushed down then counting how many frame steps it takes to see a move on screen).

Thank you.

**Comment by dogtopus** [comment]
This could also be useful when TASing.

**Comment by Ryunam** [comment]
Yes, this would be extremely helpful for investigating the root of this pesky latency issue that started to appear in the libretro core a few months ago. On RetroArch we use two separate hotkeys for this purpose:
- P for pausing;
- K to advance emulation one frame at a time for each press.

**Comment by Spikestuff** [comment]
This is similar to #463 as a note since it's one of the features requested in that list.

**Comment by RSDuck** [comment]
fixed by #1119
