### ISSUE TITLE
Ubuntu 20.04 melonDS doesn’t work well with ffmpeg streaming

### ISSUE THREAD

**Issue by jianmingyong** [Arisotura/melonDS#1032]
melonds is doing something really odd that is killing my screen capture via ffmpeg x11grab.

My main purpose is to stream the emulator to youtube live. Just like how a normal person stream their game live.

melonds runs fine and smooth, but the stream will drop its frame to 3 fps... using the same exact configuration on desmume, citra and all other emulator doesn’t have the same issue.

(The stream starts to fail or disconnect the moment melonds is open without any game running)

I don’t see a high cpu usage at all but it seems like it does something to the screen captures making it impossible to stream online.

**Comment by nathanielcwm** [comment]
Does it also affect other screen capture software, like OBS?

**Comment by jianmingyong** [comment]
I am sorry about this, I just realized for some reason, running melonDS without sudo seemed to have some issues. (and its also laggy for some reason)

Don't know why I have to run this in root user... though as far as I like not to run in root user but well... I guess it is better than nothing.

**Comment by jianmingyong** [comment]
Edit 2: running in sudo doesn't load audio devices... :(
A brick wall from migrating desmume to melonDS...

**Comment by jianmingyong** [comment]
It seems I have to change the config for ffmpeg...
"-f pulse -i default" to "-f alsa -i default"
Welp, who knows getting from pulseaudio can be a huge gap stopper for melonDS
