### ISSUE TITLE
Allow to add the BIOS/firmware files via drag & drop

### ISSUE THREAD

**Issue by dfv54gdmsnsecfzsmfwhermkml** [Arisotura/melonDS#1033]
Hello,

for example I have these 3 files bios7.bin, bios9.bin, firmware.bin and I want to add it via drag & drop under "Emu settings" -> "DS-mode". It should also be possible to add all 3 files with one drag & drop action.

I use melonDS on Windows.

**Comment by Arisotura** [comment]
oo, that would be an interesting thing to add

**Comment by Arisotura** [comment]
er, this works by drag/dropping onto the textboxes themselves. not sure about drag/dropping multiple files onto something else, and not sure how to go about recognizing the files esp for DSi mode.

**Comment by sculpordwarfsuntea** [comment]
> not sure about drag/dropping multiple files onto something else, and not sure how to go about recognizing the files esp for DSi mode.

I have an idea. The idea is that for DS-Mode and DSi-Mode you only allow certain file names. Only if this file name is correct, melonDS can recognize it automatically and allows dragging and dropping of multiple files. Maybe as an additional help an internal checksum database is integrated in melonDS. 

Is this possible, if so can you create a report?

**Comment by RSDuck** [comment]
I mean there are some common filenames, but it's not really worth the hassle implementing this, because in the time spent learning how this feature works, you can also just enter your files like it's possible now.
