### ISSUE TITLE
Castlevania: OoE - Garbage Tiles Briefly Show During Some Fade Transitions

### ISSUE THREAD

**Issue by Awakened0** [Arisotura/melonDS#1035]
When transitioning between certain areas, garbage tiles show up for a frame or so during the fade transition. I tested on the Win64 0.9.1 build with both Software and OpenGL renderers. JIT and threaded software rendering were disabled.

![garbage tiles](https://user-images.githubusercontent.com/4565863/111259426-3bb2fe00-85f5-11eb-9b77-9f90f051c618.png)

After loading this save file, you can enter the door to the right, then when leaving the room you should see the garbage.

[Castlevania - Order of Ecclesia (USA) (En,Fr).zip](https://github.com/Arisotura/melonDS/files/6146270/Castlevania.-.Order.of.Ecclesia.USA.En.Fr.zip)

This may be related to https://github.com/Arisotura/melonDS/issues/92 .

**Comment by iamthelaw2041** [comment]
This is still an issue.

![Capture](https://user-images.githubusercontent.com/94656803/144743482-c10d9676-b40d-4a86-a636-f7957fbfd23f.PNG)

**Comment by Arisotura** [comment]
happens on hardware. it's hard to see, but I recorded it with my capture-card DS.

**Comment by iamthelaw2041** [comment]
@Arisotura Any idea why? I'm curious how the devs fucked up.

**Comment by RSDuck** [comment]
it's probably just some miscalculation where they thought the fadeout it would already be completed.

**Comment by Awakened0** [comment]
> happens on hardware. it's hard to see, but I recorded it with my capture-card DS.

Interesting. Thanks for confirming hardware accurate behavior!
