### ISSUE TITLE
Error compiling due "reg" its not a constant expression 

### ISSUE THREAD

**Issue by iWeaker4you** [Arisotura/melonDS#1037]
Every time I try to compile it I get this error, I am using Fedora with GCC 11.0

/home/linuxgeek/Descargas/melonDS/src/ARMJIT_x64/ARMJIT_Compiler.cpp: En la función miembro ‘void ARMJIT::Compiler::LoadReg(int, Gen::X64Reg)’:
/home/linuxgeek/Descargas/melonDS/src/ARMJIT_x64/ARMJIT_Compiler.cpp:470:59: **error**: ‘reg’ its not a constant expression
  470 |         MOV(32, R(nativeReg), MDisp(RCPU, offsetof(ARM, R[reg])));
      |                                                           ^~~
/home/linuxgeek/Descargas/melonDS/src/ARMJIT_x64/ARMJIT_Compiler.cpp:470:52: aviso: ‘offsetof’ within non-standard-layout type ‘ARM’ is conditionally-supported [-Winvalid-offsetof]
  470 |         MOV(32, R(nativeReg), MDisp(RCPU, offsetof(ARM, R[reg])));
      |                                                    ^
/home/linuxgeek/Descargas/melonDS/src/ARMJIT_x64/ARMJIT_Compiler.cpp: En la función miembro ‘void ARMJIT::Compiler::SaveReg(int, Gen::X64Reg)’:
/home/linuxgeek/Descargas/melonDS/src/ARMJIT_x64/ARMJIT_Compiler.cpp:477:41: **error**: ‘reg’ its not a constant expression
  477 |     MOV(32, MDisp(RCPU, offsetof(ARM, R[reg])), R(nativeReg));

**Comment by RSDuck** [comment]
can you tell me if this branch builds for you?
https://github.com/Arisotura/melonDS/tree/fix1037

**Comment by iWeaker4you** [comment]
@RSDuck Thank you, is working !!!!
