### ISSUE TITLE
Windows builds now requires libiconv-2.dll

### ISSUE THREAD

**Issue by DartPower** [Arisotura/melonDS#1038]
Windows builds now requires libiconv-2.dll
![image](https://user-images.githubusercontent.com/2005369/111975452-adb5a680-8b11-11eb-88b5-19d2e1dca490.png)
And im cant find the libiconv-2.dll for windows on other sites...

**Comment by DartPower** [comment]
Well im taken from
https://sourceforge.net/projects/mingw/files/MinGW/Base/libiconv/libiconv-1.14-3/
the dll and...
![image](https://user-images.githubusercontent.com/2005369/111979367-0ab35b80-8b16-11eb-9a9b-92e310cbdc2b.png)

**Comment by DartPower** [comment]
Taken from "C:\Program Files\Git\mingw64\bin\libiconv-2.dll"
And melonDS is now launching.
Also please fix this in next builds pls

**Comment by RSDuck** [comment]
which builds? Builds you made yourself or the builds from the CI? And static builds are dynamic builds?

**Comment by WaluigiWare64** [comment]
This could be something related to this:
https://github.com/Arisotura/melonDS/commit/6b431a6664e6eb040729c648cffc5e31f655bbcf#diff-4429c645569353b5b9223beb6d6529d5c0def6c892fefe49511292c530c5f80cL90-R86
this change was that so it links against the system iconv instead of the Homebrew-provided iconv on macOS.

**Comment by RafaelTrepaUnCarballo** [comment]
@RSDuck For example, the builds I download from this [Github Actions](https://github.com/Arisotura/melonDS/actions?query=workflow%3A%22CMake+Build+(Windows+x86-64)%22)

**Comment by DartPower** [comment]
Yes, Im downloaded from Github CI (Actions)

**Comment by nathanielcwm** [comment]
Same here. Builds from CI now require that dll.

**Comment by nathanielcwm** [comment]
Here's a mirror since SourceForge was dying earlier:
[libiconv-2.zip](https://github.com/Arisotura/melonDS/files/6211009/libiconv-2.zip)

**Comment by WaluigiWare64** [comment]
This should have been fixed in https://github.com/Arisotura/melonDS/commit/7e6cf61b4c2d4e1cf21183447a6b086eb6113188.
