### ISSUE TITLE
[Feature Request] Option for "toggle fast-forward" in hotkeys

### ISSUE THREAD

**Issue by aksupper** [Arisotura/melonDS#1048]
I'm not experienced with code, but I think adding a toggle fast-forward in the next version isn't too much to ask for. Really convenient for Pokémon games and desmume has it too.

**Comment by RSDuck** [comment]
already exists. It's called toggle fps limit. It currently only toggles the frame limiter not audio sync which is a design flaw discussed elsewhere already.
