### ISSUE TITLE
Clueless Fashion needs to be added so it can get past the save screen

### ISSUE THREAD

**Issue by Kurayami7** [Arisotura/melonDS#1050]
The ROM was dumped recently but doesn't work in MelonDS. 

![clueless](https://user-images.githubusercontent.com/77198254/113464566-513f7900-9479-11eb-95f3-e7066e49b32a.PNG)

![Capture](https://user-images.githubusercontent.com/77198254/113464570-56042d00-9479-11eb-8376-945c958044fb.PNG)

**Comment by Arisotura** [comment]
I'd need to get my hands on the ROM to test it and figure out the correct savemem type

**Comment by Arisotura** [comment]
that being said, going from what you provided, appears:
the gamecode is CKLP
the ROM size is 64MB
the save type would be EEPROM 64K

correct me if I'm wrong?

**Comment by Arisotura** [comment]
I added a matching entry. lemme know if it works

**Comment by Kurayami7** [comment]
Unfortunately I'm still getting this screen with the latest build.

![Capture](https://user-images.githubusercontent.com/77198254/116086476-33b1a800-a6e3-11eb-8c69-6958fde7d447.PNG)

I won't link the ROM directly, obviously but check the description of this youtube video. You'll find it through there.

https://www.youtube.com/watch?v=D8ZUR2De15s&t=0s

**Comment by Arisotura** [comment]
it's issuing a 0B command, so it's either tiny EEPROM or FLASH

**Comment by Arisotura** [comment]
judging from the commands that are issued, this looks like a tiny EEPROM. let's see

**Comment by Arisotura** [comment]
I'll let you check the latest revision

**Comment by Kurayami7** [comment]
Fixed. Hold me closer, tiny EEPROM... 

![fashion](https://user-images.githubusercontent.com/77198254/116092577-44651c80-a6e9-11eb-81b1-706a92e2e08d.PNG)

**Comment by Arisotura** [comment]
bahahah
