### ISSUE TITLE
Bad sav length in Alpine Linux

### ISSUE THREAD

**Issue by antonialoytorrens** [Arisotura/melonDS#1056]
Loading nds firmware files boots and works perfectly.
However, when loading any ROM file, an error appears.
Please see the attached file for the full log [here](https://github.com/Arisotura/melonDS/files/6290931/log.txt).

Compiler: gcc10
Note: Alpine Linux uses musl instead of glibc.

**Comment by PoroCYon** [comment]
Is it possible to get any stack trace of the exception? (eg. by running it in gdb or so)

Also, is your system under memory pressure? NDS ROMs can sometimes be quite large.

**Comment by antonialoytorrens** [comment]
> Is it possible to get any stack trace of the exception? (eg. by running it in gdb or so)

Please, see here: [log.txt](https://github.com/Arisotura/melonDS/files/6291516/log.txt)

> Also, is your system under memory pressure? NDS ROMs can sometimes be quite large.

Yes, it seems it cannot boot _large_ (well, not so large in my case, 32 MB) NDS ROMs.
I booted a sample nds file and it worked.
However, that seems odd, because I dual-boot Alpine Linux and Ubuntu, and I can boot
the same 32 MB file on Ubuntu.

**Comment by WaluigiWare64** [comment]
1. Could you provide a backtrace? (Write `bt` after melonDS crashes.)
2. Which version of melonDS are you trying to run?

**Comment by antonialoytorrens** [comment]
>  1. Could you provide a backtrace? (Write `bt` after melonDS crashes.)

[backtrace.txt](https://github.com/Arisotura/melonDS/files/6291601/backtrace.txt)

>   2. Which version of melonDS are you trying to run?

Git version, from commit `d5dbef2c22f755ad82ec59e04948111797bc270a`
Running stable is irrelevant, as errors are the same.

<br/>
Seems curious, I have tried to compile and run the same program on another machine, with same ROM, and the error is completely different:<br/>

[log-backtrace_different-x86_64-machine.txt](https://github.com/Arisotura/melonDS/files/6291624/log-backtrace_different-x86_64-machine.txt)

In both cases seems that I can run games that come with no sound.

**Comment by RSDuck** [comment]
release builds of melonDS have symbols disabled, so can you try getting a stacktrace again with a debug build? Can you also try disabling the JIT recompiler (at compile time)? Maybe that makes a difference.

>  Seems curious, I have tried to compile and run the same program on another machine, and run same ROM (even smaller sized ones), and the error is completely different:

log-backtrace_different-x86_64-machine.txt

In both cases seems that I can run games that come with no sound, as all my sample nds files have no sound.

that crash looks like https://github.com/Arisotura/melonDS/issues/747

**Comment by antonialoytorrens** [comment]
> release builds of melonDS have symbols disabled, so can you try getting a stacktrace again with a debug build? Can you also try disabling the JIT recompiler (at compile time)? Maybe that makes a difference.

I was using the source code release from release [see in this link](https://github.com/Arisotura/melonDS/archive/refs/tags/0.9.1.tar.gz), not builds.

> > Seems curious, I have tried to compile and run the same program on another machine, and run same ROM (even smaller sized ones), and the error is completely different:
> 
> log-backtrace_different-x86_64-machine.txt
> 
> In both cases seems that I can run games that come with no sound, as all my sample nds files have no sound.
> 
> that crash looks like #747

It's quite the opposite of #747, because crashes occurred when I was using software rendering.
Then I switched it to opengl.
Seems it solves all issues on both of my machines.
Thank you!

**Comment by RSDuck** [comment]
> I was using the source code release from release see in this link, not builds.

I wasn't talking about CI-builds, but about builds in general.

> Then I switched it to opengl.
Seems it solves all issues on both of my machines.

that makes it even weirder, usually the OpenGL renderer is the one which causes problems.

**Comment by antonialoytorrens** [comment]
> > I was using the source code release from release see in this link, not builds.
> I wasn't talking about CI-builds, but about builds in general.

I pass `-DCMAKE_BUILD_TYPE=Debug` when building the package, is this what you meant?

> Can you also try disabling the JIT recompiler (at compile time)?

I'll do it now and I'll attach the log and backtrace here too.

**Comment by WaluigiWare64** [comment]
> I pass `-DCMAKE_BUILD_TYPE=Debug` when building the package, is this what you meant?
Yes.

**Comment by antonialoytorrens** [comment]
> that makes it even weirder, usually the OpenGL renderer is the one which causes problems.

I switched back to software rendering and it worked (weird).
However, I get this (using both software rendering and openGL):
[log.txt](https://github.com/Arisotura/melonDS/files/6291744/log.txt)

Which is also common to previous log files. It seems there's a bad save length (it's not a preloaded sav file, it's from scratch), as well as unknown arm7 and arm9 reads.
This prevents some games from loading sav files, even some of them from booting.

**Comment by WaluigiWare64** [comment]
> 
> 
> > that makes it even weirder, usually the OpenGL renderer is the one which causes problems.
> 
> I switched back to software rendering and it worked (weird).
> However, I get this (using both software rendering and openGL):
> [log.txt](https://github.com/Arisotura/melonDS/files/6291744/log.txt)
> 
> Which is also common to previous log files. It seems there's a bad save length (it's not a preloaded sav file, it's from scratch), as well as unknown arm7 and arm9 reads.
> This prevents some games from loading sav files, even some of them from booting.

There's no backtrace.

**Comment by antonialoytorrens** [comment]
> > > that makes it even weirder, usually the OpenGL renderer is the one which causes problems.
> > 
> > 
> > I switched back to software rendering and it worked (weird).
> > However, I get this (using both software rendering and openGL):
> > [log.txt](https://github.com/Arisotura/melonDS/files/6291744/log.txt)
> > Which is also common to previous log files. It seems there's a bad save length (it's not a preloaded sav file, it's from scratch), as well as unknown arm7 and arm9 reads.
> > This prevents some games from loading sav files, even some of them from booting.
> 
> There's no backtrace.

I cannot load the backtrace because no crash is reported.

**Comment by nergzd723** [comment]
Hey, all! I tried to launch melonDS on Alpine Linux too, now on ARM architecture.

I get a segmentation fault with the following error message(see log1.txt for details):
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
[log1.txt](https://github.com/Arisotura/melonDS/files/6294479/log1.txt)

I ran gdb, see backtrace in log2.txt.
[log2.txt](https://github.com/Arisotura/melonDS/files/6294483/log2.txt)

Also, the weird thing is that if I `touch` the .sav file and the .mch file, it starts working.

**Comment by PoroCYon** [comment]
Hmm, so I guess it manages to open the file but `fseek`/`ftell` are failing? Lemme try writing a patch for this...

**Comment by PoroCYon** [comment]
Ok [here](https://github.com/PoroCYon/melonDS/commit/9425f4a70da5c669a02d99666aded05369155e98)'s a patch, could you please try it?

```patch
diff --git a/src/NDSCart.cpp b/src/NDSCart.cpp
index 56a454a..f9dfd5e 100644
--- a/src/NDSCart.cpp
+++ b/src/NDSCart.cpp
@@ -127,8 +127,11 @@ void LoadSave(const char* path, u32 type)
     FILE* f = Platform::OpenFile(path, "rb");
     if (f)
     {
-        fseek(f, 0, SEEK_END);
-        SRAMLength = (u32)ftell(f);
+        if (fseek(f, 0, SEEK_END) == -1) goto new_sram;
+        long told = ftell(f);
+        if (told == -1) goto new_sram;
+
+        SRAMLength = (u32)told;
         SRAM = new u8[SRAMLength];
 
         fseek(f, 0, SEEK_SET);
@@ -138,6 +141,7 @@ void LoadSave(const char* path, u32 type)
     }
     else
     {
+    new_sram:
         if (type > 9) type = 0;
         int sramlen[] = {0, 512, 8192, 65536, 128*1024, 256*1024, 512*1024, 1024*1024, 8192*1024, 32768*1024};
         SRAMLength = sramlen[type];
```

**Comment by nergzd723** [comment]
Hey, I think that patch actually fixes it! Although I'm not sure if it's not biased by my workaround(I tried to get rid of it but I can't be sure if I completely did), can you, @antonialoytorrens , please double-check it works correctly?

**Comment by antonialoytorrens** [comment]
Sorry for the late response. I've tested the same games as before. Now the sav file is created without issues and I can load it correctly.

This patch fixes musl issue :)
Thank you very much for working on that.

**Comment by PoroCYon** [comment]
(I guess this can be closed now that cart refactor has been merged?)
