### ISSUE TITLE
Nanostray 2 (USA) - Title priority problem (OpenGL)

### ISSUE THREAD

**Issue by arnoldsecret** [Arisotura/melonDS#1057]
melonDS 0.9.1
![Untitled](https://user-images.githubusercontent.com/41223243/114325829-a445ba00-9b64-11eb-8273-8e4136ba0348.png)

What it should look like
![418048-nanostray-2-nintendo-ds-screenshot-title-screen](https://user-images.githubusercontent.com/41223243/114325863-c6d7d300-9b64-11eb-8ecf-3b78a46569e6.png)

Tested on a No-Intro ROM.

**Comment by Brankale** [comment]
Have you tried with builds in the Actions section? This is issue was present also in other games and it has already been fixed.

**Comment by arnoldsecret** [comment]
Latest action build fixes it, Closing this and https://github.com/Arisotura/melonDS/issues/1058.
