### ISSUE TITLE
Allow hiding mouse cursor while cursor is in game screen

### ISSUE THREAD

**Issue by KenDeep** [Arisotura/melonDS#1061]
I am currently playing with MelonDS with a graphic tablet and would like to hide the mouse cursor permanently as long as the cursor is inside the game window, however that is currently not possible. I think this would be a nice little feature that would increase enjoying NDS games on a PC through intended inputs (touch screen) by a lot.

**Comment by WaluigiWare64** [comment]
Already exists in latest master, however, it is not in a release yet.
