### ISSUE TITLE
Images Crash DSi Emulation

### ISSUE THREAD

**Issue by OnlyBMan** [Arisotura/melonDS#1064]
If one has a picture starred in the Camera app and it shows on the home screen, you will get a white screen upon firmware load, the emulator also hangs when trying to view any image on the DSi Camera App. Both work with NO$GBA so I know it's not the same issue where the DSi crashes on trying to take a picture because that also occurs with NO$GBA.

**Comment by Arisotura** [comment]
that's because taking a picture tries to change the camera resolution,
which relies on unsupported registers for now

**Comment by OnlyBMan** [comment]
This issue isn't about taking the picture though, only viewing it whether it be through the DSi Camera app, or when it loads on the home screen. When taking a picture, the DSi crashes while with this issue of viewing a picture the emulator just hangs

**Comment by Arisotura** [comment]
if even showing a picture is problematic... I'd be interested into seeing that.

**Comment by OnlyBMan** [comment]
Here are two nand images, one with the picture and one without on the homescreen, both have the image in the camera roll
[](https://drive.google.com/file/d/1REGhlmr4w7oCiPbgpYWDpFjI6NlWxkcK/view?usp=sharing)

**Comment by OnlyBMan** [comment]
I'm so sorry I didn't know I couldn't put them here, @Arisotura if you need them for testing, shoot me a dm on discord BMan#5577

**Comment by Arisotura** [comment]
well, that issue has been fixed, but for now it's in the nand_fatfs branch, which will be merged later
