### ISSUE TITLE
[Graphics] [Bug] 3D-managed screen doesn't show 2D content (bottom by default?)

### ISSUE THREAD

**Issue by CatsLover2006** [Arisotura/melonDS#1065]
Noticed in Mario Kart DS, tested on a Mid-2012 Unibody MacBook Pro on Catalina 10.15.7.
**EDIT:** Applies to both OpenGL and Software Renderer

**Comment by RSDuck** [comment]
screenshot?

Also did you try a build from latest source (see the CI for prebuilt ones)?

**Comment by CatsLover2006** [comment]
I tried from latest source and it worked.
Also I now have another issue to report upon building it (it's a prebuilt binaries issue, not a code issue)
