### ISSUE TITLE
[Build] No arm64 macOS build action

### ISSUE THREAD

**Issue by CatsLover2006** [Arisotura/melonDS#1066]
It's in the title. I just tested compiling from source and M1 can run a version built for it (although the x86_64 version crashes upon translation)
<img width="1065" alt="Screen Shot 2021-04-20 at 1 28 13 PM" src="https://user-images.githubusercontent.com/28163018/115453231-9c2cf080-a1dc-11eb-9649-5dbb2a1e88fc.png">

**Comment by CatsLover2006** [comment]
This also applies to the OpenGL renderer (which I thought was removed on M1 due to Rosetta 2, but whatever)

**Comment by CatsLover2006** [comment]
Here's some gameplay: https://www.youtube.com/watch?v=8D3oNF7j8yw

**Comment by WaluigiWare64** [comment]
Files did need to be changed, in fact, that's what I was working on a while ago.

See the melonDS blog.

**Comment by WaluigiWare64** [comment]
The build action is something I still need to work out.

GitHub provides only x86-64 macOS. (You can cross-compile but the issue is getting the libraries.)

**Comment by CatsLover2006** [comment]
I tried a naive solution on a test fork and it didn't work (it was pretty naive so I shouldn't have hoped it would work)

**Comment by CatsLover2006** [comment]
Pretty sure when [this](https://github.com/actions/virtual-environments/issues/2486) is resolved you could use a naive solution.

**Comment by WaluigiWare64** [comment]
I've just added an ARM64 macOS build action (thanks MacStadium!)
