### ISSUE TITLE
WarioWare DIY saving not fully functional in cart_refactor branch

### ISSUE THREAD

**Issue by Dionicio3** [Arisotura/melonDS#1068]
I noticed that anything related to DIY Music or Comics does not save at all. I believe WarioWare DIY saves are supposed to be 16MB, but melonDS is resizing it to 8MB.

**Comment by RSDuck** [comment]
> I believe WarioWare DIY saves are supposed to be 16MB, but melonDS is resizing it to 8MB

they aren't, see http://melonds.kuribo64.net/comments.php?id=141

I'm not sure if that part of the cart_refactor branch is ready for use yet.

**Comment by Arisotura** [comment]
I've seen 32MB savefiles, so dunno what the correct size should be, and how
to determine it.

that being said, I looked at that savefile I had, and there _is_ stuff past
the 8MB limit, so I guess it is indeed 16MB.

my bad. I need to fix that, I guess.

**Comment by Dionicio3** [comment]
From my understanding, 32MB save files are just what flashcarts generated. I have a DSTwo+, and the save file it generated for WWDIY was indeed 32MB.

**Comment by Arisotura** [comment]
I went with 8MB because that was what the size for Jam with the Band was -- atleast, no real way it could be bigger given where it starts in the ROM address space.

that being said, WarioWare's starts at a lower address, and a 16MB file would definitely fit in there.

**Comment by Dionicio3** [comment]
Hey, despite the file now being the correct size, WWDIY still isn't saving DIY Music or Comics still isn't actually saving.

**Comment by Arisotura** [comment]
so wait, is this bigger than 16MB or what

I'd need to get a cart and see how far this goes

**Comment by Dionicio3** [comment]
As far as I know they are indeed 16MB. I do own a WWDIY cart, if there's any way I can help you

**Comment by Arisotura** [comment]
I'd need to whip up a test ROM to see what the writable range is, but that needs a haxed DSi to run.

**Comment by Dionicio3** [comment]
I also own a hacked DSi, and I have all my data backed up to a save on a flashcart

**Comment by Arisotura** [comment]
so I might send you a test ROM

anyway I'm giving the whole record shito a try. I logged command B2 and it doesn't seem to ever go past the 16MB bound.

**Comment by Arisotura** [comment]
there's definitely something weird going on tho. I saved a record and it somehow became something else.

**Comment by Arisotura** [comment]
well this was definitely a mistake on my part, the write command was using a hardcoded 8MB for the SRAM window check instead of using SRAMLength like everything else.

saving shit in WarioWare should work correctly now. I tested the record thing and it seems to work right.

**Comment by Arisotura** [comment]
however I'd still be interested into running tests on a WarioWare cart, wanna see if it does have the same read-only 128K at the end as Jam with the Band, and the same ID data near the end of that

**Comment by Dionicio3** [comment]
Yeah I can still help with the tests if you want
