### ISSUE TITLE
Linux x64 build not executable

### ISSUE THREAD

**Issue by ItsRogueRen** [Arisotura/melonDS#1075]
The new build for x64 linux is a shared library file, not an executable of anything (its a .so file) attempting to run from a terminal after setting executable results in 
`cannot execute binary file: Exec format error`

**Comment by Arisotura** [comment]
isn't it just an issue of file permissions

**Comment by ItsRogueRen** [comment]
I did the `chmod +x` like usual with every pervious release to no avail

**Comment by PoroCYon** [comment]
It's erroring because it's an Aarch64 binary (hooray for `readelf`)... I think the archive context in the release got mixed up

**Comment by Sanaki** [comment]
Came to report the same. `file` shows `ELF 64-bit LSB shared object, ARM aarch64`.

**Comment by Arisotura** [comment]
well, my bad.

I reuploaded that file, should be okay now.

**Comment by Sanaki** [comment]
[This still contains the ARM version, unless you mean somewhere else.](https://github.com/Arisotura/melonDS/releases/download/0.9.2/melonDS_0.9.2_linux64.7z)

**Comment by PoroCYon** [comment]
[try this one, maybe?](http://melonds.kuribo64.net/comments.php?id=142)

**Comment by Arisotura** [comment]
you might need to force-refresh, due to cache shenanigans. I'm sure I uploaded a different file.

**Comment by Arisotura** [comment]
thanks for the heads-up. should be good now

**Comment by ItsRogueRen** [comment]
Its been 3 months and I still cannot get 0.9.2 to run on Linux (Pop!_OS 21.04)

Trying to run it from a terminal gives
`./melonDS: error while loading shared libraries: libslirp.so.0: cannot open shared object file: No such file or directory`

I am at a complete loss, this has gone from my go-to emulator to being completely unusable. Which sucks because, again, this was my go-to emulator for every DS game.

**Comment by PoroCYon** [comment]
If you're getting that error now, have you tried installing the libslirp package on your system?

**Comment by ItsRogueRen** [comment]
> If you're getting that error now, have you tried installing the libslirp package on your system?

Installing from apt doesn't give me anything

**Comment by PoroCYon** [comment]
By that, do you mean that apt can't find such package, or that installing it succeeds, but doesn't help the situation? (I think with apt, the package may be called `libslirp0` instead. At least on an Ubuntu 20.04 LTS server install where I just did an `apt search slirp` on.)

**Comment by ItsRogueRen** [comment]
> By that, do you mean that apt can't find such package, or that installing it succeeds, but doesn't help the situation? (I think with apt, the package may be called `libslirp0` instead. At least on an Ubuntu 20.04 LTS server install where I just did an `apt search slirp` on.)

Didn't find a package. The package name you gave is already installed

**Comment by PoroCYon** [comment]
Which `libslirp`-related files are you getting in your `/usr/lib`? This is what I have:

```
~$ ls /usr/lib/*slirp*
/usr/lib/libslirp.so  /usr/lib/libslirp.so.0  /usr/lib/libslirp.so.0.3.0
```

Also, can you give me the output of `ldd ./melonDS`?

**Comment by ItsRogueRen** [comment]
> Which `libslirp`-related files are you getting in your `/usr/lib`? This is what I have:
> 
> ```
> ~$ ls /usr/lib/*slirp*
> /usr/lib/libslirp.so  /usr/lib/libslirp.so.0  /usr/lib/libslirp.so.0.3.0
> ```
> 
> Also, can you give me the output of `ldd ./melonDS`?

`pop-pc@pop-os:~$ ls /usr/lib/*slirp*
ls: cannot access '/usr/lib/*slirp*': No such file or directory`

`ldd ./melonDS` is super long so I made a pastebin: https://pastebin.com/vHhNrsx3

**Comment by PoroCYon** [comment]
See line 5 of your pastebin: it found `libslirp` just fine it seems:

`libslirp.so.0 => /lib/x86_64-linux-gnu/libslirp.so.0 (0x00007fa7985db000)`

And yeah, `ls /usr/lib/*slirp*` doesn't work due to debianisms, so you need to do `ls /usr/lib/x86_64-linux-gnu/*slirp*` instead. But we now know where your libslirp lives so that's not needed anymore.

So uh. Why is it even saying it can't find libslirp when ldd can find it just fine? Clearly there's something weird with your setup.

**Comment by ItsRogueRen** [comment]
> See line 5 of your pastebin: it found `libslirp` just fine it seems:
> 
> `libslirp.so.0 => /lib/x86_64-linux-gnu/libslirp.so.0 (0x00007fa7985db000)`
> 
> And yeah, `ls /usr/lib/*slirp*` doesn't work due to debianisms, so you need to do `ls /usr/lib/x86_64-linux-gnu/*slirp*` instead. But we now know where your libslirp lives so that's not needed anymore.
> 
> So uh. Why is it even saying it can't find libslirp when ldd can find it just fine? Clearly there's something weird with your setup.

I have no idea, I somehow manage to have the weirdest tech issues but my existing (I've managed to completely brick a Windows install 3 times in a row)

`pop-pc@pop-os:~$ ls /usr/lib/x86_64-linux-gnu/*slirp*
/usr/lib/x86_64-linux-gnu/libslirp.so    /usr/lib/x86_64-linux-gnu/libslirp.so.0.2.3
/usr/lib/x86_64-linux-gnu/libslirp.so.0`

**Comment by PoroCYon** [comment]
Ok so as a final try:

* What's the output of `echo $LD_LIBRARY_PATH`
* Are there any libslirp library files elsewhere in some of those directories listed in the above output, or in the directory where your melonDS binary resides, etc.?

**Comment by ItsRogueRen** [comment]
> Ok so as a final try:
> 
>     * What's the output of `echo $LD_LIBRARY_PATH`
> 
>     * Are there any libslirp library files elsewhere in some of those directories listed in the above output, or in the directory where your melonDS binary resides, etc.?

Output of `echo $LD_LIBRARY_PATH` is blank

And I have no idea, I never had this happen until 0.9.2

**Comment by PoroCYon** [comment]
Try `LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ ./melonDS`.

If that doesn't work, I don't know either ¯\_(ツ)_/¯.

**Comment by ItsRogueRen** [comment]
> LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ ./melonDS

`bash: ./melonDS: Is a directory` is all I get

**Comment by PoroCYon** [comment]
... then you're running it in the wrong directory.

**Comment by ItsRogueRen** [comment]
> ... then you're running it in the wrong directory.
> 
> EDIT: as in, your current directory is one that has a subfolder called `melonDS`. Trying to execute that as a program will not go well.

ok running that in the folder where melonDS is runs the emulator. I am EXTREMELY confused

**Comment by PoroCYon** [comment]
Well if it works, that's good I guess.

But there's clearly something wrong with your setup. `LD_LIBRARY_PATH` is the envvar used to specify in which directories .so files can be found. If Debian-based distros put them all in `/usr/lib/x86_64-linux-gnu` but that's not in the default search list, something is Very Wrong (and I'm not going to figure out what, nor help you with it. Also partly because it's 5 AM here by now, so I realy need to go to bed)

Either way, you can try working around this by adding `export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"` to your `~/.profile`. This fix is applied next time you log in. If you don't want to log out right now, you can run `export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"` in every terminal you open/use to run melonDS. Then running just `./melonDS` should work.

Good night.

**Comment by ItsRogueRen** [comment]
> Well if it works, that's good I guess.
> 
> But there's clearly something wrong with your setup. `LD_LIBRARY_PATH` is the envvar used to specify in which directories .so files can be found. If Debian-based distros put them all in `/usr/lib/x86_64-linux-gnu` but that's not in the default search list, something is Very Wrong (and I'm not going to figure out what, nor help you with it. Also partly because it's 5 AM here by now, so I realy need to go to bed)
> 
> Either way, you can try working around this by adding `export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"` to your `~/.profile`. This fix is applied next time you log in. If you don't want to log out right now, you can run `export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"` in every terminal you open/use to run melonDS. Then running just `./melonDS` should work.
> 
> Good night/morning.

Appreciate the help, and this might have indirectly helped me with a few WINE issues I've been having so I'll look into if something's wrong with my defult search list
