### ISSUE TITLE
Emu settings are missing in melonDS 0.9.2

### ISSUE THREAD

**Issue by HilbertIdeals5** [Arisotura/melonDS#1077]
I'm using the 64-bit stable build of melonDS on macOS Big Sur 11.3, running in Rosetta.

When I clicked on Config to open the settings and switch to the DSi firmware, the "Emu settings" option was missing.
Here's what it looks like in melonDS 0.9.2:
<img width="425" alt="Screen Shot 2021-04-27 at 7 45 21 AM" src="https://user-images.githubusercontent.com/63978875/116236485-1e616b80-a72d-11eb-9f14-6f5b1126c4cd.png">
Here's what it looked like in melonDS 0.9.1:
<img width="425" alt="Screen Shot 2021-04-27 at 7 44 48 AM" src="https://user-images.githubusercontent.com/63978875/116236525-27ead380-a72d-11eb-853d-a5b7885ca7b4.png">

Otherwise the emulation is fine. What happened?

**Comment by Arisotura** [comment]
what. how is that even possible?

(I don't actually know. waiting for the Mac folks to get back on this. on Windows the menu is fine)

**Comment by HilbertIdeals5** [comment]
Actually, I just accidentally found out the Emu settings were under melonDS > Preferences..., so the settings are still there :D

**Comment by nadiaholmquist** [comment]
Qt wants to automatically map a menu entry to the Preferences item in the app menu, as that's where it's always supposed to be - it was picking up cheat settings which seemed rather unintuitive, so I made it the "primary" settings window instead.

**Comment by Arisotura** [comment]
we put up a new Mac build that doesn't do that kind of stupid shit

we might rework the settings dialogs later, but for now, this will cover this kind of issue

**Comment by WaluigiWare64** [comment]
I think this is fixed.
