### ISSUE TITLE
MelonDS 0.9.2 crashes with when selecting opengl

### ISSUE THREAD

**Issue by Felipefpl** [Arisotura/melonDS#1078]
Win7 x64 and (UNFORTUNATELY) intel hd 2000 here, i'm using the latest drivers. Other emus dont crash here.

**Comment by RSDuck** [comment]
any other other information? GPU, OS, etc.?

**Comment by WaluigiWare64** [comment]
Did it crash on 0.9.1?

**Comment by WaluigiWare64** [comment]
Just saw your edit, on Windows the driver supports up til OpenGL 3.1, whereas on macOS and Linux, the drivers support up til OpenGL 3.3.

melonDS requires a minimum of OpenGL 3.2.

**Comment by Felipefpl** [comment]
@WaluigiWare64 

I see, thanks for the reply. I guess i'll have to stick only with desmume then.

**Comment by WaluigiWare64** [comment]
Yep.
Your only other option is to stick to the software renderer, or use a Linux distro.
