### ISSUE TITLE
Glitch in Pokemon Heart Gold

### ISSUE THREAD

**Issue by nonsio280** [Arisotura/melonDS#1082]
I'm using Ubuntu 20.04 and this version of MelonDS
https://github.com/Arisotura/melonDS/tree/0a3a2ad00909fa14f6ab85229b94b17ff257fa5b

To trigger the glitch you have to
1) Start battling (I tested only battles with trainers, but it might glitch also with wild pokemon)
2) Get one pokemon in the party paralized, and don't let it faint
3) Win the battle

After the battle the pokemon should still be paralized, but it isn't.

**Comment by RSDuck** [comment]
can you try making a savefile just before some trainer who uses paralysing moves and give it to us, so we can reproduce it?

**Comment by nonsio280** [comment]
Just discovered that this isn't a glitch, it's just Celebi's ability. Sorry about that, I'm closing
