### ISSUE TITLE
Power Rangers Go-Busters (Korea) doesn't get past the first screen

### ISSUE THREAD

**Issue by Kurayami7** [Arisotura/melonDS#1084]
I can't read Korean but It might be something to do with save data? Probably just missing from the database or something. 

![Capture](https://user-images.githubusercontent.com/77198254/116728910-de023600-aa29-11eb-8454-30087f3f63ec.PNG)

**Comment by Arisotura** [comment]
try the latest revision, just addressed that one

**Comment by Kurayami7** [comment]
This is the latest version, right? It's the one I'm using and I still can't get past the screen in Power Rangers. 

![Capture](https://user-images.githubusercontent.com/77198254/116737454-992fcc80-aa34-11eb-8771-3dd68a2071ae.PNG)

**Comment by Arisotura** [comment]
it's weird because I thought I had explicitly fixed that, I even remember testing that particular game...

**Comment by Arisotura** [comment]
o wait that was the Japanese version

**Comment by Kurayami7** [comment]
Yeah Korea isn't part of Japan anymore. Not to get political.

**Comment by Arisotura** [comment]
well, I don't have the Korean version, what is the gamecode?

**Comment by Kurayami7** [comment]
![Capture](https://user-images.githubusercontent.com/77198254/116739164-b5346d80-aa36-11eb-8db0-9ab16b6b002f.PNG)

https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=z049

**Comment by Arisotura** [comment]
thanks

try the latest revision? I added the entry

**Comment by Kurayami7** [comment]
Power rangers is fixed. While we're here could you add Around the World in 80 Days & Fishdom (Germany) (Fr,De)? Same deal.

![Capture](https://user-images.githubusercontent.com/77198254/116740747-c7171000-aa38-11eb-96e5-d0fdb753b62e.PNG)

![Capture2](https://user-images.githubusercontent.com/77198254/116740856-e877fc00-aa38-11eb-9dfb-f22ff11d2a49.PNG)

https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=6475

**Comment by Arisotura** [comment]
I'll have to test that one to see what the savemem type is

**Comment by Kurayami7** [comment]
Sure, then I'll close this.

**Comment by Kurayami7** [comment]
Fixed. Thanks for those. I'll try and find something more interesting for my next issue report.

**Comment by Arisotura** [comment]
> 
> 
> Yeah Korea isn't part of Japan anymore. Not to get political.

for the record, I just saw the screenshot and thought "wait, I already saw that screen", that's all. I may not be too got at geography but not to this point.
