### ISSUE TITLE
Click-drag issues with DSi touch screen, action jumps to bottom-right corner if it crosses other boundaries.

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [Arisotura/melonDS#1087]
Hi-hi-- first, just want to express gratitude for how amazing melonDS' DSi compatibility is, and in _so short_ a timespan, my goodness. Having an absolute blast, especially being able to hear such crisp audio, finally.

So far, really, the only one big issue seems to be something involving the DSi touch screen! If you click and drag around on the touchscreen, and just so happen to, say, go a pixel too high, so you're crossing into the other DSi screen, the focus of your touch goes haywire and thinks it's in the bottom-right corner of the screen, instead! On no$gba, this action is read as simply staying as close to the corresponding edge of the touch screen. If you happen to be playing in windowed mode, and the window is shaped to fit the boundaries of the touch screen that _aren't_ touching the other DSi screen, you're not likely to run into other problems along that axis. HOWEVER, if you're in full-screen mode, moving a pixel off the touch screen in those directions will also send you to the bottom-right corner of the screen. Same with crossing too far down-- if you go to the bottom-left, it will send you to the bottom-right.

[Here's a video I took to describe the problem by showing you footage from no$gba and melonDS.](https://www.youtube.com/watch?v=6fxndT7rtD8)

This is a HUGE issue on, say, a game like X-SCAPE, which depends on you dragging your cursor like crazy to every extremity of the touch pad. Hope this is of help, thank you so much for all your hard work, and looking forward to doing graceful donuts in the vector-world of the early-8000s. :  ) All the best!

**Comment by Arisotura** [comment]
I recall touchscreen input working fine, who broke it? blarg
