### ISSUE TITLE
Cartridge Construction Kit (World) (v1.22) (Unl) hangs after the opening screen

### ISSUE THREAD

**Issue by Kurayami7** [Arisotura/melonDS#1093]
Shows this then hangs on a white screen. Also tested in Desmume and in that emulator is just hangs instantly and never shows anything. 

![Capture](https://user-images.githubusercontent.com/77198254/116881424-96b4b900-ac66-11eb-9163-19a7b34c623a.PNG)

No Intro page with more info.

https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=z052

**Comment by Arisotura** [comment]
this ROM seems to require a specific cart to function, but it's atleast failing gracefully on hardware, so, something worth looking into

also: is this a 'Cartridge Construction Kit' (whatever that is) or a media player???

**Comment by Kurayami7** [comment]
Yeah to be honest I'm not really sure what it is. 

![20190310_053723_z052_boxart1](https://user-images.githubusercontent.com/77198254/116895517-a20fe080-ac76-11eb-9085-150b4555faf7.jpg)

**Comment by Arisotura** [comment]
weird.

regardless, seems the ARM7 is shitting itself??

**Comment by Arisotura** [comment]
more on this: the ARM7 shits itself because it tries to jump to 0x080000C0, which doesn't go well

it tries to detect whether, presumably, a GBAMP is present, but that seems to go wrong for some reason

so, prolly some stupid shenanigans

noting that emulating this in its full extent would require me to own the required hardware, which I don't

**Comment by Arisotura** [comment]
problem is the kind of open-bus GBA slot values returned, the ROM expects these to have decayed to the point that each odd byte will be 7F or FE or FF, or almost. returning that kind of values makes it work correctly.

**Comment by Arisotura** [comment]
relatedly: that thing piqued my interest. I managed to snatch one off eBay, so we'll see how this goes :P 

in the meantime, the issue at hand here can be fixed relatively easily.

**Comment by Kurayami7** [comment]
Cheers.
