### ISSUE TITLE
GoPets - Vacation Island! (USA) has brief but massive framerate drop every time the game transitions between opening messages and title screen

### ISSUE THREAD

**Issue by ghost** [Arisotura/melonDS#1097]
Tested with all settings default. Every time the game transitions between these two screens the framerate drops massively and destroys the audio. Goes from 60 FPS to 40 or as low as 30. Tested a bunch of times and it differs but always happens. 

![Capture4](https://user-images.githubusercontent.com/77198254/117503284-14105e80-afc4-11eb-8659-066f2aa72bfa.PNG)

![Capture](https://user-images.githubusercontent.com/77198254/117503303-1d99c680-afc4-11eb-82f2-7f75edfe65b2.PNG)

![Capture3](https://user-images.githubusercontent.com/77198254/117503252-09ee6000-afc4-11eb-917d-398df0f01461.PNG)

![Capture2](https://user-images.githubusercontent.com/77198254/117503270-0d81e700-afc4-11eb-89ba-5d837a1cf4c7.PNG)

**Comment by iamthelaw2041** [comment]
This seems to be fixed. I don't get any slowdown at all.
