### ISSUE TITLE
how do I compile

### ISSUE THREAD

**Issue by dumsfr** [Arisotura/melonDS#1121]
cmake .. -G "MSYS Makefiles"
make -j$(nproc --all)
../tools/msys-dist.sh
 
i dont know how to do it

**Comment by RSDuck** [comment]
then use the builds from the CI: https://github.com/Arisotura/melonDS/runs/2754118505 the binaries are under Artefacts

**Comment by dumsfr** [comment]
> then use the builds from the CI: https://github.com/Arisotura/melonDS/runs/2754118505 the binaries are under Artefacts

idk what im looking at lmao im stupid

**Comment by RSDuck** [comment]
press Artefacts (in the top right corner) then melonDS, a download should appear.

**Comment by dumsfr** [comment]
but then what do i do after that

**Comment by dumsfr** [comment]
how do i get the gba slot though

**Comment by RSDuck** [comment]
open the gba rom first then open the ds rom.
