### ISSUE TITLE
Pokemon Mistery Gift

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [Arisotura/melonDS#1140]
I don't know if this is just me or if this happens to everyone, but when I try to use Mistery Gift in Pokemon Diamond/Pearl/Platinum,  the wifi emulation shows no reception and the feature just won't work.

As a side note, for exchanging Pokemon on those same games I have to use an instance of v0.9 and one of v0.4, since if I try to use two v0.9 none of them recognize each other and if I try to use two v0.4 connection crashes (the combination of the two versions works almost always if I remember to uncap the framerate in the v0.9 and I start every interaction from that one).

**Comment by RSDuck** [comment]
> I don't know if this is just me or if this happens to everyone, but when I try to use Mistery Gift in Pokemon Diamond/Pearl/Platinum, the wifi emulation shows no reception and the feature just won't work.

Are you sure you have the right DNS server setup/does it work on a real DS?

> As a side note, for exchanging Pokemon on those same games I have to use an instance of v0.9 and one of v0.4, since if I try to use two v0.9 none of them recognize each other and if I try to use two v0.4 connection crashes (the combination of the two versions works almost always if I remember to uncap the framerate in the v0.9 and I start every interaction from that one).

do you have mac randomisation enabled and frame limiter + audio sync disabled?

**Comment by l-l-l-l-l-l** [comment]
For the second thing, MAC randomization did the trick. Wonder why I missed that thing.
For the first thing, I don't have 2 real DS to try, just the one, and I didn't know that you needed to configure a server for regular game-to-game or non-CWF Wi-Fi MGs (of course you need to configure one for CWF MGs, but that's not what I'm trying).
As a side note, I can tell you that when I tried v0.9 to v0.4 MG sharing I soon got an "RX buffer full" (usually after a number of "received packet 0080 but it didn't pass the BSSID check").

**Comment by RSDuck** [comment]
ah I thought you were talking about mystery gift via wifi instead of one of those distribution cartridges.

**Comment by ElHave247** [comment]
If someone want any pokemon games on 2023 and get mistery gifts or any cwf content even in mistery dungeons games and definitivelly play any ds games online, just connect to wimmiffi put dns 167.86.108.126 and secondary 1.1.1.1 and you will be fine all works except tournaments (due to register in original web) and gts for that you need to use the other poke classic network DNS 178.62.43.212 and secondary 0.0.0.0 dont patch the rom, use a clean one, and just set up cwf settings.
