### ISSUE TITLE
Old save files no longer work.

### ISSUE THREAD

**Issue by bobhob314** [Arisotura/melonDS#1144]
My _ml1 files that I made roughly half a year ago no longer open. I get state load failed. Please help. I'm on Windows 10 and this fails on both 0.9.2 and 0.8.3.

```https://anonfiles.com/f0caV627ue/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml1
https://anonfiles.com/h1c9V12au5/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml2
https://anonfiles.com/j2c2V621uc/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml3
https://anonfiles.com/n2c8V029ue/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml4
https://anonfiles.com/l2caVe26u1/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_-_Copy_sav
https://anonfiles.com/V5c0V421u3/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml5
https://anonfiles.com/X7c8Va2cu0/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml6
https://anonfiles.com/Zbc8V52cua/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml7
https://anonfiles.com/b7dfVb2eu5/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_sav
https://anonfiles.com/d0d8Vf25u7/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_ml8
https://anonfiles.com/32gaV32bu6/Rune_Factory_2_A_Fantasy_Harvest_Moon_Undub_nds```

**Comment by Arisotura** [comment]
savestates made on older melonDS versions may not be compatible with newer versions, because the savestate format has evolved since then.

**Comment by bobhob314** [comment]
> savestates made on older melonDS versions may not be compatible with newer versions, because the savestate format has evolved since then.

@Arisotura I've tried on 0.8.3 and 0.9.2 as I stated above, which are the only two versions I've ever used.

**Comment by bobhob314** [comment]
@Arisotura Actually I tried 0.9.1 and it finally worked. Thanks for the hint on versions for states. It seems kind of not well-thought-out to have save files not be compatible between versions though. Hopefully that can be addressed in the future. In any case thanks for the support.

**Comment by RSDuck** [comment]
> It seems kind of not well-thought-out to have save files not be compatible between versions though. Hopefully that can be addressed in the future. In any case thanks for the support.

savestates contain internal emulator state which can change between versions, so as bad as it is, there's no way around it. If you want to reliably save game progress use in-game saves.

**Comment by bobhob314** [comment]
@RSDuck

> in-game saves

You mean just use the normal save features of the game? Do those saves get "saved into the .nds rom file"? So no matter what version of what emulator I open that .nds file with in the future, it should probably have the save still?

**Comment by RSDuck** [comment]
no, they're saved inside .sav files, but yes they will always be compatible. They're even compatible with other emulators (though sometimes you need to do some format converting) and can even be put onto real cartridges/read from real cartridges.

**Comment by Arisotura** [comment]
> 
> 
> @Arisotura Actually I tried 0.9.1 and it finally worked. Thanks for the hint on versions for states. It seems kind of not well-thought-out to have save files not be compatible between versions though. Hopefully that can be addressed in the future. In any case thanks for the support.

actually, that depends on the kind of changes that are made. savestates have a major/minor version scheme. sometimes we add state that, for older savestates, can be inferred from something else with little drawbacks, so we just increase the minor version and add code to handle older savestates. sometimes we add state that can't be inferred from what older savestates have, or we change the structure for one reason or another, and we end up needing to change the major version (and lose compatibility with older melonDS versions).

**Comment by Antiflex** [comment]
@Arisotura is it possible to edit a save state file made in 0.9.2 to make it work in 0.9.3 ?

**Comment by RSDuck** [comment]
no

**Comment by Antiflex** [comment]
damn
