### ISSUE TITLE
wifi: RX buffer full

### ISSUE THREAD

**Issue by orlp** [Arisotura/melonDS#1147]
While playing Pokemon Black 2, after a while the console constantly spits out the warning "wifi: RX buffer full". Worse, if this happens you can no longer save, attempting to do so soft hangs the game (the sound continues and NPC will keep moving in the background, but the save will never progress).

**Comment by RSDuck** [comment]
duplicate of #739

**Comment by orlp** [comment]
Oh, yes it is. My bad.
