### ISSUE TITLE
In-Game Cursor Glitching Out

### ISSUE THREAD

**Issue by FunElectric** [Arisotura/melonDS#1150]
Whenever I go nearby or outside one of the two screens while holding left-click, the in-game cursor would glitch out and go crazy.
I used Rhythm Heaven as an example, since it showcases my problem the best. On DeSmuME, for example, the cursor peacefully follows the mouse regardless of its position, so I assumed it's not an issue with my PC, but with the emulator.

_**I'm sorry if this problem has already been documented. I've made this Github account just now just to send this issue, so I'm really unfamiliar with the UI at the moment.**_ It's just a small, mildly infuriating problem, that just messes me up sometimes while playing my games. Here is a video showcasing the problem:

https://user-images.githubusercontent.com/87086653/124795556-d5156f80-df58-11eb-92c7-8c7ccc600f01.mp4

**Comment by WaluigiWare64** [comment]
Have you tried the latest builds off GitHub Artifacts?

**Comment by FunElectric** [comment]
> Have you tried the latest builds off GitHub Artifacts?

I'm unaware of what you're talking about, unfortunately, since this is my first time using Github.
The version of melonDS I am showcasing from the official site (version 0.9.2), which I thought was the latest. Could you please direct me to GitHub Artifact to test this version you're mentioning out?

**Comment by WaluigiWare64** [comment]
Go to the README on the main repository page, then click the OS you are using (for Windows you would click the "Windows x86-64" badge).
Then click the topmost entry in the list, then click the melonDS under the Artifact header.

**Comment by FunElectric** [comment]
> Go to the README on the main repository page, then click the OS you are using (for Windows you would click the "Windows x86-64" badge).
> Then click the topmost entry in the list, then click the melonDS under the Artifact header.

I am finding difficulties with step 6 (Windows), where MSYS just doesn't find "cmake" to be a command for some odd reason, even after installing the dependencies, so unless I get this fixed, I might be unable to try the version out.

**Comment by WaluigiWare64** [comment]
![image](https://user-images.githubusercontent.com/68647953/124806813-a09bb680-df4c-11eb-9c02-ee1a0025b10e.png)
Click this.

**Comment by FunElectric** [comment]
> ![image](https://user-images.githubusercontent.com/68647953/124806813-a09bb680-df4c-11eb-9c02-ee1a0025b10e.png)
> Click this.

I feel so stupid wasting so much time over-complicating myself. I'm sorry for the trouble!
But now that I managed to get the build, I can confirm that the bug I previously mentioned was fixed! Thank you so much for your help!

**Comment by WaluigiWare64** [comment]
I'm glad it works for you!
