### ISSUE TITLE
Fails to build Ubuntu Bionic Aarch64

### ISSUE THREAD

**Issue by theofficialgman** [Arisotura/melonDS#1151]
Build fails during the qt5 GUI fronted compilation

```
/src/frontend/qt_sdl/main.h:159:1: error: expected class-name before ‘{’ token
  159 | {
```

I've seen the buildservers which seem to be able to build just fine. Maybe something changed in newer qt5 versions?
Full log:https://pastebin.com/Rbnqz4xG
cmake output: below

```
-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-11 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pow in m
-- Looking for pow in m - found
-- The C compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-11 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc-11
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'epoxy'
--   Found epoxy, version 1.4.3
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Found Iconv: /usr/lib/aarch64-linux-gnu/libc.so  
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.14
-- Checking for module 'slirp'
--   Found slirp, version 4.1.0
-- Checking for module 'libarchive'
--   Found libarchive, version 3.2.2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/garrett/melonDS-master/melonDS/build
```

**Comment by RSDuck** [comment]
could it be possible that you don't have regular desktop OpenGL (as opposed to GL ES)? Because the reason it doesn't compile is that `QOpenGLFunctions_3_2_Core` isn't defined. If so this issue is related: #982.

**Comment by theofficialgman** [comment]
no, this is on switch l4t ubuntu
it has both opengl (up to 4.4) and openglES

**Comment by theofficialgman** [comment]
https://forum.qt.io/topic/107657/qopenglfunctions_3_2_core-problems-on-arm-platforms

only solution I've seen was to compile Qt5 from scratch...

**Comment by theofficialgman** [comment]
yes thats the case on ubuntu bionic arm64 qt5 packages as well... they built with `-opengl es` instead of `-opengl desktop`

**Comment by RSDuck** [comment]
> no, this is on nintendo switch L4T ubuntu bionic

it will run pretty badly on Switch anyway without all the optimisations from my port :D

**Comment by theofficialgman** [comment]
> > no, this is on nintendo switch L4T ubuntu bionic
> 
> it will run pretty badly on Switch anyway without all the optimisations from my port :D

yes I've run your port before on linux on switch as well. just wanted to see how many of those optimizations made it over

I guess I forgot that bionic arm64 qt5 is built with opengles and arm64 focal and newer use desktop GL... I previously built on ubuntu hirsute

**Comment by WaluigiWare64** [comment]
If you want you can try using the `opengl-es-renderer` branch... it's my (bad) attempt at adding OpenGL ES support to the melonDS OpenGL renderer. Note that it has some issues as I have no knowledge on this and have mainly searched and used the docs.

**Comment by theofficialgman** [comment]
> > no, this is on nintendo switch L4T ubuntu bionic
> 
> it will run pretty badly on Switch anyway without all the optimisations from my port :D

oh well looks like running your fork on linux is getting more difficult than a few months ago, lol. what is the DekoRenderer?

**Comment by RSDuck** [comment]
> oh well looks like running your fork on linux is getting more difficult than a few months ago, lol. what is the DekoRenderer?

I've abandoned just optimising the cpu renderers (which could then just be compiled on linux as well) in favour putting the work onto gpu. For rendering I'm not using OpenGL but deko3d which only runs on horizon and is more low level.

**Comment by theofficialgman** [comment]
> I've abandoned just optimising the cpu renderers (which could then just be compiled on linux as well) in favour putting the work onto gpu. For rendering I'm not using OpenGL but deko3d which only runs on horizon and is more low level.

ah well thats nice for the HOS homebrew schene. any chance of vulkan on linux or why you didn't use vulkan on switch?

**Comment by RSDuck** [comment]
> any chance of vulkan on linux or why you didn't use vulkan on switch?

There's no Vulkan on HOS, so that isn't an option, though I plan on porting everything over to OpenGL.

**Comment by theofficialgman** [comment]
just to confirm, it is because the arm64 qt5 packaged with ubuntu bionic and lower uses opengl es instead of opengl. it works fine once I get a qt5 version with opengl instead of opengles

for anyone else wanting to build on ubuntu bionic arm64 or armhf and their gpu supports opengl, you can use qt5.12 using opengl from this ppa: https://launchpad.net/~theofficialgman/+archive/ubuntu/opt-qt-5.12.0-bionic-arm
