### ISSUE TITLE
setup cheat codes nonexistent on apple silicon macs

### ISSUE THREAD

**Issue by crazynoob458** [Arisotura/melonDS#1153]
running non dev build on a apple silicon mac i cant seem to find the setup cheat code button
<img width="1440" alt="Screen Shot 2021-07-12 at 3 34 12 pm" src="https://user-images.githubusercontent.com/65052972/125236103-f23c9c00-e2d2-11eb-9b88-e2298f6290af.png">

**Comment by nadiaholmquist** [comment]
Should be fixed by af36d1002315fc90c79d8daf638f497faecf5005.

**Comment by crazynoob458** [comment]
oh thanks for the info
im too lazy to compile a version so...
