### ISSUE TITLE
Buggy Reshiram face on any render

### ISSUE THREAD

**Issue by H-Wifall** [Arisotura/melonDS#1166]
Noticed a glitch in the graphics of Pokemon BW2, if you notice Reshiram's left eye, it will be buggy even in the software render!
![image](https://user-images.githubusercontent.com/78131583/127402405-501f1c8f-7e27-4b65-8a66-cb1095a91541.png)
In OpenGL, the same thing happens!
![image](https://user-images.githubusercontent.com/78131583/127402467-185366f1-aad6-4aea-bf49-f7e95c2a6edb.png)
if you disable polygon splitting, it will be fixed while making everything else buggy
![image](https://user-images.githubusercontent.com/78131583/127402587-72a6b717-3b68-4f9d-aec4-881bfc01d73b.png)
and every issue disappears IF you both upscale in OpenGL and enable polygon splitting!
![image](https://user-images.githubusercontent.com/78131583/127402714-40015f79-9481-4498-9f32-d11b8a9b1281.png)
It's also buggy on Desmume. Probably some emulation-wide bug.

**Comment by poudink** [comment]
do you have a save file?

**Comment by H-Wifall** [comment]
I do, I can send it to you you through Discord if you want.

**Comment by Brankale** [comment]
it happens on real hardware too, so it's not a problem of the emulator
![hw](https://user-images.githubusercontent.com/45881310/127456749-d7f43df4-067a-4c85-bf50-2546d4f3a2c2.JPG)

**Comment by Arisotura** [comment]
well, then, you guess how this goes
