### ISSUE TITLE
DSI Firmware failing to boot in latest action release of MelonDS

### ISSUE THREAD

**Issue by Bonboon229** [Arisotura/melonDS#1169]
Exactly as the title says.
When trying to boot DSI firmware, it hangs on a white screen.
The FPS counter just hover's around 31-34 fps.
DS Firmware boots normally, as does loading games directly.

**Comment by RSDuck** [comment]
@DesperateProgrammer you broke this, I just bisected it :D

**Comment by DesperateProgrammer** [comment]
Let me setup an image that works on the old version and I'll check. Can't be much :-P
Iirc no fotos, no unlaunch must be present?

**Comment by RSDuck** [comment]
>  Iirc no fotos, no unlaunch must be present?

yep, I'm not sure about the photos (though I have a vague memory of something like that, so you're probaly right).

**Comment by DesperateProgrammer** [comment]
There is a second part to this issue I found and I am working on it. Need to get onto that with a fresh head. An error occures when writing to the second half of a 64k Page on NWRAM_A.

**Comment by NICOHACKER2021** [comment]
I hope this is fixed

**Comment by DesperateProgrammer** [comment]
The fixes are in the PullRequest. After someone reviewed it and I did not mess up, it is.

**Comment by Bonboon229** [comment]
Tested the changes, works now. I shall close the issue now.
