### ISSUE TITLE
Communication Error in Gen IV

### ISSUE THREAD

**Issue by getCursorsExe** [Arisotura/melonDS#1170]
You get a Communication Error in Gen IV Pokemon on RetroArch after you go to save screen. This doesn't happen in DeSmuME.

**Comment by RSDuck** [comment]
please first try to reproduce with regular melonDS. Otherwise create an issue here: https://github.com/libretro/melonDS/issues

Also more details.

**Comment by MojoJojoDojo** [comment]
Retroarch is missing libslirp integration so it will never work there.
Winpcap is out of the question as well lol.

**Comment by getCursorsExe** [comment]
I'm asking there because the RetroArch fork is not active very often, which forced me to create an issue here.

**Comment by RSDuck** [comment]
> I'm asking there because the RetroArch fork is not active very often, which forced me to create an issue here.

well that's their fault not ours.

**Comment by getCursorsExe** [comment]
> Retroarch is missing libslirp integration so it will never work there.
> Winpcap is out of the question as well lol.

**But the DeSmuME has no issues with this.**

**Comment by getCursorsExe** [comment]
Just closing this...

**Comment by RSDuck** [comment]
desmume has no wifi support at all (unless you count the hacky pcap stuff).
