### ISSUE TITLE
Pokémon Platinum Honey Tree's Clock

### ISSUE THREAD

**Issue by gpavelski** [Arisotura/melonDS#1178]
Hello,

Well, let me try to explain this.
Actually, in Gen IV Pokémon games in Sinnoh (Diamond & Pearl, Platinum), there is a mechanism for capturing some rare Pokémons slathering Honey in some special trees. 
The idea is simple: There are 21 trees spread around the continent, the player can slather honey on them. After this, a timer starts and, around 6 hours later (real-time), some Pokémon may appear and you can start a battle. After the battle, the tree resets, it is necessary to use another honey and wait for 6 hours for a new Pokémon.
After 24 hours, if the trees are left unchecked, the Honey disappear and the trees reset to the initial state.

Ok, for some reason, while playing it on MelonDS, there is some kind of issue with this clock. You may wait 6, 12, 24 hours, but no Pokémon appear, and even after 24 hours, the Honey is still there, but nothing happens.
When I tried this with the physical console, using the same ROM and the same save file as the emulator, it works.
For instance, if I slathered Honey around 3 o'clock and save the game and then shut down, around 9 o'clock I will see the tree shaking. But on MelonDS the tree does not shake.

According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Honey_Tree):
 _Changing the Nintendo DS's clock will have no impact on the Honey Tree's timer._ 

So, I don't know how exactly this mechanism is implemented in the Nintendo DS, but I wonder if there is a way to implement a similar function on MelonDS.

Thanks for the great job, I really enjoy this emulator.

**Comment by poudink** [comment]
If you do, disable it.

**Comment by gpavelski** [comment]
Yes, you are right. It works when you disable this option.

Thank you.
