### ISSUE TITLE
[Feature Request] add android gui

### ISSUE THREAD

**Issue by Yoshi9800** [Arisotura/melonDS#1191]
Android gui of melon ds emulator really good also has  Feature like per game ds mode selected
![Screenshot_20210824-225109_Google Play Store](https://user-images.githubusercontent.com/87396495/130718609-b9c38fbf-eda6-4bb0-9e04-e17d0070b3de.jpg)
![Screenshot_20210824-225114_Google Play Store](https://user-images.githubusercontent.com/87396495/130718615-0eedd891-85a6-46d9-8736-4db98401ce24.jpg)

**Comment by Gamemulatorer** [comment]
That's unofficial port of MelonDS.

**Comment by WaluigiWare64** [comment]
we don't develop or support the unofficial melonDS Android port.
