### ISSUE TITLE
Tapping non-functional on Surface Laptop 3 Touch-Screen

### ISSUE THREAD

**Issue by zurgeg** [Arisotura/melonDS#1203]
I decided to try some DS emulation on the Surface Laptop 3, for the most part it runs well, except for the fact that you need to tap and drag rather than just tap the touchscreen in order for it to register. 
Is there a fix? Thanks.

**Comment by RSDuck** [comment]
have you tried a [build from latest source](https://github.com/Arisotura/melonDS/suites/3613927323/artifacts/87315458)?

**Comment by zurgeg** [comment]
Nope, not yet

**Comment by zurgeg** [comment]
Oops, accidentally hit "close with comment"

**Comment by WaluigiWare64** [comment]
In the [FAQ](http://melonds.kuribo64.net/faq.php), scroll to the 'latest development builds' section.
