### ISSUE TITLE
melonDS crashing on load state

### ISSUE THREAD

**Issue by Nezteb** [Arisotura/melonDS#1213]
melonDS version: 0.9.2
OS version: macOS 10.15.7

Game is Pokemon SoulSilver acquired from here: *redacted* 

My save file: https://www.dropbox.com/s/7qgzut0utxrsefi/4781%20-%20Pokemon%20SoulSilver%20%28U%29%28Xenophobia%29.ml1

I've noticed this in a few other games. It seems inconsistent. Sometimes I'll save state, and then loading that same state later works fine. Other times, it immediately causes melonDS to crash.

Here is the Mac crash report: https://pastebin.com/raw/BGLU0giK

**Comment by WaluigiWare64** [comment]
try latest melonDS 0.9.3

**Comment by Nezteb** [comment]
Just installed 0.9.3 and still have the same issue with my 0.9.2 save file. I'm going to have to just restart the game and see if the newer saves have this problem or not. I'll report back later with results.

**Comment by Nezteb** [comment]
I tried three different games, trying different save state slots, verifying all of them, quitting the app, opening it again, and loading each of the save states. Thus far everything seems to work fine. I'll close this for now.
