### ISSUE TITLE
FTBFS on i686

### ISSUE THREAD

**Issue by abenson** [Arisotura/melonDS#1222]
The static assertion at https://github.com/Arisotura/melonDS/blob/master/src/teakra/src/test.h#L37 fails on i686. I'm wondering if its some kind of padding issue?  I'm looking through to see if there's anything that removing the static assertion would fail.

**Comment by RayyanAnsari** [comment]
teakra code is here: https://github.com/wwylele/teakra
the issue you are experiencing whilst compiling is this issue: https://github.com/wwylele/teakra/issues/34

**Comment by abenson** [comment]
I appreciate it!
