### ISSUE TITLE
[Regression] Sound Popping When Booting Firmware in 0.9.3

### ISSUE THREAD

**Issue by Awakened0** [Arisotura/melonDS#1232]
There are noticeable popping sounds when booting firmware in 0.9.3. This is with all default settings on Win10.

https://user-images.githubusercontent.com/4565863/135330035-988f8633-bb91-4bfc-a333-cd5ebd6af75f.mp4

https://user-images.githubusercontent.com/4565863/135330102-53282295-80b7-41a6-95cd-4d2b62ea647e.mp4

**Comment by Arisotura** [comment]
these might come from SOUNDBIAS emulation -- I know the SetSoundBias function does it by increments and waits for the SOUNDBIAS register to reflect each new value, so I figure it takes a while to reflect changes and we need to emulate that

**Comment by Arisotura** [comment]
actually, you can also hear sound pops when starting a DS

**Comment by nadiaholmquist** [comment]
Indeed this popping started when I added SOUNDBIAS emulation, though a real DS does this too so I wouldn't call it a regression.

**Comment by Awakened0** [comment]
My DS Lite doesn't turn on anymore (fuse might be blown) so I can't record from the headphone jack to check. But I'll take your word it's real hardware behavior and close this.
