### ISSUE TITLE
Pokemon black 2 Chinese translated version can not created save file.

### ISSUE THREAD

**Issue by Copox** [Arisotura/melonDS#1249]
this version can be saved successfully on console and DESMUME

but on melon, it said as the picture showed

![2021-10-25 221410](https://user-images.githubusercontent.com/13120696/138714039-15de7e2d-2f8c-4855-8752-ee7917bcadf7.png)

```
Unable to save data
The backup function is faulty or has reached its service life
Unable to save
But you can still play the game
Do not cut off the power
```
I think it is the save size error for when i imported the save from DESMUME into melon. the melon said `"savefile shorter than sram"`
actually the save size on DESMUME is 513KB, on console is 512KB.

rom info
![2021-10-25 223440](https://user-images.githubusercontent.com/13120696/138715683-e6112684-0513-43f7-9a93-bd955ca11006.png)

**Comment by Copox** [comment]
it's related to the IR function and the latest rom patch (V5) has fix this issue.
![屏幕截图 2022-01-31 120818](https://user-images.githubusercontent.com/13120696/151737975-06629b88-45c4-4ca7-973e-6cb0d2bdd326.png)

**Comment by ashgx** [comment]
> it's related to the IR function and the latest rom patch (V5) has fix this issue. ![屏幕截图 2022-01-31 120818](https://user-images.githubusercontent.com/13120696/151737975-06629b88-45c4-4ca7-973e-6cb0d2bdd326.png)

其实我忘了说了是跟IR红外部分功能，但是下屏的红外连接（双方互联）我测试了一下是没生效
