### ISSUE TITLE
[Feature Request] Wireless Comms with a Real DS/DSi

### ISSUE THREAD

**Issue by zurgeg** [Arisotura/melonDS#1255]
This probably seems a little niche, but I'm curious to see it it would work?

**Comment by RSDuck** [comment]
Not realistically possible for a number of reasons:

1. Frames in melonDS aren't run in real time.
2. You would need some special peripheral as normal wifi cards don't allow you to just blast/receive raw packages.

**Comment by zurgeg** [comment]
Ah, ok!
