### ISSUE TITLE
Can't open MelonDS

### ISSUE THREAD

**Issue by Mimi-mara02** [Arisotura/melonDS#1257]
I have a MacBook Pro M1, 13", 8GB ram, 256GB rom.
I have tried both version 0.9.3 and 0.9.2 and also the native version in arm as the intel version (universal) and nothing, there is no way to open it. could someone help me? Thank you very much in advance.

**Comment by nadiaholmquist** [comment]
What error do you get?

You may have to open the security settings under system preferences to allow running it, as melonDS is not signed with an Apple developer cert or notarized.

**Comment by SA-X0** [comment]
On my case Windows 11, it works if i disable the real microphone, if i use it the emu just closes. 
Was working fine 6 or 8 versions behind with it enabled, not sure what was changed but once it access the mic, the emu closes as soonest something is started, be a game or the main menu of DS/DSi.

**Comment by RSDuck** [comment]
we're already a bit further in debugging this issue on Windows. It was seemingly introduced with an update for SDL. It crashes inside SDL's microphone code and at the moment we're not sure whether the problem really is just SDL or just some really bad issue caused by us which causes something to go wrong with SDL.

**Comment by nadiaholmquist** [comment]
The Windows issue is completely unrelated to this one, OP is using macOS and encountered gatekeeper warning about the application because it's not signed by a trusted cert.

**Comment by SA-X0** [comment]
I know nadiaholmquist, sorry i just didn't want to open a whole issue.
Since was mentioned can't open, wanted to mention the issue, i know each issue need it's own issue open. 
But RSDuck mentioned the problem.
Thanks RSDuck for the info.

**Comment by Mimi-mara02** [comment]
> What error do you get?
> 
> You may have to open the security settings under system preferences to allow running it, as melonDS is not signed with an Apple developer cert or notarized.

Thank you for your answer! In the end I managed to solve it by activating the SIP since I had previously disabled it

**Comment by Atomicblz** [comment]
Hi Mimi-mara02 I had the same issue as you I was wondering if you could please tell mw how you resolved it?

Any help would be greatly appreciated thanks in advance
