### ISSUE TITLE
Constant audio crackling in Kid Paddle - Lost in the Game (France)

### ISSUE THREAD

**Issue by iamthelaw2041** [Arisotura/melonDS#1261]
Tested with software and OpenGL and with JIT on and off. Game is at 60/60 speed and never changes so I don't think that's the problem. Just stand idle at the beginning of the level and you'll hear it. I guess it's possible it could be a problem with the game but I don't have a DS to check. 

![Capture](https://user-images.githubusercontent.com/94656803/142913258-c8f1c4c1-823e-4b80-9601-7e9b162cdb57.PNG)

**Comment by Arisotura** [comment]
I confirm that this doesn't happen on hardware

**Comment by iamthelaw2041** [comment]
Quick work. Very nicely done.

**Comment by Arisotura** [comment]
well, I gave DeSmuME a quick try and didn't observe it, so dunno about that one

**Comment by iamthelaw2041** [comment]
I'm sure I heard crackling. That's what made me think it might have been a game bug.

**Comment by poudink** [comment]
DeSmuME has a bunch of different audio settings so it might depend on that.
