### ISSUE TITLE
Loud audio popping during the first cutscene of SpongeBob's Atlantis SquarePantis (USA)

### ISSUE THREAD

**Issue by iamthelaw2041** [Arisotura/melonDS#1265]
As soon as you go into the cave. Tested with software and OpenGL, with JIT on and off. Speed never drops below 60/60. 

![spub](https://user-images.githubusercontent.com/94656803/143212436-407fbd65-0db5-458f-8815-e418f4d75435.PNG)

I found a video of it being played on real hardware and don't hear any popping.

https://www.youtube.com/watch?v=eumYlduC0_Q&t=7s

**Comment by Arisotura** [comment]
have you tried the last revision?

**Comment by iamthelaw2041** [comment]
Yeah.

**Comment by Arisotura** [comment]
o! well, I'm gonna check it out, let's see what we find this time

**Comment by Arisotura** [comment]
I compared against hardware and I'm not hearing anything out of the ordinary, it sounds the same on hardware and melonDS.

**Comment by iamthelaw2041** [comment]
Maybe my copy is broken. I'll try a different one.

**Comment by Arisotura** [comment]
if we're referring to the same thing: I hear it, but also on hardware. the song just is like that.

I can also hear it in the video you linked, though of course it's more muffled.

**Comment by iamthelaw2041** [comment]
Thanks for checking.
