### ISSUE TITLE
Possible audio issues in Diddl im Kaesekuchenland (Europe) (En,Fr,De)

### ISSUE THREAD

**Issue by iamthelaw2041** [Arisotura/melonDS#1267]
Distorted music on the title screen 

![diddle](https://user-images.githubusercontent.com/94656803/143306747-e78a0cf7-8bd5-4c54-87e4-459a4b4b7798.PNG)

Audio seems to break completely and turn into static for a few seconds if you pick the wrong cards in the first minigame.

![Capture](https://user-images.githubusercontent.com/94656803/143306843-38f7367a-cf13-4f2a-935a-99477e4eaac3.PNG)

**Comment by Arisotura** [comment]
have you compared it against hardware, this time?

**Comment by iamthelaw2041** [comment]
No I don't have a DS. If this is a real hardware issue I won't bother reporting anything else until I can get one.

**Comment by Arisotura** [comment]
well, we should make a list of issues that are known to be game issues. in the meantime, it's a good idea to check against hardware when you think you found an issue. sometimes games are just piles of crapo code :P

anyway, I gave this one a quick test, and I can confirm there's an issue with melonDS. the crackling/shitting doesn't happen on hardware.

I'm also seeing a bunch of NULL reads. let's try and see what's causing that.

**Comment by Arisotura** [comment]
sound shits itself reliably at the beginning of the minigame. it seems different in the menu, seems it doesn't happen if you already have a save.

tweaking the cache constants made no change, so, likely not a CPU timing issue. interesting shit!

**Comment by Arisotura** [comment]
the shitting happens because some channels are given a start-address that is zero.

now I guess I need to find out a) whether it's part of the game's normal operation and b) how does hardware react to that

**Comment by Arisotura** [comment]
well, thank you for the heads-up

**Comment by iamthelaw2041** [comment]
No problem. If bugs think they can hide from me by being in utter garbage that no one in their right mind would ever play, they're mistaken.
