### ISSUE TITLE
Corrupted graphics during screen transition in Game de Demashita! Powerpuff Girls Z (Japan)

### ISSUE THREAD

**Issue by iamthelaw2041** [Arisotura/melonDS#1270]
Choose Blossom and get to this screen. As it transitions to the next one the graphics break for a few seconds. Happens with Software and OpenGL. Tested with JIT off.

![Capture2](https://user-images.githubusercontent.com/94656803/143609344-164a0bb9-1f81-4816-ac2b-d5bdfb2d9049.PNG)

![Capture](https://user-images.githubusercontent.com/94656803/143609361-7b360cbf-71a4-4554-8142-a5cadc560754.PNG)

Here's a video of the game on Youtube and as far as I can tell this doesn't happen.

https://youtu.be/0VwSqL4LOtE?t=45

**Comment by Arisotura** [comment]
happens on hardware.

I would attach a recording captured from hardware, but Github is being stupid.
