### ISSUE TITLE
Garbage line briefly appears during the first cutscene in Horrid Henry - Missions of Mischief (Europe) (En,Fr,De,Es,It)

### ISSUE THREAD

**Issue by iamthelaw2041** [Arisotura/melonDS#1275]
Happens with Software and OpenGL. Doesn't happen in Desmume. Tested using external BIOS. Seems to be effected by JIT. With JIT on the line appears in the middle of the screen. With it off it appears more towards the top. 

![Capture](https://user-images.githubusercontent.com/94656803/144115320-dd68fbb5-f6a1-45f9-8d25-470b08bdb820.PNG)

**Comment by RSDuck** [comment]
if it's affected by JIT it could very well be a timing issue.
