### ISSUE TITLE
The Oregon Trail DSiWare

### ISSUE THREAD

**Issue by TylerJaacks** [Arisotura/melonDS#1285]
Installing The Oregon Trail DSiWare to NAND causes "An error has occured. Press and hold the Power Button to turn the system off. Please see the Nintendo DSi Operations Manual for help troubleshooting". This also happens also when booting the .nds file.

![chrome_Jvappz6CjX](https://user-images.githubusercontent.com/1505374/144785429-cd8fc2c0-5bdd-4206-bb16-56dc1949347d.png)

**Comment by Peter0x44** [comment]
I can reproduce this too. After installing it, attempting to start it for the first time will result in booting to that screen on all subsequent attempts, until it is uninstalled.

**Comment by Peter0x44** [comment]
Nevermind. This was caused by the NAND being full.
@TylerJaacks Try uninstalling a different title, and then trying again.

**Comment by TylerJaacks** [comment]
@Peter0x44 Can confirm that the was indeed the issue.
