### ISSUE TITLE
QT dependency

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [Arisotura/melonDS#1298]
would be possible to change all everything UI and QT (i dunno how much is shared with SDL)... to a separate DLL?
like MelonDS-UI.dll (with C exports) so that such dll could be implemented separately to not require the QT dependency? 

i could try to make a patch myself... but i rather not have my eyes bleeding reading C++ OOP/QT code, but once that is done
it would be a honor to make a native winapi version of the UI :)

**Comment by Arisotura** [comment]
no

**Comment by MyTDT-Mysoft** [comment]
now who is being childish?

**Comment by Arisotura** [comment]
have you tried synesthesia? you can get a can of it for about $7 at any grocery store. it changes your perception!

**Comment by nadiaholmquist** [comment]
The Qt frontend is already separated from the actual emulation code, and the emulator itself isn't even code that would cause your eyes to bleed by your definition.

Simply make a new folder in src/frontend and have fun with your winapi frontend.

**Comment by MyTDT-Mysoft** [comment]
> The Qt frontend is already separated from the actual emulation code, and the emulator itself isn't even code that would cause your eyes to bleed by your definition.
> 
> Simply make a new folder in src/frontend and have fun with your winapi frontend.

ok that is useful info... altough if the emulator calls the Qt Frontend with a class... (or worse except the QT to callback with classes)  it would still count as the QT eye bleeding part... but ok... thanks, i will fork and fix that myself

btw why it is using 140mb of ram right at start? (is that QT or that some huge buffers being allocated somewhere?)

**Comment by Arisotura** [comment]
the Qt part is strictly separated from the emu core. the Platform namespace is used from core side, but implemented on frontend side, it's a means for the core to call frontend-specific code, and you'll have to reimplement that bit.

**Comment by Arisotura** [comment]
![derpthread2](https://user-images.githubusercontent.com/1311867/146697601-f2ff806e-ce23-4fe6-943d-ebeef80c73b0.png)
fun fact.

**Comment by iamthelaw2041** [comment]
![FAxGX4aXoAQEde5](https://user-images.githubusercontent.com/94656803/146698239-67990310-67ba-46d1-becc-ad25184cfe6d.jpg)

**Comment by leranger** [comment]
@MyTDT-Mysoft 
maybe you should use the [32bits libretro core](http://buildbot.libretro.com/nightly/windows/x86/latest/melonds_libretro.dll.zip) (without JIT I guess) with a frontend like [sdlarch](https://github.com/heuripedes/sdlarch) to begin with and replace SDL functions with Win32 ones

**Comment by nadiaholmquist** [comment]
melonDS itself does not depend on Qt so going with upstream would be just as easy.

**Comment by MyTDT-Mysoft** [comment]
> 

yeah its one idea indeed, as long they keep updating with this melonDS, but at some point there will be some camera emulation, and fully working DSi wifi... and when it reaches that point i plan to remove all the C++ dependencies and change mutliples files into included files (separating modules only for actual different components) and so on, and then get rid of need for LTO, which will greatly speed up compile time, and it will cause the 32bit to be faster than the 64bit one. As well make the 32bit jit, to close the gap, So in a way or another i need to get used to the code, to be able to do that :)
