### ISSUE TITLE
Simple DS Series Vol. 35 - The Genshijin (Japan) instantly hangs on a white screen

### ISSUE THREAD

**Issue by iamthelaw2041** [Arisotura/melonDS#1309]
Tested with software and external BIOS. Works fine in Desmume and on real hardware with a flash cart so not a bad dump. 

![Capture](https://user-images.githubusercontent.com/94656803/147283814-fd98db86-d580-42fc-a004-e9ebb7fe1941.PNG)

With JIT the entire emulator crashes.

![Capture2](https://user-images.githubusercontent.com/94656803/147283831-deb41b3e-201f-4c8a-a7ca-0f88addc9b04.PNG)

**Comment by RSDuck** [comment]
timing issue. Works with kDataCacheTiming=kCodeCacheTiming=15

**Comment by iamthelaw2041** [comment]
Guess I better check the rest of the Simple Series games as well.

**Comment by RSDuck** [comment]
I think they were mostly different games, developed by different developers. What they have in common is that they're less sophisticated games made to be sold at a lower price point.
