### ISSUE TITLE
Consistent 15 FPS speed drop during screen transitions in Simple DS Series Vol. 11 - Mou Ichido Kayoeru - The Otona no Shougakkou (Japan)

### ISSUE THREAD

**Issue by iamthelaw2041** [Arisotura/melonDS#1311]
Every time you transition to the next screen the emulation speed drops from 60/60 to 45/60. Happens using software and with and without JIT. Doesn't happen in Desmume or on real hardware.

![Capture2](https://user-images.githubusercontent.com/94656803/147303481-0ad68129-1dbd-4b7f-a5d5-88603b709e9a.PNG)

![Capture](https://user-images.githubusercontent.com/94656803/147303486-a05a9ea4-ef70-4793-925f-baf628a21e5b.PNG)

**Comment by nadiaholmquist** [comment]
This is most likely your PC just being too weak to run the game, it might be doing something intensive during loading screens.
