### ISSUE TITLE
Randomize MAC address does not work unless "override settings from external firmware" is enabled

### ISSUE THREAD

**Issue by nadiaholmquist** [Arisotura/melonDS#1342]
This is not strictly a bug, as this might well be intended behavior, however it's somewhat unintuitive that a network setting requires overriding of user settings to be enabled.

We're going to trip up *a lot* of users trying to use local Wi-Fi with this change, and I'd suggest maybe making MAC randomization not depend on that option, and perhaps even moving it to the Wi-Fi settings?
Alternatively all the options in that dialog, including MAC randomization, could be grayed out if overriding settings is not checked to make it clear that it can't be used.

**Comment by Arisotura** [comment]
good point

**Comment by KaiHez** [comment]
> good point

The mac user can't do the local multiplayer I think this is probably the reason that was mentioned.
But the question is, I can't find the option that "override settings from external firmware" on MelonDS for mac. 
Is there no way to enable that option on mac？

**Comment by nadiaholmquist** [comment]
The option is only there in the development bulids, in the current stable local multiplayer is completely broken on macOS and *BSD.

**Comment by nadiaholmquist** [comment]
Fixed by https://github.com/Arisotura/melonDS/commit/02b859ad9dcfbc06cdb8f3a69e12a053752b85f0
