### ISSUE TITLE
[libretro] Hybrid mode + Duplicate not respecting Screen gap

### ISSUE THREAD

**Issue by boomshroom** [Arisotura/melonDS#1348]
I like to play with one main screen, and then the two screens on top of each other smaller next to it. With melonDS, this is available as Hybrid Mode just as it is on Desmume, however when the Hybrid Ratio is set to 3 (as I find 2 to be too big), the two screens from Duplicate are spaced out as far as possible. When like this, the Screen gap option has no effect.

Expected behavior: with Hybrid small screen mode set to Duplicate, setting Screen gap to `n` pixels would show a height of `n` pixels scaled from the original resolution and screen size between the two smaller screens

Observed behavior: The two screens are flush with the top and bottom of the main screen with 192 pixels, or 1 full small screen, between them. Changing Screen gap has no effect.

Version: melonDS 0.9.3 (Retroarch 1.9.14)
OS: Linux 5.10.89 (NixOS 22.05 unstable)

**Comment by RayyanAnsari** [comment]
https://melonds.kuribo64.net/faq.php#Unofficial_Ports

**Comment by boomshroom** [comment]
Ah. Thank you for informing me that the libretro port is unofficial.
