### ISSUE TITLE
Yoshi's Island DS - Title screen graphical bug

### ISSUE THREAD

**Issue by GaussTek** [Arisotura/melonDS#1353]
This shows up on the game's title screen, using both Software and OpenGL. Seems the sky is missing and bottom screen doesn't display properly:

![60_60  melonDS 0 9 3 27_01_2022 12_54_06 p  m](https://user-images.githubusercontent.com/43524067/151430440-b1217862-03f5-4ee4-8d1d-815548fd7375.png)

This is how it must look (screen from Desmume on Retroarch):
![RetroArch DeSmuME git 7ea0fc9 27_01_2022 12_59_15 p  m](https://user-images.githubusercontent.com/43524067/151430713-2f453893-c312-410d-9c5a-5144405b5284.png)

Graphical bug is also present on RetroArch core.

**Comment by CasualPokePlayer** [comment]
This is a bug with FreeBIOS. It doesn't appear with official BIOS files.

**Comment by Brankale** [comment]
Maybe a FreeBIOS label should be added for these type of issues

**Comment by RSDuck** [comment]
good idea

**Comment by smtha-alt** [comment]
SMW2 Yoshi's Island Hacks
