### ISSUE TITLE
unable to compile on linux VM on chromebook (debian 10)

### ISSUE THREAD

**Issue by NEPETAISCUTE** [Arisotura/melonDS#1356]
basically i tried to compile melonds on the linux VM of chromebook (which is under debian 10, buster) managed to install all of the dependencies, no problem, though i get linking errors, that looks very obscure, and i don't really see what could be missing:

[100%] Linking CXX executable ../../../melonDS
/usr/bin/ld: /tmp/ccP6re5k.ltrans0.ltrans.o: in function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format) [clone .constprop.696]':
<artificial>:(.text+0xc1a8): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: /tmp/ccP6re5k.ltrans20.ltrans.o: in function `FATStorage::CleanupDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
<artificial>:(.text+0x46ee): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x46f6): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x49a5): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x49ad): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: /tmp/ccP6re5k.ltrans20.ltrans.o: in function `FATStorage::DeleteHostDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
<artificial>:(.text+0x5219): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x5253): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x5317): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: <artificial>:(.text+0x53a3): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: <artificial>:(.text+0x54de): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: <artificial>:(.text+0x56bd): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x5711): undefined reference to `std::filesystem::permissions(std::filesystem::__cxx11::path const&, std::filesystem::perms, std::filesystem::perm_options, std::error_code&)'
/usr/bin/ld: <artificial>:(.text+0x5719): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x59c8): undefined reference to `std::filesystem::permissions(std::filesystem::__cxx11::path const&, std::filesystem::perms, std::filesystem::perm_options, std::error_code&)'
/usr/bin/ld: <artificial>:(.text+0x59d0): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x5b34): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: /tmp/ccP6re5k.ltrans20.ltrans.o: in function `FATStorage::ExportDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)':
<artificial>:(.text+0x60c5): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x61a9): undefined reference to `std::filesystem::permissions(std::filesystem::__cxx11::path const&, std::filesystem::perms, std::filesystem::perm_options, std::error_code&)'
/usr/bin/ld: <artificial>:(.text+0x64a4): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x66d0): undefined reference to `std::filesystem::last_write_time(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x6a83): undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&, std::error_code&)'
/usr/bin/ld: <artificial>:(.text+0x6c9b): undefined reference to `std::filesystem::permissions(std::filesystem::__cxx11::path const&, std::filesystem::perms, std::filesystem::perm_options, std::error_code&)'
/usr/bin/ld: /tmp/ccP6re5k.ltrans20.ltrans.o: in function `FATStorage::Save()':
<artificial>:(.text+0x71bd): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x7216): undefined reference to `std::filesystem::permissions(std::filesystem::__cxx11::path const&, std::filesystem::perms, std::filesystem::perm_options, std::error_code&)'
/usr/bin/ld: <artificial>:(.text+0x721e): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: /tmp/ccP6re5k.ltrans20.ltrans.o: in function `FATStorage::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
<artificial>:(.text+0x8a09): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x8a16): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x9376): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: <artificial>:(.text+0x9394): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::recursive_directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: <artificial>:(.text+0x9496): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0x94fe): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0x954e): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0x9558): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0x9562): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0x98c6): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator*() const'
/usr/bin/ld: <artificial>:(.text+0x9983): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x9a2c): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator++()'
/usr/bin/ld: <artificial>:(.text+0x9a44): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x9a60): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x9a70): undefined reference to `std::filesystem::file_size(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0x9a7b): undefined reference to `std::filesystem::last_write_time(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0xa00a): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::recursive_directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: <artificial>:(.text+0xa0be): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0xa12e): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0xa157): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0xa15f): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0xa169): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text+0xa1d4): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator*() const'
/usr/bin/ld: <artificial>:(.text+0xa1f6): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator++()'
/usr/bin/ld: <artificial>:(.text+0xa204): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0xa21e): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: <artificial>:(.text+0xa22a): undefined reference to `std::filesystem::file_size(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: /tmp/ccP6re5k.ltrans20.ltrans.o: in function `FATStorage::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) [clone .cold.10]':
<artificial>:(.text.unlikely+0xa84): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text.unlikely+0xa8e): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text.unlikely+0xa98): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text.unlikely+0xb6b): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: <artificial>:(.text.unlikely+0xb73): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: /tmp/ccP6re5k.ltrans20.ltrans.o:<artificial>:(.text.unlikely+0xb7d): more undefined references to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build.make:478: melonDS] Error 1
make[1]: *** [CMakeFiles/Makefile2:274: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

is it a problem on my end with some library missing?

**Comment by RSDuck** [comment]
looks like all std::filesystem stuff which seems to be missing while linking.

**Comment by NEPETAISCUTE** [comment]
huh? isn't std::filesystem part of iostream? i thought it was linked by default, and installed by default on like, every computer?

**Comment by NEPETAISCUTE** [comment]
ok just found out the issue from googling, it's because my version of gcc is 8.3.0, and uh, the version 8.3.0 didn't include std::filesystem by default, while versions above does

**Comment by NEPETAISCUTE** [comment]
imma close the issue because i updated my distrib to bullseye and now it works
