### ISSUE TITLE
This video game ROM Nintendo DS it is slowing and crashing the emulator for phone because of what?... cell phone weak?

### ISSUE THREAD

**Issue by KielYam1212008** [Arisotura/melonDS#1362]
## Read before you proceed (and delete this section before posting)
Only post the issue if you believe there is a problem with the emulator. If you have a question, feature request or other generic topic, you are encouraged to open a [Discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions) instead. If you are not sure whether you are dealing with an issue or not, don't worry and post it wherever you feel is the most appropriate place.

Issues asking about online Wi-Fi will most likely be ignored and deleted since that feature is not yet implemented. You can, however, open a discussion if you believe you have valuable information to add regarding this topic.
**********************

* **Device model:** Samsung Galaxy J7 Prime weak
* **Android version:** Android Nougat 7 and Oreo 8 weak

**Problem:**  
causes and issues of video games nintendo DS ROM that I played this game in the emulator MelonDS got slow and crashing! for cell phone weak?

**Steps to reproduce (if applicable):**
1. Write a list of steps
2. Required for the problem
3. To appear

Add screenshots if the issue can be visualized.

**Comment by nadiaholmquist** [comment]
We do not maintain the android poet dl we can't really help you much with it.

In my estimation you will need a device roughly on par with a Raspberry Pi 4 for full speed most of the time in normal DS mode with JIT enabled.
