### ISSUE TITLE
Path Error when compiling:  The CMAKE_CXX_COMPILER: g++.exe is not a full path and was not found in the PATH.

### ISSUE THREAD

**Issue by extherian** [Arisotura/melonDS#1368]
" Tell CMake where to find the compiler by setting either the environment variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler name if it is in the PATH."

I'm using MSYS2 on WIndows, no idea how to do this. I know how to edit the Windows path file, but I don't know what I'm supposed to put in it. Since cmake.exe isn't in my path file, I'm currently trying to get melonDS to compile with this command: C:/msys64/mingw64/bin/cmake.exe .. -G 'MSYS Makefiles' -DBUILD_STATIC=ON -DQT5_STATIC_DIR=/mingw64/qt5-static

Also, please include instructions on adding the necessary path entries in the README.md.

**Comment by nadiaholmquist** [comment]
You shouldn't modif your Windows PATH.

In the Start menu, MSYS2 has installed several shortcuts to different terminals, you want to open the MinGW 64-bit terminal, that has the environment correctly set up to use the mingw-w64 packages.

**Comment by extherian** [comment]
Yes, I just figured out that I was in the 32-bit terminal...which is the one that the program opens by default when you finish installing it. That isn't Arisotura's fault, but I'd appreciate it if the README.md warned about this. My own stupid fault, anyway.
