### ISSUE TITLE
melonDS compilation fails when linking CXX executable 

### ISSUE THREAD

**Issue by extherian** [Arisotura/melonDS#1369]
I got the following error message:

[100%] Linking CXX executable ../../../melonDS.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib\libb2.a(libb2_la-blake2sp.o):(.text+0x14): undefined reference to `omp_get_thread_num'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib\libb2.a(libb2_la-blake2sp.o):(.text+0x96): undefined reference to `omp_get_thread_num'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib\libb2.a(libb2_la-blake2sp.o):(.text+0x55c): undefined reference to `omp_set_num_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib\libb2.a(libb2_la-blake2sp.o):(.text+0x582): undefined reference to `GOMP_parallel'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib\libb2.a(libb2_la-blake2sp.o):(.text+0x9a2): undefined reference to `omp_set_num_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib\libb2.a(libb2_la-blake2sp.o):(.text+0x9d7): undefined reference to `GOMP_parallel'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/frontend/qt_sdl/CMakeFiles/melonDS.dir/build.make:814: melonDS.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:248: src/frontend/qt_sdl/CMakeFiles/melonDS.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

 No idea what this means, unfortunately. I followed all the instructions in README.md, so I don't know why I'm getting undefined reference errors.

**Comment by RayyanAnsari** [comment]
known issue with msys2, they added a package for `libb2` which we depend on via `libarchive`.

**Comment by RayyanAnsari** [comment]
This should now be fixed by https://github.com/msys2/MINGW-packages/pull/10707#issuecomment-1044636544

**Comment by extherian** [comment]
OK, I'll just have to wait until the main MSYS2 website updates its download with these new changes.

**Comment by Biswa96** [comment]
The fixed package is uploaded https://packages.msys2.org/updates. It may take time to reach all the mirrors. Meanwhile keep spamming `pacman -Syyuu` command to update packages.

**Comment by extherian** [comment]
@RayyanAnsari this fixed my problem and I compiled the program successfully, thanks for all your help!

**Comment by Biswa96** [comment]
Thank you too for reporting this issue quickly 🤗 It is easier to fix an issue with a minimal reproducible sample.
