### ISSUE TITLE
Black Particles in Pokemon 

### ISSUE THREAD

**Issue by FeyrisTan** [Arisotura/melonDS#1376]
If this issue is already open i close it of course.

I like melonds but damn those black particles in DP are annoying.
Adding shaders like xbrz would be amazing as well.

**Comment by RSDuck** [comment]
OpenGL renderer?

**Comment by nadiaholmquist** [comment]
This is an issue with the OpenGL renderer that is very hard to fix. Use software rendering if it bothers you too much.

Before being replaced with a compute shader-based renderer this likely won't be fixed with OpenGL.

**Comment by FeyrisTan** [comment]
Software is the same :/

**Comment by RSDuck** [comment]
pictures?

**Comment by nadiaholmquist** [comment]
Which melonDS version? Software should not have this issue.

**Comment by FeyrisTan** [comment]
I expect u to solve my problems without me detailing anything at all. 

Reinstalling my Nvidia driver version 461.92  with DDU fixed the software issue (461.92 is the best driver hands down compatibility and performance wise and ofc non dch) 

So either I play it in sucky resolution or i play in upscaled opengl with black particles? That about it?

**Comment by nadiaholmquist** [comment]
> I expect u to solve my problems without me detailing anything at all.

I'm terribly sorry to disappoint but we can't read your mind,  and neither can we remotely access your PC. You'll sadly have to provide the information yourself :(

Anyway, the DS GPU behaves very differently from modern GPUs, making what melonDS is doing with OpenGL very hard to do properly without issues. Currently you'll have to deal with it or play at native resolution with software rendering. The version of your graphics driver should have no impact on the software rendering.
