### ISSUE TITLE
How to open on linux (parrotOS, debian-based)

### ISSUE THREAD

**Issue by anonaddict** [Arisotura/melonDS#1390]
I've setup flatpak following 
https://flatpak.org/setup/Debian
and installed it with the following command
┌─[user@host]─[~]
└──╼ $flatpak install flathub net.kuribo64.melonDS
Looking for matches…
Skipping: net.kuribo64.melonDS/x86_64/stable is already installed

However I can't find melonDS anywhere on my system

**Comment by nadiaholmquist** [comment]
`flatpak run net.kuribo64.melonDS`

If you just set up flatpak you may have to reboot for the paths where it installs things to be added to the environment.

**Comment by anonaddict** [comment]
I solved the issue, i found the file under
./var/lib/flatpak/app/net.kuribo64.melonDS/current/active/export/bin/net.kuribo64.melonDS

**Comment by anonaddict** [comment]
I solved the issue, i found the file under
./var/lib/flatpak/app/net.kuribo64.melonDS/current/active/export/bin/net.kuribo64.melonDS
