### ISSUE TITLE
Error while generating

### ISSUE THREAD

**Issue by AM7999** [Arisotura/melonDS#1403]
While following the instructions to compile melonDS i get the following error:
![image](https://user-images.githubusercontent.com/62681612/159142114-cb4f7942-fbc6-4335-ab5b-ebeb969d1791.png)

**Comment by RSDuck** [comment]
you either don't have libslirp installed, or it can't be found.

**Comment by AM7999** [comment]
After installing libslirp i am now getting this error 
![image](https://user-images.githubusercontent.com/62681612/159172843-951c7100-ecae-4fd6-a54b-5e27b90a16fc.png)

**Comment by nadiaholmquist** [comment]
Follow the instructions in the readme, they tell you not to do an in-source build by making a `build` directory.

**Comment by AM7999** [comment]
Well now I've got another issue
![image](https://user-images.githubusercontent.com/62681612/159173182-1cded646-f16f-4a7b-af21-d040a1dadd0c.png)

**Comment by nadiaholmquist** [comment]
Doesn't line up with the latest source but I assume that is trying to find libarchive, can't see because you cut off the output above.

What are you building on anyway?

**Comment by AM7999** [comment]
Im compiling on Manjaro ARM 64 bit

**Comment by nadiaholmquist** [comment]
In that case you'll want to install `pkg-config qt5-base sdl2 libarchive libslirp`. Alternatively just use the AUR package, that will pull in the dependencies for you.

**Comment by AM7999** [comment]
Yup, it did work thanks for the help!
