### ISSUE TITLE
Question about the minimum OS X deployment version

### ISSUE THREAD

**Issue by eisnerguy1** [Arisotura/melonDS#1407]
So, I'm on a machine that still needs to use 32-bit apps quite a bit. Because of that, I'm stuck on 10.14 for the time being. [The minimum OS X deployment version was bumped to 10.15](https://github.com/Arisotura/melonDS/commit/2af8e65f23e0311389bb309fc7cf039b82b28f87) earlier this month.  [This was the last version to support macOS 10.14](https://github.com/Arisotura/melonDS/commit/2af8e65f23e0311389bb309fc7cf039b82b28f87). In the source for melonDS 0.9.4, how difficult would it be to change the minimum OS X deployment version back to 10.14? Or, could a 10.14 build be included among the compiled builds?

Thanks!

**Comment by RayyanAnsari** [comment]
melonDS might work for the time being on macOS 10.14 if you change some stuff - but there's no guarantees. Neither Apple, nor GitHub Actions, nor Homebrew supports that version (have fun compiling something massive like Qt). This means that it's a lot of work to support it, and this doesn't even factor in things like 10.14's libc not supporting `std::filesystem`.

**Comment by eisnerguy1** [comment]
I kinda figured it was a long shot. I'll stay with 0.9.3 for now then :)
