### ISSUE TITLE
Mobile compatible?

### ISSUE THREAD

**Issue by BlackoftheDawn** [Arisotura/melonDS#1410]
I seen that it looks to be for computers right?

**Comment by RSDuck** [comment]
we only officially support desktop operating systems.

**Comment by BlackoftheDawn** [comment]
> we only officially support desktop operating systems.

Thank you for your time.

**Comment by Arisotura** [comment]
there's an Android port, but it's not made by us

**Comment by Bardock88** [comment]
> there's an Android port, but it's not made by us

I don't know if I'm going to be indiscreet with what I'm going to ask, but a partnership between you and the author of the port for Android could be considered, where it really becomes an official version of the project for this platform and that can also help both versions can improve on their respective OS platforms, as happens for example with the partnership of PCSX2 with AetherSX2?
