### ISSUE TITLE
After melonDS has been acquired by Meta. Will melonDS keeping open source and clean ? 

### ISSUE THREAD

**Issue by katyurua** [Arisotura/melonDS#1414]
## Will melonDS keeping open source and clean ? 
***
https://melonds.kuribo64.net/comments.php?id=159

Apr 1st 2022

Or it's a April Fool's Day joke?
***
A while ago we had an... unusual visit at the melonDS HQ: Mark Zuckerberg, no less. 
Zuck stated that he had always been a great fan of emulation, and that he loved our project greatly.

He offered us $324 million for the melonDS company, including both the HQ and the Melon Factory of Kuribo64.

An offer we could hardly refuse

On more practical terms: this means lots of new exciting developments for melonDS.
For example, one of the new ideas is selling NFTs of the best melonDS screenshots. 
That is an obvious one, but not the only one at all.

melonDS will also become smarter, for an enhanced user experience. 
We are thinking about keeping a database of games, so melonDS can detect which game it is running, 
and offer ads related to that game. 
That is a start, but with AI we might be able to take this even further and offer the most relevant ads an emulator has ever offered.
***

**Comment by RSDuck** [comment]
> Will melonDS keeping open source and clean ?

yes and yes if you take off your shoes before using it.

**Comment by katyurua** [comment]
> > Will melonDS keeping open source and clean ?
> 
> yes and yes if you take off your shoes before using it.

Sorry about my poor English, What do mean "take off your shoes before using it" ? I don't get it.

Is melonDS has been acquired by Meta or not ?

**Comment by RSDuck** [comment]
> Sorry about my poor English, What do you mean "take off your shoes before using it" ? I don't get it.

That was a terrible joke.

> Is melonDS has been acquired by Meta or not ?

no, melonDS is open source and will stay open source, it was all just an april fool's day joke.

**Comment by FrostKnight** [comment]
> > Sorry about my poor English, What do you mean "take off your shoes before using it" ? I don't get it.
> 
> That was a terrible joke.
> 
> > Is melonDS has been acquired by Meta or not ?
> 
> no, melonDS is open source and will stay open source, it was all just an april fool's day joke.

Some people don't know trolling or satire when they see it...

;)

Ah...

I remember the days, I used to not have a damn clue what either of those were...

Man simpler times...  before the orange plague descended upon America...

;P
