### ISSUE TITLE
LEGO Batman 2 - DC Super Heroes (Canada) (En,Fr) - stuck on loop at start

### ISSUE THREAD

**Issue by mariomadproductions** [Arisotura/melonDS#1420]
[LEGO Batman 2 - DC Super Heroes (Canada) (En,Fr)](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=z377) is stuck on a loop initialising the save data. The USA version gets past this screen, and both versions get past the screen in Desmume. I tried v0.9.4 and 529a690.

**Comment by poudink** [comment]
perhaps the canadian version is missing an entry in the save type list

**Comment by mariomadproductions** [comment]
Ah. src/ROMList.h? I guess that list is just filled out by trying different save types out and seeing what works?

**Comment by poudink** [comment]
Yeah, I think so. This one shouldn't be any different from the other region's save types, tho. You may be able to check by letting the US version generate a save file and renaming it for the Canadian version's ROM.

**Comment by mariomadproductions** [comment]
That doesn't work for some reason. But manually adding an entry to ROMList.h (is there a utility for this?) worked.
i.e. after `{0x4B5A5A43, 0x10000000, 0x00000005},`, I added `{0x4C463642, 0x08000000, 0x00000001},`.

**Comment by nadiaholmquist** [comment]
It is just edited manually so you can simply submit a pull request making that edit.
