### ISSUE TITLE
Feature Request: Clock offset

### ISSUE THREAD

**Issue by mitchellhumphrey** [Arisotura/melonDS#1424]
Certain games interact with the current time. Currently, melonDS just grabs system time and set's that to the DS's clock from what I can tell. Being able to adjust the DS clock without adjust system time would be an amazing feature. Currently the workaround I have found is adjusting system time, however that breaks a lot of other programs on my Computer.

**Comment by CasualPokePlayer** [comment]
https://github.com/Arisotura/melonDS/issues/208
Already an issue opened on it, and a PR is open to add this feature: https://github.com/Arisotura/melonDS/pull/1237
