### ISSUE TITLE
it shows white screen when running ecyrepted games 

### ISSUE THREAD

**Issue by dananothername** [Arisotura/melonDS#1427]
i realy need this

**Comment by Arisotura** [comment]
you need original BIOS dumps if you want to run encrypted ROMs

**Comment by dananothername** [comment]
i dobut its leagel to shear bois

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/issues/3217

**Comment by dananothername** [comment]
you closed the comments there i still have some on topic question

**Comment by dananothername** [comment]
can i search for unknown address
the value should be 0 but the results 2 million
![Uploading Screenshot 2022-04-16 16112.png…]()

**Comment by Arisotura** [comment]
what
