### ISSUE TITLE
qt5-default is missing in ubuntu 22.04

### ISSUE THREAD

**Issue by nonsio280** [Arisotura/melonDS#1435]
As title says, I'm trying to install the dependencies, but qt5-default is no longer available. What should I do?

**Comment by nadiaholmquist** [comment]
It might be named something like qt5-base.

**Comment by nonsio280** [comment]
I just tried, there's no package named qt5-base. Also I found some "solutions" to this problems on google, but since I'm a noob I'm afraid to mess up, could you developers update the dependecies, please?

**Comment by RayyanAnsari** [comment]
The package is called `qtbase5-dev` - you can easily find package names by searching for them online.
https://packages.ubuntu.com/

**Comment by nonsio280** [comment]
Thank you, now everything works just fine. I'm closing
