### ISSUE TITLE
'Hybrid Top' screen layout swap duplicates bottom screen, instead of swap

### ISSUE THREAD

**Issue by TrashmanJigs** [Arisotura/melonDS#1437]
Hello,

I want to play games in the 'hybrid top' screen layout. But when I press the swap screens key, the touch screen gets duplicated. Instead of actually swapping the two screens.
This works fine on the standalone version of MelonDS.

The only solution I've found is to use either the Top/Bottom layout, or Left/Right. But both those options make the 'game' screen way too small on my Steam Deck.

![20220508_222014](https://user-images.githubusercontent.com/1648011/167314904-581899cb-32dd-426b-8ec1-537f2f9d17a5.jpg)

![20220508_222021](https://user-images.githubusercontent.com/1648011/167314962-1de7b80c-8867-42d6-b7bb-0ddc77bfe82c.jpg)

**Comment by RSDuck** [comment]
you're probably looking for https://github.com/libretro/melonDS/issues
