### ISSUE TITLE
[Feature Request] Allow Binding Both a Joystick and Physical Directional Pad to the Emulated Directional Pad

### ISSUE THREAD

**Issue by hiddeninthesand** [Arisotura/melonDS#1446]
The 3DS introduced the circle pad , which when used with DS and DSi games allowed it to also function as a directional pad, alongside the actual directional pad. This can be much more comfortable for some games and controllers, so I think it'd be a good feature to implement.

**Comment by sandwichwater** [comment]
im pretty sure this is already a thing , ive been using a joystick as a dpad for years , at least its been there for as long as ive used this emulator . unless you mean to separate the circle and dpad into their own separate things , which cannot be done , the ds only ever had one pad so telling it to separate one pad into two would either a) break a lot of things or b) just keep functioning as it is already , where pressing up on the joystick or dpad still does the same thing , moves the character , menu , etc in the direction you press

**Comment by hiddeninthesand** [comment]
To clarify, the request is to implement the same behavior that the 3DS has, where both the joystick and the directional pad can be used for movement in DS mode at the same time, not for the already implemented feature of being able to use a joystick as a directional pad by itself.

**Comment by sandwichwater** [comment]
huh , in all my 9 years of owning a 3ds i never knew they could be used at the same time . my apologies , thats lack of knowledge on my part . this would definitely be a cool feature to have

**Comment by sandwichwater** [comment]
as far as i know thats is already a thing , ended up accidentally binding the R button to both buttons on my controller which messed with the swap screens button and had to figure out on my own that multiple keybindings could be set to a single button

**Comment by hiddeninthesand** [comment]
@sandwichwater is correct, it seems the feature is already implemented but simply undocumented. Thanks for showing me that.
