### ISSUE TITLE
Feat .req. Build with GCC 12.1 and try -O3 flag

### ISSUE THREAD

**Issue by necros2k7** [Arisotura/melonDS#1454]
subj

**Comment by RayyanAnsari** [comment]
you already can

**Comment by necros2k7** [comment]
Can you make it to Release tab?

**Comment by nadiaholmquist** [comment]
The normal build instructions make a release build, simply follow what README.md says and you should be good to go.

**Comment by necros2k7** [comment]
> The normal build instructions make a release build, simply follow what README.md says and you should be good to go.

I talk for people who don`t have build environment and / or time, someone did setup current Release tab right? So can this someone change settings for above wish? Tweak Appveyor I don`t know what you use to make Release tab build

**Comment by RayyanAnsari** [comment]
we already use the `-O3` flag anyway
