### ISSUE TITLE
Black lines

### ISSUE THREAD

**Issue by 3lc3z4r** [Arisotura/melonDS#1457]
Before I do a whole line, just tell me if you have already solved the problem of black lines when using opengl. If they solved it, can you please leave me which post has the solution, thanks

**Comment by 3lc3z4r** [comment]
> This is a known and already reported issue and very hard to fix, there is no fix yet so for now use software rendering if you want to avoid them.

If that is what I have in mind, the use of software does not bother me, what does bother me is that it does not have to increase resolution x2, x3, etc; or am I missing something that does the same?

**Comment by sandwichwater** [comment]
software renderer cant increase resolution because , well its supposed to emulate how the actual ds renders games , which cannot upscale in any way . if they could be it would be huge for 3ds users for the increased resolution

**Comment by 3lc3z4r** [comment]
> software renderer cant increase resolution because , well its supposed to emulate how the actual ds renders games , which cannot upscale in any way . if they could be it would be huge for 3ds users for the increased resolution

well then I'll wait until they solve the thing, rather on the other side... Drastically I don't know how they did to improve the textures internally without having problems with the black lines, you know how it really makes this drastic possible and have any idea to use that technology or something similar in melonds?

**Comment by CasualPokePlayer** [comment]
Software renderer could potentially upscale but it is very pointless to do as that is very taxing for CPUs to do (unlike GPUs which can easily do that compared to CPus), you would likely not have full speed in games with any upscaling done.

**Comment by Brankale** [comment]
If you want software upscaling there was a pull request that tried to add it #1009 that was never merged for the explanations given above. I'll leave it here if you want to give it a try but remember that it requires a lot of power to be used and that it's a very old build so it doesn't support newer features.

[hires.zip](https://github.com/Arisotura/melonDS/files/8832507/hires.zip)
