### ISSUE TITLE
Harry Potter Goblet of Fire DS boots to white screen

### ISSUE THREAD

**Issue by kevincrans** [Arisotura/melonDS#1464]
does anyone else have this issue?

**Comment by Arisotura** [comment]
do you have JIT on or off?

**Comment by kevincrans** [comment]
Oh I'm terribly sorry, I was in DSI mode.

**Comment by Arisotura** [comment]
oh right, direct boot is still not perfect in DSi mode, it can't boot DS titles for some reason. I still need to work on it, heh.
