### ISSUE TITLE
Can't use bottom screen.

### ISSUE THREAD

**Issue by DriftWare07** [Arisotura/melonDS#1470]
I can press a, but it always presses in the middle of the screen. I'm using the retroarch core. The mouse doesnt appear to select either.

**Comment by sandwichwater** [comment]
the a button doesnt control the touchscreen , unless theres been a new build that adds "a to touchscreen input" , as for the mouse not being able to do anything maybe its an issue with the rom ¿ try it out with different emulators to see if they give the same issue

**Comment by DriftWare07** [comment]
nevermind, figured it out in core settings
