### ISSUE TITLE
Unable to copy data from DSI SD card in Retroarch core

### ISSUE THREAD

**Issue by Zkyo42** [Arisotura/melonDS#1477]
Hi, I think I ran across an issue with the melonDS Retroarch core (lastest version, 0.9.3 as of writing this). I set up a SD card, which I intend to use to store my DSiWare games, as they won't all fit on the internal storage. I would copy them to the internal storage when I want to play, then copy back and delete to free space. This works perfectly in the Windows version of melonDS (0.9.4_win_x64), but not retroarch. The file manager just displays the error "This software cannot be copied."

I also noticed that the .idx file melonDS (windows version) generated isn't required by retroarch. Idk if that's related, but I thought I'd mention it.

**Comment by RSDuck** [comment]
--> https://github.com/libretro/melonDS/issues/
