### ISSUE TITLE
Can't reset controller input bindings on Mac.

### ISSUE THREAD

**Issue by seanrosshughes** [Arisotura/melonDS#1491]
On Mac, once bindings are set for a controller (I used Xbox 1 Wireless), bindings cannot be reset. Mac doesn't have a dedicated backspace button, not allowing the use of clicking backspace to delete bindings. The hotkey for backspace on back does not work as well. 

To replicate: 
Set a controller binding on Mac, and try to delete it. 

Expected result: 
Binding is deleted when backspace is pressed.

Observed result: 
Binding is not deleted when backspace is pressed.

**Comment by Arisotura** [comment]
> Mac doesn't have a dedicated backspace button, not allowing the use of clicking backspace to delete bindings. The hotkey for backspace on back does not work as well.

what

**Comment by seanrosshughes** [comment]
I apologize if my wording was bad. 

On Mac, there exists only a delete key, not a backspace key. Although the Mac delete key functions the same as the backspace key on PC, it sends a completely different ASCII code. The ASCII code for backspace is not possible to send on Mac without using a shortcut (fn + del). 

Im not sure why on Mac key bindings can't be reset for the emulator (at least in my case), but this is the first thing that came to mind.

**Comment by RayyanAnsari** [comment]
does the fn+del shortcut work to delete the binding?

**Comment by Arisotura** [comment]
o, I see

I guess it'd be trivial to check for the delete key scancode, then

alternately: the keybindings are the first bunch of entries in melonDS.ini. editing them to -1 will remove any keybindings.

**Comment by seanrosshughes** [comment]
> does the fn+del shortcut work to delete the binding?

No, the shortcut has no effect on changing the keybindings at all.


> I guess it'd be trivial to check for the delete key scancode, then
> 
> alternately: the keybindings are the first bunch of entries in melonDS.ini. editing them to -1 will remove any keybindings.

Yeah it does seem like a super trivial fix, I would assume checking the delete keyscan code would do the job. 
To my understanding though, .ini files are windows specific. As I am running on macOS, specifically the ARM architecture, I cant find anything in the build files even relating to the .ini file / any other initialization file whatsoever.

**Comment by Arisotura** [comment]
melonDS does use a melonDS.ini file on all desktop platforms, I don't recall where it's stored on macOS

**Comment by RayyanAnsari** [comment]
it should be somewhere in ~/Library/Preferences

**Comment by nadiaholmquist** [comment]
`~/Library/Preferences/melonDS/melonDS.ini`

**Comment by nadiaholmquist** [comment]
This was caused by a small oversight in the code, latest commit should fix it.
