### ISSUE TITLE
[Feature Request] (Retroarch) Touch Mode - Multiple Options Simultaneously

### ISSUE THREAD

**Issue by rawdatafeel** [Arisotura/melonDS#1499]
Hello, 

In the MelonDS Retroarch core, would it be possible to use both the touch screen and the mouse as touch inputs for "Touch Mode" simultaneously?

Currently, you can only select one or the other. 

My use case would primarily be on a Steam Deck, allowing users to use both the trackpads and the touch screen as inputs for DS games.

**Comment by nadiaholmquist** [comment]
The libretro port of melonDS is not official and is not maintained by the melonDS team. You'll have to ask the libretro devs rather than here.
