### ISSUE TITLE
Missing an include line in camera-betterer branch

### ISSUE THREAD

**Issue by Raz0rblade06** [Arisotura/melonDS#1502]
The file [interpreter.h](https://github.com/Arisotura/melonDS/blob/camera_betterer/src/teakra/src/interpreter.h) fails to compile. My friend figured out that it's missing the line `#include <utility>`; adding the line seems to have addressed the issue and I was able to compile once it was in place.

![image](https://user-images.githubusercontent.com/98237582/185769073-2f8314b7-8d83-43df-9fa5-94541c565a31.png)
(I had already tried to compile once before, so the compiler picked up where it had left off, hence 1% completion)

**Comment by CasualPokePlayer** [comment]
This is fixed in master already in https://github.com/Arisotura/melonDS/commit/4cc34121b0db2cf77541014271af8d79fed35f26, it's only an issue for compiling on gcc12, older versions had the header included implicitly by some other header so it compiled.

**Comment by Raz0rblade06** [comment]
> This is fixed in master already in [4cc3412](https://github.com/Arisotura/melonDS/commit/4cc34121b0db2cf77541014271af8d79fed35f26), it's only an issue for compiling on gcc12, older versions had the header included implicitly by some other header so it compiled.

I see, thanks for letting me know. I guess it's not too big of an issue then, since this branch will probably just merge with the master branch anyways.
