### ISSUE TITLE
Please optimize rendering speed.

### ISSUE THREAD

**Issue by TsukiZero** [Arisotura/melonDS#1505]
For whatever reason, MelonDS 0.9.4 tanks the framerate HEAVILY in some games, specially the ruined hotel in the south of Metal Max 2 Reloaded, where the framerate can tank to 45 FPS on some floors, and it is impossible to speed up for some reason. Meanwhile the other emulator (DeSmuME 0.9.13 x64 SSE2) not only maintains a framerate there of 50+ and still allows to speed up emulation just fine!

Note: this was done in all rendering modes (OGL, Software, Display HW, Display SW), and the constant is that MelonDS performed poorly.

**Comment by Brankale** [comment]
Have you enabled JIT?

**Comment by nadiaholmquist** [comment]
Computer specs? OS?

melonDS should run full speed on most devices, even phones from the last few years can handle it.

If you have a very low end PC, try NO$GBA.

**Comment by TsukiZero** [comment]
JIT is enabled (by default, last I checked)

I think my PC is low end (AMD, "six" core, 3.3ghz; 8 gb ram, Geforce GTX 970), but it is able to run a decent number of recent games with little to no issue.

**Comment by TsukiZero** [comment]
OK, looking deeper, it might be a game-specific issue, because DeSmuME is handling the 3D part well, but when there's too many 2D assets its FPS dips; and the exact opposite happens with MelonDS. Even stranger is that Phantasy Star Zero (which is pretty much all 3D) doesn't lose its framerate on either emulator UNLESS upscaling is on (and only at 4x+ factors).

**Comment by nadiaholmquist** [comment]
If you're having problems like this with DeSmuME as well it probably just is your CPU not being up to the task.

There's only so much that can be done to improve performance while preserving emulation accuracy, so this probably won't be fixed.

Try NO$GBA.

**Comment by TsukiZero** [comment]
NO$GBA is... Even worse for different reasons.

At this point I'd say only someone more tech-savvy could really check if the game specifically isn't doing something unnecessary to chug things... Which wouldn't surprise me, I've seen my fair share of games that behaves weirdly depending on emulator.
