### ISSUE TITLE
Different ARM Bios/Firmware names

### ISSUE THREAD

**Issue by Krutonium** [Arisotura/melonDS#204]
The most common NDS Dumping tool I could find, `dsbf_dump.nds` dumps the firmware with the names `BIOSNDS7.ROM`, `BIOSNDS9.ROM` and in the case of my DS, `FW576472.BIN`. I would like to propose 2 changes to the codebase:

1) The BIOS files for ARM7 & ARM9 be allowed to go by that name
2) The Firmware searched for by doing a search for `.BIN` files beginning with `FW` with 6 numbers after.

This will allow files dumped from a real DS via this tool to work correctly without renaming by the end user. Not that this is a hassle, for sure, but it would make it easier for a new user who just dumped their own files to get up and running.

Dumper Attached.

[189255-dsbf_dump_dldi.zip](https://github.com/StapleButter/melonDS/files/1424923/189255-dsbf_dump_dldi.zip)

**Comment by SatoMew** [comment]
Perhaps a better solution would be not to look for specific filenames but to allow the user to specify their path (relative or absolute) in the INI file and exposing this on the UI.

**Comment by StapleButter** [comment]
this is planned, eventually
