### ISSUE TITLE
Fullscreen/Stretch

### ISSUE THREAD

**Issue by Catarax** [Arisotura/melonDS#205]
A fullscreen without bar and options for stretching a bit more would be nice, thank you!

**Comment by Shideravan** [comment]
That's something missing in this awesome emulator yet, unfortunatelly

**Comment by StapleButter** [comment]
I'm just not too sure how I'd go about scaling screens in different modes if we break the assumption that we can preserve their aspect ratio (the current scaling code is based entirely on that)

**Comment by WaluigiWare64** [comment]
fullscreen was added in ea64039

**Comment by WaluigiWare64** [comment]
Fullscreen was added in https://github.com/Arisotura/melonDS/commit/ea640398f9d2a28a8807e618ab79c5b6a7960d00, and stretch was added in https://github.com/Arisotura/melonDS/commit/b9a56bc4e47bbb315f88ba5eaa57ce2b3efece73.
