### ISSUE TITLE
Any thoughts on android support sometime soon?

### ISSUE THREAD

**Issue by leem919** [Arisotura/melonDS#227]
The title says it all! You should think about it! I would LOVE to have your amazing emulator in my pocket when I want to do VS in SM64-DS with a couple buddies.

**Comment by strikersix23** [comment]
Sorry for the very late response but that may not be implemented try using retroarch as includes the melonds core

**Comment by strikersix23** [comment]
and i am not speaking for the dev

**Comment by Emulatorer** [comment]
DrasTic is the best DS emulator for android and soon to be open-soures...

**Comment by Arisotura** [comment]
there was an attempt at an Android frontend but not by me. right now I have enough on my plate so Android support will not be coming from me for a while.

**Comment by RSDuck** [comment]
the libretro frontend has finally received some love in recent times. Though I wouldn't put my hopes to high up, because performance likely won't that good, atleast until not until the Arm64 dynarec is ready and some further optimisations are done.

**Comment by Gamemulatorer** [comment]
This issue can be close now there is already an android port of melonDS here https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2

**Comment by poudink** [comment]
it's not official though so idk about closing the issue

**Comment by Arisotura** [comment]
my stance is still the same, I deal with the melonDS core and desktop version and that's enough.
