### ISSUE TITLE
[FEATURE REQUEST] The option to clear firmware settings

### ISSUE THREAD

**Issue by PeladoFeo** [Arisotura/melonDS#229]
On a real console, this involves removing the battery, waiting a while and reinserting the battery.

**Comment by scottbeebiwan** [comment]
could someone provide more information? i can't seem to find any documentation of how this TECHNICALLY works, or i'm looking in the wrong places.

**Comment by StapleButter** [comment]
you can do System->Run with no game loaded, which will run the firmware. from there you can change the configuration.

**Comment by Zettymaster** [comment]
can we close this, as it already seems possible and easy enough to not need a menu entry.
