### ISSUE TITLE
Firmware settings (possible tool)

### ISSUE THREAD

**Issue by strikersix23** [Arisotura/melonDS#232]
I have been comparing some of your code to Desmume and some of the issues with firmware settings and i found a tool on the Github of desmume that might help with people with firmware settings. This might be possible to integrate into melonds for linux and as separate tool
for windows.

Here is the link of the tool (source code)

https://github.com/TASVideos/desmume/tree/master/tools/nds_firmware_tool

**Comment by scottbeebiwan** [comment]
why though? isn't it good enough to change the firmware settings within the built-in setup?

**Comment by strikersix23** [comment]
That depends i personaly like the firmware from my own ds because it helps emulation and compatilibity
