### ISSUE TITLE
[Feature request] Fullscreen

### ISSUE THREAD

**Issue by Shideravan** [Arisotura/melonDS#237]
That would be nice, run the games with this awesome emulator without the "visual pollution" of the gui
Thanks!

**Comment by wingedonezero** [comment]
I vote for this as well although you would need texture scaling and or filtering to make it look good and not blurry. Which will come when he adds the hw renderer. Hopeful sooner than later. I created a feature request for the hw renderer and linked to this in the mean time.

**Comment by KrossX** [comment]
F11 now toggles fullscreen, with a libui hack to hide the menu on Windows.

[changes_fullscreen.zip](https://github.com/StapleButter/melonDS/files/2555896/changes_fullscreen.zip)

**Comment by Anuskuss** [comment]
Can we also get an `-f` / `--fullscreen` command line option with this?

**Comment by Arisotura** [comment]
yeah, once I get there

**Comment by Shideravan** [comment]
Thanks! But why isn't this option in the main release yet?

**Comment by Shideravan** [comment]
Also, it's fun that some users are sharing unnoficial workarounds for this (LOL)
https://www.youtube.com/watch?v=oBDwXyH8oGM

**Comment by poudink** [comment]
added in https://github.com/Arisotura/melonDS/commit/ea640398f9d2a28a8807e618ab79c5b6a7960d00

**Comment by teconmoon** [comment]
Some feedback based on the latest nightly, if you specify a joystick hotkey for fullscreen, that is not properly saved in the config. Subsequently launching the program will show the hotkey mapped to Toggle FPS Hotkey.

Also, any momentum on adding a cli flag for fullscreen? This would be helpful for adding the emulator to things like Playnite or Launchbox.

**Comment by WaluigiWare64** [comment]
PR #821

**Comment by WaluigiWare64** [comment]
@teconmoon fixed with a1cf196

**Comment by WaluigiWare64** [comment]
melonDS has a fullscreen feature as of melonDS 0.9.1.
Config -> Input and Hotkeys -> General Hotkeys.

**Comment by Anuskuss** [comment]
@WaluigiWare64 I would consider https://github.com/Arisotura/melonDS/issues/237#issuecomment-483508367 as part of the feature request and AFAICT it's not implemented yet.

**Comment by varlesh** [comment]
Vote to command line option.
`melonDS --fullscreen`
All popular emulators have this option (or option on config start roms with fullscreen mode). It's very comphortable for usage with Launchbox, Pegasus and other launchers with gamepads. And do not press constantly F11

**Comment by Anuskuss** [comment]
@varlesh Check out [my fork](https://github.com/Anuskuss/melonDS/actions/runs/879435713) if you need that functionality right now. Just run it from command line (you don't need any flags).

**Comment by varlesh** [comment]
@Anuskuss Big thx man !!! It's worked.
Linux version: https://github.com/Anuskuss/melonDS/suites/2838282579/artifacts/63304812
Windows version: https://github.com/Anuskuss/melonDS/suites/2838282569/artifacts/63306364

**Comment by varlesh** [comment]
Who don't want wait next release here Linux x64 binary (can extract on `~/.local/bin`):
[melonDS.tar.gz](https://github.com/Arisotura/melonDS/files/8810957/melonDS.tar.gz)
