### ISSUE TITLE
[Feature Request] Hw renderer

### ISSUE THREAD

**Issue by wingedonezero** [Arisotura/melonDS#239]
I know its on your todo list but considering a ton of games run pretty well at this point i figured id open the request. I saw someone else mention full screen on issue #237 and that wouldn't make sense unless we had this. And the texture scaling, shaders, filters and so on you mentioned. Melon ds is the future of ds emulation as a lot of people have been saying. And this would help push it forward in that direction.

**Comment by Shideravan** [comment]
Why fullscreeen wouldn't make sense unless there's other things implemented?
A lot of emulators such MAME doesn't have (and maybe never will have) HW renderer but have the option to run in fullscreen...
I don't understand the logic in which if the user preffer to run a game without visual pollution from the GUI  necessarily has to use these extra features...
Also, fullscreen is much easier to implement than a hw renderer... I also like the idea to give the users every possible option, but it's a lot easier to implement fullscreen than the options which you're requesting
