### ISSUE TITLE
WarioWare D.I.Y. Saving doesn't work

### ISSUE THREAD

**Issue by scottbeebiwan** [Arisotura/melonDS#250]
No .SAV is created, and the shop employee doesn't remember my name. Hoping this will be the first emulator to actually support WWDIY. (at least afaik no emulators support WWDIY saves)

**Comment by zeromus** [comment]
https://github.com/StapleButter/melonDS/issues/258

**Comment by StapleButter** [comment]
giving this the generic tags, although afaik that game has fancypants rewritable ROM (technically NAND, but eh)

**Comment by StapleButter** [comment]
"Hoping this will be the first emulator to actually support WWDIY. (at least afaik no emulators support WWDIY saves)"

not quite right there. DeSmuME supports it.

**Comment by benderscruffy** [comment]
can be closed now
