### ISSUE TITLE
[Feature Request] Hardware acceleration using KVM for ARM hosts

### ISSUE THREAD

**Issue by baconwaifu** [Arisotura/melonDS#251]
ARM hosts can use KVM for native emulation of ARM targets, and the Raspberry pi, which (somewhat) supports this, currently lacks a decent DS emulator. I suggest for implementing KVM as a backend for emulation. Given the *relatively* abstract interface for the `NDS` namespace, this *should* be relatively simple (compared to the tangled mess that is desmume, and not accounting for the actual KVM implementation)
Currently working on a pull request, but don't have much free time (and haven't looked at the code enough to tell what I need to rewrite)
Suggest adding a build flag for ARM targets to enable it at compile time.

**Comment by StapleButter** [comment]
not sure you can run DS ARM code on more recent CPUs. DS ARMs have quirks
that behave differently in more recent CPUs, and that games can rely in as
they run on bare metal.

**Comment by baconwaifu** [comment]
Depending on what instructions have quirks, and how often they're called, it might still be doable to trap and emulate them without tanking performance as much as a full interpreter. The most major problem I can see is the lack of thumb mode on the arm7, meaning that code targeting it might have branches accidentally jumping to thumb mode on cores that support it.

**Comment by strikersix23** [comment]
That's weird as kvm is used as an hypervisor framework for oses if you plan on doing that you need an custom os from ds

**Comment by StapleButter** [comment]
the ARM7 does support THUMB mode

anyway, might try it, but the DraStic guy said that doing something like that gave little to no performance boost.

also there's no 'custom OS from DS', games run on the bare metal. the BIOS provides a few services but that's about it.

**Comment by strikersix23** [comment]
A real firmware.bin shows there is a mini os in it

**Comment by strikersix23** [comment]
Exophase is right anyway Kvm won't do any performance enhancement as it is not meant for Game emulation. Try using better settings or graphics API appropriate for your os

**Comment by strikersix23** [comment]
AlsoStaple if you want the firmware.bin i have ill send to you for development

**Comment by baconwaifu** [comment]
You do realize you're talking about sending the firmware.bin to the person who *created* the project, right? I'm pretty sure they already have several copies of it.
The NDS firmware is a just a simple boot environment that is mostly discarded when an application loads; The best way to describe it would be a built-in "game" in the sense that every game runs it's own engine on bare metal. there is no OS on top of the game aside from the BIOS, which is mainly for hardware abstraction. (and some config settings in the firmware that games can access; which is what the 3DS DS mode firmware provides, IIRC)
On some embedded devices, KVM *could* hypothetically improve performance, however that would only work if your bottleneck was the CPU emulation, KVM for this application would require a pretty bad CPU emulator in order for it to have any performance benefit, as it's overhead is pretty high around context switches

**Comment by strikersix23** [comment]
I Agree with you there would have to would need a bad CPU emu to use  KVM anyway I think it would not be a good idea for right now and a lot of work for the dev

**Comment by RSDuck** [comment]
There's infrastructure for JIT recompilers and two backends now, if anyone wants to add 32-bit ARM support to it, go ahead. Though 32-bit is dead anyway.
