### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by LOuroboros** [Arisotura/melonDS#255]
Hi. Before stating the problem, I have to say that this is the first time I ever try to use this CodeBlocks application.
Right now, the official download seems to be down so I'm using CodeBlocks v17.12, I have no idea if it's the latest stable version or not.

Alright, what I basically did was:
**1)** I downloaded melonDS' source
**2)** Ran melonDS.cbp with CodeBlocks
**3)** After reading [this issue](https://github.com/StapleButter/melonDS/issues/240), I pointed the compiler to a 64-bits version of MinGW, [like this](https://i.imgur.com/Oed2o1u.png).
**4)** Then I just chose "Release Windows" in CB's main window, and went to Build > Build.

The result is this log full of warnings and errors.
https://pastebin.com/19CjCeRY

It looks like there's a header file called "SDL.h" missing or something?
Could anyone tell me what am I doing wrong here? Sorry for bothering and thanks for reading :)

**Comment by StapleButter** [comment]
you need to install the SDL2 dev package

**Comment by LOuroboros** [comment]
Thank you @StapleButter, I think that I more or less got it. A quick google search took me to a post in GameDev.net where I found a video showing how to setup SDL2 for Code Blocks, I followed it and well, it looksl like it almost works now. I'm still getting an error, but at least it's a different one now.
> C:\Users\Lunos\Desktop\melonDS\src\libui_sdl\main.cpp|1269|error: 'strncpy' was not declared in this scope|

Full log: https://pastebin.com/YpXXdE45

**Comment by StapleButter** [comment]
see if the last revisions fix it?

**Comment by RSDuck** [comment]
we have a new build system now
