### ISSUE TITLE
Jam with the Band (Europe) (En,Fr,De,Es,It) fails to load data

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#258]
![jam](https://user-images.githubusercontent.com/2696404/47598650-9d954d80-d9d1-11e8-96b5-8b6503512ae3.PNG)

**Comment by benderscruffy** [comment]
i think this is the anti piracy

**Comment by zeromus** [comment]
no, it's the fact that the game requires a NAND game card.

**Comment by StapleButter** [comment]
so...

tried coding some NAND support, got to a point where the game proceeds without shitting itself

but every time I run it, it ignores the save file and starts over

same thing it does in DeSmuME.

I guess this needs further investigation.

**Comment by benderscruffy** [comment]
has been fixed in 0.9.2
