### ISSUE TITLE
Running melonDS on macOS

### ISSUE THREAD

**Issue by IamRifki** [Arisotura/melonDS#261]
I'm not sure if MelonDS should be able to run on mac or not, but when trying to compile it, it seems like it doesn't have that many errors. https://gist.github.com/IamRifki/6df3dc310eccb692822a0926bf799776

**Comment by joshleaves** [comment]
Managed to compile it on my side using this
- `brew install gettext && brew link gettext --force`

Could run the emulator and run a game.

However:
- Warnings about GDK-PixBuf when opening the menu bar:
```
(<unknown>:55617): Gtk-WARNING **: 11:57:45.684: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

- Segmentation fault when trying to access the "Input config dialog".

(Suggestion: rename this thread to "Running Medusa on Mac OS X" ?)

**Comment by IamRifki** [comment]
Thanks for your suggestion, unfortunately i still wasn't able to compile it, same errors and everything, that that brew command did not work on my end

**Comment by IamRifki** [comment]
Tried it out with the latest commit, it compiles, but with a couple of warnings and this happens if I start the executable 
```
(process:43118): Gtk-WARNING **: 20:41:47.432: Locale not supported by C library.
	Using the fallback 'C' locale.

(<unknown>:43118): GLib-GObject-CRITICAL **: 20:41:47.436: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(<unknown>:43118): GLib-GObject-CRITICAL **: 20:41:47.436: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(<unknown>:43118): GLib-GObject-CRITICAL **: 20:41:47.436: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(<unknown>:43118): GLib-GObject-CRITICAL **: 20:41:47.436: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(<unknown>:43118): GLib-GObject-CRITICAL **: 20:41:47.437: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Gtk-Message: 20:41:48.519: GtkDialog mapped without a transient parent. This is discouraged.


```

**Comment by aldelaro5** [comment]
I get very odd results. I performed the following commands

```
brew install pkgconfig
brew install sdl2
brew install gtk+3
```

This made cmake work, but it fails on compiling because it can't find the sdl.h header.  I was able to find the problem: it was searching under '/usr/local/include/SDL2' instead of /usr/local/include. I hacked the CMakeLists to solve this error, but then it failed on linking gtk despite the fact it is installed (I tried to append to my LDFLAGS environment variable to test and it does find it, but then can't find the next gtk librairy).

This seems to be a weird problem with cmake because it's as if it finds the packages, but can't have the paths setup properly which I don't understand.

**Comment by IamRifki** [comment]
Latest Commit compiles on my end, but with this happens when running now https://pastebin.com/FLdwiimA

**Comment by azoreseuropa** [comment]
I have an experienced compiling several emulators myself. This one is a problem. 

Am I missing something ? I have everything:

brew install pkgconfig
brew install sdl2
brew install gtk+3
brew install wxwidgets

I compiled it and I got an error after 100% complete:

undef: __ZN3LAN10SendPacketEPhi
undef: __ZN3LAN10RecvPacketEPh
undef: __ZN15DlgWifiSettings4OpenEv
undef: __ZN3LAN4InitEv
undef: __ZN3LAN6DeInitEv
Undefined symbols for architecture x86_64:
  "LAN::SendPacket(unsigned char*, int)", referenced from:
      Wifi::USTimer(unsigned int) in lto.o
  "LAN::RecvPacket(unsigned char*)", referenced from:
      Wifi::CheckRX(bool) in lto.o
  "DlgWifiSettings::Open()", referenced from:
      OnOpenWifiSettings(uiMenuItem*, uiWindow*, void*) in lto.o
  "LAN::Init()", referenced from:
      Wifi::Write(unsigned int, unsigned short) in lto.o
  "LAN::DeInit()", referenced from:
      EmuThreadFunc(void*) in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [melonDS] Error 1
make[1]: *** [CMakeFiles/melonDS.dir/all] Error 2
make: *** [all] Error 2
azoress-MacBook-Pro:build azoreseuropa$

**Comment by azoreseuropa** [comment]
Sorry to bother you but can anybody help ?

**Comment by IamRifki** [comment]
Update latest commit broke MacOS support 
`/Users/rifkik/Downloads/melonDS-master/src/libui_sdl/LAN_PCap.cpp:36:11: fatal error:
      'linux/if_packet.h' file not found
        #include <linux/if_packet.h>
                 ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/melonDS.dir/src/libui_sdl/LAN_PCap.cpp.o] Error 1
make[1]: *** [CMakeFiles/melonDS.dir/all] Error 2
make: *** [all] Error 2`

**Comment by Arisotura** [comment]
welp. I need to figure out what's the MacOS equivalent for that file.

**Comment by azoreseuropa** [comment]
I compiled it for the macOS.. almost successfully. It stopped at 68 percent. Error:
/Users/blank/melonDS/src/libui_sdl/libui/darwin/window.m:237:1: warning: 
      'NSWindow' may not respond to 'contentHuggingPriorityForOrientation:'
uiDarwinControlDefaultHuggingPriority(uiWindow, window)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/blank/melonDS/src/libui_sdl/libui/darwin/../ui_darwin.h:138:32: note: 
      expanded from macro 'uiDarwinControlDefaultHuggingPriority'
                return [type(c)->handlefield contentHuggingPriorityForOr...
                        ~~~~~~~~~~~~~~~~~~~~ ^
/Users/blank/melonDS/src/libui_sdl/libui/darwin/window.m:238:1: warning: 
      'NSWindow' may not respond to 'setContentHuggingPriority:forOrientation:'
uiDarwinControlDefaultSetHuggingPriority(uiWindow, window)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/blank/melonDS/src/libui_sdl/libui/darwin/../ui_darwin.h:143:25: note: 
      expanded from macro 'uiDarwinControlDefaultSetHuggingPriority'
                [type(c)->handlefield setContentHuggingPriority:priorit...
                 ~~~~~~~~~~~~~~~~~~~~ ^
/Users/blank/melonDS/src/libui_sdl/libui/darwin/window.m:370:11: error: 
      conflicting types for 'uiNewWindow'
uiWindow *uiNewWindow(const char *title, int width, int height, int hasMenubar)
          ^
/Users/blank/melonDS/src/libui_sdl/libui/darwin/../ui.h:127:22: note: 
      previous declaration is here
_UI_EXTERN uiWindow *uiNewWindow(const char *title, int width, int heigh...
                     ^
2 warnings and 1 error generated.
make[2]: *** [src/libui_sdl/libui/CMakeFiles/libui-temporary.dir/darwin/window.m.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/libui_sdl/libui/CMakeFiles/libui-temporary.dir/all] Error 2
make: *** [all] Error 2

**Comment by azoreseuropa** [comment]
Have you figured it out, @Arisotura ? 

And can you take a look at my error ? I think it is something to do with Windows that isn't acceptable for macOS, I don't know.

**Comment by azoreseuropa** [comment]
> welp. I need to figure out what's the MacOS equivalent for that file.

Have you figure it out for the macOS ?

**Comment by azoreseuropa** [comment]
???

**Comment by IamRifki** [comment]
Aris said in IRC that she might support macOS if it was feasible, closing this issue until further notice.

**Comment by alexwiedermann** [comment]
I not sure but a believe melonDS doesn't not support MacOS 10.15.
Some OpenGL libraries are deprecated
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl.h:2490:13: note: 'glFlush' has been explicitly marked deprecated here
extern void glFlush (void) OPENGL_DEPRECATED(10.0, 10.14);

**Comment by azoreseuropa** [comment]
I hope it can be resolve someday. I guess.
