### ISSUE TITLE
Make it compile on Windows with MSVC

### ISSUE THREAD

**Issue by KrossX** [Arisotura/melonDS#272]
Here's a few changes and a crappy makefile I ended up making. It works with the msvc 14.13 (VS2017) compiler I used it with.  I was gonna try and see if I could make the fullscreen mode but didn't want to get codeblocks or mingw. 

I noticed no speed difference, although I don't have a fancy CPU with AVX to try and compile it with. Less dlls though, which is nice I think.

As for the changes. The change in `Config.cpp` makes both defines point to the same version. Otherwise I would get an error due to mismatch. The change in `libui_sdl/Platform.cpp` makes it so that `PCAP_OPENFLAG_PROMISCUOUS` is defined, I don't know if it has to be a zero or one though, otherwise there would be an error since it's referenced later on the file.

[makefile_and_diff.zip](https://github.com/StapleButter/melonDS/files/2555769/makefile_and_diff.zip)

**Comment by StapleButter** [comment]
I guess this will need updating due to changes in the code this affects.

PCAP_OPENFLAG_PROMISCUOUS is defined to 1.

I need to rework that code and how pcap is integrated anyway.

**Comment by KrossX** [comment]
Here's an updated set. It outputs a few warnings:
```

src/Config.cpp(129): warning C4477: 'fprintf' : format string '%s' requires an argument of type 'char *', but variadic argument 2 has type 'void *'
src/NDS.cpp(1211): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'u64'
src/NDS.cpp(1211): note: consider using '%llu' in the format string
src/NDS.cpp(1211): note: consider using '%Iu' in the format string
src/NDS.cpp(1211): note: consider using '%I64u' in the format string
src/NDS.cpp(1212): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'u64'
src/NDS.cpp(1212): note: consider using '%llu' in the format string
src/NDS.cpp(1212): note: consider using '%Iu' in the format string
src/NDS.cpp(1212): note: consider using '%I64u' in the format string
src/NDS.cpp(3224): warning C4552: '&': result of expression not used
src/libui_sdl/libui/windows/colordialog.cpp(859): warning C4312: 'type cast': conversion from 'int' to 'HMENU' of greater size
```
Only a small change was required to the source:

```diff
-    #define NTDDI_VERSION		0x06000000 // GROSS FUCKING HACK
+    #define NTDDI_VERSION		NTDDI_WIN6 // GROSS FUCKING HACK
+    #define _WIN32_WINNT _WIN32_WINNT_WIN6
+    #define WIN32_LEAN_AND_MEAN
```
[makefile_and_diff.zip](https://github.com/Arisotura/melonDS/files/3175112/makefile_and_diff.zip)

**Comment by MojoJojoDojo** [comment]
How can I use this? 
Can I enable PGO when I compile? 
Thanks.

**Comment by NarryG** [comment]
Have you updated this to support the latest version? I've been trying to get it working but I've been running into countless errors due to the addition of the OpenGL renderer. C++ build config is not my forte.

**Comment by KrossX** [comment]
That one was before the OpenGL update. Here's a current one, needs more changes though but it compiles.

[makefile_and_diff.zip](https://github.com/Arisotura/melonDS/files/3316637/makefile_and_diff.zip)

**Comment by NarryG** [comment]
Thanks! Less changes than I had to make to get it to build via cmake (did over the time after I posted my question).

Is dropping that aligned macro safe? If I'm not mistaken, this is C++11 so we have alignas right?

**Comment by Ace4896** [comment]
Yeah, it's C++ 11, so we could just prefix those with `alignas(8)` so we don't have to drop the aligned macro.

@NarryG How did you get CMake to find `GL/glext.h`? Apparently this header was in the `opengl-registry` vcpkg package, but CMake doesn't want to use it for some reason...

**Comment by KrossX** [comment]
The macro wasn't dropped though, it was added. It replaces the GCC extension. I didn't know about `alignas`, does it work like how the extension seems to? As in, per tagged member vs entire struct.

**Comment by Ace4896** [comment]
Ah, my bad, I thought the macro was removed.

`alignas` is like the original `__attribute__` extension, so we'd tag each member we want to align, except we add `alignas` as a prefix:

```diff
-    u32 BGOBJLine[256*3] __attribute__((aligned (8)));
+    alignas(8) u32 BGOBJLine[256*3];
```

**Comment by KrossX** [comment]
Thanks! That worked quite fine.
I'll close this since there's now a PR to use instead.

**Comment by NarryG** [comment]
@Ace4896 I gave up on that and swapped gl.h and glext.h out for glew.h. I had a ton of issues getting everything linked so my current cmakelists are an absolute disaster. I may take #467 and see if I can get cmake working on top of it without needing to swap to glew.
