### ISSUE TITLE
Suggestion: Option to simulate cart removal

### ISSUE THREAD

**Issue by hiccupjul** [Arisotura/melonDS#293]
Would be useful for testing crashes and activating certain debug screens (e.g. in some Nintendo EAD games and the DS firmware).

**Comment by Arisotura** [comment]
done

**Comment by hiccupjul** [comment]
Nice, I downloaded the autobuild of 709a598 and I can trigger the PictoChat version screen (colour screen) and the [debug screen](https://tcrf.net/New_Super_Mario_Bros.#Crash_Debugger) in NSMB.

**Comment by Arisotura** [comment]
it's also part of the 0.9.4 release :P

**Comment by hiccupjul** [comment]
oh right, i just assumed you had only just commited it. i will downgrade back to 0.9.4 lol
