### ISSUE TITLE
Glitch in Adventure Time: Hey Ice King! Why'd You Steal Our Garbage?

### ISSUE THREAD

**Issue by kurayami6** [Arisotura/melonDS#294]
Notice the line going through the circle next to the attack option?

![capture](https://user-images.githubusercontent.com/31968468/49619642-88b8ca80-fa11-11e8-82bc-f2aba2b440ec.PNG)

**Comment by StapleButter** [comment]
can I get to that part relatively quickly, or do you have a savefile I can use?

**Comment by kurayami6** [comment]
It's about 5 minutes into the game.

**Comment by benderscruffy** [comment]
does this still happen in 0.7.3

**Comment by kurayami6** [comment]
Yes it does. 
![capture2](https://user-images.githubusercontent.com/31968468/50796447-b309ea80-1325-11e9-89bd-b42ba7f5335c.PNG)

**Comment by kurayami6** [comment]
This is fixed as of 0.8.1
![Capture](https://user-images.githubusercontent.com/31968468/59461526-eb799b80-8e64-11e9-91de-94298ea14aa6.PNG)

**Comment by Arisotura** [comment]
does that happen in other emulators too? I guess it's the same bug as the iCarly one
