### ISSUE TITLE
Extra items in Castlevania Dawn of Sorrow

### ISSUE THREAD

**Issue by ghost** [Arisotura/melonDS#298]
If you play Castlevania Dawn of Sorrow while Aria of Sorrow is in the DS' GBA slot, you unlock several bonus items. I'm not sure if it's possible to emulate this, but I thought I'd point it out anyway.

**Comment by extherian** [comment]
I believe code for this has already been merged into melonDS as of commit 548432c, there's just no way to select it in the GUI yet.

**Comment by StapleButter** [comment]
'for later'

it just returns 0xFF bytes, but it's there, and checking EXMEMCNT properly.

we can later make it return meaningful crap, but I need to design a clean system for supporting multiple things in that slot (regular cart, cflash, guitargrip, rumblepak, etc).

same goes for slot1 btw.

**Comment by poudink** [comment]
wasn't this added with rzumer's gba cart connectivity pull request

**Comment by RSDuck** [comment]
yes it was
