### ISSUE TITLE
Problem with Xbox One controller

### ISSUE THREAD

**Issue by kurayami6** [Arisotura/melonDS#319]
Using an wired Xbox One controller with MelonDS. If the controller gets unplugged or disconnected at any point, it won't work with MelonDS again until I've shut down and restarted the emulator. Not sure if this affects other types of controllers. 

Using MelonDS 0.7.2 and Windows 7.

**Comment by StapleButter** [comment]
I guess the controller is seen as disconnected when it's off, or something like that.

melonDS doesn't reopen joystick handles. not sure how to detect if they need to be reopend (SDL_JoystickGetAttached()??).

**Comment by aoyawale** [comment]
Just started playing today some of the castlevania games and getting this. Using EmuDeck and melonDS 1.0, I'm using an 8bitdo controller which I increased the disconnect timer. Helps but, doesn't solve it.
