### ISSUE TITLE
Music crackle in Nostalgia (DS)

### ISSUE THREAD

**Issue by ghost** [Arisotura/melonDS#341]
During the opening cutscene. Specifically as the camera zooms in on the floating artifact and the girls says "what is this". Happens consistently. Doesn't happen on real hardware.

**Comment by StapleButter** [comment]
is it running at a solid 60FPS?

**Comment by kurayami6** [comment]
Yes, the game seems to be running full speed. It only crackles for a moment and in the exact same spot every time.

**Comment by StapleButter** [comment]
sounds like a timing problem then

**Comment by kurayami6** [comment]
Using 0.7.3 it now only crackles very slightly.

**Comment by nathanielcwm** [comment]
I don't hear any cracking on d5dbef2c22f755ad82ec59e04948111797bc270a

**Comment by iamthelaw2041** [comment]
Game sounds fine. No crackling whatsoever. This can be closed.

![Capture](https://user-images.githubusercontent.com/94656803/144363548-c15ab2a3-b26f-4c62-835a-d1ca17d45404.PNG)
