### ISSUE TITLE
Music crackles in Disney's Kim Possible: Global Gemini (USA)

### ISSUE THREAD

**Issue by ghost** [Arisotura/melonDS#345]
During the tutorial. Every time you close a dialogue box the music crackles for a brief moment. When this happens the FPS counter drops from a solid 60 to about 47 then goes right back to 60.

**Comment by StapleButter** [comment]
that's normal behavior, atleast for now.

**Comment by StapleButter** [comment]
although the slowdown might need investigation

**Comment by iamthelaw2041** [comment]
Game sounds fine. No crackling or FPS drops. This can be closed.

![Capture](https://user-images.githubusercontent.com/94656803/144476963-29170ff4-f7ea-4d97-ab8d-99e988ae94b3.PNG)
