### ISSUE TITLE
[Feature Request] Hotkey for toggling framerate limiter

### ISSUE THREAD

**Issue by Ace4896** [Arisotura/melonDS#347]
Would be nice to have a hotkey for this option (both keyboard and joystick).

**Comment by StapleButter** [comment]
noted

**Comment by Anuskuss** [comment]
I would also like these actions as hotkeys:
- Exit emulator
- Switch screen (1/2/both) and switch layout (h/v)
- Save/load state

P.S. speaking of layouts, it would be nice if melonDS would remember the layout I used on a per-game basis. Just an idea 😃

**Comment by Arisotura** [comment]
ideas noted
