### ISSUE TITLE
Coropata (Japan) missing black lines on top of speech bubbles during the intro

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#350]
using 0.7.3
![coro](https://user-images.githubusercontent.com/2696404/50733149-06aff300-11c3-11e9-89b4-63e5aa6fe219.PNG)
![coro1](https://user-images.githubusercontent.com/2696404/50733145-0283d580-11c3-11e9-83f4-33fb559afd18.PNG)

**Comment by Arisotura** [comment]
something to do with edge marking

**Comment by Arisotura** [comment]
the borders are rendered by submitting line-y polygons alongside the triangles that form the bubble. they take care to set proper Z values so nothing can be acting up there...

**Comment by Arisotura** [comment]
welp. this means I fail at line polygons.

**Comment by Arisotura** [comment]
noting that those are still not perfect according to the test I wrote, but atleast they render now
