### ISSUE TITLE
changing audio setting crashes out the emulator

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#351]
using 0.7.3
go to audio settings
change it to WAV file then load in any wav file and the emulator will crash out then everytime after you start the emulator up it will crash straight away 

so i have to choose white noise then load my wav file and it works fine

**Comment by StapleButter** [comment]
weird. I can't reproduce it.

anything special about your WAV files or platform or whatever?

**Comment by benderscruffy** [comment]
here is my wav
[yes-indeed.zip](https://github.com/StapleButter/melonDS/files/2731025/yes-indeed.zip)
