### ISSUE TITLE
[Linux]melonDS.ini not saved at the right location

### ISSUE THREAD

**Issue by John-Gee** [Arisotura/melonDS#352]
Hello,

I'm the one who left the comment about that on reddit and looked a bit into it.

So the problem seems to be this:

- You call Config.cpp's Save()

- It calls main.cpp's LocalFileExists 

- This in turn calls melon_fopen.cpp's melon_fopen_local

- That returns true because there is a config file in ~/.config/melonDS (it's the third path it checks for).

- We get back in Save(), which will then write a file by calling melon_fopen_local again

- This time the check will be on writing permission, not file's existence, which will work for the first test f = fopen(fileName, permissions);

and that's how we get the config file in cwd.

If you want I could write a patch, but I don't really understand the logic you have there with these 3 functions so I would need some explanation first, which would probably be more difficult that fixing this directly.

Thanks!

(I'll try to debug the gamepad issue too, but that's probably going to take more time)

**Comment by StapleButter** [comment]
outch! thank you for pointing out this oversight.

**Comment by Arisotura** [comment]
pls retest under Linux; should work, but we never know
