### ISSUE TITLE
The Strongest Demo by St. Vincent and the Grenadines white screens

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#354]
using 0.7.3
nothing but white screens
https://www.pouet.net/prod.php?which=52967

**Comment by Arisotura** [comment]
I figure this requires DLDI

**Comment by nathanielcwm** [comment]
Still on a white screen with dldi enabled on fbca473

**Comment by iamthelaw2041** [comment]
This works now. Can this be closed?

![Capture](https://user-images.githubusercontent.com/94656803/144358160-451d91d5-e5bf-405d-82eb-3feb831ff873.PNG)
