### ISSUE TITLE
[Linux]Unable to properly set more than one gamepad button in a row

### ISSUE THREAD

**Issue by John-Gee** [Arisotura/melonDS#358]
Hello,

so I've investigated it a bit, but because I don't know SDL and libui I'm stuck for now, and hoped you might know enough to help.

In DlgInputConfig.cpp you set the callback JoyPoll after clicking on a button in the UI.

Somehow, when I get the issue SDL_JoystickGetButton(joy, i) returns 1 for the button that was previously pressed, though nothing is pressed anymore. I'm able to easily see that by setting a breakpoint on https://github.com/StapleButter/melonDS/blob/214f9797fbbf40ae360b03eb4d90e1208c54eb73/src/libui_sdl/DlgInputConfig.cpp#L201 .

I start by a click on a button in the UI, and as long as I don't press on my gamepad, the breakpoint won't trigger. Once I press one, it triggers, and I just press resume. I then click on another button in the UI, and right away get the breakpoint to activate, which shouldn't happen. Obviously SDL_JoystickGetButton(joy, i) says a button is pressed down even though none is, so it looks like there is some sort of cache or something not refreshing.

**Comment by StapleButter** [comment]
well, I can't really see what I'd be doing wrong there. I mean, I'm calling SDL_JoystickUpdate() every time. I'd say that's some bug in your joystick driver or in SDL.

does it also cause sticky keypresses when playing a game?

**Comment by John-Gee** [comment]
I thought about it being a bug on my system, but antimicro seems to work fine and also uses SDL2. Now I have not looked at its code, but one potential thing is you're using the joystick API, maybe antimicro is using the gamecontroller one, and that's why it works.

I've just tried this SDL sample and it works fine: https://www.libsdl.org/tmp/SDL/test/testjoystick.c
If you don't have any idea there, maybe I should try shorten it as much as possible to just get the button pressed thing and see what is different with melonDS if anything.

I actually have never tried a game, I've only been trying to fix bugs so far. :) I'll try later and update this.

**Comment by John-Gee** [comment]
Now that's interesting because the sample that works indeed keeps polling for events with SDL_PollEvent().

I'm trying to write something smaller without a loop to see how/if it works. How could I simply workaround such issue to try it out?

**Comment by John-Gee** [comment]
I've just tried cat on the event and js devices.

On the js, it's clean, but on the event I don't even need to press anything to get my screen flooded, which makes me think you're right. I haven't tried pressing buttons because I wouldn't be able to tell anything... I don't remember that being the case before, but I also may have never tried looking at the event so maybe not.

**Comment by John-Gee** [comment]
I've just tried with the gamecontroller API instead of the joystick one, just in case, but there is no difference in the behavior.

**Comment by Ace4896** [comment]
Would also just like to mention that I occasionally encounter this issue in Linux (KDE Neon) with my DS4 controller as well. Usually, I can set all of the buttons without a problem, but if it does get stuck, then I can only set a couple buttons. I don't get any stuck key-presses in a game though after I get this issue in the input dialog.

I've also tried PR #362 which uses SDL events instead, and it seemed to be roughly the same for me.

**Comment by John-Gee** [comment]
I've just realized I have the same issue with m64p, so it really seems like it should be fixed in SDL or maybe the driver.
