### ISSUE TITLE
Crash when setting microphone input method

### ISSUE THREAD

**Issue by Ace4896** [Arisotura/melonDS#363]
I get a crash when I change audio settings with these steps:

1. Set microphone input method to WAV file, browse to a WAV file and save audio settings
2. Close and re-open the emulator
3. Open audio settings, change microphone input to something other than using a WAV file, and save audio settings
4. Open audio settings again, change microphone input to WAV file and save audio settings. The emulator just crashes out.

I'm not sure if this is the same as #351, but I used various WAV files to no success.

I've tested this on Linux, but I'll check Windows as well just in case. I didn't get anything too useful when running in a terminal either, it just crashes with a `Segmentation fault`.

I also noticed a few other things:
- In step 2, before re-opening the emulator, if I change the `MicWavPath` in the `.ini` file so that it points to a non-existent file, the crash doesn't occur, even if I continue to do steps 2-4 without changing the path in the `.ini` file.
- In step 4, if I change the path to the WAV file as well as setting the option, the crash doesn't happen, but repeating steps 2-4 again without changing the WAV file in the path will still crash out the emulator.

EDIT: This doesn't seem to occur on Windows, I'll see if I can narrow this down to something.

**Comment by Ace4896** [comment]
After using GDB on a debug build, I found that it segfaults at this line:

```
(gdb) start
Temporary breakpoint 1 at 0x4d580: file /home/jon/Documents/Repos/GitHub/melonDS/upstream/src/libui_sdl/main.cpp, line 1654.
Starting program: /home/jon/Documents/Repos/GitHub/melonDS/upstream/build/melonDS
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffdac8)
    at /home/jon/Documents/Repos/GitHub/melonDS/upstream/src/libui_sdl/main.cpp:1654
1654    {
(gdb) continue
Continuing.
melonDS 0.7.3
http://melonds.kuribo64.net/
[New Thread 0x7fffd8611700 (LWP 14587)]
[New Thread 0x7fffc3fff700 (LWP 14588)]
[New Thread 0x7fffc37fe700 (LWP 14589)]
[New Thread 0x7fffc2ffd700 (LWP 14590)]
[New Thread 0x7fffc099e700 (LWP 14592)]
[New Thread 0x7fffa2456700 (LWP 14593)]
[New Thread 0x7fffa1c55700 (LWP 14594)]

Thread 1 "melonDS" received signal SIGSEGV, Segmentation fault.
0x000055555559db6b in MicLoadWav (name=0x5555558f7060 <Config::MicWavPath> "/home/jon/Downloads/test.wav")
    at /home/jon/Documents/Repos/GitHub/melonDS/upstream/src/libui_sdl/main.cpp:187
187                 u16 val = ((u16*)buf)[res_pos];
```

**Comment by Arisotura** [comment]
likely same as #351 -- pls check again now

**Comment by Ace4896** [comment]
Seems to be fixed in latest revision now, thanks for the heads up.
