### ISSUE TITLE
DTM Race Driver 3 - Create & Race (Germany) (En,Fr,De,Es,It) glitchy black lines on car

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#368]
using 0.7.3
![dtm](https://user-images.githubusercontent.com/2696404/51419838-93e24700-1bc8-11e9-9040-4727d19f0325.PNG)

**Comment by Arisotura** [comment]
weird. no idea what could be causing that.

**Comment by benderscruffy** [comment]
still happens in 0.8.1

**Comment by Arisotura** [comment]
gave it a quick test. this also occurs on hardware.
