### ISSUE TITLE
Awa Tama (Japan) freeezes up during the intro

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#369]
using 0.7.3
the emulator freezes up during the intro with the music still playing

**Comment by benderscruffy** [comment]
still happens in 0.8.1

**Comment by Arisotura** [comment]
does it happen on 0.7?

**Comment by benderscruffy** [comment]
yep happens on 0.7

**Comment by Arisotura** [comment]
o so there's a chance this isn't some timing issue :P 

let's see

**Comment by Arisotura** [comment]
it's odd because it happens on 0.8 but not 0.8.1 here

**Comment by benderscruffy** [comment]
still happens for me on 0.8.2

**Comment by Arisotura** [comment]
weird

my ROM SHA1 is: 8251E8368FF7DA4214C5DD2B21DB7B82BE057BB9

does that match yours?

**Comment by JMC47** [comment]
I can confirm this issue is happening in melonDS 0.8.2.

**Comment by Arisotura** [comment]
melonDS 0.8.2 release build here. it's not freezing.

I need to go as far back as 0.7 to get a freeze.

try deleting your savefile??

I don't see how else this is possible. JMC verified that he's using the same ROM as me, so I don't see what paranormal force can be causing different results

**Comment by benderscruffy** [comment]
my rom sha1 is different
this is from no intro
![awa](https://user-images.githubusercontent.com/2696404/61165113-b8ebbd00-a54e-11e9-8f98-54688e1b894c.PNG)

**Comment by benderscruffy** [comment]
ok i just figured it out 
got to blow into microphone (DUHHH)
closing
