### ISSUE TITLE
Dream Day - Wedding Destinations (Europe) music is buzzing or  staticky on one channel

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#371]
using 0.7.3
choose any couple then it doesnt matter if you choose spa or jewelry store and about a minute or 2 the music will start to sound  staticky on one channel

**Comment by Arisotura** [comment]
sounds like another timing issue

it's weird that it would only do that on one channel tho

**Comment by iamthelaw2041** [comment]
I've been on this screen for a few minutes and don't hear any static. Is this still happening for you or can this be closed? 

![Capture](https://user-images.githubusercontent.com/94656803/144478247-e40dcd78-8530-4074-820b-726df0a7df28.PNG)
