### ISSUE TITLE
Dragon Quest 9 saves not loading

### ISSUE THREAD

**Issue by Luke-MacInnes1803698** [Arisotura/melonDS#374]
When playing dragon quest 9 saves can be created and the .sav file is made, but when the game is closed and then restarted there is no option to load game as if the file isn't being found or something, I've also noticed that some savestates don't load

**Comment by Arisotura** [comment]
are you using regular saves alongside savestates?

**Comment by Snagglepup** [comment]
> are you using regular saves alongside savestates?

Neither seem to work properly for me, if I make a new game go straight to first church save and quit, when the game is loaded the save isn't available on the title, and savestates don't just crash if I close and then re-open the emulator

**Comment by benderscruffy** [comment]
normal saves work for me
![dragon](https://user-images.githubusercontent.com/2696404/52894522-b4141e80-31e5-11e9-88ff-7d5b182552ca.PNG)
![dragon1](https://user-images.githubusercontent.com/2696404/52894523-b70f0f00-31e5-11e9-83df-04e64576a19e.PNG)

**Comment by Snagglepup** [comment]
That's a different game

**Comment by benderscruffy** [comment]
yep sorry just noticed that myself

**Comment by benderscruffy** [comment]
sorry here it is
![dragon](https://user-images.githubusercontent.com/2696404/52894727-ea539d00-31e9-11e9-8129-2c5e2cb155de.PNG)
![dragon1](https://user-images.githubusercontent.com/2696404/52894729-ecb5f700-31e9-11e9-802f-5a4c37e02e1e.PNG)

**Comment by Snagglepup** [comment]
I'm not sure then, cause when I save a file is made but I don't have the option to load on the menu

**Comment by iamthelaw2041** [comment]
Saving works fine. This can be closed.

![Capture](https://user-images.githubusercontent.com/94656803/144368966-b0409aac-00e7-4134-b6a0-03220fdf4432.PNG)
