### ISSUE TITLE
iCarly - Groovy Foodie! (USA)graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#375]
using 0.7.3
on the title screen there is green glitchy lines and during game  play there are glitchy red lines in the completed bar in the top screen
![icarly](https://user-images.githubusercontent.com/2696404/52172197-971f2a80-27a5-11e9-9f8c-b4020576b4ab.PNG)
![icarly1](https://user-images.githubusercontent.com/2696404/52172199-99818480-27a5-11e9-97cd-36f59c9c3526.PNG)

**Comment by Arisotura** [comment]
3D renderer accuracy issue, I guess. interesting

**Comment by Arisotura** [comment]
ok, quick testing shows that both DeSmuME and NO$GBA also have this bug

guess this is going to be interesting

unless it also occurs on hardware?

**Comment by Arisotura** [comment]
confirmed to not occur on hardware

so, sit down and fasten your belt, this is going to be a fun ride

**Comment by Arisotura** [comment]
first of all we can take down the 3D label as that has nothing to do with it

the titlescreen logo is made with sprites; it seems to be doing something weird like changing them midframe

**Comment by Arisotura** [comment]
well yeah it's updating the OAM midframe. welp

trying to figure out why that's shitting itself, tho

**Comment by Arisotura** [comment]
for example: it updates OAM right before scanline 30 (during the hblank period of scanline 29), but the changes aren't supposed to apply till scanline 31

I think it's because the hardware renders sprites one scanline in advance or something like that, but I need to do hardware tests
