### ISSUE TITLE
Bad Apple Demo music is glitchy

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#377]
using 0.7.3
music plays for a second or 2 then repeats itself then continues on then keeps repeating 
https://gbatemp.net/threads/bad-apple-for-the-nintendo-ds.466504/
here is the direct download
https://mega.nz/#!dgkmhSiL!5jLs7cIPuYO9R2oXaP8gGepAl9KeAEQ4heBsMl19Lsc

**Comment by Arisotura** [comment]
* demo is also running in a weird laggy fashion
* DeSmuME suffers from the exact same issues

this is quite probably a timing issue

**Comment by Arisotura** [comment]
odd notes, though

* NO$GBA runs it perfectly (despite its habit to run everything too fast)
* tweaking the cache timing values doesn't change shit

**Comment by Arisotura** [comment]
welp. the lag seems to be caused by the cart read delays

**Comment by Arisotura** [comment]
cart reg is set to E97F3FFF

but it's weird

it's like that code path is never triggered in NO$GBA

**Comment by Arisotura** [comment]
welp.

NO$GBA seems to just entirely avoid the bad codepath (faulty NitroFS driver) by mapping the ROM to the GBA slot (like how desmume did in the old days)

**Comment by Arisotura** [comment]
noting that the sound is still a little weird, but the lag is fixed

**Comment by Arisotura** [comment]
coming back to this: the ROM only works correctly on hardware because it uses the DLDI interface there. for some reason it tries to use NitroFS on melonDS, but its NitroFS driver is faulty -- if you force it to use that driver on hardware, it doesn't work.
