### ISSUE TITLE
Cars 2 (Europe) (En,Sv,Fi) (NDSi Enhanced) glitchy sounds

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#378]
using 0.7.3
during the race the car engines do not sound right

**Comment by JMC47** [comment]
Is this reproduceable in MelonDS 0.82?  If so, can you give a greater description of the issue.  The game sounds like a mess on both melonDS and my DS classic.

**Comment by Arisotura** [comment]
I think I tried and failed to hear anything wrong

**Comment by benderscruffy** [comment]
ok no probs
