### ISSUE TITLE
Challenge Me - Brain Puzzles (USA) missing grid

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#379]
using 0.7.3
choose picture logic and the grid is missing
![challenge](https://user-images.githubusercontent.com/2696404/52518122-a3f9bd80-2c80-11e9-9047-dfd57934030e.PNG)

**Comment by Arisotura** [comment]
sounds like some interesting 3D accuracy issue. does it also happen in other emulators?

**Comment by benderscruffy** [comment]
no

**Comment by Arisotura** [comment]
welp.

odd.

**Comment by Arisotura** [comment]
confirmed to be a bug in the software renderer. does not happen with OpenGL.

**Comment by Arisotura** [comment]
the background has the grid and all, cool and all

the problem is that the little quads that fill the grid are misaligned

**Comment by Arisotura** [comment]
the vertices at the bottom of the screen are sliiiightly below -1 (coord is FFFFEFFF instead of FFFFF000), which is causing it to get clipped

the clipping is in turn botching the texcoords a bit

I need to test this on hardware, tho
