### ISSUE TITLE
Error 52000 Connecting to Wi-Fi

### ISSUE THREAD

**Issue by Aarmaster11** [Arisotura/melonDS#381]
Upon adding the melonAP connection in the Wi-Fi settings, melonDS attempts to connect to the Internet and then times out with error 52000 (failed to obtain IP). I'm using the 0.7.3 build on an Ethernet connection.

![image](https://user-images.githubusercontent.com/1887380/52903667-e6764980-31ee-11e9-9b1e-e54e1ebbee9e.png)

**Comment by MojoJojoDojo** [comment]
You need to have Winpcap installed. 
Try npcap or winpcap.

**Comment by Aarmaster11** [comment]
I've tried both on my home computer and laptop and neither of them seem to make any difference. I've tried uninstalling and reinstalling countless times, do you think there may be remnants left over that are causing issues?

**Comment by MojoJojoDojo** [comment]
For the laptop use the official melonDS from the site and have Ethernet connected to it or create a bridged network.

**Comment by Aarmaster11** [comment]
I'm still not having any luck. I had a bunch of virtual switch adapters thanks to Hyper-V, but I disabled that and re-installed npcap again to no avail. I also tried winpcap, but that makes the game crash upon using anything that opens wireless communications (Pokémon save file select screen). Any other ideas?

**Comment by MojoJojoDojo** [comment]
Nah got nothing.
Wait for version 0.7.4 it gonna make things easier.

**Comment by MojoJojoDojo** [comment]
This build will fix any issues remaining for error 52000 : https://cdn.discordapp.com/attachments/506287145439461378/549327407820046336/melonds__adapter_list.rar

**Comment by Aarmaster11** [comment]
Nice, the build worked! I had to enable direct mode, but I get a successful connection message with the nds-constraint DNS. Thanks!
