### ISSUE TITLE
Building melonDS for macOS -- NEW PROBLEM.

### ISSUE THREAD

**Issue by azoreseuropa** [Arisotura/melonDS#383]
I have an experienced compiling several emulators myself. This one is a problem.

Am I missing something ? I have everything:

brew install pkgconfig
brew install sdl2
brew install gtk+3
brew install wxwidgets

I compiled it and I got an error after 100% complete:

undef: __ZN3LAN10SendPacketEPhi
undef: __ZN3LAN10RecvPacketEPh
undef: __ZN15DlgWifiSettings4OpenEv
undef: __ZN3LAN4InitEv
undef: __ZN3LAN6DeInitEv
Undefined symbols for architecture x86_64:
"LAN::SendPacket(unsigned char*, int)", referenced from:
Wifi::USTimer(unsigned int) in lto.o
"LAN::RecvPacket(unsigned char*)", referenced from:
Wifi::CheckRX(bool) in lto.o
"DlgWifiSettings::Open()", referenced from:
OnOpenWifiSettings(uiMenuItem*, uiWindow*, void*) in lto.o
"LAN::Init()", referenced from:
Wifi::Write(unsigned int, unsigned short) in lto.o
"LAN::DeInit()", referenced from:
EmuThreadFunc(void*) in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [melonDS] Error 1
make[1]: *** [CMakeFiles/melonDS.dir/all] Error 2
make: *** [all] Error 2
azoress-MacBook-Pro:build azoreseuropa$

**Comment by MojoJojoDojo** [comment]
I think Arisotura said you can only compile on Windows for now because of the recent code changes. 
So you have to wait I guess.

**Comment by azoreseuropa** [comment]
Ah. Okay, I thank you. I will wait then.

**Comment by Nadia-h** [comment]
Build commit 78c259121bac4a0adfabb2e07d06f81f64e54891, the newer ones after that are broken.

**Comment by azoreseuropa** [comment]
> Build commit [78c2591](https://github.com/Arisotura/melonDS/commit/78c259121bac4a0adfabb2e07d06f81f64e54891), the newer ones after that are broken.

I see. I guess I will wait for next one. Thanks you kindly.

**Comment by Arisotura** [comment]
WIP code. I didn't code the Linux side yet.

**Comment by azoreseuropa** [comment]
Now can I try and compile this build for macOS ?

**Comment by azoreseuropa** [comment]
I decide to give it another try. Something's new. I do this:

git clone https://github.com/Arisotura/melonDS.git
cd melonDS
export Qt5_DIR=$(brew --prefix)/opt/qt5
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja

Then I type ninja and I got this new error:

[12/88] Building CXX object src/CMakeFiles/core.dir/GPU3D_OpenGL.cpp.o
FAILED: src/CMakeFiles/core.dir/GPU3D_OpenGL.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++    -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -O3 -flto -fno-pic -std=gnu++11 -MD -MT src/CMakeFiles/core.dir/GPU3D_OpenGL.cpp.o -MF src/CMakeFiles/core.dir/GPU3D_OpenGL.cpp.o.d -o src/CMakeFiles/core.dir/GPU3D_OpenGL.cpp.o -c ../src/GPU3D_OpenGL.cpp
In file included from ../src/GPU3D_OpenGL.cpp:24:
../src/OpenGLSupport.h:24:10: fatal error: 'GL/gl.h' file not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
[15/88] Building CXX object src/CMakeFiles/core.dir/GPU2D.cpp.o
../src/GPU2D.cpp:731:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
../src/GPU2D.cpp:2743:33: warning: operator '<<' has lower precedence than '-'; '-' will be evaluated first [-Wshift-op-parentheses]
            pixelsaddr += (width-1 << 1);
                           ~~~~~^~ ~~
../src/GPU2D.cpp:2743:33: note: place parentheses around the '-' expression to silence this warning
            pixelsaddr += (width-1 << 1);
                                ^
                           (      )
2 warnings generated.
[17/88] Building CXX object src/CMakeFiles/core.dir/GPU3D.cpp.o
ninja: build stopped: subcommand failed.

Something to do with GPU3D.cpp.o

**Comment by azoreseuropa** [comment]
Anybody ? I wait for 7 days to give you time. :)
