### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by Delta456** [Arisotura/melonDS#385]
So I cloned the repo with the latest commit `5edf40` and I use Elementary OS Loki which is based on Ubuntu 16.04. I get the following errors:

`/tmp/ccz2oB5C.ltrans18.ltrans.o: In function `Wifi::DeInit()':
<artificial>:(.text+0x128f): undefined reference to `LAN_Socket::DeInit()'
<artificial>:(.text+0x12c5): undefined reference to `LAN_PCap::DeInit()'
/tmp/ccz2oB5C.ltrans23.ltrans.o: In function `OnOpenWifiSettings(uiMenuItem*, uiWindow*, void*)':
<artificial>:(.text+0x121): undefined reference to `DlgWifiSettings::Open()'
/tmp/ccz2oB5C.ltrans25.ltrans.o: In function `WifiAP::RecvPacket(unsigned char*)':
<artificial>:(.text+0x15d): undefined reference to `LAN_Socket::RecvPacket(unsigned char*)'
<artificial>:(.text+0x381): undefined reference to `LAN_PCap::RecvPacket(unsigned char*)'
/tmp/ccz2oB5C.ltrans25.ltrans.o: In function `WifiAP::SendPacket(unsigned char*, int)':
<artificial>:(.text+0xc11): undefined reference to `LAN_Socket::SendPacket(unsigned char*, int)'
<artificial>:(.text+0xc1b): undefined reference to `LAN_PCap::SendPacket(unsigned char*, int)'
/tmp/ccz2oB5C.ltrans27.ltrans.o: In function `Platform::LAN_RecvPacket(unsigned char*)':
<artificial>:(.text+0x156b): undefined reference to `LAN_Socket::RecvPacket(unsigned char*)'
<artificial>:(.text+0x1571): undefined reference to `LAN_PCap::RecvPacket(unsigned char*)'
/tmp/ccz2oB5C.ltrans27.ltrans.o: In function `Platform::LAN_SendPacket(unsigned char*, int)':
<artificial>:(.text+0x158b): undefined reference to `LAN_Socket::SendPacket(unsigned char*, int)'
<artificial>:(.text+0x1591): undefined reference to `LAN_PCap::SendPacket(unsigned char*, int)'
/tmp/ccz2oB5C.ltrans27.ltrans.o: In function `Platform::LAN_DeInit()':
<artificial>:(.text+0x15ab): undefined reference to `LAN_Socket::DeInit()'
<artificial>:(.text+0x15b1): undefined reference to `LAN_PCap::DeInit()'
/tmp/ccz2oB5C.ltrans27.ltrans.o: In function `Platform::LAN_Init()':
<artificial>:(.text+0x15cb): undefined reference to `LAN_PCap::Init()'
<artificial>:(.text+0x15d1): undefined reference to `LAN_Socket::Init()'
/tmp/ccz2oB5C.ltrans30.ltrans.o: In function `NDS::DeInit()':
<artificial>:(.text+0xe5c): undefined reference to `LAN_Socket::DeInit()'
<artificial>:(.text+0xe73): undefined reference to `LAN_PCap::DeInit()'
collect2: error: ld returned 1 exit status
CMakeFiles/melonDS.dir/build.make:1971: recipe for target 'melonDS' failed
make[2]: *** [melonDS] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/melonDS.dir/all' failed
make[1]: *** [CMakeFiles/melonDS.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by MojoJojoDojo** [comment]
Probably all the new Wi-Fi code is doing this. 
You need to wait for it to get fixed.

**Comment by Delta456** [comment]
Ok
