### ISSUE TITLE
Network adapter list is blank in the Wi-Fi options on a laptop. 

### ISSUE THREAD

**Issue by SIGMA-AX** [Arisotura/melonDS#386]
There's a person who even after installing WinPcap, cannot seem to find any network adapters when they enter the WiFi settings. They're on a Laptop with Windows 10 using an Ethernet connection. Their WiFi settings essentially look like this:
![unknown](https://user-images.githubusercontent.com/44013214/54469178-99a17680-478c-11e9-8a91-7cb47176d147.png)

This is the second time I've seen this issue, I wonder what the cause of it is.

**Comment by MojoJojoDojo** [comment]
You need to install npcap with winpcap API compatibility mode ticked in the installation options.

**Comment by SIGMA-AX** [comment]
Thanks, this seems to have solved the issue for the person. I'll now close this thread.
