### ISSUE TITLE
New network code no longer builds on OpenBSD

### ISSUE THREAD

**Issue by bentley** [Arisotura/melonDS#393]
I’ve used melonDS on OpenBSD up till 0.7.3. But 0.7.4 doesn’t build, for at least three reasons:

* `linux/if_packet.h` is (not surprisingly) a Linux‐only header.
* POSIX specifies `struct sockaddr` is defined in `sys/socket.h`.
* POSIX and OpenBSD don’t have `sockaddr_ll` or `AF_PACKET`.

This trivial change improves the headers, although it does nothing for the last bullet:

     #ifdef __WIN32__
     	#include <iphlpapi.h>
    -#else
    +#elif __linux__
     	#include <sys/types.h>
     	#include <ifaddrs.h>
     	#include <netinet/in.h>
     	#include <linux/if_packet.h>
    +#else
    +	#include <sys/types.h>
    +	#include <sys/socket.h>
    +	#include <ifaddrs.h>
    +	#include <netinet/in.h>
     #endif

**Comment by Arisotura** [comment]
if_packet.h was included for AF_PACKET and the relevant address structure (basically, so we can grab the adapters' MAC addresses).

not sure whether OpenBSD and MacOS support returning MAC addresses via getifaddrs().

if they don't, we can set a dummy blank MAC or whatever.

either way, we can get rid of the includes by having our own define for AF_PACKET & co., but... meh.
