### ISSUE TITLE
Divide by zero exception

### ISSUE THREAD

**Issue by Ammako** [Arisotura/melonDS#394]
Closing the lid causes a divide by zero exception (0xc0000094) when Limit framerate is off. This is because the framerate shoots way up due to there not being anything to render anymore (it shows 30,000 FPS at the time of crashing.)

**Comment by Arisotura** [comment]
oopsies

**Comment by Arisotura** [comment]
should be fixed now. even though machine isn't absurdly fast enough to reproduce it.
