### ISSUE TITLE
[Feature Request] Allow stretching to 16:9

### ISSUE THREAD

**Issue by ghost** [Arisotura/melonDS#395]
As far as I can tell there's no way to let the aspect ratio stretch in melonDS, correct me if I'm wrong.
But something interesting popped up recently, a widescreen patch for Mario 64 DS https://www.youtube.com/watch?v=NR9DdLQLT1Y (And another for Sonic Rush https://www.youtube.com/watch?v=9eWA-quAZY4)
Since it works by rendering 16:9 squished into 4:3, you have to disable maintain aspect ratio so you can stretch it back to 16:9. You can do this in Desmume but not in melonDS to my knowledge.
So having an option to let the screen stretch to the window size would be nice, or an option to stretch specifically to 16:9 would be even better.

**Comment by Arisotura** [comment]
I'll take the latter -- a lot of the current screen sizing code works by assuming a fixed aspect ratio, so stretching to the window would be an entirely separate mode

**Comment by Anuskuss** [comment]
@Arisotura Does the patched game request a different aspect ratio? Would be perfect if melonDS could just detect it so that there would be no need for an extra setting.

**Comment by ToppestOfDogs** [comment]
As far as I know it doesn't. I think it just changes the horizontal FOV.

**Comment by ToppestOfDogs** [comment]
Another interesting thing, here's a thread on how to make a widescreen cheat for almost any 3D game
https://gbatemp.net/threads/how-to-play-nds-games-in-hd-widescreen-16-9-21-9-32-9.538988/
It's as simple as searching for a hex value of 1555 and freezing it to 7281, and it works pretty reliably. It's so easy to do it may even be possible to create some sort of automated version of it. Say for example a tool that searches for 1555 and replaces each value one at a time, asking the user if the screen changed, and when the user says yes it creates an AR code of that one value. Of course I'm just spitballing here though.

**Comment by WaluigiWare64** [comment]
This feature was added in https://github.com/Arisotura/melonDS/commit/b9a56bc4e47bbb315f88ba5eaa57ce2b3efece73

**Comment by Ghost-Bit** [comment]
eh... it's only doing that to the framebuffer though, instead of drawing outside the usual screen space. I'd say this is still a valid issue.
