### ISSUE TITLE
DSi Emulation

### ISSUE THREAD

**Issue by Amul2004** [Arisotura/melonDS#404]
Will you guys ever add support for **DSi emulation**?

Just like No$GBA has done!!

**Comment by Arisotura** [comment]
yeah, but whenever we get there

'we'

melonDS is actually mostly me, so this will take a while

**Comment by v1993** [comment]
How ready is `melonDSi` branch? It looks currently abandoned, but is it worth a shot?

**Comment by RSDuck** [comment]
http://melonds.kuribo64.net/comments.php?id=103

it's functional and even got a release, though it needs a revisit

**Comment by Arisotura** [comment]
it's not abandoned, we just have higher priorities atm

**Comment by RSDuck** [comment]
the dsi branch has been merged for a while
