### ISSUE TITLE
When 3DRenderer set to 1 melonds ignores DirectBoot setting.

### ISSUE THREAD

**Issue by nathanielcwm** [Arisotura/melonDS#405]
When the 3DRenderer setting in the ini file is set to 1 melonds ignores the DirectBoot setting in the ini file and proceeds to just boot the game directly regardless of what that is set to.

I built it using commit https://github.com/Arisotura/melonDS/commit/c81bcccadc9ac8394ba8d4a836d7c954dd528751 on the blackmagic branch which is currently the latest on github.

**Comment by nathanielcwm** [comment]
nvm looks like regardless of what 3DRenderer in the ini file is set to now it ignores it and boots the game directly

**Comment by nathanielcwm** [comment]
on https://github.com/Arisotura/melonDS/commit/f2282e9e32cce0c335f0ca065e5a3b1bc564e406 when 3DRenderer is set to 0 and DirectBoot is set to 0 it doesn't boot the game directly but now regardless of what 3DRenderer is set to it boots the game directly

**Comment by nathanielcwm** [comment]
idk what you did but now with the latest commit it runs at a stable 60 fps where previously it would run at 30-45fps *albeit with this weird tint* keep up the good work!

**Comment by Arisotura** [comment]
the blackmagic branch is a work in progress, so expect things to randomly break and work again until I'm done ironing it out (and merge it back to master)

also yeah I changed the way hires is done >:)

**Comment by nathanielcwm** [comment]
idk if it matters that much but i'm using msys2 and codeblocks to compile
