### ISSUE TITLE
[Feature Request] Importing of Desmume saves

### ISSUE THREAD

**Issue by nathanielcwm** [Arisotura/melonDS#406]
Maybe melonDS could automatically convert and import Desmume saves so they can be used in melonDS

**Comment by sweetsbeats** [comment]
A conversion tool could be put together with some hacking at both emulators; a quick solution could be stripping Desmume down to just it's save states and core, then grabbing the data and writing out to a melon save state.

**Comment by Arisotura** [comment]
they meant regular saves, not savestates, I think

which is doable by stripping the extra shito DeSmuME adds at the end of its files and renaming it to .sav, or using its built-in 'export backup memory' feature

savestates would be another deal entirely, those typically contain a lot of emulator-specific state, so I'm not sure a DeSmuME savestate could be magically converted to a melonDS savestate that works

**Comment by sweetsbeats** [comment]
Ah, I see, that would be a lot easier than trying to convert state between emulators

**Comment by nathanielcwm** [comment]
@Arisotura the main reason why im asking for this is because for rune factory 3 exporting the save using the function in desmume doesn't seem to work

**Comment by Arisotura** [comment]
well then...

grab the .dsv, throw it up into a hex editor, remove the extra bytes at the end. the file size should be an exact power of two.

then save it with a .sav extension, and, same name as the ROM file.

**Comment by nathanielcwm** [comment]
![image](https://user-images.githubusercontent.com/22572406/57983354-6d072500-7a83-11e9-84b0-2914572df734.png)
Still isn't working. btw both manually removing the end and using the export function in desmume gives a file that is 32kb

**Comment by nathanielcwm** [comment]
nvm i increased changed the filesize of the savefile to 64kb in the hex editor and now it works

**Comment by Ace4896** [comment]
Just wanted to say I also have Rune Factory 3 and have been playing through it on MelonDS; I can verify that the save file is 64kb.

**Comment by Arisotura** [comment]
yeah, 32KB is a bogus size. I didn't think of that, but apparently, desmume does that kind of shit

that breaks because melonDS relies on the file size to identify the underlying memory type (EEPROM, FLASH, etc) and how the game will access it

**Comment by Arisotura** [comment]
a possibility would be going by the database when encountering a bogus file size (and fixing the size accordingly)

**Comment by MojoJojoDojo** [comment]
I think desmume can export the save to no$gba format and that fixes the problem.

**Comment by nathanielcwm** [comment]
random but it states that it failed exporting to no$gba format

**Comment by Arisotura** [comment]
I don't see how using no$gba format would fix anything tho, melonDS can't parse that format

**Comment by m1trix** [comment]
You can use desmume's "export backup memory" to dump a raw .sav file which you can then use in melonds.

**Comment by RSDuck** [comment]
has been added a while ago. Go to File -> Import save file

**Comment by xeuc** [comment]
I tried the technique of exporting as raw data from DeSmuME and importing it in melonDS for 2 games:
For `New Super Mario DS`, it worked well. 
For `Dragon Ball Z Supersonic Warior 2`, it crashed:
![image](https://github.com/melonDS-emu/melonDS/assets/80948867/ef345229-ee95-440b-bd80-ec2a9c89136c)
So I croped the 32kb save file to the same save file length melonDS created (i.e. 8kb) but it didn't resolve the situation.
I tried 8kb, 64kb (by adding some `ÿ`), exporting the save file into No$GBA save format from DeSmuME then converting it using http://www.shunyweb.info/convert.php but nothing worked.
I just noticed that the sav files are quite similar:
![image](https://github.com/melonDS-emu/melonDS/assets/80948867/08880f20-8a00-4361-bfae-1c14025dadf1)
but at the moment, exporting a sav fie from DeSmuME only return me a 8kb file full of `ÿ` so I give up..
I think the issue come from DeSmuME but I may use my real DS to figure out what a REAL empty sav file should look like..

**Comment by RSDuck** [comment]
does saving work properly in the game with a savefile created in melonDS? It could be possible that melonDS's save database entry for the game is wrong.

**Comment by Jaklyy** [comment]
are you using external or the built-in bios for melonDS?
does it occur in latest dev builds?
wouldn't be surprised if this was related to a bug that got fixed recently with how the built-in bios does checksum calculations.
this game could be another one that uses them for save file validity checking
