### ISSUE TITLE
HTTPS on site?

### ISSUE THREAD

**Issue by nathanielcwm** [Arisotura/melonDS#408]
While there is a https version of the site it uses a self signed certificate.

NGINX has built in letsencrypt support which is free, there is a tutorial on setting it up on their site: https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/.

**Comment by Arisotura** [comment]
self-signed or nothing.

I am waiting for the day a nice big juicy Let's Encrypt scandal breaks out, like with every cheap/free CA ever.

**Comment by nathanielcwm** [comment]
ok anyway the normal http site works just fine
