### ISSUE TITLE
NSMBDS romhacking: FMV cutscene code hack issues

### ISSUE THREAD

**Issue by poudink** [Arisotura/melonDS#410]
I was working on my romhack and decided to try out this code hack for custom intro cutscenes:
https://nsmbhd.net/thread/3258-video-intro-with-streamed-sound/
Interestingly, it exuded different behaviours on desmume, a real DS and melonDS.
On Desmume, the cutscene plays normally. This is due to the code hack itself, which is adjusted to Desmume's timings.
On a real DS, the video portion of the cutscene plays much slower than on Desmume while the audio portion plays normally. The cutscene also ends earlier than on Desmume.
On melonDS, the cutscene plays like on a real DS, except it freezes midway through.
I will add a patch to this post soon, since getting the code hack to work is somewhat tricky.

**Comment by poudink** [comment]
I might have made a mistake. closing this for now.

**Comment by poudink** [comment]
there was a mistake, but melonds still does something wrong. it's just that desmume actually does not play the video correctly (which means I made a mistake while setting up the code hack, but that doesn't matter) and behaves exactly like melonds

**Comment by poudink** [comment]
[STREMNEW.zip](https://github.com/Arisotura/melonDS/files/3219009/STREMNEW.zip)
The broken graphics outside the cutscene are normal, I just lazily applied all the code hacks in my hack to a clean NSMBDS rom.

**Comment by Arisotura** [comment]
tried applying the patch with https://www.romhacking.net/utilities/598/ but it says 'unknown compressor' something

blarg.

**Comment by poudink** [comment]
you must have an outdated xdelta version. try this version: https://github.com/jmacd/xdelta-gpl/releases/tag/v3.0.11 ( just replace the xdelta.exe from the version you downloaded with that one).

**Comment by Arisotura** [comment]
same shit

xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent

when using option -n, it does apply the patch, but that results in a broken ROM

using a USA ROM

**Comment by poudink** [comment]
shit. can I send you a rom on the board?

**Comment by Arisotura** [comment]
yup, that'll be easier

**Comment by Arisotura** [comment]
that's probably interrupt-delay shenanigans

I notice that there is code that waits for vblank by polling vcount, but sure enough you also have a vblank handler, so... yea

**Comment by Arisotura** [comment]
well, I tested it on hardware and it froze the exact same way as on melonDS, so I'm putting this on the backburner for now

**Comment by poudink** [comment]
might be because I tested it on nds-bootstrap, then.
