### ISSUE TITLE
Star Wars The Force Unleashed - Broken with the hardware renderer

### ISSUE THREAD

**Issue by K0bin** [Arisotura/melonDS#423]
Star Wars The Force Unleashed doesn't really render at all with the hardware renderer. It's both broken on 1x and 8x. It works fine using the software renderer. 

I don't know if this is a genuine bug or if the game is trying to use some weird obscure hardware quirk that you don't plan on implementing in the OpenGL renderer.

Tested with: 0.80
Windows, Nvidia 430.86
Game Id: 2661

![grafik](https://user-images.githubusercontent.com/1131720/58750018-07586700-848d-11e9-892c-873f8927f00c.png)

**Comment by Arisotura** [comment]
mh

that might be that compositing bug, I hope it is

**Comment by K0bin** [comment]
![grafik](https://user-images.githubusercontent.com/1131720/59358675-44461880-8d2d-11e9-93cf-67dc9be1481d.png)

Nice work, it's fixed in 0.81.
