### ISSUE TITLE
OpenGL renderer: 3D graphics not displayed

### ISSUE THREAD

**Issue by Niklink** [Arisotura/melonDS#425]
Opening an issue here so I can drop some screenies: [Various example screenshots](https://imgur.com/a/lLBiBRm)

I will also note that the OpenGL renderer usually produces comparable or slightly lower framerates than the software renderer. For example: 45 fps on the NSMB map screen versus 42 fps with the OpenGL renderer. Of course, this is all at 1x internal resolution.

melonDS: 0.8 hotfix
CPU: AMD Athlon II X4 630
GPU: AMD Radeon HD 6750
OS: Win7

**Comment by amayra** [comment]
i have same problem with my i7 3770 and hd 4000

**Comment by kirbyquaza** [comment]
same problem with the 3d graphics (no problem with framerate so far)
i5 3450
intel HD graphics 2500

**Comment by thiaguinhohp** [comment]
hi i have the same problem (brown screen and framerates are between 50~60)
OS: Windows 8.1
i5-3317U
intel hd graphics 4000

**Comment by Niklink** [comment]
No change in behavior in melonDS 0.8.1.

**Comment by RSDuck** [comment]
If you're experiencing this problem, could you please try my fix: #456
