### ISSUE TITLE
Open GL: SM64 DS title screen causes program to crash

### ISSUE THREAD

**Issue by 5kyl4rk** [Arisotura/melonDS#426]
The game starts, but when the star shows up it quickly freezes the screen.  The game still runs as the music is still playing and you can touch the bottom screen or click buttons and it will start the game, but the screen still shows the star and black screen despite resetting or loading a new ROM, forcing me to have to close melonDS and re-run it.  The only way around it is to turn off OpenGL before starting and as soon as you're in game to turn it back on.

**Comment by Zemeon** [comment]
I had a similar issue that I fixed by changing the internal resolution back and forth.

**Comment by Arisotura** [comment]
I think I already fixed that bug, was some real stupid oversight

**Comment by 5kyl4rk** [comment]
I figured out what was wrong, I had it set to _Native 2x_ on the upscaling which didn't do well with my crappy Intel graphic card I guess.  If I change it back to _Native 1x_ it loads fine, but there's still some games that don't work
