### ISSUE TITLE
OpenGL renderer - graphical glitches on Pokemon Gen5 battle textboxes

### ISSUE THREAD

**Issue by shutterbug2000** [Arisotura/melonDS#440]
Example:

![unknown (1)](https://user-images.githubusercontent.com/8000700/59071083-ce503600-8882-11e9-8742-025252f07c01.png)

**Comment by teatime-dev** [comment]
this seems fixed in 0.8.1
![image](https://user-images.githubusercontent.com/40647704/59558323-e1a59300-9032-11e9-809e-f7bc54b95254.png)
