### ISSUE TITLE
Final Fantasy III backup memory error

### ISSUE THREAD

**Issue by ginnedup** [Arisotura/melonDS#444]
When I start up Final Fantasy III, I get a "Unable to access Backup Memory.  Please try again after turning your system OFF and reinserting the DS card." message, and while the game appears to continue running (FPS counter changes as normal), nothing else happens.  What's going on here?  (Was this on a FAQ somewhere and I missed it?)

Versions affected:
0.8
0.8.1
possibly others, but I haven't tested them.

**Comment by Arisotura** [comment]
what size is your save file?

**Comment by ginnedup** [comment]
Huh.  It was zero (0) KB in size.  Had a date of 4/22/2017, for some reason.  I deleted that file, then restarted melonDS and started the FF3 ROM; worked fine this time!  Said "initializing backup data" and went into the game's opening movie.  Looks like it's fine now; that file was... corrupted, I guess?  Anyway, looks like I can close this issue.  Thanks for your help!

**Comment by Arisotura** [comment]
maybe you tried it on medusa? it likes to create empty, 0KB save files.

melonDS doesn't quite appreciate that as it relies on the save file size to determine which memory interface to use.

**Comment by ginnedup** [comment]
I don't have medusa (or mGBA for that matter), though I've toyed around with VBA-M, no$gba, smygb, and VBA 1.8.0.  Dunno if any of them could have done that (especially since the save files are kept in the melonDS directory; it'd be weird if medusa could get into melonDS' directory), but at least it's good to know that blowing away the 0 KB file made the problem go away.  I guess it's not a real permanent fix, maybe; I'm not the expert on this.

**Comment by Arisotura** [comment]
well, thing is

melonDS needs a savefile with the correct size; the idea was that if it failed to find out the correct backup memory type on its own, you could provide an existing save file and it would work

I could make melonDS fall back to the backupmem type database if it finds an incorrect/zero savefile size, tho

**Comment by ginnedup** [comment]
I see.  Yeah, I didn't have an existing save file for FF3, so I was unable to do that.  Making it fall back to a backup database might work, if that would let me get in-game so I could overwrite the 0 KB file with a new, properly-sized save.

**Comment by Arisotura** [comment]
I'm not aware of any save issues with FF3, so that should work.
