### ISSUE TITLE
Story of Noah's Ark, The (USA) graphic glitches on opengl

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#446]
using 0.8.1
most of the screens are pink and graphics missing
![noah](https://user-images.githubusercontent.com/2696404/59418303-61e1b380-8dfb-11e9-83d7-095a9d884e81.PNG)

**Comment by Arisotura** [comment]
game might be using a clear bitmap, which isn't supported yet

**Comment by iamthelaw2041** [comment]
This is fixed and can be closed. OpenGL at x5. 

![Capture](https://user-images.githubusercontent.com/94656803/144358733-72461ffe-3031-46d5-8e4b-e46fe68fcc11.PNG)
