### ISSUE TITLE
[Feature Request] Interface for editing your firmware settings, including the MAC address

### ISSUE THREAD

**Issue by Peduls** [Arisotura/melonDS#447]
Every time I launch a game in MelonDS thinks it's from a new DS. This affects games like Tomodachi Collection, Nintendogs, and Animal Crossing.
![Capture](https://user-images.githubusercontent.com/34750422/59479977-1ab7ea80-8e1c-11e9-9368-c21dbea402e7.PNG)

**Comment by Arisotura** [comment]
I guess the game checks the MAC address, which melonDS randomizes every start (so that local multiplayer can function without colliding).

maybe I should make that optional. shrug

**Comment by Ammako** [comment]
#443

**Comment by Peduls** [comment]
Yeah, DeSmuME just uses the MAC address in the firmware file but PPSSPP assigns you a random MAC address at first launch and then it stays the same unless you manually change it in the settings if you need to for some reason. Maybe something like that could work for melonDS?
![Capture](https://user-images.githubusercontent.com/34750422/59546228-39cf7e80-8ee7-11e9-89a7-c3ad990149e1.PNG)

**Comment by Arisotura** [comment]
or I could just provide an interface for editing your firmware settings, including the MAC address

**Comment by RSDuck** [comment]
Has been implemented.
