### ISSUE TITLE
3DS BIOS/FIRM Files.

### ISSUE THREAD

**Issue by NeccoWafer** [Arisotura/melonDS#451]
So I was able to dump the files and rename them to their proper format.
(Dumped using a 2ds on firmware 11.10.0-43U, and R4i Gold 3DS Plus.)

Both the bios9.bin, and firmware.bin both work and the bios9 checksum is correct.
The problem lies with the bios7.bin file.

bios9.bin sha1: BFAAC75F101C135E32E2AAF541DE6B1BE4C8C62D - WORKS!
bios7.bin sha1: 24F67BDEA115A2C847C8813A262502EE1607B7DF - FAILS!

Turns out it is dumping the correct arm9 bios, but seemingly dumping the arm7  of a DSi.
The needed arm7 bios has a sha1 of '24F67BDEA115A2C847C8813A262502EE1607B7DF'.

Here is a list of hashes for the bios files. https://pastebin.com/PAGSVC92

**Comment by MojoJojoDojo** [comment]
How you dumped the files from your 3ds?

**Comment by Arisotura** [comment]
open your ARM7 BIOS in a hex editor and see if the 32 first bytes are all FF or 00

**Comment by NeccoWafer** [comment]
@Arisotura the first 32 bytes are all FF.

@MojoJojoDojo  Using a DS flashcart, and the tool provided on the website.

**Comment by NeccoWafer** [comment]
@Arisotura so it turns out only the first 32bytes are different.

**3DS Dumped BIOS:**
`FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF`

**NDS Dumped BIOS:**
`06 00 00 EA 20 0B 00 EA 73 0B 00 EA 1E 0B 00 EA 1D 0B 00 EA 1C 0B 00 EA 69 0B 00 EA 1A 0B 00 EA`

**Comment by Arisotura** [comment]
yup, sometimes DSi/3DS BIOS dumps are lacking the first 32 bytes on the ARM7 BIOS

for a DSi-mode BIOS, those should be:

06 00 00 EA 06 00 00 EA 1F 00 00 EA 04 00 00 EA 03 00 00 EA FE FF FF EA 13 00 00 EA 00 00 00 EA

for a DS-mode BIOS, they should be what you mentioned ('NDS Dumped BIOS')

I could make melonDS autofix them if needed, but at the same time, having correct dumps is important as far as preservation is concerned

**Comment by NeccoWafer** [comment]
Yeah that makes sense, I would also agree that having melonDS auto fix them wouldn’t be the best solution. Maybe have melonDS read the first 32 bytes on launch, and show a warning if they do not match. That way people don’t assume they have a proper dump. I’ll go ahead and close this as it is strictly a 3DS/DSI issue, and not a melonDS one.
