### ISSUE TITLE
Final Fantasy Crystal Chronicles: Echoes of Time cannot load saves

### ISSUE THREAD

**Issue by GrieverV** [Arisotura/melonDS#457]
melonDS is able to save the game and generates a savefile but there is no option to 'continue' when restarting the emulator, only 'start' which begins a new game.

**Comment by GrieverV** [comment]
Turned out romlist.bin was not included in the package I installed. The game properly saves and loads with romlist.bin.

Perhaps there should be a warning when romlist.bin isn't present?

**Comment by Arisotura** [comment]
'd like to know where you got it from, then

'cause all the release packages from 0.7.3 come with romlist.bin, unless I forgot one of them

**Comment by GrieverV** [comment]
I used the [melonds-git](https://aur.archlinux.org/packages/melonds-git/) PKGBUILD from Arch Linux's AUR to generate a package.  

Does melonds support any [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) paths such as `/opt` or `/usr/share` for romlist.bin? I'm not sure which would be appropriate.

**Comment by Arisotura** [comment]
melonDS can look in /home/<user>/.melonds/

**Comment by GrieverV** [comment]
I'm not sure if $XDG_CONFIG_HOME/melonds/ would be possible to use for packagers. I was able to create a working [PKGBUILD](https://gitlab.com/GrieverV/PKGBUILDs/tree/master/melonds-git) that uses `/opt`, however I now run into #448 for some reason.
