### ISSUE TITLE
Melon DS 0.8.1 Input Menu binds a Button 1 alongside my axis joypad, conflicting with my A button.

### ISSUE THREAD

**Issue by Zemeon** [Arisotura/melonDS#460]
Using Buffalo Classic Usb Gamepad. Screenshot of my input screen: https://i.imgur.com/rcws7Ti.png

Back at it again with the input menu. For some reason when binding directions, MelonDS declares all of them as Button 1/(the proper axis)

Hitting A (the real Button 1) in this scenario triggers a directional input action, while actual directional input buttons work as intended (hitting them doesn't act as an A button)

This doesn't happen on other emulators, eliminating controller fault. BSNES for example correctly detect my directional buttons as an axis and nothing else. (in fact for it, button 1 is the B button)

Replacing my MelonDs.ini did not fix the issue.

**Comment by Arisotura** [comment]
huh, this is weird af

so, try this

clear one of the direction mappings, then, remap the axis

does it, like, map the axis and button at the same time?

because that's weird af. looking at the mapping code, and I see no way it could map a button and an axis at the same time.

**Comment by Zemeon** [comment]
Yup. For each directional input I cleared the mapping and hit the button.  I have done this multiple times. It puts in what you see in the screenshots. I have no other controller plugged in while testing, however I have used a different controller before.

Before and after screenshots:
https://i.imgur.com/ySVHISb.png

https://i.imgur.com/Vscq0cs.png

**Comment by Zemeon** [comment]
More information: looking at an input reader (this one: https://html5gamepad.com/) says that the D pad is an axis as well as buttons 12 - 15. However my A button is still distinctly Button 1; so you'd assume that naturally it'd map the dpad as B12-15/correct axis respectively and therefore have no conflicts.

**Comment by Arisotura** [comment]
thing is, the joystick mapping code works by running a timer that polls the joystick until input is detected

but, the timer will immediately stop running if it detects, by order of priority:
* button input
* hat direction input
* axis input

the first input encountered discarding any further input.

so, I fail to see how this can map a button and an axis at the same time.

**Comment by Arisotura** [comment]
ok can you try the following build

http://kuribo64.net/get.php?id=TWvxtDreaNn19YI6

try clearing the mappings then mapping the one that causes problems

and paste the console output here

**Comment by Arisotura** [comment]
owait I see the bug

it's when mapping an axis but no button

**Comment by Zemeon** [comment]
Yup, latest commit fixed the issue; it's only mapping the axis and gameplay works as expected.
