### ISSUE TITLE
Touch screen input broken in NTR-CSPE-USA (Lock's Quest)

### ISSUE THREAD

**Issue by wertercatt** [Arisotura/melonDS#461]
To reproduce: Simply boot the game and attempt to press the button on the touch screen to start the game. Instead of the game beginning, the character on the screen just runs towards the top left forever.

ROM SHA-1 hash: e1e41fd8f2a9f9ad9e01cd50108f8e6276a87e6f

**Comment by wertercatt** [comment]
Testing other games seems to show that the touch screen is broken in the same way every time. I'm Lubuntu 18.10

**Comment by Arisotura** [comment]
if it breaks with every game, that's... weird

perhaps a problem with your firmware's data somehow? melonDS normally patches it with its own touchscreen calibration data, but, well, we never know.

try running the firmware (with no game loaded: System -> Run) and doing a touchscreen calibration?

**Comment by wertercatt** [comment]
Given that melonDS crashed hard when I attempted System -> Run, I'm going to assume that No-Intro's firmware.bin is busted and that's where the problem lies.

**Comment by Arisotura** [comment]
might be. I'd have to look at that firmware file to know what's wrong with it.
