### ISSUE TITLE
Pressing F11 causes a segfault on Linux

### ISSUE THREAD

**Issue by GrieverV** [Arisotura/melonDS#465]
Backtrace:  

    #0  0x00007ffff6c3baf2 in fwrite () at /usr/lib/libc.so.6
    #1  0x000000000044dc96 in NDS::debug(unsigned int) (param=param@entry=0)
        at /usr/src/debug/melonDS/src/NDS.cpp:1555
            val = 0
            i = 33554432
            shit = 0x0
    #2  0x0000000000410f15 in OnAreaKeyEvent(uiAreaHandler*, uiArea*, uiAreaKeyEvent*) (handler=<optimized out>, area=<optimized out>, evt=0x7fffffffd670)
        at /usr/src/debug/melonDS/src/libui_sdl/main.cpp:1221
    #3  0x0000000000478138 in areaKeyEvent
        (a=0x17518a0, up=up@entry=0, e=e@entry=0x15b4840)
        at /usr/src/debug/melonDS/src/libui_sdl/libui/unix/area.c:527
            ke =
              {Key = 0 '\000', ExtKey = 0, Modifier = 0, Modifiers = 0, Scancode = 87, Up = 0, Repeat = 0}
            state = <optimized out>
    #4  0x0000000000478217 in areaWidget_key_press_event
        (w=0x7fff74009630, e=0x15b4840)
        at /usr/src/debug/melonDS/src/libui_sdl/libui/unix/area.c:535
            aw = <optimized out>
            a = <optimized out>
    #5  0x00007ffff7c7696c in  () at /usr/lib/libgtk-3.so.0
    #6  0x00007ffff7416add in g_signal_emit_valist ()
        at /usr/lib/libgobject-2.0.so.0
    #7  0x00007ffff7417fb0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
    #8  0x00007ffff79e0526 in  () at /usr/lib/libgtk-3.so.0
    #9  0x00007ffff79c55bc in gtk_window_propagate_key_event () at /usr/lib/libgtk-3.so.0
    #10 0x00007ffff79c566c in  () at /usr/lib/libgtk-3.so.0
    #11 0x00007ffff7c7696c in  () at /usr/lib/libgtk-3.so.0
    #12 0x00007ffff74172d5 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
    #13 0x00007ffff7417fb0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
    #14 0x00007ffff79e0526 in  () at /usr/lib/libgtk-3.so.0
    #15 0x00007ffff7b270fa in  () at /usr/lib/libgtk-3.so.0
    #16 0x00007ffff7b2a60c in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
    #17 0x00007ffff783c514 in  () at /usr/lib/libgdk-3.so.0
    #18 0x00007ffff780bb74 in  () at /usr/lib/libgdk-3.so.0
    #19 0x00007ffff733890f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
    #20 0x00007ffff733a869 in  () at /usr/lib/libglib-2.0.so.0
    #21 0x00007ffff733b7f2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
    #22 0x00007ffff7b23bbf in gtk_main () at /usr/lib/libgtk-3.so.0
    #23 0x0000000000481724 in uiMain () at /usr/src/debug/melonDS/src/libui_sdl/libui/unix/main.c:77
    #24 0x000000000040c91d in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/melonDS/src/libui_sdl/main.cpp:2692
            ui_opt = {Size = 0}
            ui_err = <optimized out>
            whatIwant = {freq = 44100, format = 32784, channels = 1 '\001', silence = 0 '\000', samples = 1024, padding = 0, size = 0, callback = 0x40d370 <MicCallback(void*, unsigned char*, int)>, userdata = 0x0}
            whatIget = {freq = 44100, format = 32784, channels = 1 '\001', silence = 0 '\000', samples = 1024, padding = 0, size = 2048, callback = 0x40d370 <MicCallback(void*, unsigned char*, int)>, userdata = 0x0}

melonDS: e2dc98d
OS: Arch Linux

Arch Linux (debug) package: [melonds-git-0.8.1.r914.e2dc98d-1-x86_64.pkg.tar.xz](https://framadrop.org/r/x4SLsdtWKI#GfAjh/bhtVWnaNaeyXh5rkkh6W7OXgki31Uql2VNxAw=) (expires 2019-08-20)

**Comment by Arisotura** [comment]
debug crap I forgot about removing. blarg

**Comment by Arisotura** [comment]
I took care of this one
