### ISSUE TITLE
Framerate dips slightly at random intervals causing audio stutters

### ISSUE THREAD

**Issue by NarryG** [Arisotura/melonDS#470]
Renderer doesn't seem to matter. If I unlock the framerate, I'm easily pushing at minimum 150fps. Seems to happen in any game, but it's the most obvious to me in Mystery Dungeon Explorers of Sky's intro on the screen transitions. CPU core isn't maxed out or anything.  This is on Windows.

**Comment by Arisotura** [comment]
I observed that on Pokémon games every other frame takes more than 16ms (but the other takes less)

which fools the framerate limiter into limiting too much

so far my attempts at making it smarter haven't really worked

**Comment by NarryG** [comment]
That's some weird behavior. That even applies to the non-gamefreak games like PMD?

**Comment by Arisotura** [comment]
dunno about PMD, but that was observed on some Pokémon games

**Comment by RSDuck** [comment]
the frame limiter has been improved several times
