### ISSUE TITLE
Closing a config menu with esc crashes on Windows

### ISSUE THREAD

**Issue by NarryG** [Arisotura/melonDS#471]
If you open any config menu then press esc, the entire program crashes.

**Comment by Arisotura** [comment]
can't reproduce

**Comment by NarryG** [comment]
Happening consistent for me on both the official build as well as my own custom build.
Here's some actual debug output. It is under my own custom build which I made under MSVC (which is why it's an image of VS), but it happens on 0.8.1 official as well.

[img](https://narry.land/0krvjD.png)

This may actually be a bug in LibUI based on what the exception says? Interestingly enough, it only crashes when I'm not attached to the debugger. When I'm on the debugger, it hits the breakpoint then it's fine afterwards.

**Comment by NarryG** [comment]
How old is the libUI implementation? Peeking over on their repo, it looks like this may be an issue that was already solved.
https://github.com/andlabs/libui/issues/55#issuecomment-242757219

**Comment by Arisotura** [comment]
try the latest revision?

**Comment by NarryG** [comment]
Works
