### ISSUE TITLE
Mario Party DS: Stick and Spin Completely Broken

### ISSUE THREAD

**Issue by JMC47** [Arisotura/melonDS#479]
**Title**: Mario Party DS

**Issue**

The minigame "Stick and Spin" is completely broken.  The game is supposed to drop colored balls onto a spinner where you play a rather standard match five clear puzzle game.  in MelonDS however, the balls immediately disappear before dropping.  Eventually after waiting long enough, the game **internally** starts dropping frames and becomes incredibly sluggish.  melonDS is full speed, which makes me believe that the number of objects has climbed beyond what the game anticipated, meaning the balls have gone *somewhere*.

MelonDS:
![melonDSStickandSpin](https://user-images.githubusercontent.com/6598209/60217889-c52c0680-983b-11e9-951e-b2046b927a21.jpg)
DeSmuME:
![Desmume](https://user-images.githubusercontent.com/6598209/60217848-a594de00-983b-11e9-980d-52daa6be0f85.jpg)

**To Reproduce**

Simply start up the game and go to puzzle mode.  There are 5 puzzle games available including this one.  No savefile is required.

**Other Notes**

Renderer does not affect this issue.  It does not appear to be a graphical issue.

**Comment by Arisotura** [comment]
weird. all the balls are given the same coords (120,103)

**Comment by Arisotura** [comment]
welp.

I found a function that applies a cute 2D (3x2) transform matrix to the incoming positions

have to see what the input is
