### ISSUE TITLE
Input issue with the Japanese Pokémon Diamond debug build

### ISSUE THREAD

**Issue by SatoMew** [Arisotura/melonDS#480]
Both Windows versions 0.8.1 and 0.8.2 experience an annoying behavior with this ROM in which pressing the default mapped key for the R button (right Shift) and then the default mapped key for the X button (W) or the START button (Enter) does not open the in-game overworld debug menu as expected.

The START button can be optionally mapped to the X button in-game via a setting.

**Comment by KernelEquinox** [comment]
I've tried to reproduce the issue, and I can confirm that melonDS 0.8.2 isn't registering the user pressing the R button.

When holding R and walking around in the overworld of the Japanese Pokémon Diamond debug ROM, it should make you run very fast and noclip through objects. However, when holding the default R button (Right Shift) and attempting to walk around, your character doesn't move at all, and it's as though the direction keys are ignored entirely.

Remapping the R button to the "Z" key allowed usage of the arrow keys, but it only moved the player character normally instead of registering as pressing the R button.

In addition, holding L+R+Start+Select in-game should normally perform a soft reset, whereas it doesn't seem to do anything in melonDS build 0.8.2.

**Comment by Arisotura** [comment]
I don't see how melonDS's input system could fail (it's tried-and-true at this point)

so that means there's something else preventing teh ROM from doing what it should

weird

**Comment by KernelEquinox** [comment]
I tested with DeSmuME and No$gba just to make sure it wasn't an issue with the ROM, and both emulators ran all functions as expected.

I also tried mapping the L and R buttons to the `.` and `/` buttons respectively, then checking whether soft resetting worked on the 3 different releases of the Japanese version of Pokemon Diamond: The release version (0577), Rev 5 (6635), and Rev 6 (6641).

On all 4 versions (the 3 official releases plus the proto ROM), soft resetting was not possible.

In addition, holding Start+Select+L offered the ability to input additional buttons (e.g. A, B), but holding Start+Select+R did not allow any additional inputs. Holding Start+Select+L and then pressing R did not reset the game, but rather seemed to only have the effect of disallowing further inputs.

As an unrelated issue, it also seems that melonDS may be mishandling modifier keys. Holding Ctrl, Alt, or Shift makes melonDS ignore any additional inputs, which makes Right Shift effectively a non-viable input key for the R button.

**Comment by Arisotura** [comment]
there's one issue I didn't think of, that is: if you press right-Shift for example, all further key presses are considered to be 'Shift+<key>'

I guess I should avoid that if Shift is mapped as a regular key, or smth


regarding the problems with your game... try with a joystick if possible? now I wonder what problems come from melonDS's input system and what problems stem from emulation bugs.

**Comment by flingrocks** [comment]
Related to what is described, keyboard input keys can get stuck down if modifier key pressed.
Press and hold a key, then hold a modifier key (Shift, Ctrl, Alt), release the first key, and then release the modifier key. It will act like the first key is still held down.

Found it out with the arrow keys. Player character continues to move in same direction without having key held, until pressing "stuck" key again (or countering temporarily by holding opposite direction).

**Comment by Ammako** [comment]
I think it's unlikely to be related to any specific roms. Try remapping your controls to more different keys for now.
There's definitely an issue with having certain key presses being recognized when using these very specific keys as input, but I have no issues if I just remap the keys to something else (I used Q+W+E+R for L+R+Start+Select), and everything is fine with a controller.

**Comment by iamthelaw2041** [comment]
I set the keyboard controls to exactly that and it worked fine. Holding Right shift + W brought up the debug menu. This can be closed. 

![Capture](https://user-images.githubusercontent.com/94656803/145011040-6e1c6a80-90a8-4417-8582-c86608f367c8.PNG)

**Comment by SatoMew** [comment]
> I set the keyboard controls to exactly that and it worked fine. Holding Right shift + W brought up the debug menu. This can be closed.

I know this account has been deleted, but I confirm that the issue was fixed in version 0.8.3.
