### ISSUE TITLE
Lag at random intervals even with framerate limiting turned off.

### ISSUE THREAD

**Issue by Karadoll** [Arisotura/melonDS#482]
Seems to be a bug introduced in version 0.8.2 as this doesn't happen with the previous version, which I have gone back to using for now. Seems to affect most games I tried. The exception being Ni No Kuni, which only lags when loading new areas, which it didn't do noticeably in the previous version of the emulator.

**Comment by Arisotura** [comment]
are you using OpenGL in the previous version?

**Comment by Karadoll** [comment]
Yes, I am using OpenGL in both versions, sorry for not specifying.

**Comment by Arisotura** [comment]
this looks like the framerate limiter is acting up. shit was smooth before because it used vsync.

the framerate limiter needs fixing, and I need to add a vsync toggle.

**Comment by RSDuck** [comment]
the frame limiter has been improved a lot since then. Most likely fixed.
