### ISSUE TITLE
[Feature Request] New layout

### ISSUE THREAD

**Issue by Anuskuss** [Arisotura/melonDS#484]
I think the "Emphasize top/bottom" layout is a good idea, but why waste all that screen space when we could have something like this:
![1920x1080](https://user-images.githubusercontent.com/7157389/60402699-4a445200-9b93-11e9-8f1e-e9f01a890c12.png)

**Comment by poudink** [comment]
and why would we need to have two times the same screen displayed? wouldn't that just make things laggier?

**Comment by Arisotura** [comment]
probably wouldn't be a big difference as far as performance is concerned, but this layout looks redundant to me

**Comment by Krusher97** [comment]
wouldn't it be better to be able to separate the two screens as a borderless window and then resize/reposition them to your liking?
Probably harder to do as the only DS emulator that did this that I know of was iDeaS

**Comment by Anuskuss** [comment]
Some games actually need you to see both screens at the same time / in the top/bottom layout, e.g. an animation going from one screen to the other, or a picture which streches from top to bottom, which wouldn't work with a sideways/emphasize layout. It's also useful for when you don't know which screen you're at or if you want to visualize the whole DS.
And lastly, **I** would like that layout, the user can choose to **not** use the layout, and the more the merrier when it comes to customization.

**Comment by ToppestOfDogs** [comment]
Backing this up, I also like this idea. There's some games where you mainly need one screen but occasionally are supposed to look at both.

**Comment by poudink** [comment]
you could look at both screens even with the old layout

**Comment by Arisotura** [comment]
thing is, supporting two potential locations for each screen would add complexity to the layout code

**Comment by Spikestuff** [comment]
Going to agree with the idea but the going about it is wrong.

You have the prioritized screen at 512x384 (double 256x192) and the sub at 256x192 and then it'll scale more efficiently and avoiding any black bars from appearing.

Showing an example image by having the top screen as priority with appropriate numbers and a scale up in theory numbers that go with that are these:
![DS-Theory](https://user-images.githubusercontent.com/12412764/60706025-eb445b80-9f4b-11e9-9d03-7f62504f3088.png)

If you want to know the scaling here are the numbers.
Main Screen: x2,x3,x4,x5,x6 (and so forth)
Sub Screen: x1,x1.5,x2,x2.5,x3 (and so forth)

Avoiding x3,x5,x7 etc. seems like the important if you don't want to deal with x1.5,x2.5,x3.5 etc. on the scaling.

If you want to know the screensizes by what's represented in that image they're:
768x384, 1152x576, 1536x768, 1920x960, 2304x1152

The transparent area represented by the image I provided can just be filled with black.

**Comment by Zemeon** [comment]
I agree with Spikes stuff. To state it simply, I think on either "Emphasize screen" option there is a lot of wasted space that the other screen could use. Push the emphasized screen flush and resize the other screen (maintaining aspect ratio of course) until it's flush on its side. Here's my rough mock up with a real game example: https://i.imgur.com/68RvUNI.png

As things currently stand the screen is absolutely tiny even though it has plenty of room to be bigger, even without budging the emphasized screen.

**Comment by Anuskuss** [comment]
@Spikestuff Although I like your idea since the screens use integer scaling, it's a little bit more wasteful (216000 vs 230400 useless pixels) *but* I'd be fine with either.

![Spikestuff](https://user-images.githubusercontent.com/7157389/60773035-1327f080-a0ff-11e9-8548-6c9559ad2d45.png)

Personally, I think the absolute best way to go about this would be a draggable separator which splits the main from the top/bottom area and resizes the screens accordingly. The seperator should be lockable.
