### ISSUE TITLE
Mario Party DS - Dress for Success Minor Graphical Issue - OpenGL

### ISSUE THREAD

**Issue by JMC47** [Arisotura/melonDS#487]
In this minigame, players are told what specific characters should look like and are required to dress them accordingly by matching two cards.  If your cards match, a 3D model of the character will pop out of the card.

On the Software renderer, this minigame works perfectly.  On OpenGL, one of the layers of smoke appear to be rendered improperly.  A comparison is included.  OpenGL is on the left, Software Renderer on the right.

![image](https://user-images.githubusercontent.com/6598209/61019451-3dc8b200-a368-11e9-9eb6-2936e1276a4b.png)

**Comment by Arisotura** [comment]
fixed
