### ISSUE TITLE
SVatG Loves You by St. Vincent and the Grenadines demo black screen

### ISSUE THREAD

**Issue by benderscruffy** [Arisotura/melonDS#49]
http://www.pouet.net/prod.php?which=59692
nothing but black screens

**Comment by DarkSwan86** [comment]
Still present on ad58a68 with a lot of:

unknown ARM9 IO read16 040002A2 0202005E
unknown ARM9 IO read16 040002AA 0202005E
unknown ARM9 IO read16 040002B2 0202005E
unknown ARM9 IO read16 0402991C 0202005E
unknown ARM9 IO read16 04104672 0202005E
unknown ARM9 IO read16 0402922E 0202005E
unknown ARM9 IO read16 0402991A 0202005E
unknown ARM9 IO read16 04039A16 0202005E

**Comment by StapleButter** [comment]
it seems to shit itself rather badly, it's accessing garbage addresses

**Comment by benderscruffy** [comment]
still present in 0.7

**Comment by benderscruffy** [comment]
still present in 0.7.2

**Comment by StapleButter** [comment]
it's probably shitting itself just because DLDI isn't emulated

**Comment by nathanielcwm** [comment]
Still stuck on a black screen with dldi enabled in the settings on fbca473

**Comment by Arisotura** [comment]
you need to make sure the ROM file is present within your DLDI image.

**Comment by poudink** [comment]
I tried placing the rom at the root of my virtual SD card. Still black screen.

**Comment by iamthelaw2041** [comment]
This demo works now. Can this issue be closed?

![Capture](https://user-images.githubusercontent.com/94656803/144357334-5def1323-75df-46a9-b137-c8112431fda0.PNG)
