### ISSUE TITLE
Contra 4 - Sudden jumps to white during fade transitions

### ISSUE THREAD

**Issue by fsvgm777** [Arisotura/melonDS#491]
During certain fade transitions where the game fades to black, melonDS will suddenly jump to white when the fade to black ends. This does not occur on real hardware.

[Here's some footage that shows the issue](https://youtu.be/XT6CqJcgOtQ) and [here's the expected output (captured directly from a DS)](https://www.youtube.com/watch?v=TuNWmPc2lKU).

This affects both the software renderer and the OpenGL renderer on any setting.

This was tested on the latest revision available on the site (Revision 204b5d8 as of this writing).

EDIT: Just checked on the latest commit (22f3cae as of this writing), the issue still persists

**Comment by Arisotura** [comment]
probably something dumb like not applying master brightness during forced-blank or whatever
