### ISSUE TITLE
Mosaic + windowing wrong output

### ISSUE THREAD

**Issue by RSDuck** [Arisotura/melonDS#492]
This is a tiny edge case, so not so much of importance. In GPU2D.cpp in multiple occasions (like here: https://github.com/Arisotura/melonDS/blob/master/src/GPU2D.cpp#L1661) the mosaic counter is only updated while inside an area which isn't blocked by the window.

The effect of this can be tested with this: https://gist.github.com/RSDuck/e8064791e80f27bd797001af7f4e2084

melonDS:
![grafik](https://user-images.githubusercontent.com/9352526/61590138-5e88d700-abb4-11e9-97ee-7ff82f8a9f24.png)

hardware:
![grafik](https://user-images.githubusercontent.com/9352526/61590141-6ea0b680-abb4-11e9-8f4e-0180e50bdfe5.png)

**Comment by Arisotura** [comment]
relatedly: mosaic will not work on large BG due to a stupid-ass oversight.

mosaic needs a overhaul anyway.
