### ISSUE TITLE
Would it have killed you to just release the full folder of that emulator as download?

### ISSUE THREAD

**Issue by Dendaru** [Arisotura/melonDS#496]
As the title states. 
Ive downloaded so much shit from github alread never had i ever do such a backass method by downloading some prompt thing and execute commands which lead to 50 million new downloads.
Why make it as incovenient as possible i dont get it.

**Comment by Arisotura** [comment]
request denied. turn off asshole mode and try again.

**Comment by Arisotura** [comment]
besides I don't get why you'd have to do '50 million new downloads'. we have binaries.
