### ISSUE TITLE
Publish the melonDS on Flathub

### ISSUE THREAD

**Issue by LeandroStanger** [Arisotura/melonDS#501]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by brushtool** [comment]
Why make thihttps://github.com/Arisotura/melonDS/issues/484s issue? I feel like this is a decision the developer would make themselves.

**Comment by RSDuck** [comment]
melonds is on flathub now https://github.com/flathub/net.kuribo64.melonDS
