### ISSUE TITLE
New framerate limiter stuck at 59/60 fps resulting in additional audio stuttering.

### ISSUE THREAD

**Issue by NarryG** [Arisotura/melonDS#512]
Since I was interested in the framerate limiter + audio sync (#470) I compiled the latest build with the new framerate limiter under Windows, and I'm having more issues than before. I'm sitting at a constant 59/60fps resulting in constant audio stuttering. 

I've tried various games and they all seem to have the same behavior.

**Comment by Arisotura** [comment]
o yeah there was a bug in the new audio code
