### ISSUE TITLE
[Feature request] Allow user to specify save data directory

### ISSUE THREAD

**Issue by Metasynic** [Arisotura/melonDS#513]
Having the save data location locked to the ROM directory is very inconvenient, even a config option would suffice if it can't be done in the UI. I love melonDS and think it's the best DS emulator out there, and it would be even better if we could choose what directory saves go in - this allows users to sync saves across the cloud, allows for better organization, etc. Almost every other emulator out there has an option for this and it would allow more flexibility!

**Comment by Arisotura** [comment]
seeing how often this one is requested, it's going to be in the TODO list for melonDS 0.9 or sooner

**Comment by Zettymaster** [comment]
Maybe when I'm done with the RTC offset stuff I will do this... especially
seeing how often this gets requested.

**Comment by Arisotura** [comment]
well, I already have some ideas in mind regarding how I want it done

**Comment by Metasynic** [comment]
Is there a plan for this in the works? It might be nice to just do a config option for now if that would be easier.

**Comment by poudink** [comment]
apparently it's in the plans for 0.9.1

**Comment by ipkpjersi** [comment]
Do we know when #946 will be merged? This is a great feature that I would love to see in this amazing emulator.

I am hoping #946 will be suitable for how you want it done @Arisotura so we can see this amazing feature merged. 

I'm really hoping it'll make it into the 0.9.3 release, that would be huge.

**Comment by Arisotura** [comment]
done
