### ISSUE TITLE
White screen when loading firmware (Ubuntu)

### ISSUE THREAD

**Issue by michaelcpuckett** [Arisotura/melonDS#519]
Loading ROMs works, but System > Run just loads both white screens

Is this a common issue?

**Comment by RSDuck** [comment]
you might have a bad bios files. Try comparing the checksums with the ones which can be found here: https://drastic-ds.com/viewtopic.php?t=5417

**Comment by michaelcpuckett** [comment]
Did not match. Updated and working, thanks
