### ISSUE TITLE
Audio Sync

### ISSUE THREAD

**Issue by Priestyle** [Arisotura/melonDS#520]
On MelonDS 0.8.x having "Audio Sync" enabled does not make Gen 4 Pokemon Games (DPPtHGSS) connect. Also disabling "Audio Sync" makes Frame Limit ON/OFF work as intended. Please look into this.

**Comment by poudink** [comment]
that sounds like intended behaviour to me?

**Comment by Spikestuff** [comment]
That's definitely Intended behavior.

**Comment by Arisotura** [comment]
audio sync isn't meant to make wifi work better. it's meant to avoid any audio stuttering by syncing the emulator to the audio output rate.
