### ISSUE TITLE
Ultimate Mortal Kombat 3 - gameplay is slow

### ISSUE THREAD

**Issue by MojoJojoDojo** [Arisotura/melonDS#528]
Continuing from my post at the forums : 
http://melonds.kuribo64.net/board/thread.php?pid=851#851
The game got issues with the framerate being really slow at about 30 fps.
Note that this was the problem on desmume as early as version 0.9.7 as reported here:
https://forums.desmume.org/viewtopic.php?id=9056.
Maybe it will be useful for debugging the problem.
on the latest desmume git it still hangs from time to time on my PC at least.
There is also issues with graphics using the OpenGL renderer but everything works correctly in the software renderer.

**Comment by Pik-a-boo** [comment]
It's not my PC that causing it , I can run 3D games in full speed and this is a 2D game.
It's something else that causes it , you can try and see for yourself.

**Comment by MojoJojoDojo** [comment]
It's not my PC its a known issue with how the game is programmed.

**Comment by RSDuck** [comment]
as I already said in the forum thread, the game is probably so slow, because it constantly reconfigures the MMU(which games usually do once at the start), which leads to lot of huge stuff being constantly recalculated.

**Comment by poudink** [comment]
if it's just the game being slow, then that just means the game takes more power to emulate. not sure you could really that a bug, and not sure you could really "fix" it without relying on speed hacks. if others have the same issue, then I guess it just takes that much power. the jit will probably help, for what it's worth.

**Comment by MojoJojoDojo** [comment]
> if it's just the game being slow, then that just means the game takes more power to emulate. even if the way the game is programmed is what makes it slow, that doesn't really change anything. not sure you could really that a bug, and not sure you could really fix it without relying on speed hacks. the jit will probably help, though.

JIT wont help I already tried it.
I also mentioned about the graphical issues with OGL tho.

**Comment by poudink** [comment]
well the opengl graphical issue sounds more like an issue. can you give more detail about it?

**Comment by RSDuck** [comment]
that's a completely different story.

Haven't you read my post? The game indeed does something very unusal, melonDS is not prepared, which could be looked into. This is something different than a game which is slow, because it pegs the CPU (I'm looking at you Golden Sun).

**Comment by poudink** [comment]
well the game does something unusual sure, but it's the game that's doing something unusual. what's melonds supposed to do about that?

**Comment by RSDuck** [comment]
the game constantly triggers the recalculation of some data. Currently melonds naively does that, because most games only trigger this once at the start. The reason the game is slow is due to the way certain things are implemented in melonds. The recalculation might not even be needed.

**Comment by Arisotura** [comment]
bürp

I'm going to look into it and tell you whether the constant recalculation is warranted

**Comment by MojoJojoDojo** [comment]
There is still the OGL issue but I guess it's not that critical lol.

**Comment by RSDuck** [comment]
make a separate issue with images
