### ISSUE TITLE
Support for cheat code entry

### ISSUE THREAD

**Issue by yuya495** [Arisotura/melonDS#529]
Hi nice to meet you Arisotura's
I want cheat code input function

**Comment by MojoJojoDojo** [comment]
You can use DSATM for now. 
Not the best but it works.

**Comment by yuya495** [comment]
Unfortunately I could not download DSATM
So I used Pro Action Replay (PAR) with melonDS
I would like to enter a cheat code

**Comment by poudink** [comment]
this was added in 0.9
