### ISSUE TITLE
Broken graphics in TloZ Spirit Tracks since cb90475

### ISSUE THREAD

**Issue by windwakr** [Arisotura/melonDS#531]
Before cb90475:
![before](https://user-images.githubusercontent.com/284886/67595286-4a64f080-f734-11e9-9083-c8e523afe20a.png)

After cb90475:
![after](https://user-images.githubusercontent.com/284886/67595297-4e910e00-f734-11e9-87af-6c896086d9f4.png)

**Comment by poudink** [comment]
which renderer

**Comment by Arisotura** [comment]
renderer is irrelevant there, that affects the 2D engine

**Comment by Arisotura** [comment]
I encourage to continue testing further revisions tho; I intend on making more changes to sprite mosaic and shit, which might break things again
