### ISSUE TITLE
[Arch linux]Wifi config hangs when selected

### ISSUE THREAD

**Issue by heavysink** [Arisotura/melonDS#532]
Environment: Archlinux
Version:melonds git

Config->Wifi settings, console output libpcap.so.1 init successful and then hangs

**Comment by i404788** [comment]
Had same issue on ubuntu, seems to be caused by active devices with `null` addresses.

**Comment by Arisotura** [comment]
oops. my bad

**Comment by WaluigiWare64** [comment]
Was fixed in the PR that linked here.
