### ISSUE TITLE
Harvest Moon The Tale of Two Towns - Black outline around sprites

### ISSUE THREAD

**Issue by Krusher97** [Arisotura/melonDS#533]
Theres a black outline around the sprites at the summit of the mountain when using the software renderer. It doesn't exist when using the OpenGL one.
![melonDS_2019-11-05_02-13-42](https://user-images.githubusercontent.com/25664221/68158310-6444d580-ff75-11e9-87cc-18893eda702d.png)
![melonDS_2019-11-05_02-13-50](https://user-images.githubusercontent.com/25664221/68158384-850d2b00-ff75-11e9-906e-ffbbc0fce7f0.png)
First screenshot is from the software renderer and the second one is from OpenGL. Screen filtering has no effect on it.

**Comment by Krusher97** [comment]
I noticed that you labelled it as OpenGL. 
The OpenGL renderer has the proper behavior in this case. Its the software one which is glitched.

**Comment by RSDuck** [comment]
oh, sorry for the mislabelling, I was a bit overly eager there.

**Comment by Arisotura** [comment]
odd. generally the OpenGL renderer would be the one being less accurate, but, welp. the DS GPU is a pile of quirks after all.

**Comment by Arisotura** [comment]
can you re-test this on the latest revision? I suspect it's the same class of issue as those that were fixed.

**Comment by Krusher97** [comment]
Is there a build bot somewhere? I cannot build it. 

Alternatively you could confirm it by starting a new game and running to the summit.

**Comment by RSDuck** [comment]
there is but it looks like it's broken for Windows currently

**Comment by Arisotura** [comment]
I was going to direct you to the Actions tab, but it looks like the latest build failed for whatever reason. it's wierd because I didn't even touch anything big.

**Comment by Arisotura** [comment]
regardless: 
[melonDS.zip](https://github.com/Arisotura/melonDS/files/4466129/melonDS.zip)

**Comment by Krusher97** [comment]
![melonDS_2020-04-12_18-47-46](https://user-images.githubusercontent.com/25664221/79069736-2ef39f00-7cee-11ea-9803-706d4c1fde56.png)

Yeah it seems to be fixed now

**Comment by Arisotura** [comment]
sweet!
