### ISSUE TITLE
Firmware issues

### ISSUE THREAD

**Issue by yuya495** [Arisotura/melonDS#535]
Quiz Magic Academy DS (J)
Quiz Magic Academy DS Futatsu no Jikuuseki (J)
When you start melonDS from the next time and press system → Ran, it will remain a white screen for a while and Firmware will not start again and other games can not be started

**Comment by yuya495** [comment]
The version of emulation used is EmuCR-melonDS-20191104-x64

**Comment by yuya495** [comment]
Derby Stallion DS (J)
Even if you select in-game wi-fi connection
Since the above phenomenon was confirmed
It may be a bug in wi-fi, not firmware

**Comment by Arisotura** [comment]
try again with one of the release builds from melonDS's site, or a build of the latest revision you made yourself, or anything that isn't from EmuCR

**Comment by yuya495** [comment]
I tested with the latest version of Arisotura official website melonDS_0.8.3_win64
When launching Quiz Magic Academy DS (J) for the first time
![amarec(20191108-083310)](https://user-images.githubusercontent.com/8580180/68437561-b18aa680-0204-11ea-9769-e2f553c44467.PNG)
![amarec(20191108-083600)](https://user-images.githubusercontent.com/8580180/68437562-b18aa680-0204-11ea-9d9c-5e9f0118527f.PNG)
![amarec(20191108-083615)](https://user-images.githubusercontent.com/8580180/68437563-b18aa680-0204-11ea-970c-99a0afa62e69.PNG)
![amarec(20191108-083617)](https://user-images.githubusercontent.com/8580180/68437564-b18aa680-0204-11ea-8363-8c1ebaf81f18.PNG)
![amarec(20191108-083624)](https://user-images.githubusercontent.com/8580180/68437573-ba7b7800-0204-11ea-9c63-a589e2cce4f9.PNG)
![amarec(20191108-083633)](https://user-images.githubusercontent.com/8580180/68437574-bb140e80-0204-11ea-9ed6-729f65bc7100.PNG)
![amarec(20191108-083639)](https://user-images.githubusercontent.com/8580180/68437575-bb140e80-0204-11ea-83fe-319b6f0c37c8.PNG)

First launch of Quiz Magic Academy DS Futatsu no Jikuuseki (J)
![amarec(20191108-084153)](https://user-images.githubusercontent.com/8580180/68437712-0f1ef300-0205-11ea-93e3-7e16f5e8926b.PNG)
![amarec(20191108-084203)](https://user-images.githubusercontent.com/8580180/68437714-0f1ef300-0205-11ea-8395-9b62cbbe5126.PNG)
![amarec(20191108-084205)](https://user-images.githubusercontent.com/8580180/68437721-1514d400-0205-11ea-8632-04c2f0971dc0.PNG)
![amarec(20191108-084212)](https://user-images.githubusercontent.com/8580180/68437722-15ad6a80-0205-11ea-99e4-0e759595a3bb.PNG)
![amarec(20191108-084214)](https://user-images.githubusercontent.com/8580180/68437723-15ad6a80-0205-11ea-918c-1af50f73e96e.PNG)
![amarec(20191108-084219)](https://user-images.githubusercontent.com/8580180/68437724-15ad6a80-0205-11ea-8cd1-08bd0f1923e7.PNG)
![amarec(20191108-084225)](https://user-images.githubusercontent.com/8580180/68437725-15ad6a80-0205-11ea-9f00-3698688fe374.PNG)
![amarec(20191108-084231)](https://user-images.githubusercontent.com/8580180/68437726-16460100-0205-11ea-9e5c-d26c02cfc73c.PNG)

When starting from the second and subsequent Firmware screens
It ’s always this white screen
![amarec(20191108-083701)](https://user-images.githubusercontent.com/8580180/68437826-79d02e80-0205-11ea-96eb-c55f97f6dfd4.PNG)

**Comment by yuya495** [comment]
I tested with melonDS_0.8.3_win64 on Arisotura's official website

When launching Quiz Magic Academy DS (J) for the first time
![amarec(20191108-083310)](https://user-images.githubusercontent.com/8580180/68438075-5659b380-0206-11ea-8f21-e998db39ce05.PNG)
![amarec(20191108-083600)](https://user-images.githubusercontent.com/8580180/68438076-5659b380-0206-11ea-99fb-e49ff941abdb.PNG)
![amarec(20191108-083615)](https://user-images.githubusercontent.com/8580180/68438078-5659b380-0206-11ea-8e29-1ed6944a204f.PNG)
![amarec(20191108-083617)](https://user-images.githubusercontent.com/8580180/68438080-5659b380-0206-11ea-8242-61dcee277be1.PNG)
![amarec(20191108-083624)](https://user-images.githubusercontent.com/8580180/68438090-5bb6fe00-0206-11ea-907a-6a58c1cc4e12.PNG)
![amarec(20191108-083633)](https://user-images.githubusercontent.com/8580180/68438092-5bb6fe00-0206-11ea-9c5e-561c128c0c02.PNG)
![amarec(20191108-083639)](https://user-images.githubusercontent.com/8580180/68438093-5bb6fe00-0206-11ea-921a-7697ba67bd31.PNG)

First launch of Quiz Magic Academy DS Futatsu no Jikuuseki (J)
![amarec(20191108-084153)](https://user-images.githubusercontent.com/8580180/68438211-b6505a00-0206-11ea-8f2a-4b08785de0ac.PNG)
![amarec(20191108-084203)](https://user-images.githubusercontent.com/8580180/68438212-b6505a00-0206-11ea-9c5e-9ac4c57a284f.PNG)
![amarec(20191108-084205)](https://user-images.githubusercontent.com/8580180/68438265-ebf54300-0206-11ea-8888-b2f863f9bae9.PNG)
![amarec(20191108-084212)](https://user-images.githubusercontent.com/8580180/68438266-ebf54300-0206-11ea-81d5-7f30827c82ca.PNG)
![amarec(20191108-084214)](https://user-images.githubusercontent.com/8580180/68438267-ec8dd980-0206-11ea-84cc-99d7f11bed79.PNG)
![amarec(20191108-084219)](https://user-images.githubusercontent.com/8580180/68438268-ec8dd980-0206-11ea-8f02-408bcbc8ec46.PNG)
![amarec(20191108-084225)](https://user-images.githubusercontent.com/8580180/68438269-ec8dd980-0206-11ea-9db4-168fdbcde015.PNG)
![amarec(20191108-084231)](https://user-images.githubusercontent.com/8580180/68438270-ec8dd980-0206-11ea-8c80-22df446b1534.PNG)

If you try to boot from the Firmware screen after the second time, this white screen will remain for some reason
![amarec(20191108-083701)](https://user-images.githubusercontent.com/8580180/68438358-4b535300-0207-11ea-9d82-d1f1f07a5efc.PNG)

My .melonDS_0.8.3_win64 .ini file .zip
[melonDS.zip](https://github.com/Arisotura/melonDS/files/3822320/melonDS.zip)

**Comment by Arisotura** [comment]
I don't think this comes from the .ini.

I have a feeling this is the old 'hacked firmware shitting itself' issue.

let's see:
* does the firmware boot to menu instantly rather than showing the health/safety screen first?
* do the games boot without issues if you enable direct boot? (in Emu settings)

if both answers are yes, then you have the bad hacked firmware, and should use a clean firmware dump.

**Comment by yuya495** [comment]
Thank you very much Arisotura
If you dump a clean firmware
Now you can start normally

I hope to be able to enter the melonDS cheat code

**Comment by yuya495** [comment]
It ’s okay to close this problem
