### ISSUE TITLE
Cross Compile?

### ISSUE THREAD

**Issue by UnicorNora** [Arisotura/melonDS#541]
After trying to hack up a Visual Studio script I figured it would be easier to cross compile using WSL. I haven’t tried but I could probally get Linux to build but how do I cross compile to windows

**Comment by RSDuck** [comment]
if you want to build for windows use mingw.

There have been some people trying msvc in the past, but nothing substantial has come from this.

**Comment by CrankySupertoon** [comment]
how do you crosscompile

**Comment by RSDuck** [comment]
from what to what?

**Comment by CrankySupertoon** [comment]
Build Linux to windows

**Comment by RSDuck** [comment]
would you mind hopping onto [irc](https://kiwiirc.com/client/irc.badnik.net/?nick=IRC-Source_?#melonds), to make this conversation a bit quicker. I am Generic there, ping me.

**Comment by RSDuck** [comment]
Can't remember how this conversation ended or whether it even happened. ¯\_(ツ)_/¯
