### ISSUE TITLE
With Audio Sync On: Closing Lid, Turning Fast-Forward Toggle On, and Opening Lid Crashes MelonDS 0.8.3

### ISSUE THREAD

**Issue by Laxbby** [Arisotura/melonDS#547]
Hey there, recently discovered MelonDS and I'm absolutely loving it, besides one minor problem:
My fast-forward toggle seems to be broken. On any emulator that supports it, I like to bind the toggle to the 'up' direction on my controller's right stick, so it's sort-of become habit for me to flick it whenever I need the game to be fast. For Melon 0.8.3, though, this function doesn't seem to work anymore. When I realized it wasn't working correctly, I bounded it to one of the face buttons instead: still didn't work. I even tried to bind it to a keyboard button (specifically the '~' key) and it refused to work. It does this on every game I've tried so far. It worked when I tried the toggle on 0.8.2 (even with the exact same config file from 0.8.3), so I'm thinking it's an exclusive issue with 0.8.3. I tried to redownload the 0.8.3 version from the site, I erased the config file, and restarted my computer several times to no luck. 
The regular fast forward button, not the toggle, works as intended on 0.8.3.
Also, I noticed something a bit strange when I was trying to get it working again: When I closed the lid via the hotkey, the toggle key worked perfectly fine, and I would get faster framerates as intended. It seems like the toggle only works when the lid is closed, for some reason. Also, when I closed the lid, turned the toggle 'on', then opened the lid (while the toggle was still on), it would crash MelonDS.
In-case you need it, I'm running Windows 10.
This isn't a huge bug, but as I mentioned earlier, it's become habit for me at this point, so it's just a little annoying. If there's any other info you need, don't hesitate to ask. Thanks for any help.

**Comment by Laxbby** [comment]
I found the issue - This wasn't a glitch, instead it was because I left "Audio Sync" on by accident. This explains why it worked fine in 0.8.2, since Audio Sync didn't exist back then. It probably sped up when the lid was closed because no audio was being played, not sure about the crash though. Oh well, the problem's been solved.

**Comment by poudink** [comment]
I'd argue the crash issue is a good reason to keep this open.

**Comment by Laxbby** [comment]
Yea, perhaps. I mostly just closed it because the main 'issue' has been solved. I'll reopen it again though.

**Comment by Arisotura** [comment]
crash's not too normal, yeah

as for the fast-forward thing, to clear any confusion:

"fast forward" works as long as the key is pressed, and disables anything that may limit emulation speed.

"fast forward toggle" is merely a shortcut for toggling the framerate limiter. if you have vsync or audio sync on, those will still limit your framerate as a side effect.

**Comment by Laxbby** [comment]
That's what I assumed about the fast-forward. Would you ever consider making the "Toggle" act the same as the regular "Fast-Forward" (as in, disabling vsync/audio sync), or is there a reason why that's not a good idea?

**Comment by Laxbby** [comment]
I did a bit more poking around, and I got MelonDS to crash a few times even without opening the lid. It seems that, if audio sync is on, and the Fast-Forward Toggle is on, and you close the lid, Melon freaks out and may crash. My guess is that the FPS is tied to the audio, so when the lid is closed, the FPS goes as quick as it wants (since audio isn't playing at all). Since the game isn't rendering anything, the FPS will jump to >10,000 FPS, averaging around 30,000. For me, the emulator would eventually stop at 77,777 and crash, which I'm guessing is because that's *way too fast* for a DS to be going, and Melon panics and quits.

**Comment by Arisotura** [comment]
it's probably a division by zero somewhere or something dumb like that. melonDS just does nothing when in lid-closed mode.

the 77777 number is a placeholder that is used in one of those divisions when it would divide by zero. I thought I'd handled all those cases... guess not.

**Comment by Arisotura** [comment]
I see where the crash is happening. seems to be a race condition where the window title is being changed so fast that it gets changed again while libui is converting it, so it panics and shits itself

**Comment by Laxbby** [comment]
Awesome, thank you for the help!
