### ISSUE TITLE
Reading Windows Touch Input

### ISSUE THREAD

**Issue by RZeratsky** [Arisotura/melonDS#548]
Not sure if this is "issue" or "enhancement request".

I have a portable PC with touchscreen input. MelonDS does not read screen touches as events translated into DS touch input. Mouse input works fine.

System is a GPD Win 2 and this was tested across multiple titles.

**Comment by Arisotura** [comment]
I'd have to look into how Windows transmits touch input, if that's in some weird way that isn't mouse-compatible.

**Comment by MojoJojoDojo** [comment]
I know citra added support for this recently but it uses Qt.

**Comment by RSDuck** [comment]
fixed by https://github.com/Arisotura/melonDS/commit/e48e45db7698e006d19b9f5422d9fc86fe8e9013
