### ISSUE TITLE
Mid-screen gap is not scaled with the window size

### ISSUE THREAD

**Issue by rzumer** [Arisotura/melonDS#553]
I have 4K displays, so 1x screen size is a bit small, but I would like to display the window with an accurate gap, and it looks like the gap sizes remain the same regardless of the window scaling. I think it would make more sense to scale the gap along with the displays.

**Comment by Arisotura** [comment]
good point.

**Comment by rzumer** [comment]
This seems to have been fixed automagically with the Qt UI.

**Comment by Tatsh** [comment]
This is caused by having a value for `QT_SCREEN_SCALE_FACTORS` set in the environment. I changed the .desktop file to use `Exec=env -u QT_SCREEN_SCALE_FACTORS melonDS`.
