### ISSUE TITLE
bios7.bin, bios9.bin and firmware.bin as download

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [Arisotura/melonDS#572]
Can you provide the files (bios7.bin, bios9.bin and firmware.bin) as download?

Can you add it under readme? This is from NDS Lite.

bios7,bios9,firmware.zip (removed by @RSDuck)

**Comment by Zettymaster** [comment]
The firmware and bios are not provided for legal reasons as I understand it, so posting them here may not be your best idea for us and the project.

**Comment by Spikestuff** [comment]
Looks like someone needs to read up [GitHub Terms of Service](https://help.github.com/en/github/site-policy/github-terms-of-service)... and have common sense about asking (and providing) something that isn't legal.

**Comment by RSDuck** [comment]
It's on the [roadmap](http://melonds.kuribo64.net/board/thread.php?id=222) to eventually provide an open source BIOS replacement.
