### ISSUE TITLE
[Small Feature Request] Option to Boot Firmware Regardless of if a ROM is Loaded

### ISSUE THREAD

**Issue by SNBeast** [Arisotura/melonDS#591]
Some people may want a configuration option to boot firmware regardless of whether a ROM is loaded or not.

Additionally, there is a portion of use cases where it would be slightly more convenient if there was a menu option in System to boot firmware instead of loading the game (for example, if you have a Pokemon Gen IV game loaded as the cartridge and want to boot into the firmware to launch DS Download Play to download the transfer program from a Gen V game running in another instance, and it would save a few clicks and possibly a Google search to have an option to boot firmware).

**Comment by RSDuck** [comment]
there already is under System -> Run
