### ISSUE TITLE
Can't set any DualShock 4 button

### ISSUE THREAD

**Issue by Filo97** [Arisotura/melonDS#593]
As stated, both in latest release and latest manually compiled build, I am unable to assign any button to my DS4. It is detected as "Wireless Controller" in nightly and "XInput Device" in last release. When I click on one of the buttons to trigger a button change in input config, then press any button on the DS4, nothing will happen. Also tried with DS4Windows to get it recognized as an "XBox 360 Controller" to no avail.

**Comment by nathanielcwm** [comment]
It works fine for me with both DS4Windows enabled and disabled.

**Comment by Filo97** [comment]
This is what happens (or rather doesn't happen) when I try to do so. I heard about there being two different "kinds" of DS4 controllers, maybe that could be the issue? 
https://www.youtube.com/watch?v=HRiHuKoQkz0

**Comment by Filo97** [comment]
I have tried over and over again and no matter what I can't manage to find a way to use the DS4. Am i the only one who has encountered this issue?

**Comment by Filo97** [comment]
If In DS4Windows I toggle the profile to make it detect as a DS4 insead of Xbox360 controller it straight up doesn't get detected as a controller. For some reason now it also doesn't get detected at all without DS4Windows.

**Comment by Filo97** [comment]
I am an idiot and i deeply apologize for everything, this is what happens when i'm sleep deprived, i didn't even realize that keyboard and controller were different tabs because i'm used to that layout with desmume.
