### ISSUE TITLE
Minor graphical issue with Software render in Metal Slug 6

### ISSUE THREAD

**Issue by ThunderAxe31** [Arisotura/melonDS#598]
In the following image, there is a comparison of Software render and OpenGL render for the main menu screen of Metal Slug 6. With Software render (left image) you can see an extra horizontal line, about at the bottom of the top screen. It's especially evident if you look at the prisoner ropes.
![sIfSqWW](https://user-images.githubusercontent.com/36802254/79011329-16f01400-7b64-11ea-99e8-ca5a27817dc3.png)

**Comment by RSDuck** [comment]
Arisotura confirmed this on hardware. The button is drawn with the 3d engine.

desmume seems to have this bug as well, while no$gba hasn't

**Comment by Arisotura** [comment]
the elements are rendered as a grid of 16x16 tiles, with button backgrounds first and then the text/images on them. oddly, the last row is getting textured wrong (which is odd as there isn't any oddity there, the texcoords are as simple as it can get).

there isn't even any difference between how that last row is drawn and the other rows. wtf

**Comment by Arisotura** [comment]
huh. the texcoords at the bottom screen edge are 0xFF instead of 0x100.

this looks like clipping shenanigans.
