### ISSUE TITLE
BGs with overlapping gfx memory don't render correctly

### ISSUE THREAD

**Issue by PoroCYon** [Arisotura/melonDS#599]
I had two backgrounds with the same VRAM address for the graphics memory backing. Instead of the PPU drawing two backgrounds with the same contents, only one was drawn. (I've only tested this with backgrounds 2 and 3, as Bmp8 256x256 backgrounds, on banks H and I, in mode 5 on the sub engine.)

The current hypothesis is that only the background with the highest priority is rendered.

A possible explanation for this is that accessing the same VRAM region multiple times at once won't work due to the way the bus is wired.

Some thing still needs to be figured out:
* Is it *actually* looking at the priorities, or hardcoded IDs, or is something else happening?
* Is this specific to the setup I used, or does the same always happen regardless of other things?
* ...

NOTE: this only happened when I gave both backgrounds the *exact* same VRAM backing address. Partially-overlapping backgrounds do seem to work fine (but I only tried backgrounds of different formats.)

EDIT: I've only tested this on my DSi, and I don't know if it was using the old or revised PPU hardware (cf. SCFG regs).

**Comment by Arisotura** [comment]
I don't even know what the DSi hardware revisions do, tbh

**Comment by Arisotura** [comment]
couldn't reproduce it with BG2 and BG3, mode 5, 256-color bitmap BGs, VRAM A and B, on the main engine

**Comment by Arisotura** [comment]
I'd need to see what your code is doing, maybe I could figure out why it's glitching.

**Comment by PoroCYon** [comment]
I knoooow, I'm trying to reproduce it again (as I made a workaround for the Revision demo), but life is getting in the way.

**Comment by PoroCYon** [comment]
Hm, couldn't manage to reproduce it again. I guess I'll close it until I come across it again.
