### ISSUE TITLE
"undefined THUMB9 instruction 4422" in Mega Man Zero Collection

### ISSUE THREAD

**Issue by windwakr** [Arisotura/melonDS#6]
https://github.com/StapleButter/melonDS/blob/master/ARM_InstrTable.h#L1695

The instruction decodes to 'add r2, r4', which from what I'm seeing in the ARM manuals is unpredictable behavior with this encoding since neither operand is a high register.

EDIT:
DeSmuME treats this as a valid high register add instruction:
https://github.com/TASVideos/desmume/blob/master/desmume/src/thumb_tabdef.inc#L307

**Comment by StapleButter** [comment]
I would have to give this a test to be sure. Thanks for the heads-up though.

**Comment by mudlord** [comment]
I'm pretty sure Desmume is **NOT** meant to be used as a reference.....

**Comment by StapleButter** [comment]
Latest revision allows this form of opcode, but it still needs verification. Maybe it only works on the ARM9 or something like that.

**Comment by endrift** [comment]
I seem to recall having this issue with mGBA (not medusa). UNPREDICTABLE in ARM parlance does not mean "oh god the CPU will explode", it means "a specific ARM implementation will probably do the same thing but we don't know what". I believe ARM7 treats it as a valid opcode with no high registers, and ARM9 is probably the same.

**Comment by poudink** [comment]
this was fixed in melonDS 0.2

**Comment by Arisotura** [comment]
I'd kept this open before because I wanted to confirm that there wasn't anything special about these instructions. just tested them on both ARM9 and ARM7: nothing special.
