### ISSUE TITLE
JIT: jit_master_merge branch is gone

### ISSUE THREAD

**Issue by jackdroido** [Arisotura/melonDS#612]
Hi !

Since now I was testing the JIT emulation building the jit_master_merge branch. At least since a few days ago cause now has disappeared. I tried the generic_jit branch, but I cannot trigger JIT mode with that (since I have a slow machine I just look at fps value, no JIT, no play :-)

Where the JIT work is going on right now ?

Sorry if I miss the info. Thanks so much for your work and time !

**Comment by RSDuck** [comment]
the jit_master_merge branch has been removed in favor of reguarly rebasing generic_jit on master. Though looks like I made small mistake by not pulling in the latest changes of master, it sounds like you've either forgot to enabling building the JIT in cmake or to enable it in the emulator settings.

**Comment by jackdroido** [comment]
Ok thanks. Here is what I tried.
Clean checkout of generic_jit branch. Looking at CMakeLists.txt it seems JIT build is enable by default (building on my Archlinux PC).

Actually if I try to turn JIT off (with -DENABLE_JIT=OFF) build  fails with:

`/home/user/Downloads/melonds-git-jit_generic/src/melonDS/src/ARM.cpp: In member function ‘virtual void ARM::DoSavestate(Savestate*)’:
/home/user/Downloads/melonds-git-jit_generic/src/melonDS/src/ARM.cpp:130:34: error: ‘JIT_Enable’ is not a member of ‘Config’
  130 |     if (!file->Saving && Config::JIT_Enable)
      |                                  ^~~~~~~~~~
`

So I'm sure JIT is built :-)
The configuration from the working version (which was commit 40908c5 from jit_master_merge branch, if I'm correct) which gives me a pretty solid 60 FPS is all defaults except for:

- 3D renderer: Software (on my Intel integrated this works better)
- Enable JIT recompiler (with default 10 block size)

Now if I start the generic_jit version with this config and try to load Mario Kart (just an example) after a little hang it segfault right away.

If then I just untick the JIT recompiler box, and it tick it back on and try to load the game again, it just hang with both DS screen white, but does not crash.

Here is a backtrace from an unstripped build with LTO off: https://pastebin.com/VmQG3gUa

**Comment by RSDuck** [comment]
> Ok thanks. Here is what I tried.
Clean checkout of generic_jit branch. Looking at CMakeLists.txt it seems JIT build is enable by default (building on my Archlinux PC).

Actually if I try to turn JIT off (with -DENABLE_JIT=OFF) build fails with:

/home/user/Downloads/melonds-git-jit_generic/src/melonDS/src/ARM.cpp: In member function ‘virtual void ARM::DoSavestate(Savestate*)’: /home/user/Downloads/melonds-git-jit_generic/src/melonDS/src/ARM.cpp:130:34: error: ‘JIT_Enable’ is not a member of ‘Config’ 130 | if (!file->Saving && Config::JIT_Enable) | ^~~~~~~~~~ 

good catch, I'll make sure that to make the interpreter build work again

> 3D renderer: Software (on my Intel integrated this works better)

yeah, for low end systems the software renderer is the better choice. Without

> Enable JIT recompiler (with default 10 block size)

You can increase the block size. The default size was very conservative, it needs to be bumped up, I don't know any games which had problems with the maximum block size of 32.

> Now if I start the generic_jit version with this config and try to load Mario Kart (just an example) after a little hang it segfault right away.

If then I just untick the JIT recompiler box, and it tick it back on and try to load the game again, it just hang with both DS screen white, but does not crash.

Here is a backtrace from an unstripped build with LTO off: https://pastebin.com/VmQG3gUa

Ah, now I notice. I forgot to make my latest changes work on linux.

**Comment by RSDuck** [comment]
https://github.com/Arisotura/melonDS/commit/59c8d3976562ec3ed057f21116b76a3a532bc4d1 should have fixed it

**Comment by jackdroido** [comment]
Nope...it doesn't crash anymore, but just hang with both DS screens white. As mentioned in #613 , just trying to enter the DS firmware has the same outcome.

**Comment by RSDuck** [comment]
there was a second messup by me, it works now with https://github.com/Arisotura/melonDS/commit/b0b9ec42e42d491a90352aea040eb6ffb319cdf9 (tried it myself)

**Comment by jackdroido** [comment]
Yeah, now DS firmware and Mario Kart works good again. The only other game which I was and can play is Pokemon Black...with that it now just goes into a black screen at the press start screen (after the Nintendo and Game Freak screens), with audio still playing in the background but not responding to any input.
(Thanks again for your fast response !)

**Comment by jackdroido** [comment]
Oh, I also realized only now that running a ROM from command line result in a segfault, here the backtrace: https://pastebin.com/eQRSuvXs

The problem was there also in the jit_master_merge version. master instead is good.

**Comment by RSDuck** [comment]
it might have been a different issue, but I found two issues with Pokemon Black/White which have been fixed in the last commit :)

**Comment by RSDuck** [comment]
the crashing when running from the command line is a different problem not related to the JIT

**Comment by jackdroido** [comment]
> it might have been a different problem, but I found two issues with Pokemon Black/White which have been fixed in the last commit :)

OK ! I confirm it works now.

> the crashing when running from the command line is a different problem not related to the JIT

Just reporting... I see now there was a similar issue #584, but there it was an occasional problem, here it seems systematic.

I'm a happy player for now :-)

**Comment by RSDuck** [comment]
fine, the other issue should be fixed in master too, expect to see it soon in the jit branch too
