### ISSUE TITLE
When streaming melonDS to Discord, Discord doesn't capture its sound

### ISSUE THREAD

**Issue by GoggleBoy** [Arisotura/melonDS#619]
Very sorry if this is a wrong place to post about this problem.
But the title pretty much says it all. While trying to use Discord's "Go Live" feature with melonDS, it streams the video output, but those who watch the stream can't hear the sound emulator produces, Discord simply refuses to broadcast it for some reason.
I figured it may actually be a problem on melonDS's side, since Discord has no such issues with any other emulator software (or any other software period).

Thank you for all your amazing work.

**Comment by poudink** [comment]
I think it's an issue on discord's end. melonds or any other app weren't designed to be streamed with discord, it's discord that was designed to stream apps. if it has trouble streaming a certain app, I don't think it's the app's fault.

**Comment by GoggleBoy** [comment]
You are right. But it's very very doubtful that Discord will do anything on its end to fix the streaming of one very specific and not highly popular app. On the other hand, there's a chance that melonDS's handling of audio could be slightly tweaked to be less weird (if it is indeed weird) to be compatible with a very popular service used by almost everyone.

**Comment by Arisotura** [comment]
melonDS doesn't do anything weird? it's just a SDL audio output stream.

**Comment by GoggleBoy** [comment]
It seems that my system might be at fault. I asked my friend to stream melonDS to me on Discord, and I could hear the sound. But when I try streaming it to Discord, no one hears melonDS's sound. But they can hear literally ANY other app or game that I stream.

No idea what's wrong and why Discord refuses to capture the sound of this specific app on my PC. But the issue seems to be unique to me.
