### ISSUE TITLE
One of the screens gets too small for me to see.

### ISSUE THREAD

**Issue by desertboi** [Arisotura/melonDS#625]
When I try to play Pokemon HeartGold, one of the screens gets really small, and I can't see what is happening and essentially can't play. In the intro its the bottom screen and after that its the top. Changing the screen sizing doesn't fix it. I also can't make the emulator work in full screen, because I can only see a corner of the game when I try. I'm very new to emulation so if I'm making some silly mistake I apologize in advance.

**Comment by poudink** [comment]
https://github.com/Arisotura/melonDS/pull/611 this should fix it

**Comment by desertboi** [comment]
I tried changing the screen layout but it didn't change anything. The second screen is also much smaller than the first picture in the link.

**Comment by poudink** [comment]
can you send a screenshot

**Comment by desertboi** [comment]
![HeartGold Small Screen 1](https://user-images.githubusercontent.com/65210391/81986668-416f3a00-9606-11ea-879d-23a27d5ffb4e.PNG)
![HeartGold Small Screen 2](https://user-images.githubusercontent.com/65210391/81986672-42a06700-9606-11ea-8d55-f9833e4d0e06.PNG)

**Comment by RSDuck** [comment]
this is going to be fixed with the new QT frontend which will receive a new layout code

**Comment by desertboi** [comment]
Ok thanks! When will this be released?

**Comment by RSDuck** [comment]
when it's done.

If you want to follow progress, observe the [QT branch](https://github.com/Arisotura/melonDS/tree/qt)
