### ISSUE TITLE
[JIT Build] Super Mario 256 Demo: JIT crashes the game when entering a stage

### ISSUE THREAD

**Issue by poudink** [Arisotura/melonDS#627]
Demo download: http://kuribo64.net/get.php?id=Wx1BNA6YvghU40As (apply to an european SM64DS rom)
Using the JIT build that was released on the melon blog. this might have been fixed by commits after, but since auto builds have been disabled for all non master branches in https://github.com/Arisotura/melonDS/pull/588, I can't check. When entering any pipe in the hub world, the game will black screen. This happens whenever the JIT is on, even when branch and literal optimizations are disabled and block size is set to 1.

**Comment by RSDuck** [comment]
can't reproduce with latest master, seems to be already fixed.

**Comment by poudink** [comment]
alright, then.
