### ISSUE TITLE
Fire Emblem Shadow Dragon - chapter text displays incorrectly

### ISSUE THREAD

**Issue by jcharris98** [Arisotura/melonDS#628]
![2020051618560300-76DCFB461CA00888054641E6A9C09703](https://user-images.githubusercontent.com/55642209/82119304-e000b580-9742-11ea-8ddd-a8ec336fd068.jpg)
![2020051618555100-76DCFB461CA00888054641E6A9C09703](https://user-images.githubusercontent.com/55642209/82119305-e131e280-9742-11ea-9ce2-fa671227cc1b.jpg)

**Comment by RSDuck** [comment]
which 3d renderer? Software or GL?

**Comment by jcharris98** [comment]
I don't see the option to select a renderer. This is the switch version, right?

**Comment by RSDuck** [comment]
say that right away.

1. Do you use NSPs or things like that? If you do don't.
2. Try disabling literal and/or branch optimisations.
3. Otherwise it's probably an issue with gpu2d neon.

**Comment by jcharris98** [comment]
1. not using nsps
2. I tried one, the other, and both with no success
3. Can I do anything about that, or do I need to wait for the next release?

**Comment by RSDuck** [comment]
I think I already fixed that issue, are you sure you're using the [latest version](https://gbatemp.net/threads/melonds-for-switch.518300/page-47#post-8948531)(note the version from the hb appstore is outdated)?

**Comment by jcharris98** [comment]
I'm sure. Fix 2 was the version I had, and just to be sure I re-downloaded it and tried again.

**Comment by RSDuck** [comment]
fixed in https://github.com/RSDuck/melonDS/commit/2b26e3b95c32596af758e42d51fe2fa4523e37b7

thanks for reporting 😺
