### ISSUE TITLE
Add costum save directory

### ISSUE THREAD

**Issue by DLandDS** [Arisotura/melonDS#629]
Add this feature it's makes more easily to manage save game file (.dsv) for end-users.

**Comment by poudink** [comment]
melonDS doesn't use DSV files as far as I'm aware. That's desmume.

**Comment by Zettymaster** [comment]
@poudink correct. melonDS uses .sav

**Comment by RSDuck** [comment]
please be careful, no$gba saves it's savefiles with the extension .sav as well, though it compresses the saves by default.

melonDS uses raw savefiles with no padding.

**Comment by Amnesia1000** [comment]
Regardless of the output format of the save file, it would be great to be able to choose where saved games, save states, screenshots and recordings are saved (when available)

**Comment by Arisotura** [comment]
done
