### ISSUE TITLE
Static build does not start outside of minGW

### ISSUE THREAD

**Issue by autofire372** [Arisotura/melonDS#636]
I get the following error trying to launch a statically-linked melonDS.exe directly from Windows:

`The procedure entry point
_Z21qRegisterResourceDataPKhS0_S0_ could not be located
in the dynamic link library
C:\Emulation\melonds\source\build\melonDS.exe.`

The build launches properly from minGW (`./melonDS`)

**Comment by RSDuck** [comment]
did you build it with msys or mingw-64?

**Comment by autofire372** [comment]
mingw64. Is that wrong?

**Comment by RSDuck** [comment]
no, that should be the correct one

**Comment by autofire372** [comment]
I fixed it.

For future reference, the proper cmake command is:
`cmake -DCMAKE_PREFIX_PATH=/mingw64/qt5-static -DBUILD_STATIC=ON .. -G "MSYS Makefiles"`
