### ISSUE TITLE
(Left) Shift, Alt, and Ctrl can't seem to be used for setting up inputs, but the right version can

### ISSUE THREAD

**Issue by ShadowWalker13** [Arisotura/melonDS#653]
In the "Input config" section, for the keyboard, if I try setting left shift, left control, or left alt as a control, nothing happens. However, if I use right shift, right control, or right alt it works.
Edit: also, the escape key registers as the enter key.

**Comment by RSDuck** [comment]
if you were still using the libui frontend, this reconfirmation with QT
