### ISSUE TITLE
[Proposal] MelonDS portable

### ISSUE THREAD

**Issue by Amnesia1000** [Arisotura/melonDS#663]
In the latest versions of git I have noticed (in linux) that the MelonDS.ini file is created in the /home/user/.config/MelonDS folder and not in the folder where the executable is, as it was before, it could be reversed and that the configuration be generated again in the folder where the executable is located?

**Comment by pypy702** [comment]
In Windows, the same behaviour happens too.
It is now saved in C:\Users\*user*\AppData\Local\melonDS\melonds.ini.
This now means I can't have different instances of melonDS with different settings.

**Comment by RunisDauphin** [comment]
The developpement versions I tried create the MelonDS.ini file next to MelonDS.exe, wherever you have that executable file. I think that makes it portable, isn't it?

**Comment by Amnesia1000** [comment]
I am using the latest version from the Git and keep creating the ini file in the /home/user/.config/MelonDS folder (in linux, I suppose in windows it continues creating it in C:\Users\user\AppData\Local\melonDS ). It already makes several versions that have the same behavior.

**Comment by nadiaholmquist** [comment]
That's what's applications on Linux are supposed to do when saving their configuration files. You can pass `-DPORTABLE=ON` to CMake while building to make it use the windows like behavior of putting the file in the same directory.

**Comment by Amnesia1000** [comment]
Great! Thanks for the reply. In previous versions it saved the configuration next to the executable without having to use -DPORTABLE=ON.

**Comment by nadiaholmquist** [comment]
The behavior was changed so it would work properly with the emulator installed to `/usr/bin` or so like it would be for distro packages, and because other emulators generally behave this way.

I added the portable build option because I know some people might prefer the old behavior.

**Comment by Amnesia1000** [comment]
Thank you very much it worked perfectly!
