### ISSUE TITLE
Live Battle Card: Live-On DS - doesn't boot (white screen) 

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Arisotura/melonDS#665]
The game Live Battle Card - Live-On DS doesn't boot and goes to a white screen in both OpenGL and Software.
I think the Korean version of the game (Live-On Card Live-R DS) also have the same problem. It boots on others but not MelonDS.

**Comment by Arisotura** [comment]
it's a regression, it stopped working in version 0.7.3. gonna try to find out why.

**Comment by Arisotura** [comment]
ok I found the commit that breaks it, and it's dd30b417b817024d48b4e14a23a2b19370e8ff97

probably means something in there is implemented wrong

**Comment by Arisotura** [comment]
issue there is that melonDS's GPU-disable is too aggressive and also disables display capture, which should still work even if GPU A is disabled.

display capture is actually separate logic from GPU A, so the code in melonDS should be reorganized to reflect that. in the meantime, this can be fixed quickly.
