### ISSUE TITLE
Spider-Man 3 - Data could not be written error

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Arisotura/melonDS#666]
The Spider-Man 3 DS version, when running on melonDS has a problem after starting the game and selecting a file, in fact it goes with an "Data could not be written. Turn off the power and reinsert the DS card" error. This never happened in other emulators or a real DS. The problem is caused by the game having a different save rom type than other DS games.

**Comment by MojoJojoDojo** [comment]
I think someone in the forums talked about a smiliar issue with Solatorobo so maybe its related.
