### ISSUE TITLE
QDADD (probably QDSUB too) CPU bug with negative Rn

### ISSUE THREAD

**Issue by RockPolish** [Arisotura/melonDS#672]
```
mov r2, #144
mov r3, #-12
qdadd r1, r2, r3
```
Should result in r1 = 120 = 0x00000078, gives r1 = 0x80000090 on MelonDS 0.8.3

**Comment by RSDuck** [comment]
the problem is that the check whether the doubled operand overflows doesn't take negative values into account
https://github.com/Arisotura/melonDS/blob/master/src/ARMInterpreter_ALU.cpp#L1081
