### ISSUE TITLE
Mouse input offset

### ISSUE THREAD

**Issue by Ralayax** [Arisotura/melonDS#677]
Hello devs,

I've been messing around with nintendo DS emulation and it appears that the mouse input is a little offset in melonDS.
By offset I mean that while the pointer is detected the position is consistently off by about the third of the screen's size, which makes it impossible to click on the lower part of the DS screen.

I suspect it is linked with the GUI part of melonDS.

I'm using Ubuntu 20.04 and I have self compiled melonDS.
I am available for some testing if you want.

**Comment by nadiaholmquist** [comment]
Maybe you need to calibrate the touchscreen in your firmware settings, especially if you're using DSi mode.

**Comment by Ralayax** [comment]
And of course this was the issue, thank you good sir.
It might be a good idea to warn new users inside the emulator to avoid further issue reports.

**Comment by nadiaholmquist** [comment]
"good sir" not quite, but I'm glad it worked.

**Comment by Ralayax** [comment]
> "good sir" not quite, but I'm glad it worked.

And here I go assuming genders based on nothing. Have a nice day good person (not taking any risks anymore :) )

**Comment by nadiaholmquist** [comment]
Heh, it happens, no hard feelings :) But it's a good thing to keep in mind for the future.
