### ISSUE TITLE
Transparency effect is incorrect with OpenGL in Ed, Edd n Eddy - Scam of the Century (USA)

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#690]
OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/88749351-75361680-d196-11ea-9d7d-d698f50e6633.PNG)

Software

![Capture](https://user-images.githubusercontent.com/68873449/88749371-7f581500-d196-11ea-8c1d-f4bc97716ae6.PNG)

**Comment by poudink** [comment]
how does software look without screen filtering enabled

**Comment by Tiberius1437** [comment]
Software with OpenGL display off and screen filtering off looks like this. Does that mean the issue is invalid? 

![Capture](https://user-images.githubusercontent.com/68873449/89114059-e25dea80-d4bb-11ea-850b-81fd792c061b.PNG)

**Comment by poudink** [comment]
I think so. it appears the difference between software and opengl was just caused by the screen filtering.
