### ISSUE TITLE
Text in Pac-Man flickers with both OpenGL and software in Namco Museum DS (USA)

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#696]
![Capture](https://user-images.githubusercontent.com/68873449/88971112-ce1cc080-d2f6-11ea-9b0d-9106f1018282.PNG)

**Comment by nadiaholmquist** [comment]
This might be done deliberately by the game's developers if the machine it's emulating has a higher resolution than the DS to try and simulate that higher resolution. The screens on the DS have some ghosting so you can kinda get sesh with something like this, but it will be far more noticeable on an emulator with a more modern display and potentially less even frame pacing.

Please try and verify on real hardware.

**Comment by Arisotura** [comment]
as Nadia said -- the DS screens have a higher response time, so it's not too uncommon to see games use 60FPS flickering to simulate blending.

that being said, I'm going to investigate it quickly.

**Comment by Arisotura** [comment]
yeah, they're using it as a cheap antialiasing for their downscaling.

that being said, I'm considering the addition of some filter to simulate this effect, to make this less brutal in melonDS.

**Comment by Tiberius1437** [comment]
Thanks for checking. I'll look into getting real hardware to test on.
