### ISSUE TITLE
View and touchscreen misaligned on Linux

### ISSUE THREAD

**Issue by unresolvedsymbol** [Arisotura/melonDS#697]
Tried tons of different sizes and touch calibration but touch is always is way off to the bottom right and the view is oddly off to the mid left.
![img](https://i.imgur.com/lfpMTGd.png)

**Comment by Arisotura** [comment]
you need to calibrate the touchscreen from within melonDS.

normally melonDS auto-patches touchscreen calibration data, but this is not supported yet in DSi mode.

**Comment by unresolvedsymbol** [comment]
@Arisotura where?

**Comment by Arisotura** [comment]
you need to reach the system's calibration app, yeah.

**Comment by Arisotura** [comment]
the way the screens are off-center seem to indicate this is some hiDPI related bug in melonDS. are ya using hiDPI?

**Comment by nadiaholmquist** [comment]
I know on Linux if you're using hidpi the screen with OpenGL display enabled will be drawn unscaled, but the touch area will be scaled correctly, causing the touch not to line up with the display.

**Comment by Arisotura** [comment]
can any of you try something real quick?

src/frontend/qt_sdl/main.cpp, line 907, replace

float factor = devicePixelRatioF();

with

float factor = 1;

see if that fixes the issue?

**Comment by abcdjdj** [comment]
> can any of you try something real quick?
> 
> src/frontend/qt_sdl/main.cpp, line 907, replace
> 
> float factor = devicePixelRatioF();
> 
> with
> 
> float factor = 1;
> 
> see if that fixes the issue?

This didn't work for me. Both screens simply shifted down a bit down. Touch area and bottom screen continue to be unaligned.

![Image of unaligned screen](https://i.imgur.com/IGHYaio.png)

**Comment by Arisotura** [comment]
could not reproduce this on Win7

**Comment by unresolvedsymbol** [comment]
> > can any of you try something real quick?
> > src/frontend/qt_sdl/main.cpp, line 907, replace
> > float factor = devicePixelRatioF();
> > with
> > float factor = 1;
> > see if that fixes the issue?
> 
> This didn't work for me. Both screens simply shifted down a bit down. Touch area and bottom screen continue to be unaligned.
> 
> ![Image of unaligned screen](https://camo.githubusercontent.com/3ead30a65c66a6d6600d53921ebf3ccf95b44b11/68747470733a2f2f692e696d6775722e636f6d2f4947485961696f2e706e67)

Same results here. I don't know if he's using hiDPI but I'm not.

> could not reproduce this on Win7

Of course, seems to only be a Linux QT issue.

**Comment by urmum-69** [comment]
I cannot reproduce this either, and I am also using KDE.
![Screenshot_20201027_233556](https://user-images.githubusercontent.com/49879065/97373139-2b4ff000-18ad-11eb-9728-6e4914851785.png)
Not really sure what is up here, this is quite strange.

**Comment by nadiaholmquist** [comment]
To reproduce, run `QT_SCALE_FACTOR=1.5 melonDS`, this issue happens specifically with high-DPI screens.

**Comment by WaluigiWare64** [comment]
Could you test as of latest master?
https://github.com/Arisotura/melonDS/commit/97643586fafd573b02566ddafb92329c40cb44c4 should have fixed it.

**Comment by unresolvedsymbol** [comment]
![Screenshot_2021-02-22-170200957x1038](https://user-images.githubusercontent.com/48220091/108782792-2b62b280-7564-11eb-8446-7eccd64a22eb.png)
Indeed it is fixed, I just remembered I had set `QT_SCALE_FACTOR` to `1.25` because of some QT applications being way too small. Thanks for the patch, @nadiaholmquist
