### ISSUE TITLE
Madagascar Kartz (USA) (En,Fr) has random crashes

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#698]
Tried it three times and it always happens a few seconds after the race begins. Using the software renderer with OpenGL display off and threaded off. I was doing Single player, quick race, 50cc, playing as Gloria and the stage was King Of New York. Sorry I couldn't provide any more info but MelonDS doesn't have any way to view logging as far as I can tell. 

![Capture](https://user-images.githubusercontent.com/68873449/88993115-65e6d280-d328-11ea-8956-fbc7a9f32c9b.PNG)

**Comment by Arisotura** [comment]
crashing melonDS itself?? that's some interesting thing

**Comment by Arisotura** [comment]
well, gave it a quick try, couldn't reproduce it

**Comment by Tiberius1437** [comment]
Could it be because we're using different operating systems? I'm on Windows 7. Is there anything I can do to provide more information?

**Comment by Arisotura** [comment]
Win7 here too. only difference was that I had threaded software enabled, but I doubt it'd make a change.

anyway, see the Actions tab for development builds. but I quickly tested on 0.8.3 too, and nothing there either.

**Comment by Tiberius1437** [comment]
This is gonna sound strange but it only seems to happen with the software renderer. If I start with software it crashes almost immediately. If I start with OpenGL it works fine but crashes after a few seconds if I switch to software. Here's my computer specs.

![Capture](https://user-images.githubusercontent.com/68873449/89078330-8f0a7000-d3c7-11ea-8faf-14405442223d.PNG)

**Comment by RSDuck** [comment]
have you disabled OpenGL display for the software renderer

**Comment by Tiberius1437** [comment]
Tried it with the latest development build and can't get it to crash. Whatever was causing it must have been fixed at some point. Thanks for looking into it.
