### ISSUE TITLE
SDL2 is not found with libsdl2-2.0 <= 2.0.2

### ISSUE THREAD

**Issue by mdeguzis** [Arisotura/melonDS#70]
```
-- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_gtk2u_xrc-3.0;-lwx_gtk2u_html-3.0;-lwx_gtk2u_qa-3.0;-lwx_gtk2u_adv-3.0;-lwx_gtk2u_core-3.0;-lwx_baseu_xml-3.0;-lwx_baseu_net-3.0;-lwx_baseu-3.0 (found version "3.0.2") 
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

I did try setting this manually:

```
        cd build && cmake \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DSDL2_INCLUDE_DIR=/usr/include/SDL2 \
                -DSDL2_LIBRARY=/usr/lib/libSDL2.so \
        ..
```

Does this project require libsdl2 >= 2.0.5? I don't see this in the README or a list of dependencies.

https://packages.debian.org/search?suite=stretch&arch=any&searchon=contents&keywords=sdl2-config.cmake

**Comment by kabili207** [comment]
Yes, it does. I'm on 2.0.4 and I'm getting errors about SDL_PIXELFORMAT_RGBA32 being undefined, which according to the [SDL2 documentation](https://wiki.libsdl.org/SDL_PixelFormatEnum) wasn't added until 2.0.5.

**Comment by mdeguzis** [comment]
Should add this to the requirements or readme  then. I have all the other deps figured out for Debian based systems. 

On June 19, 2017 11:30:44 AM EDT, Andrew Nagle <notifications@github.com> wrote:
>Yes, it does. I'm on 2.0.4 and I'm getting errors about
>SDL_PIXELFORMAT_RGBA32 being undefined, which according to the [SDL2
>documentation](https://wiki.libsdl.org/SDL_PixelFormatEnum) wasn't
>added until 2.0.5.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/StapleButter/melonDS/issues/70#issuecomment-309476371

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RSDuck** [comment]
the wxwidgets days are long gone, so I'm closing this
