### ISSUE TITLE
Japanese DSi firmware errors out when trying to load any application

### ISSUE THREAD

**Issue by rzumer** [Arisotura/melonDS#700]
Already discussed on IRC, but I never made an issue about it.
On No$GBA most software loads, though some stuff crashes after loading.

```
[19:05:26] <Arisotura> anyway I remember it was a problem with wifi versions an d shit
[19:05:31] <Arisotura> but I'd have to disassemble it
```

Log (boot to firmware -> launch application): https://gist.github.com/rzumer/331397eb0eb61b7bec08cb8fae89dfd2

**Comment by Arisotura** [comment]
yup, wifi init isn't completing. I need to figure out which ROM/etc versions it's expecting, though, and how I can determine those automatically.
