### ISSUE TITLE
Local multiplayer no working anymore

### ISSUE THREAD

**Issue by Colmines92** [Arisotura/melonDS#705]
A few weeks ago you announced that there were only about 3 days left for your operation and at the same time you announced that you had made some changes related to the way the WIFI connection works. From that moment I have been aware of each modification that you have made to melonDS, but in no case does the local game work on the same pc. I'm testing with "Dragon Quest IX"

**Comment by Arisotura** [comment]
that's because MAC randomization was removed (as it has potential for breaking in DSi mode). we're trying to find a solution to this.
