### ISSUE TITLE
Touch Screen not responsive

### ISSUE THREAD

**Issue by RinMaru** [Arisotura/melonDS#710]
Any game i try to play on MelonDS 0.8.3 works but the touch screen is unresponsive to mouse input

Windows 10 x64
Intel-i5 402p
AMD RX 480

**Comment by RinMaru** [comment]
![Screenshot 2020-08-26 095446](https://user-images.githubusercontent.com/15071652/91312404-35a51f00-e782-11ea-8a86-62ee02bfee7c.png)
have my dsi nand dumped but touchescreen is unresponsive idk if this is a known issue or not so i figured id throw it out there

**Comment by RSDuck** [comment]
you need to recalibrate your touchscreen for melonDS

**Comment by WaluigiWare64** [comment]
also when it is uncalibrated and the nand is formatted, i usually can't click the "OK" button.
So I had to set it up with No$GBA, and then calibrate the touchscreen with melonDS
