### ISSUE TITLE
Online mode greyed out.

### ISSUE THREAD

**Issue by Aqee1** [Arisotura/melonDS#713]
![image](https://user-images.githubusercontent.com/64429404/90040681-27ee9480-dcc0-11ea-9064-00e32f74ac8c.png)
I want to play MKDS Wiimmfi online but I can't as it won't let me select online, Im using win10 sadly so is there a fix?

**Comment by MojoJojoDojo** [comment]
Use this build and you wont need direct mode enabled anymore : https://github.com/Arisotura/melonDS/suites/1036568030/artifacts/13781427

**Comment by Arisotura** [comment]
this.

also, the 'direct mode' label explicitly states that it requires winpcap/npcap.

**Comment by Aqee1** [comment]
> Use this build and you wont need direct mode enabled/checked anymore : https://github.com/Arisotura/melonDS/suites/1036568030/artifacts/13781427

Thanks for the help! 😄
