### ISSUE TITLE
About cheat codes

### ISSUE THREAD

**Issue by yuya495** [Arisotura/melonDS#714]
Hi Arisotura
I'm using melon DS Git (2020/08/13)

Cheat code is not reflected
Is the input method wrong?

![amarec(20200814-044256)](https://user-images.githubusercontent.com/8580180/90180627-39cc5680-ddea-11ea-8803-531fabd0506a.PNG)

**Comment by yuya495** [comment]
Posted on this site
http://ds-cheat-code.sblo.jp/article/34363592.html
By the way, I have MAX (999999G)
You entered the cheat code for 020C55F0 000F423F

**Comment by autofire372** [comment]
I don't think the cheat stuff is fully functional yet.

**Comment by yuya495** [comment]
We understand. Thank you autofire372
I am looking forward to the PAR cheat code input function being implemented in melonDS early.

**Comment by Arisotura** [comment]
the feature wasn't finished.
