### ISSUE TITLE
Pokemon Black/White: Graphical glitches after loading a savestate

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [Arisotura/melonDS#716]
In Victory Road, I noticed that when I enter in certain caves and load a savestate created outside, a brown flog appears.
It disappears after changing locations.

Both OpenGL and Software renders are affected. Probably the savestate doesn't carry all the info needed by the render to recreate the scene, creating that glitch.

Only tested Victory Road, but surely more places are affected.

1- Create a savestate outside
![bug1](https://user-images.githubusercontent.com/16591467/90342658-48915400-e00a-11ea-93a0-8637d0f03caa.png)
2- Enter in a cave and load the savestate
![bug2](https://user-images.githubusercontent.com/16591467/90342659-49c28100-e00a-11ea-8e67-8aec441fce5c.png)
3- Fog!
![bug3](https://user-images.githubusercontent.com/16591467/90342660-4a5b1780-e00a-11ea-839c-f80892c78139.png)

Save and savestate for the Eur-Spain release.
[Pokemon - Edicion Negra (Spain) EUR save and savestate.zip](https://github.com/Arisotura/melonDS/files/5081276/Pokemon.-.Edicion.Negra.Spain.EUR.save.and.savestate.zip)

**Comment by RSDuck** [comment]
oof, fog seems to be completely omitted from savestates, fortunately that's an easy fix

**Comment by Arisotura** [comment]
same goes for toon tables and shit. oops, my bad.
