### ISSUE TITLE
MelonDS forgets configuracion when you open an associated ROM directly.

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [Arisotura/melonDS#717]
1-Associate .nds files to MelonDS
2-Put a ROM in a new folder
3-Doble click on the ROM.

The emulator will open, but won't boot the rom since it has forgotten the bios files location among the rests of options. It doesn't show an error message, it only stays black.

After setting those paths and options, MelonDS will create a new melonDS.ini in that directory with the new configuration, but that ini file will only affect the roms of that directory, if you have roms in other folders it will happen again.

I have a few suggestions to improve this situation:

A) MelonDS should use by default the preferences in the ini file from the emulator folder. Customizable preferences per game (or game folder) can be useful for games that require a specific presentation, but it should be optional, falling back to the global ini if there isn't a local ini in the folder.
B) MelonDS should show a warning if it fails to boot a ROM due to lack of bios. Currently the emulator show that message if you try to load a game in the **Open Rom...** dialog, but not if you launch a rom file directly (by double-clicking on it or dragging to the melonds.exe)
C) MelonDS could autodetect the bios files in the emulator folder, or looking for a "bios" subfolder.

**Comment by RSDuck** [comment]
the smartest thing is probably search the config file directly next to the executable file, instead of in the current working directory
