### ISSUE TITLE
Configurable bios/firmware location

### ISSUE THREAD

**Issue by kabili207** [Arisotura/melonDS#72]
I've created an ebuild for Gentoo (which will show up [here](http://gpo.zugaina.org/games-emulation/melonds), as soon as the website syncs), and I realized that melonDS has no way to configure where to look for the bios and firmware files. I've added a message that will show up after the user installs the package to warn them of this behavior, but it would be nice to have this be configurable by the user.

On a side note, can you tag your releases in git, or make a [release in github](https://help.github.com/articles/creating-releases/)? It's rather clunky to need to reference everything by commit ID in my ebuilds.

**Comment by hcorion** [comment]
Just FYI, melonDS now loads bios and config from ~/.config/melonds if it can't write to the executable directory.

**Comment by Arisotura** [comment]
this has been addressed in the upcoming 0.9, so, closing this
