### ISSUE TITLE
Rain/Fog effect bugged in Spectrobes

### ISSUE THREAD

**Issue by C4J3** [Arisotura/melonDS#725]
**OpenGL Render Issue**
![GL Melon](https://user-images.githubusercontent.com/13005453/90984353-3d8b7600-e56c-11ea-869c-f600ca1f3af3.png)
**OpenGL Alternate Render Issue**
![Melon GL Alt](https://user-images.githubusercontent.com/13005453/90984354-3ebca300-e56c-11ea-89b1-3b3081823eb9.png)
**Working Software Render**
![Software Melon](https://user-images.githubusercontent.com/13005453/90984355-3fedd000-e56c-11ea-9d30-35f09fc7a2d6.png)

Okay more testing and more accurate information:

- Software render does seem to work, it's only OpenGL that is having problems.
- The fog effect seems to work fine on the top screen at first only having issues on the bottom screen.
- Changing  from OpenGL to Software render and back again seems to relatively consistently cause the effect to appear way too far back.
- A weird shadow of the character appears on the top screen after the rain disappears into the background. Not sure why or if it helps troubleshoot but a detail I noticed (hard to see in screenshot)

Works fine in release 0.8.3
Built from master up to commit b5f9278b3a12dbeca2a3b33e8c6331dd9995d5e0

Issue happening on the first planet. (Just start a game and spam through text boxes then walk out of ship.)
Seems to be an issue with depth (z axis) and how far close the surfaces are from the camera perspective I think, I am no programmer/game designer/engine dev. I have no clue what I'm talking about.

**Comment by C4J3** [comment]
Also not present in 0.8.3 release

**Comment by Arisotura** [comment]
oops. I (accidentally) found out why that broke.
