### ISSUE TITLE
DSi firmware hangs on white screen while booting when "Fast Memory" in the "CPU Emulation" options tab is enabled

### ISSUE THREAD

**Issue by txmutt** [Arisotura/melonDS#727]
The Nintendo splash screen that is normally displayed after booting never appears. The screen remains white, and the FPS remains at 60 indefinitely.
![Screenshot at 2020-08-24 19-03-18](https://user-images.githubusercontent.com/65118388/91105297-b9092800-e63d-11ea-97b1-fc4091fa5d2e.png)

**Comment by nadiaholmquist** [comment]
Can reproduce this here on Linux x86_64 but only sometimes. Sometimes it shows a white screen like here, others an error code from the firmware and other times it boots successfully.

**Comment by WaluigiWare64** [comment]
Never had this issue on Windows 10 64-bit.
could be linux specific.
