### ISSUE TITLE
[Request] Ability to set fast forward on controller button

### ISSUE THREAD

**Issue by guitaristtom** [Arisotura/melonDS#737]
It would be an awesome addition to be able to map the fast foward, and/or other special hotkeys, on to the controller. I have tried both the current release as well a build from master and I wasn't able to.

**Comment by C4J3** [comment]
Config > Input and Hotkeys > General Hotkeys. Then look at the right hand menu (Should say Joystick) and make sure the drop-down at the bottom is set to the right input device (I have found it to always select the correct device but best to check.) I have used this with my Xbox One controller with no issues (both Fast forward and toggle frame limit,)
