### ISSUE TITLE
Pressing F11 causes MelonDS to stop responding, requiring a force close.

### ISSUE THREAD

**Issue by n1ghttrap** [Arisotura/melonDS#745]
Full screen not working as stated in the subject.  Windows 10 1909, Geforce 2060 Super, 1440p 120hz display.  Tried various resolutions and refresh rates to no avail.

**Comment by Arisotura** [comment]
my bad.

we don't actually have a fullscreen key afaik, but the F11 key was mapped to a debug function that makes RAM dumps (and lags like aforementioned when the debug folder doesn't exist). looks like I forgot to disable that for the release.

**Comment by n1ghttrap** [comment]
Ah, I think I googled it at one point and saw F11 key associated.  Sorry
about that.

**Comment by CodingKoopa** [comment]
Can confirm that commenting out [this](https://github.com/Arisotura/melonDS/blob/f8c4bf6db140f590f2cf781e9da67ed208bd47f5/src/frontend/qt_sdl/main.cpp#L1334) line fixes the issue for me.

**Comment by poudink** [comment]
getting the same issue. prevents me from using the full screen key that was added.

**Comment by RSDuck** [comment]
you can also use every other key on the keyboard

**Comment by CodingKoopa** [comment]
Fixed with b00cd8bdee42a2e21b4f83ace34e7f5efa8ed2fc/release [0.9.1](https://github.com/Arisotura/melonDS/releases/tag/0.9.1) :)
