### ISSUE TITLE
Alow using other language (?)

### ISSUE THREAD

**Issue by mariogamer2** [Arisotura/melonDS#75]
For now, ROM language is english,even if the ROM has other language.

Is it possible to add other language support?

**Comment by Nadia-h** [comment]
Change the language setting on your DS and dump the firmware with that language set. This is currently the only way to change in-game language for games that change it based on the language setting of your DS.

**Comment by mariogamer2** [comment]
First I don't have an original ds (only a dsi).

Also DeSmuME has a possibility to boot a game (maybe not all but the game I am running) with a certain language.

**Comment by StapleButter** [comment]
melonDS lets you change the firmware language through the firmware itself, but the saves aren't changed, so... yeah.

Regardless, an interface to do it externally (firmware settings override) would be nice to have.

**Comment by RSDuck** [comment]
It's now possible to override firmware settings from melonDS's GUI.
