### ISSUE TITLE
statically link libQtCore and libslirp in the linux build

### ISSUE THREAD

**Issue by eadmaster** [Arisotura/melonDS#751]
The latest 0.9 linux build is not starting in my Ubuntu Bionic setup due to missing libs:
````
$ ldd melonDS  | grep found

./melonDS: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by ./melonDS)
        libslirp.so.0 => not found
````

Edit: sorry, wrong ubuntu release name

**Comment by PoroCYon** [comment]
Qt cannot typically be linked statically on Linux (unless you compile it from source yourself, afaics). Static linking will also be annoying with OpenGL video, as those can absolutely not be linked in statically.

There's a Flatpak thingy available in the repo, however, it still uses the old dependencies (libpcap and in-tree libui) and thus will break. @nadiaholmquist something you should look at?

Qt 5.12 and libslirp are both available on Ubuntu Focal, is there a reason you can't update to it? I suppose supporting Qt 5.9 (the one on Bionic) is still possible (with linking libslirp statically), but, I don't know how realistic supporting Xenial/Qt 5.5 is.

**Comment by eadmaster** [comment]
As alternative, a flatpak package would be great for me :-)

**Comment by gal20** [comment]
Try this one #769.

**Comment by eadmaster** [comment]
is there  a public build i can try?

**Comment by gal20** [comment]
Currently no. You'll have to build yourself like this:
`flatpak install flathub org.kde.Platfom//5.15 org.kde.Sdk//5.15`
`flatpak-builder --user --install <build-dir> net.kuribo64.melonDS.yml`
This will create two folders, <build-dir> and .flatpak-builder. You can delete them after installation is done.

**Comment by FrostKnight** [comment]
appimage might be a good way to go, but obviously make sure it depends on the qt version within the appimage and not the one that is outside of the container.

**Comment by eadmaster** [comment]
UPDATE: [build added to flathub](https://flathub.org/apps/details/net.kuribo64.melonDS).
