### ISSUE TITLE
"No Disk" error

### ISSUE THREAD

**Issue by mariomadproductions** [Arisotura/melonDS#753]
I get this error when starting MelonDS v0.9. I'm on Windows 8.1. It works fine after dismissing this message, but its still annoying and odd that it appears.
![image](https://user-images.githubusercontent.com/9919020/92933057-a82e2400-f43d-11ea-91cd-dc20a55debe1.png)

**Comment by nathanielcwm** [comment]
Sorry but the only thing I can find about it are some threads about this happening quite frequently on Vista.

IBM in a support page states that the only known work around is to click continue and hope there's less than 8 message boxes, which doesn't appear to match up with your experience,

**Comment by mariomadproductions** [comment]
Since I made this I've encountered it with other programs, so I think its an issue with Windows.
