### ISSUE TITLE
Crash with DSi NAND with unlaunch installed

### ISSUE THREAD

**Issue by mariomadproductions** [Arisotura/melonDS#754]
It works in no$gba. The reason I wanted to try this was so I could boot dsiware without having to install it to the NAND. But maybe melonds will provide a mechanism to do that through the emulator interface in the future.

**Comment by Wiiucoop** [comment]
My DSI's nand also crashes on MelonDS, it has Unlaunch and HiyaCFW installed, hope they allow such nands in the future.

**Comment by nadiaholmquist** [comment]
In the meantime you can simply uninstall unlaunch, then dump your NAND and reinstall it.

**Comment by urmum-69** [comment]
Seems fixed as of https://github.com/Arisotura/melonDS/commit/af0a9e92c414ccf48d7936b51942e1b9b1d127d2
I don't see any reason for the issue to remain open.

**Comment by Arisotura** [comment]
'aight
