### ISSUE TITLE
Rom live patching

### ISSUE THREAD

**Issue by Hejsil** [Arisotura/melonDS#756]
Hi. I've implemented a feature for melonDS that allows for roms to be patched while running. The code can be found here:
https://github.com/TM35-Metronome/melonDS/commit/557f4f83699ee1c1a5431bbb2f0505bc72de3057

How it works is that melonDS reads offsets+data from stdin and patches `NDSCart::CartROM` at that offset with the data. The format read in looks like this:
```
[<offset>]=<hex2>+
[1]=0a0fff
[1220]=0bbb
```

Is this a feature that would be useful to upstream? It is currently just a rough implementation that is linux specific and uses c++ 17 features. I'd be happy to make it more portable and use the older c++ standard if this is a feature melonDS is interested in.

**Comment by RSDuck** [comment]
in it's current state I doubt it's useful for many people, especially since the format is proprietary. There exist other binary patch formats like IPS which are often used to distribute romhacks, though I don't know if that's what you're interested in.

**Comment by Hejsil** [comment]
Let me clarify. What I'm interested in is the ability to patch the rom in ram while the game is running. How this is done exactly and what format is used is less of a concern for me. I can always adapt my tools to work with another system.

My current usecase is the ability to allow twitch chat to modify the Pokémon game I'm playing it.

**Comment by RSDuck** [comment]
I see. That would fit well as a scripting feature (which of course would be far more complicated). See this issue: https://github.com/Arisotura/melonDS/issues/561

**Comment by Hejsil** [comment]
Aah i see. Yes, I think that is the solution to this as well. Thanks for pointing to the issue 👍
