### ISSUE TITLE
Weird data writes in extended palette handling

### ISSUE THREAD

**Issue by PoroCYon** [Arisotura/melonDS#762]
Caught by ASan

The code [here](https://github.com/Arisotura/melonDS/blob/9772201345ab47cc820fd6c08247c133605f8b84/src/GPU2D.cpp#L1224-L1265) and [here](https://github.com/Arisotura/melonDS/blob/9772201345ab47cc820fd6c08247c133605f8b84/src/GPU2D.cpp#L816-L817) writes 32- or 64-bit values every *two* *bytes*, which seems... weird (it might just be the step that needs to be increased? not sure though)

**Comment by Arisotura** [comment]
first one, we worked out that it was fine, because dst is u16*.

second one, I fixed it a while ago.
