### ISSUE TITLE
Add support for original ds savefile

### ISSUE THREAD

**Issue by JakobDev** [Arisotura/melonDS#774]
I use godmode9 on my 3DS to create a ROMs of my cartridges. These roms are working without any problems. But I want to use my saves from the cartridges, too. The cartridges contains .sav file. I copied this .sav file on my Computer, but it doesn't work with melonDS. .nds and .sav has the same name and is in the same folder.

**Comment by RSDuck** [comment]
it could be possible that the savefiles need to be trimmed. Can you tell me whether a savefile you got from your 3ds is bigger than one created by melonDS for that appropriate game?

**Comment by JakobDev** [comment]
The sav file from melonDS has a size of 512KB and the file from the cartridge has a size of 8KB.

**Comment by RSDuck** [comment]
I've added recently a feature for cases like this to import savefiles, but it's not in the latest version. You can download the latest build from our CI: https://github.com/Arisotura/melonDS/runs/1161793133 (in the upper right corner where it says artefacts).

Otherwise you can also compile it yourself or use a hexeditor to manuall trim the size down to 8KB.

**Comment by JakobDev** [comment]
Import savefile does not work.

**Comment by RSDuck** [comment]
can you elaborate?

**Comment by JakobDev** [comment]
It happens nothing. I tried it for example with Pokemon Platin. If I try to import the savestate, it starts just the dialogue with Professor Rowan like there is no save. It shows me no error or somethig else.

**Comment by RSDuck** [comment]
oh sorry I just noticed that these are unusal circumstances, can you name us the game? The dumped savefile can be greater, but normally shouldn't be smaller than the one from melonDS.

**Comment by RSDuck** [comment]
I dumped a Pokemon Platinum save in the past and used it in melonDS, so the error is probably not on the side of melonDS. Your dump is too small.

**Comment by JakobDev** [comment]
I had taken a look on it again and it seems I switched accidentally had looked at a other file for the size. The one from the ROM is 512KB. Sorry for that. Here is a photo what it looks like in godmode9:
![IMG_20200930_182139](https://user-images.githubusercontent.com/15185051/94712897-614f9200-034a-11eb-8362-67c77d5fc51b.jpg)

**Comment by RSDuck** [comment]
I've looked it up, 512kb is the right size. Are you sure melonDS doesn't create a 512kb savefile for Pokemon Platinum?

**Comment by JakobDev** [comment]
There are both 512kb. As I said, I accidentally looked at the wrong file.

**Comment by RSDuck** [comment]
hm yeah, that's weird. Can you give me your save dump?

**Comment by JakobDev** [comment]
Sure. How can I send it to you?

**Comment by RSDuck** [comment]
zip it, then drop it into the text input here on github

**Comment by JakobDev** [comment]
I'm not sure, if the save contains things with copyright, but here it is. It's for a German Rom.
[PokemonPlatinSave.zip](https://github.com/Arisotura/melonDS/files/5307018/PokemonPlatinSve.zip)

**Comment by RSDuck** [comment]
the savefile loads without any problems for me. Is it maybe your rom? Also don't worry about savefiles, they usually don't reach the level of originality to qualify for copyright.

**Comment by JakobDev** [comment]
After rebooting my PC it surprisingly works. I don't know what went wrong. Maybe it was a problem with my USB Stick. Thnaks for your help.
