### ISSUE TITLE
Local Multiplayer Issue 0.9

### ISSUE THREAD

**Issue by Wiiucoop** [Arisotura/melonDS#775]
For some reason when I updated to 0.9 local multiplayer seemed to stop working for me, I don't know if there is any specific setting that fixes it, but for versions 0.8 and prior to that Local Multiplayer (NSMB DS) worked just fine.

Using original DS arm7,9 and firmware.

**Comment by RSDuck** [comment]
did you enable Mac Randomisation in the wifi settings?

**Comment by Wiiucoop** [comment]
I enabled it and it started working again! I really think that MAC Randomization should be turned on by default though.

**Comment by RSDuck** [comment]
that screws with some games which use the MAC address to detect if you're still playing on the same DS. It can also be problematic with savestates. See #443
