### ISSUE TITLE
Encountering a pokemon in pokemon white

### ISSUE THREAD

**Issue by jokalst** [Arisotura/melonDS#782]
I'm currently using melon ds version 0.9, and whenever I head into some grass and find a pokemon, the screen becomes grey and weird. It 's supposed to like zoom into the character and show the pokemon. Sory if I didnt make any sense I'll provide some pictures.
![Capture](https://user-images.githubusercontent.com/72353332/95053356-97956480-06f0-11eb-8645-16c3874459e9.PNG)

**Comment by RSDuck** [comment]
duplicate of #474
