### ISSUE TITLE
How do i make an proprer IMG file for DSi SD?

### ISSUE THREAD

**Issue by PedroxTheBest99** [Arisotura/melonDS#795]
title says it all

**Comment by Arisotura** [comment]
you can use something like Win32DiskImager under Windows

**Comment by v1993** [comment]
What about Linux? I guess it would be a combo of `dd` for image creation and `mkfs.???` for FS, but what exact one?

**Comment by PoroCYon** [comment]
```
truncate -s 128M stuff.img
mkfs.vfat -F 32 -s 64 stuff.img
```

Then mount it as a regular FAT partition. I heard the DSi system software will accept a single volume spanning the entire device, instead of requiring an MBR and partition layout.
