### ISSUE TITLE
request: make libslirp optional

### ISSUE THREAD

**Issue by FrostKnight** [Arisotura/melonDS#797]
I wondered if you can make libslirp optional for those of us who don't use wifi and just want to play offline. 
Let me know if this is possible.  My distro also doesn't have this library.

I assume libslirp is used for wifi purposes only? 
If not let me know.

**Comment by WaluigiWare64** [comment]
What distro are you using?

**Comment by rzumer** [comment]
Adding a CMake build flag and greying out direct mode in the Wifi settings seems reasonable.

**Comment by Arisotura** [comment]
except greying out direct mode is for when pcap isn't available. what do we do if neither pcap nor libslirp are present?

**Comment by rzumer** [comment]
Maybe I mixed up direct and indirect modes.

**Comment by FrostKnight** [comment]
Using Hyperbola, x86_64, they like to avoid as much freedesktop.org stuff as possible. I have pcap though.  Maybe make a different thing to grey out when libslirp isn't present? i dunno.

**Comment by FrostKnight** [comment]
By the way, if you do make a beta with this, I will report what happens when I try it.  Btw, does this build aka 0.9 fallback to drastic's freebios?  Curious...

**Comment by RSDuck** [comment]
no it doesn't

**Comment by nathanielcwm** [comment]
#787 adds the fallback @FrostKnight

**Comment by WaluigiWare64** [comment]
> Using Hyperbola, x86_64, they like to avoid as much freedesktop.org stuff as possible.

It seems `libslirp` is not available on Hyperbola, but you should still be able to build the library.

**Comment by FrostKnight** [comment]
Hmm, okay, I can build the library, today perhaps, but I want to make sure I can continue to use it for the foreseeable future.  
It would help to have that library be optional.  If not, it may be blacklisted later.  I am not sure.   So once a new version is out the  #787 commit will be used? At least I think that's what one of you is trying to say. 

But yeah, how long would it take to make libslirp optional?  If its too long, can you let me know the difficulty level? On a scale of like 1-10 or something?  I might know someone who could fix this issue on Hyperbola's end.  If you are unwilling/can't.  Appreciate you guys giving me the benefit of the doubt and not closing this right away.   
In the future though, dependencies from freedesktop.org will be a problem 2 years down the road for darn sure for me and others using it.  They will be making a BSD version which won't support anything with freedesktop depends.  Although if libslirp is made optional, it will be easy to port to that as well.  
Again, I am willing to test if you want.  just make a patch whenever or if you don't want to... but please let me know.

**Comment by FrostKnight** [comment]
Oh and by the way, not in a huge hurry.  Just let me know if youll consider in the future or not.  :)
I would love to ditch that annoying desmume, its an old stable release after all. ;)

**Comment by WaluigiWare64** [comment]
It would be possible but then two versions of melonDS would have to be released with each new version.  Also direct mode using libpcap may be [retired at some point](http://melonds.kuribo64.net/comments.php?id=119).

However, we could statically link libslirp.

**Comment by FrostKnight** [comment]
Hmmm I talked to someone and he said, that #ifdef would be a work around. Do you know what he means, I am not a programmer for the most part.  
If statisitcly linking libslirp works than sure.  That could work.

**Comment by q3cpma** [comment]
Not available on Gentoo either. Would make a lot of sense for this to be optional.

**Comment by WaluigiWare64** [comment]
@q3cpma it is - https://packages.gentoo.org/packages/net-libs/libslirp

**Comment by q3cpma** [comment]
On Mon, Nov 09, 2020 at 01:18:48PM -0800, WaluigiWare64 wrote:
> @q3cpma it is - https://packages.gentoo.org/packages/net-libs/libslirp
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Arisotura/melonDS/issues/797#issuecomment-724284140

God, sorry, I'm tired.

**Comment by FrostKnight** [comment]
I wonder if OpenBSD has libslirp, it doesn't seem like it. I did a quick search online and it turned up nothing.  
So it seems Hyperbola might not be the only OS with this issue. Unless anyone can find evidence to the contrary.  

Although... I also don't it it in OpenBSD's repos either. Weird... 

By the way, couldn't ifdef statements help in making libslirp optional? 

Regardless,  if not, then the above option you mentioned would be good.

**Comment by FrostKnight** [comment]
Still watching this,  let me know if you have anything for me to test in future. :) 
If it would help though, feel free to wait till Hyperbola 0.4 is out.  Which might be happening by next march or april. For newer packages.

**Comment by WaluigiWare64** [comment]
melonDS now has a flatpak package on flathub, but I assume your distro doesn't have flatpak either.
As I said, currently your only option is to build the library yourself.
I might look into it once I finish the macOS PR.

**Comment by FrostKnight** [comment]
Hmm... yeah no flatpak, no pip and definitely no snaps which are very bad anyways to have.  Well, if nothing else, I wait to see the future. 
For the linux version, appimage would work. When the BSD version comes out... I dunno. But yeah, I am willing to wait on both  for now.  2022+ for beta of the BSD version.  (of Hyperbola)    I guess my point being, there's no big rush for at least part of this. thanks though for the info!

**Comment by FrostKnight** [comment]
Actually, make that 2025, for the BSD version...

But yeah, I am still interested,

**Comment by WaluigiWare64** [comment]
melonDS should work with FreeBSD and NetBSD (use paxctl to disable mprotect restrictions on melonDS first on NetBSD).

Regarding the packages not being available on the BSDs, packages should be able to be made for them (I may try later).

I guess I could maybe add a build flag to disable libslirp.

**Comment by FrostKnight** [comment]
That would help a lot. let me know when it can be tested.

**Comment by FrostKnight** [comment]
Also, a side note, have you tested on OpenBSD?  That's what HyperbolaBSD will be based on although it will happen much later, so no worries if you don't have time now for that particular thing.  development slowed on the bsd version, won't be out till 2024 or something like that and that is the base version. The current Hyperbola though, is of course a different story. 
If I could combine the two posts, I would, github is annoying when used by uxp browsers sadly.

**Comment by FrostKnight** [comment]
I have some good news, Hyperbola GNU/Linux-Libre 0.4 seems to be planning to use libslirp anyways... I don't know if HyperbolaBSD will use it, but at least for now, this is a non issue... it seems. 

So, thank you for being willing, but it may not be an issue at this juncture... :)
