### ISSUE TITLE
Translation | Emulator Localization. 

### ISSUE THREAD

**Issue by andercard0** [Arisotura/melonDS#799]
Hi, 

I'd like to know if you intend to support different languages in the emulator. 
If so, I would do my best to support my native language.

Thank You!

**Comment by WaluigiWare64** [comment]
I was thinking about this yesterday.
QT has [tools to translate applications](https://doc.qt.io/qt-5/qtlinguist-index.html).
I don't see why not this could be implemented!

**Comment by andercard0** [comment]
> 
> 
> I was thinking about this yesterday.
> QT has [tools to translate applications](https://doc.qt.io/qt-5/qtlinguist-index.html).
> I don't see why not this could be implemented!

Perfect, QT is the exact tool i use in translation of Duckstation; (aka Psx emulator) by the way!

Any news let me know. do you have discord channel by any chance?

**Comment by Arisotura** [comment]
not sure how translating shit works with Qt, but I'm wary of this in general -- localizing applications before the end of the dev cycle makes things a pain to work with later. especially if translators don't stick around to maintain their translations.

**Comment by PoroCYon** [comment]
See how Dolphin does this: [linky](https://github.com/dolphin-emu/dolphin/tree/master/Languages/po)

But yeah, doing this right now feels like very bad timing indeed.

**Comment by WaluigiWare64** [comment]
We have an IRC channel, see the README.

**Comment by poudink** [comment]
why was this closed
