### ISSUE TITLE
Help, I'm new to all this... How do I use branches?

### ISSUE THREAD

**Issue by leokatchu** [Arisotura/melonDS#800]
I was running into an issue with Sonic Chronicles and read in one of the posts here that this issue could be solved by using the arm9timinghack branch. I downloaded it, changed the files I had to change for it to work... But now I have no idea how to access the melonDS emulator with this branch. I just have a lot of files and no .exe. What do I have to do here? (Like I said, sorry, I'm a complete newbie to emulation and to Github as a whole)
![screenshot](https://user-images.githubusercontent.com/73904568/98021307-76fe1e80-1e04-11eb-8924-920b2b840a9d.PNG)
(These are all the files I have in the downloaded branch folder.)

**Comment by WaluigiWare64** [comment]
You can follow the instructions in the README.
You need to install MSYS2.

**Comment by leokatchu** [comment]
> You can follow the instructions in the README.
> You need to install MSYS2.

I tried just that and followed every instruction, but I can't seem to get it to work.
About the commands in Step 5 for Windows: Do I have to enter them individually?

**Comment by WaluigiWare64** [comment]
You do have to enter them individually.
Which command is not working?

**Comment by leokatchu** [comment]
> You do have to enter them individually.
> Which command is not working?

Give me a few minutes, I'll try to follow all the steps again

**Comment by RSDuck** [comment]
I can't recommend using the arm9timinghacks branch, it's only a stupid experiment and not meant to be used. We have plans for a better correcter arm9 timing implementation.

**Comment by leokatchu** [comment]
![screenshot2](https://user-images.githubusercontent.com/73904568/98022660-2be50b00-1e06-11eb-8555-741dc7cfad77.PNG)
It showed this error at the step cmake .. -G "MSYS Makefiles"

**Comment by WaluigiWare64** [comment]
Which instructions are you following, the static or the dynamic?

**Comment by leokatchu** [comment]
> Which instructions are you following, the static or the dynamic?

I was following the dynamic instructions (these were the only instructions given in the Readme)

**Comment by leokatchu** [comment]
> I can't recommend using the arm9timinghacks branch, it's only a stupid experiment and not meant to be used. We have plans for a better correcter arm9 timing implementation.

Okay, I didn't know that. I used the arm9timinghacks branch because a post here said it would solve my issue:

https://github.com/Arisotura/melonDS/issues/359
"Hi, I just got around to this and I was able to get past this point by messing the cache timings. Raising
kDataCacheTimingSlow to 28 fixed it, any lower and it would crash."

**Comment by WaluigiWare64** [comment]
Use the README from here -> https://github.com/Arisotura/melonDS/blob/master/README.md

**Comment by leokatchu** [comment]
> Use the README from here -> https://github.com/Arisotura/melonDS/blob/master/README.md

Okay, thank you, I'll try

**Comment by leokatchu** [comment]
> Use the README from here -> https://github.com/Arisotura/melonDS/blob/master/README.md

Neither the static nor the dynamic instructions worked. They both just showed the same error

**Comment by WaluigiWare64** [comment]
Are you sure you have the qt package installed?

**Comment by leokatchu** [comment]
Do you install them by using this command (Step 4 in the Readme)?:
pacman -S git make mingw-w64-x86_64-{cmake,mesa,SDL2,toolchain,qt5,libslirp}
Because I did that

**Comment by leokatchu** [comment]
Oh my god I am simply the dumbest human on this planet. I haven't installed the Qt5 package. I now installed it from an external source and now it's working. Thank you guys so much!

**Comment by RSDuck** [comment]
looks like you haven't build melonDS yet. Did you advance to the `make -j$(nproc --all)` step?

**Comment by leokatchu** [comment]
> 

> looks like you haven't build melonDS yet. Did you advance to the `make -j$(nproc --all)` step?

I did, yes

**Comment by RSDuck** [comment]
there should be a directory somewhere called build, with a file called melonDS in there. Is this correct?

**Comment by leokatchu** [comment]
> there should be a directory somewhere called build, with a file called melonDS in there. Is this correct?

![image](https://user-images.githubusercontent.com/73904568/98028607-a44fca00-1e0e-11eb-927e-6459ce1d3c30.png)
These are all the files in the build directory.

I did see an error message in the Msys console though, at the end of the command make -j$(nproc --all).
![Unbenannt](https://user-images.githubusercontent.com/73904568/98029130-5d160900-1e0f-11eb-8e23-6f4fa82f570b.png)
The red numbers are phrases in German (I am from Germany). Here are the translations:
1: Error 1
2: Still waiting for unfinished proccesses...
3: Error 2

**Comment by RSDuck** [comment]
I made a build for you:
[dist.zip](https://github.com/Arisotura/melonDS/files/5483569/dist.zip)

**Comment by leokatchu** [comment]
> I made a build for you:
> [dist.zip](https://github.com/Arisotura/melonDS/files/5483569/dist.zip)

Thank you so much, It really means a lot to me.
