### ISSUE TITLE
Writes to IPCFIFOCNT always clear the error bit

### ISSUE THREAD

**Issue by fleroviux** [Arisotura/melonDS#801]
https://github.com/Arisotura/melonDS/blob/05e274a1f69b976ae5826e0660f9510c2b3878af/src/NDS.cpp#L3234-L3236
the code conditionally clears the error flag in IPCFIFOCnt7/9 but then unconditionally overwrites its value with `val` anyways.
applies to both NDS7 and NDS9

**Comment by Arisotura** [comment]
I'm late there, but thanks for the heads-up
