### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by CatsLover2006** [Arisotura/melonDS#807]
Need I say more? If need be I can help test builds (I own a MacBook)

**Comment by nadiaholmquist** [comment]
https://github.com/Arisotura/melonDS/pull/771

**Comment by WaluigiWare64** [comment]
https://github.com/Arisotura/melonDS/runs/1367458542
@CatsLover2006 could you test Opengl?

**Comment by CatsLover2006** [comment]
I'm still on Catalina (can't update to Big Sur) so possibly?

**Comment by CatsLover2006** [comment]
I can. I'm installing libslurp as I type this.

**Comment by CatsLover2006** [comment]
I haven't tested DSi functionality, but this works. OpenGL works (in the firmware, at least). One issue: keyboard input doesn't work. Touch works fine, though. I don't know what causes that keyboard issue, but I'll look into using a controller when I can access one a fair bit later.

**Comment by RSDuck** [comment]
> keyboard input doesn't work

did you bind keys?

**Comment by CatsLover2006** [comment]
I tried but it wouldn't bind any keys.

**Comment by RSDuck** [comment]
ah ok

**Comment by CatsLover2006** [comment]
Also one other thing to note: when using OpenGL 3D content doesn't show up. 2D content works fine. That said, the software renderer has no issues handling this and I don't loose frames even though I'm on the second least powered system the latest version of macOS can run on (the least powerful is the same just without hyperthreading).

**Comment by WaluigiWare64** [comment]
Could you post the logs from the Terminal with OpenGL?

**Comment by CatsLover2006** [comment]
I used Mario Kart DS, best example.
In the menus:
`melonDS 0.9
http://melonds.kuribo64.net/
Audio output frequency: 48000 Hz
OpenGL: renderer: Intel HD Graphics 4000 OpenGL Engine
OpenGL: version: 4.1 INTEL-14.7.8
ARM9 BIOS loaded
ARM7 BIOS loaded
Resetting JIT block cache...
done resetting jit mem
done resetting jit mem
MAC: 00:16:56:83:31:F9
FW: WIFI CRC16 = GOOD
FW: AP1 CRC16 = GOOD
FW: AP2 CRC16 = GOOD
FW: AP3 CRC16 = GOOD
FW: USER0 CRC16 = GOOD
FW: USER1 CRC16 = GOOD
Game code: AMCE
ROM CRC32: 49E436D8
ROM entry: 02000000 00000005
!! bad ROM size 25562150 (expected 33554432) rounded to 33554432
Cart ID: 00001FC2
Re-encrypting cart secure area
ARM9: offset=00004000 entry=02000800 RAM=02000000 size=000E7534
ARM7: offset=00141600 entry=02380000 RAM=02380000 size=000289A4
remapping SWRAM
Secure area decryption OK
remapping DTCM 3000000 3004000 ffffffff ffffffff
Game is now booting
Save file: /Users/chancelp/Google Drive/Roms/Mario Kart DS.sav
remapping DTCM ffffffff ffffffff 3000000 3004000
PU: region 0 = 04000033 : enabled, 04000000-08000000
PU: region 1 = 0200002D : enabled, 02000000-02800000
PU: region 2 = 027E0021 : enabled, 027E0000-02800000
PU: region 3 = 08000035 : enabled, 08000000-10000000
PU: region 4 = 027E001B : enabled, 027E0000-027E4000
PU: region 5 = 0100002F : enabled, 01000000-02000000
PU: region 6 = FFFF001D : enabled, FFFF0000-FFFF8000
PU: region 7 = 027FF017 : enabled, 027FF000-02800000
remapping DTCM 27e0000 27e4000 ffffffff ffffffff
PU: region 1 = 0200002B : enabled, 02000000-02400000
PU: region 2 = 023E0021 : enabled, 023E0000-02400000
unknown ARM9 IO write32 04001060 00000000 01FFFE54
unknown ARM9 IO write32 04001064 00000000 01FFFE54
unknown ARM9 IO write32 04001068 00000000 01FFFE54
WIFI OFF`
When selecting a player, the character doesn't appear on the top screen.
Switching back to OpenGL, I get these lines:
`OpenGL: renderer: Intel HD Graphics 4000 OpenGL Engine
OpenGL: version: 4.1 INTEL-14.7.8
QThread::start: Thread termination error (No such process)`
I'm thinking that last line is the culprit.

**Comment by WaluigiWare64** [comment]
Does it crash when you do it?

**Comment by CatsLover2006** [comment]
It doesn't. I don't know why.

**Comment by WaluigiWare64** [comment]
I think it should happen.
https://github.com/Arisotura/melonDS/blob/master/src/GPU3D_Soft.cpp#L74
https://github.com/Arisotura/melonDS/blob/master/src/frontend/qt_sdl/Platform.cpp#L200

**Comment by CatsLover2006** [comment]
It should crash?

**Comment by WaluigiWare64** [comment]
Nope, it's just that that happens when you close melonDS.
I looked into it a bit more and it says that when a thread is terminated (which I'm pretty sure should happen because the SW renderer thread is terminated when switching to OpenGL) that usually happens.

**Comment by CatsLover2006** [comment]
Also one other thing to note: the app crashes when I launch a game with the JIT on. Honestly, with the amount of CPU is most computers now, I think that it's somewhat unnecessary on Macs (I have no performance issues without it on this Mac and again it's the second least powerful that can run the latest version of macOS), leaving it off by default and calling it an "experimental feature" on Mac is probably all that needs to be done.

**Comment by WaluigiWare64** [comment]
Try disabling fastmem, that's a known issue and in my to-do list.

**Comment by CatsLover2006** [comment]
Fastmem is the issue. Also that QThread error is causing _something_, it's pretty clear to me now.

**Comment by WaluigiWare64** [comment]
I get the QThread error on Linux whilst switching from SW to OpenGL, and disabling Use seperate thread for the SW renderer.
When do you get the error when not doing any of those things?

**Comment by CatsLover2006** [comment]
I get the error every now and again when _starting_ the OpenGL thread.
Also, I think I found the culprit after I tried building from source code. When I build from source, `cmake` worked fine but then when I ran `make`, I got this error message: `/Users/chancelp/melonDS/src/OpenGLSupport.h:26:10: fatal error: 'GL/gl.h' file
      not found`
This might be the issue.

**Comment by WaluigiWare64** [comment]
Don't build from master.
Instead. build from my PR - https://github.com/WaluigiWare64/melonDS/tree/platform/macos-support
Also follow the instructions in the README - https://github.com/WaluigiWare64/melonDS/blob/platform/macos-support/README.md

**Comment by CatsLover2006** [comment]
I still get the same `GL/gl.h` missing error

**Comment by WaluigiWare64** [comment]
Do you have Homebrew installed, as in the README.
Installing Homebrew automatically installs the XCode Command Line Tools, which should have the OpenGL headers.

**Comment by CatsLover2006** [comment]
I do have Homebrew installed. I'm on macOS Catalina though, so OpenGL is deprecated.

**Comment by WaluigiWare64** [comment]
I meant that you have to clone my fork's `platform/macos-support` branch and build with that.

**Comment by CatsLover2006** [comment]
Compiled from source, still nothing. Random question relating to GPU support: would Metal usage be possible or no?

**Comment by WaluigiWare64** [comment]
Maybe, if someone wrote a Metal renderer.
Also what is the command you used to clone?
As is builds fine on my VM and on the Github Actions CI.

**Comment by CatsLover2006** [comment]
I just took the latest code, downloaded as a zip, and overwrote files. It _built_ just fine, but still the same OpenGL error. Sorry for the confusion.

**Comment by WaluigiWare64** [comment]
Try doing it to a new folder.

**Comment by CatsLover2006** [comment]
Still the OpenGL glitch. IDK what's going on at this point.

**Comment by RSDuck** [comment]
> Random question relating to GPU support: would Metal support be possible or no?

if you mean Vulkan support and MoltenVK maybe some day

**Comment by CatsLover2006** [comment]
Metal is for Apple devices (OpenGL is deprecated)

**Comment by poudink** [comment]
MelonDS appears to have been trying to keep everything cross platform, so a platform-specific Metal renderer would be an odd addition. Vulkan sounds much more likely to me, and I think it'd be a better option as well. Though, even that would be quite a long term inclusion since the OpenGL renderer still has its fair share of issues that need to be addressed first.

**Comment by CatsLover2006** [comment]
I’m pretty sure that OpenGL is already gone in iOS.

**Comment by CatsLover2006** [comment]
I’m pretty sure that OpenGL is already gone in iOS.

**Comment by RSDuck** [comment]
https://apple.stackexchange.com/questions/379326/is-opengl-deprecated-or-removed-in-macos-catalina-10-15

allegedly it's still there on Catalina

**Comment by WaluigiWare64** [comment]
ANGLE seems to be working on Metal support - https://github.com/google/angle

**Comment by WaluigiWare64** [comment]
@CatsLover2006 can you try this?
The QThread error should be gone.

[melonDS.zip](https://github.com/Arisotura/melonDS/files/5519442/melonDS.zip)

**Comment by WaluigiWare64** [comment]
@CatsLover2006 could you send a screenshot of Mario Kart DS (since you seem to already have it) in the race?

**Comment by CatsLover2006** [comment]
Here's what Mario Kart DS looks like on the character select.
![Screen Shot 2020-11-16 at 11 52 39 AM](https://user-images.githubusercontent.com/28163018/99295175-5077b480-2802-11eb-8849-169e05916aac.png)
And here's what it looks like in-race.
![Screen Shot 2020-11-16 at 11 53 44 AM](https://user-images.githubusercontent.com/28163018/99295262-70a77380-2802-11eb-8bc8-88535c07ac65.png)

**Comment by CatsLover2006** [comment]
Debugging idea: wireframe view?

**Comment by CatsLover2006** [comment]
Also I will report that controller inputs work.

**Comment by CatsLover2006** [comment]
One other thing: connecting to Wiimmfi results in error code 23917. Not sure if this is related.

**Comment by CatsLover2006** [comment]
Random question: 32 bit components in use? If so that's the big issue.

**Comment by WaluigiWare64** [comment]
@CatsLover2006 thanks for the pictures. It's certainly odd that no 3D is drawn at all.
Also Wiimmfi says 23917 is "Wiimmfi access denied".
Could you delete the connection and create it again, this time without changing the settings, and then try to get online?
If it tells you that the Nintendo WFC has shut down, that means it's connecting to the internet.

**Comment by CatsLover2006** [comment]
I know. I think this is an issue with Wiimmfi though, I'm getting this issue with all but my actual 3DS and Wii (including my Wii U's vWii).

**Comment by WaluigiWare64** [comment]
Thanks.
At least wifi is working :P

**Comment by WaluigiWare64** [comment]
@CatsLover2006 could you test OpenGL with the latest artifact?

**Comment by CatsLover2006** [comment]
OpenGL with latest code is still not working.

**Comment by WaluigiWare64** [comment]
Did you clone my branch or did you download from artifacts?

**Comment by CatsLover2006** [comment]
Where are they? I can't find them.

**Comment by WaluigiWare64** [comment]
https://github.com/Arisotura/melonDS/pull/771/checks?check_run_id=1426173750

**Comment by CatsLover2006** [comment]
It's there, but some (by that I mean a fair lot) of polygons are flickering.

**Comment by RSDuck** [comment]
that's great, we know this issue

**Comment by WaluigiWare64** [comment]
At least we know the issue this time.
So it's not something just with macOS.

**Comment by CatsLover2006** [comment]
http://clpblogimages.ueuo.com/upload/Screen%20Recording%202020-11-20%20at%2010.22.26%20AM1.mov
That's a link to the video file.

**Comment by CatsLover2006** [comment]
One other glitch: For some reason the controller you want to use needs to be connected to the Mac before actually launching the app?

**Comment by CatsLover2006** [comment]
EDIT: The above glitch also explains the "no keyboard" glitch (it would need to be connected constantly; when you click away, you'd be basically unplugging it)

**Comment by WaluigiWare64** [comment]
No I think the keyboard thing is to do with the window focus on the Input and Hotkeys window.
If I manually input the keys into the config file, the keys show up in the menu and they work.

**Comment by CatsLover2006** [comment]
Where's the config file stored?

**Comment by WaluigiWare64** [comment]
I think it's somewhere in [home dir]/Library/Preferences/melonDS.
Also you have to enter a number, not a key.
I think you can use https://wiki.libsdl.org/SDLScancodeLookup
but I'm not sure.

**Comment by WaluigiWare64** [comment]
Could you now test binding keys with the latest artifact @CatsLover2006 ?
https://github.com/Arisotura/melonDS/pull/771/checks?check_run_id=1436018083

**Comment by CatsLover2006** [comment]
Keypresses now work.

**Comment by CatsLover2006** [comment]
Not sure if this is related but the thought of Q and W being pressed together melonDS just can't comprehend.

**Comment by CatsLover2006** [comment]
Blooper ink on OpenGL in MKDS is an outline.

**Comment by WaluigiWare64** [comment]
@CatsLover2006 the OpenGL issues are probably related to what RSDuck said about the wbuffering issues.
Could you test Direct Mode with the latest artifact?
https://github.com/Arisotura/melonDS/pull/771/checks?check_run_id=1460814267

**Comment by WaluigiWare64** [comment]
@CatsLover2006 could you test the new app bundle from the latest artifact?
https://github.com/Arisotura/melonDS/pull/771/checks?check_run_id=1467761278

**Comment by CatsLover2006** [comment]
I'm sorry, but right now my mac is in a rather... unusable state. I can't charge it. I'll test when I manage to charge it a bit.

**Comment by CatsLover2006** [comment]
Bundle works (complains about malware, but that's relatively easy to fix)

**Comment by CatsLover2006** [comment]
I don't know where to find direct mode...

**Comment by PoroCYon** [comment]
It's in the "Wifi settings" tab.

**Comment by poudink** [comment]
I don't know about blooper ink in OpenGL being a wbuffer issue. It seems to show up fine on Windows.

**Comment by RSDuck** [comment]
the wbuffer issue is how individual polygons flicker, that happens under linux for me as well.

**Comment by poudink** [comment]
So the blooper ink issue is something else, then?

**Comment by MelonMonke** [comment]
Just tested the new app bundle, keep up the great work! The last time I used melonDS on my Mac was when I managed to compile it a couple of years ago with the libui interface. Issues that I have encountered include:
- When using the OpenGL renderer or display, the display does not scale correctly like the software renderer's display (Tested with firmware and Animal Crossing Wild World).
- When playing Animal Crossing Wild World, polygons flickering occurs at the ocean, windows and pitfalls seeds.
- When booting firmware it only displays a white screen.

**Comment by WaluigiWare64** [comment]
@MelonMonke what GPU do you have? I remember I had this issue on my Intel iGPU. 
Also are you sure that your dumps are fine? Booting firmware works fine for me.

**Comment by MelonMonke** [comment]
I am using integrated Intel Iris Plus Graphics and there was an issue with my dump, I can boot the firmware without any issues now. Thanks

**Comment by WaluigiWare64** [comment]
Could you show me the logs when you open it from the Terminal @MelonMonke ?

**Comment by RSDuck** [comment]
the scaling problems are likely related to stupid hidpi stuff

**Comment by WaluigiWare64** [comment]
Ah, yes.
Related to #697

**Comment by MelonMonke** [comment]
Yeah I initially thought it was related to the fact I was using a retina display l, but I wasn't sure. The SDL renderer scales property also.

**Comment by CatsLover2006** [comment]
Here’s a little piece of information that might be helpful fixing that: Retina display = 2x dpi scaling.
