### ISSUE TITLE
Save threading

### ISSUE THREAD

**Issue by ichee** [Arisotura/melonDS#810]
Whenever a game is saved, a brief, but noticeable, stutter occurs.

The save process should instead be handled in a separate thread, or possibly asynchronously, to avoid such issue.

Disk is a SSD NVME.

Windows 10

**Comment by RSDuck** [comment]
duplicate of #477

**Comment by ichee** [comment]
Seems to be fixed in 62e3f41.

Tested game was Castlevania Dawn of Sorrow.
