### ISSUE TITLE
[OpenGL] Projector Effect Doesn't Work in Ghost Trick: Phantom Detective

### ISSUE THREAD

**Issue by poudink** [Arisotura/melonDS#831]
At the very beginning of the very first cutscene in Ghost Trick, there are "projector lights" that gradually appear, revealing more and more of the scene. This effect does not work in OpenGL, and the entire scene stays obscured.
Software Renderer:
![Software Renderer](https://user-images.githubusercontent.com/29778535/100446853-87a95980-307d-11eb-9a23-c44325876f8a.png)
OpenGL Renderer:
![OpenGL Renderer](https://user-images.githubusercontent.com/29778535/100446864-8d9f3a80-307d-11eb-858e-4040a08bb15e.png)

**Comment by Arisotura** [comment]
I think I have an idea why this is happening

basically: the game renders the spotlight volume thing as a series of polygons with alpha=1, then the black background with alpha=31, but with some A5I3 texture to force it to be treated as a translucent polygon, this way it's rendered after the spotlight volume, allowing the latter to punch through it. the shit behind the spotlight is 2D layers/sprites.

however, the current GL renderer is trying to render all opaque _pixels_ first, including those of polygons considered translucent, which breaks the intended rendering order.
