### ISSUE TITLE
Time suddenly not working? 

### ISSUE THREAD

**Issue by crossmr** [Arisotura/melonDS#832]
Just ran into this issue in pokemon platinum. I got a massage for a pokemon several times, once a day. About 4 days ago, I went the next day to get the massage and it said "come back tomorrow". I thought maybe I'd done it after midnight and didn't think much of it. I haven't opened the game in 3 days and just attempted to do it again and it's yet again telling me to come back tomorrow. There's no way I'd already gotten the massage for the pokemon today. 

is there anyway to view the time the emulator has to make sure it's reading the time properly or to figure out why it doesn't seem to be advancing the date. I haven't done any clock manipulation on my machine. This is the latest version on windows 10. 

I should mention that the clock app in the pokemon game seems to be reporting the correct time, but something seems wrong with the date it has.

**Comment by poudink** [comment]
disable mac randomization

**Comment by crossmr** [comment]
ah. I had to enable that to do emulator to emulator trade. What's the reasoning behind mac randomization causing issues with the clock?

**Comment by RSDuck** [comment]
it's used to detect if you're still playing on the same DS so you can't just switch between two systems with a shifted clock to quickly activate time based events.
