### ISSUE TITLE
[Audio] Persistent Audio Stuttering

### ISSUE THREAD

**Issue by vidaliATWIT** [Arisotura/melonDS#834]
I've been having consistent regular audio stuttering at all times regardless of the game. I'm currently running melonDS_0.9.

**Comment by RSDuck** [comment]
do the games run below fullspeed (60 FPS)?

**Comment by vidaliATWIT** [comment]
Thanks for getting back to me! Games are running at 59fps consistently with the frame limiter on. With it off they shoot of into the hundreds.

**Comment by RSDuck** [comment]
maybe it's the old frame limiter. Can you try a build from our [CI](https://github.com/Arisotura/melonDS/runs/1475770055) and tell me if it's better?

**Comment by vidaliATWIT** [comment]
Absolutely fixed. Many thanks!
