### ISSUE TITLE
Chrono Trigger segfaults after intro sequence

### ISSUE THREAD

**Issue by andr2535** [Arisotura/melonDS#838]
From what I can see no settings in the emulator affects this.
I tested on Linux Mint 20 with gcc version 9.3.0.

I found the first commit where this issue occurs, but I'm not sure it's any help:
6e8bac39091d0321f43a3e7574d3359255996e9f

**Comment by RSDuck** [comment]
thank you, that commit likely introduced regressions so the faster they get reported the faster we can get rid of them

**Comment by andr2535** [comment]
That was really fast :D
Thank you very much for this fix.
