### ISSUE TITLE
The third flying level in Power Rangers - Super Legends (USA) (En,Fr,De,Es,It) doesn't show any graphics

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#840]
Tried with both OpenGL and Software. 

![Capture](https://user-images.githubusercontent.com/68873449/101495057-273ee400-39bc-11eb-9586-6eaf84494f40.PNG)

**Comment by RSDuck** [comment]
do you use 0.9 or do you build from latest source?

**Comment by Tiberius1437** [comment]
Very latest version.

**Comment by RSDuck** [comment]
this could be a regression because I recently made some changes to GPU2D. Can you give me a savefile?

**Comment by Tiberius1437** [comment]
[Power Rangers - Super Legends (USA) (En,Fr,De,Es,It).zip](https://github.com/Arisotura/melonDS/files/5659829/Power.Rangers.-.Super.Legends.USA.En.Fr.De.Es.It.zip)

**Comment by RSDuck** [comment]
how can I enter the level?

**Comment by Tiberius1437** [comment]
Go here. 

![Capture](https://user-images.githubusercontent.com/68873449/101499254-2bb9cb80-39c1-11eb-89d0-4a08c88a62b7.PNG)

Then choose mission 3 and play through it until you get to the flying section. It's after you've collected three pieces of the compass. 

![Capture2](https://user-images.githubusercontent.com/68873449/101499307-38d6ba80-39c1-11eb-8d0c-bf09b380f5d5.PNG)

**Comment by RSDuck** [comment]
thank you for the instructions, it seems to be not a regression.

**Comment by RSDuck** [comment]
no$gba seems to suffer from the same problem. Polygons seem to be submitted and seem to be rendered as well, well except that nothing appears…

**Comment by RSDuck** [comment]
oof I made some progress. What made everything more tricky is the fact that it's too issues combined. First there's one with scrolling of the 3D layer. I haven't looked much into this one yet. The other one is the fact that this game has the light color configured as black (0, 0, 0).

**Comment by RSDuck** [comment]
I figured out why the light color is zero. It's not included in savestates, uff this is so stupid…

**Comment by RSDuck** [comment]
so the game just forgets to reset the 3D layer scroll back from 256 (which it is before the 3D level starts). The 3D layer scrolling in melonDS seems to be right, I just double checked it on a real DS.

**Comment by Arisotura** [comment]
confirmed to be working correctly on hardware (so, not a bad ROM dump or anything).

my hardware tests didn't reveal anything about this for now. I fear this is some stupid timing issue (although tweaking melonDS's timing constants didn't change shit).

**Comment by MojoJojoDojo** [comment]
Is this what they call "open bus" behavior?

**Comment by RSDuck** [comment]
open bus is something pretty specific which fortunately on a DS can only happen for the cartridge slot. Maybe it's related and the game relies on this accidentally, though then the game shouldn't work on a DSi either.

**Comment by Arisotura** [comment]
I tested on a DSLite fwiw, and it works fine.

I've been banging my head at this for a while now and have no idea what that could be. I think we have a candidate for a holy-grail bug.

**Comment by RSDuck** [comment]
I just tested it on a 3DS, works fine here, so no open bus

**Comment by Tiberius1437** [comment]
Have you guys gotten to the broken part with a verified good dump of the game and a new save file and not just the one I provided? Just to be sure I didn't fuck up that particular save or ROM somehow.

**Comment by RSDuck** [comment]
we both reproduced this bug with a rom which works on real hw

**Comment by Arisotura** [comment]
technical explanation of this:

after much fumbling, we figured out that 3D layer scroll is implemented in the 3D rendering engine. BG0HOFS is forwarded to an internal register in the 3D rendering engine, but only when the rendering engine is enabled (via POWCNT) -- otherwise the internal register will retain its previous value when BG0HOFS is written to.
