### ISSUE TITLE
[Regression] - Pokemon Black & White 2, Flickering

### ISSUE THREAD

**Issue by Brankale** [Arisotura/melonDS#845]
This [commit](https://github.com/Arisotura/melonDS/commit/aac843c7deddae52ce46275f8c828bcac42b4693), which is currently the latest one, causes flickering to the following objects in Pokemon White & Black 2

![Screenshot (194)](https://user-images.githubusercontent.com/45881310/101909131-596b6400-3bbd-11eb-9c67-e58780ab1ace.png)

this is how it should look like
![Screenshot (198)](https://user-images.githubusercontent.com/45881310/101909347-a64f3a80-3bbd-11eb-8c88-c9f567c1dc64.png)

and also this one

![Screenshot (199)](https://user-images.githubusercontent.com/45881310/101909050-448ed080-3bbd-11eb-8144-e67b8021c664.png)

I can't provide a video so i can't show the flickering effect.

Here's the game save if it can be useful.
[save.zip](https://github.com/Arisotura/melonDS/files/5679398/save.zip)

**Comment by Arisotura** [comment]
looks like zfighting shenanigans. that, or I broke something in that change I made. blarg

**Comment by autofire372** [comment]
I would just like to note that this affects Pokémon Platinum (and likely all DS Pokémon games) as well, with jumpable ledges flickering in and out of visibility.

**Comment by muizzsiddique** [comment]
This is an issue in 0.9.1, but was perfectly fine in 0.9.0.

These two clips are in the same place (forest to the left of Gym 2) but I saved and exited the game inbetween.
https://streamable.com/aa71z5
https://streamable.com/3kvx5p

**Comment by RSDuck** [comment]
> This is an issue in 0.9.1, but was perfectly fine in 0.9.0. Oh, and this is Pokemon Black.

that looks like https://github.com/Arisotura/melonDS/issues/907

**Comment by RSDuck** [comment]
@muizzsiddique can you try the latest revision and tell us if it still happens?

**Comment by Brankale** [comment]
In Pokemon Black/White 2 flickering is still present. I don't know about Pokemon Black but i think it's present there too.

**Comment by muizzsiddique** [comment]
I managed to built according to the instructions on the README, and the issue still persists. Also, there's a related(?) texture flickering issue that is both in 0.9.1 and the build I just compiled, I also left it in the video:
https://youtu.be/UNJpgUSCOrM?t=152 Forest issue @ 2:32

**Comment by RSDuck** [comment]
oh no. Can you upload a save file for further investigations?

**Comment by muizzsiddique** [comment]
I dumped my Pokemon Black cartridge myself using my 3DS, so maybe there could be an issue there? Make sure to use an unmodified ROM.
[Pokemon Black Save.zip](https://github.com/Arisotura/melonDS/files/5852550/Pokemon.Black.Save.zip)

**Comment by Arisotura** [comment]
I think that has to do with equal depth-test, or similar z-fighting shenanigans.

**Comment by poudink** [comment]
if it's equal depth then why wasn't the issue in 0.9.0?

**Comment by Arisotura** [comment]
polygon ordering has been revised, which might reveal some issues. we also added a hack for equal depth test, but it's nowhere near as good as we need it to be.

**Comment by RSDuck** [comment]
@muizzsiddique https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344 fixed your issue

**Comment by Brankale** [comment]
yes, now it's fixed

**Comment by RSDuck** [comment]
I can't reproduce your issue @Brankale either. Apparently they were the same issue after all.
