### ISSUE TITLE
Bloo's face is mangled in Foster's Home for Imaginary Friends - Imagination Invaders (USA) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#850]
OpenGL

![Capture](https://user-images.githubusercontent.com/68873449/102004212-c2401100-3d62-11eb-948d-1b4dd8d5e7c0.PNG)

Software

![Capture 2PNG](https://user-images.githubusercontent.com/68873449/102004216-c835f200-3d62-11eb-9109-8523c503c5f8.PNG)

**Comment by poudink** [comment]
Couldn't reproduce with commit b9a56bc or release 0.9.0.
