### ISSUE TITLE
Graphics are broken during the cutscene where you fall down a hole partway through the first level in Galactic Taz Ball (USA) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#851]
OpenGL

![Capture](https://user-images.githubusercontent.com/68873449/102020354-dd476b00-3dcc-11eb-85c7-2fad3c3333fb.PNG)

Software

![Capture2](https://user-images.githubusercontent.com/68873449/102020361-e7696980-3dcc-11eb-8489-2cd740482605.PNG)

**Comment by RSDuck** [comment]
looks like bad old z fighting

**Comment by poudink** [comment]
Couldn't reproduce with commit https://github.com/Arisotura/melonDS/commit/b9a56bc4e47bbb315f88ba5eaa57ce2b3efece73, release 0.9.1 or release 0.9.0.
