### ISSUE TITLE
Jelly Belly - Ballistic Beans! (USA) (En,Fr,Es) softlocks after creating a new profile

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#852]
The game briefly tries to save and then shows this error message. It works fine in Desmume so I don't think it's a problem with the ROM.

![Capture](https://user-images.githubusercontent.com/68873449/102046412-67282000-3e2f-11eb-9d72-584b59f70924.PNG)

**Comment by Arisotura** [comment]
prolly just a missing/bad savemem entry

have you tried providing it a known-good save file?

**Comment by Tiberius1437** [comment]
Dunno where I'd get one. The only DS emulator's I know of are this one and Desmume and I don't think the latter creates save files that can be shared?

**Comment by Arisotura** [comment]
you can try 'export save memory' in DeSmuME. there's an alternate method if you're comfortable with using a hex editor, too.

**Comment by Tiberius1437** [comment]
Yeah it works if I have a Desmume save in the same folder as the ROM.

**Comment by Arisotura** [comment]
what's the exact size of the savefile you used btw?

**Comment by Tiberius1437** [comment]
8.00 KB

**Comment by Arisotura** [comment]
'aight, thanks

**Comment by Tiberius1437** [comment]
Ayy that was quick, thanks. Game's dogshit by the way. Wouldn't recommend playing it.

**Comment by Arisotura** [comment]
hahahahh, always good to have an accurate emulator tho :P
