### ISSUE TITLE
Taking damage in Winx Club - Saving Alfea (USA) (En,Fr,Es) permanently corrupts the score graphics when using OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#854]
This is the strangest bug I've found yet and I love an explanation. Even if you quit the level and re-enter it the graphics are still screwed up. 

OpenGL

![Capture4](https://user-images.githubusercontent.com/68873449/102084127-cb1b0a80-3e68-11eb-9dd0-40bc55ff90c5.PNG)

Software

![Capture3](https://user-images.githubusercontent.com/68873449/102084144-d4a47280-3e68-11eb-9d1b-16450d2b7dff.PNG)

**Comment by RSDuck** [comment]
probably something display capture related

**Comment by Arisotura** [comment]
I was thinking more like texture alignment shenanigans, I don't see why that would use display capture, but then again, with DS games, you never know :P

**Comment by poudink** [comment]
Fixed by https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344.
