### ISSUE TITLE
[Feature Request] Swap top and bottom screen 

### ISSUE THREAD

**Issue by anon342** [Arisotura/melonDS#855]
what your able to do now: 
![image](https://user-images.githubusercontent.com/76022027/102159169-04478080-3e51-11eb-8bc5-dd64945f01f6.png)

what i want to be able to do: 
![image](https://user-images.githubusercontent.com/76022027/102159179-0b6e8e80-3e51-11eb-9b5c-cea7707d46ce.png)

My second monitor is to the right so i want to have the main screen on the right, ability to shrink one screen for a bigger other screen in horizontal mode would be a bonus.

**Comment by poudink** [comment]
whoa, you're right, you can't swap the screens. never realized that was missing. would be a nice feature to have, for sure.
