### ISSUE TITLE
Parts of the screen don't render in Drama Queens (USA) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#856]
OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/102589021-7f1adf00-4162-11eb-98c3-d257cb5ae8a1.PNG)

Software

![Capture](https://user-images.githubusercontent.com/68873449/102589038-8641ed00-4162-11eb-8c39-c82740e853b3.PNG)

**Comment by Arisotura** [comment]
looks like good ol' equal-depth-test shenanigans

**Comment by poudink** [comment]
fixed by https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344
