### ISSUE TITLE
How do you make melonDS full screen?

### ISSUE THREAD

**Issue by MalwareLord** [Arisotura/melonDS#857]
Hi
I searched some and looks like pressing F11 will make it full screen? but it crashes for me whenever I press F11!
is there really no built-in setting for this future in melonDS or am I missing something?
it's just such a mood-killer to play Resident Evil: Deadly Silence or any horror game with these extra parts of windows on top and bottom of the game!

**Comment by RSDuck** [comment]
you need to use a build from latest source and go into the hotkeys to bind toggle fullscreen to some key (which isn't F11 because it is already taken by a none remappable debug functionality).

**Comment by MalwareLord** [comment]
> you need to use a build from latest source and go into the hotkeys to bind toggle fullscreen to some key (which isn't F11 because it is already taken by a none remappable debug functionality).

tnx for the reply!
Hmm is there a guide on how to do it and where to find this build and the latest source? I really have no knowledge of this kind of stuff so I'm 100% clueless right now on what are you trying to tell me! : )

**Comment by RSDuck** [comment]
you can download it from our [CI](https://github.com/Arisotura/melonDS/runs/1551538167)(under "Artefacts")

**Comment by MalwareLord** [comment]
> you can download it from our [CI](https://github.com/Arisotura/melonDS/runs/1551538167)(under "Artefacts")

wow worked like a charm! Thanks, man! : )
