### ISSUE TITLE
Level select screen doesn't render properly in Kamen Rider - Dragon Knight (USA) (En,Fr,Es) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#858]
OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/102615691-6f16f580-418a-11eb-864f-91fe90757cc8.PNG)

Software

![Capture](https://user-images.githubusercontent.com/68873449/102615701-76d69a00-418a-11eb-9090-8fcdbdfc6b14.PNG)

**Comment by Tiberius1437** [comment]
I don't mean to be obnoxious with all these OpenGL issue reports but there seems to be a lot of them.

**Comment by RSDuck** [comment]
First of all testing throughly is always appreciated!

Regarding OpenGL issues, most of them stem from the same few causes we are aware of (equal depth test not working, texture/polygon alignment, display capture doesn't preserve higher resolutions), though we never know what other issues there could be.

**Comment by poudink** [comment]
fixed by https://github.com/Arisotura/melonDS/commit/8a068c22947163d98b78645d5604efb20f6a3241
