### ISSUE TITLE
Giselle's face is transparent when standing in sunlight in Enchanted (USA) (En,Fr,De,Es,It,Nl) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#866]
OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/102704475-e904c700-42cf-11eb-868c-8e30c559c37c.PNG)

Software

![Capture](https://user-images.githubusercontent.com/68873449/102704478-ef933e80-42cf-11eb-8e4b-4a30d6b650df.PNG)

**Comment by poudink** [comment]
Fixed by https://github.com/Arisotura/melonDS/commit/8a068c22947163d98b78645d5604efb20f6a3241.
