### ISSUE TITLE
Large translucent square covers most of the track in Ferrari Challenge - Trofeo Pirelli (USA) (En,Fr) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#870]
![Capture](https://user-images.githubusercontent.com/68873449/102714544-5b52c700-4323-11eb-9749-1a40a40927c3.PNG)

**Comment by poudink** [comment]
fixed in https://github.com/Arisotura/melonDS/commit/8a068c22947163d98b78645d5604efb20f6a3241
