### ISSUE TITLE
The pot plant breaks if you look directly at it in Garfield - A Tail of Two Kitties (USA) (En,Fr,Es) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#874]
When looking at it from the side

![Capture](https://user-images.githubusercontent.com/68873449/102748544-791d3c00-43b6-11eb-864e-71edeaacaa20.PNG)

When looking directly at it

![Capture2](https://user-images.githubusercontent.com/68873449/102748566-833f3a80-43b6-11eb-930a-4900e522c8a3.PNG)

**Comment by poudink** [comment]
fixed in https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344
