### ISSUE TITLE
[Feature Request] Pause when inactive

### ISSUE THREAD

**Issue by LOuroboros** [Arisotura/melonDS#875]
I haven't seen this feature myself in the different settings of melonDS' GUI, so I decided to open this issue suggesting its inclusion at some point down the road.

This is a feature many other emulators such as VBA, mGBA, Desmume and Citra have. It would make the emulator pause if it's not on focus and make it resume its activity once it's put back on focus.

**Comment by WaluigiWare64** [comment]
@LOuroboros I've added the feature - let me know what you think!

**Comment by LOuroboros** [comment]
> 
> 
> @LOuroboros I've added the feature - let me know what you think!

I gave it a quick check and it seems to be working quite nicely! Thank you!
