### ISSUE TITLE
Fire poles don't render correctly in Jonas (USA) (Rev 1) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#881]
Software

![Capture](https://user-images.githubusercontent.com/68873449/102891766-e3b3a200-44b2-11eb-9b09-bc0251528b70.PNG)

OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/102891796-edd5a080-44b2-11eb-9357-c5beb39db936.PNG)

**Comment by poudink** [comment]
fixed in https://github.com/Arisotura/melonDS/commit/8a068c22947163d98b78645d5604efb20f6a3241
