### ISSUE TITLE
Severe graphical issues in Wall-e

### ISSUE THREAD

**Issue by tomrow** [Arisotura/melonDS#884]
In Wall-e (E), the main screen 3D level is completely black and the sky is an almost-black shade of yellow.

**Comment by RSDuck** [comment]
does it only happen with the OpenGL renderer or is the software renderer affected as well?

**Comment by tomrow** [comment]
Both renderers have the issue. I can't take a screenshot at the moment since the SMB share I was using to load the ROM has shut down for the day, but I will post a screenshot tomorrow, along with a hash in case it's a bad dump.

**Comment by RSDuck** [comment]
interesting. Do you use the JIT or the interpreter?

**Comment by tomrow** [comment]
Its set to use JIT.

**Comment by RSDuck** [comment]
could you try to test if the issue persists with the interpreter once you get access to your ROMs again?

**Comment by tomrow** [comment]
Sure

**Comment by Arisotura** [comment]
couldn't reproduce with JIT either on or off

**Comment by tomrow** [comment]
Never mind, I dont need to wait, I forgot i could remotely wake it up
It seems to work for me now, perhaps it is a problem with the computer rather than the software?
Perhaps my other computer's integrated graphics is having issues
I'll close this now
