### ISSUE TITLE
[Feature Requests] "Recent" items list

### ISSUE THREAD

**Issue by LOuroboros** [Arisotura/melonDS#887]
Title.

It would be nice if MelonDS had a list of recently opened ROMs like other emulators usually have. Having to File>Open or drag-and-drop all the time is a bit annoying.

**Comment by abcdjdj** [comment]
Should be fixed by #918. I have tested it thoroughly but please do give it a try and let me know if you discover any issues. Cheers.

**Comment by LOuroboros** [comment]
> 
> 
> Should be fixed by #918. I have tested it thoroughly but please do give it a try and let me know if you discover any issues. Cheers.

I gave it a quick test and it seems to work nicely! Thank you very much!
