### ISSUE TITLE
[Feature Request] Fast Forward Toggle

### ISSUE THREAD

**Issue by LOuroboros** [Arisotura/melonDS#889]
I'd like to see implemented at some point a hotkey that would let you enable or disable the Fast Forward at will with the single press of a button like other emulators allow you to.

**Comment by WaluigiWare64** [comment]
I think there is a Fast Forward Toggle.

**Comment by WaluigiWare64** [comment]
It does exist - [source](https://www.github.com/Arisotura/melonDS/tree/master/src%2Ffrontend%2Fqt_sdl%2FPlatformConfig.cpp).
This issue can be closed.

**Comment by LOuroboros** [comment]
> 
> 
> It does exist - [source](https://github.com/Arisotura/melonDS/blob/0f353e0d5f0345c40756fc7e2cdd206bf2f53d1a/src/frontend/qt_sdl/PlatformConfig.cpp#L112).
> This issue can be closed.

There isn't a way to configure it in the Input Settings window though, unless I'm missing something.

![Untitled2358](https://user-images.githubusercontent.com/4485172/103027546-d5a66580-4534-11eb-92e8-2de9fa6cbb7b.png)
![Untitled2359](https://user-images.githubusercontent.com/4485172/103027547-d6d79280-4534-11eb-839c-4128c231d36a.png)
![Untitled2360](https://user-images.githubusercontent.com/4485172/103027548-d7702900-4534-11eb-8355-77a60a8d8d9d.png)

The entry for Fast Forward present there is the one that forces you to hold down a button.

**Comment by LOuroboros** [comment]
Perhaps I wasn't specific enough originally. Should I change the title of the issue to better reflect that my suggestion comes from a user and for other users' sake?
In any case, I apologize if I made a mistake here :eyes:

**Comment by WaluigiWare64** [comment]
I think it may be the Toggle FPS Limit hotkey.
Test it out and see if it does the job.

**Comment by LOuroboros** [comment]
> 
> 
> I think it may be the Toggle FPS Limit hotkey.
> Test it out and see if it does the job.

I tested it before opening the issue. I didn't notice any changes myself, even while holding down the Fast Forward button.

**Comment by WaluigiWare64** [comment]
The fast forward hotkey is apparently broken. A PR exists to fix the issue.

**Comment by RSDuck** [comment]
could it be possible that you still have Audio Sync enabled while using the fast forward toggle?

**Comment by LOuroboros** [comment]
> 
> 
> could it be possible that you still have Audio Sync enabled while using the fast forward toggle?

> 
> 
> could it be possible that you still have Audio Sync enabled while using the fast forward toggle?

Oh, I completely forgot about it. Yes, I did have Audio Sync enabled. Now it makes perfect sense why the Toggle FPS Limit option wasn't working. Although the Fast Forward-by-holding-a-key feature was.

Anyway, thank you very much and sorry for the troubles!

**Comment by poudink** [comment]
I don't think this should be closed. I think the toggle should disable audio sync.

**Comment by RSDuck** [comment]
audio sync is pretty useless, it can probably be removed
