### ISSUE TITLE
Part of the menu doesn't render in Girls Only (USA) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#891]
Software

![Capture](https://user-images.githubusercontent.com/68873449/103060330-e1109400-45fb-11eb-8f28-539222320c56.PNG)

OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/103060344-e8d03880-45fb-11eb-9852-4d8a284c1654.PNG)

**Comment by poudink** [comment]
fixed in https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344
