### ISSUE TITLE
Multiple graphical issues in Cocoto - Kart Racer (USA) (En,Fr,Es) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#894]
The starting line banner doesn't render properly.

Software

![Capture2](https://user-images.githubusercontent.com/68873449/103076362-ac173800-4621-11eb-933e-dc1e430caf21.PNG)

OpenGL

![Capture](https://user-images.githubusercontent.com/68873449/103076375-b2a5af80-4621-11eb-9742-3612d2885565.PNG)

Items on the track don't render properly.

Software

![Capture3](https://user-images.githubusercontent.com/68873449/103076399-c0f3cb80-4621-11eb-95ea-85c1129149a3.PNG)

OpenGL

![Capture4](https://user-images.githubusercontent.com/68873449/103076406-c6e9ac80-4621-11eb-8535-96fd71c7fa56.PNG)

**Comment by poudink** [comment]
https://github.com/Arisotura/melonDS/commit/8a068c22947163d98b78645d5604efb20f6a3241 fixed the starting line banner and https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344 fixed the items.
