### ISSUE TITLE
Text doesn't render properly in The Croods - Prehistoric Party! (USA) (En,Fr,Es) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#895]
Software

![Capture2](https://user-images.githubusercontent.com/68873449/103079502-14691800-4628-11eb-95dc-483042496763.PNG)

OpenGL

![Capture](https://user-images.githubusercontent.com/68873449/103079514-1a5ef900-4628-11eb-94f3-da2c1fae8631.PNG)

**Comment by poudink** [comment]
fixed in https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344
