### ISSUE TITLE
Input for numpad stopped working

### ISSUE THREAD

**Issue by Go-Merk** [Arisotura/melonDS#896]
It seems that melonDS has no support for numerical keyboard anymore? I'm very sure that it worked prior 0.9. I'm just asking to be sure if this was intentional or accidental. 😅 

Great Work on the emulator btw, it is the best available.

**Comment by WaluigiWare64** [comment]
It was fixed, it will work in the next release.

**Comment by WaluigiWare64** [comment]
melonDS 0.9.1 has been released!
This issue is now resolved.
Let us know if you still are experiencing issues.

**Comment by Go-Merk** [comment]
Nop, no issues, it is perfect now, this can be closed. :)
