### ISSUE TITLE
Wheels don't render on the firetruck when it's in the garage in Jake Power - Fireman (USA) (En,Fr,Es) with OpenGL

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#905]
Software

![Capture](https://user-images.githubusercontent.com/68873449/103148806-a8b5b500-47b7-11eb-8241-a3d324febba3.PNG)

OpenGL

![Capture2](https://user-images.githubusercontent.com/68873449/103148808-aeab9600-47b7-11eb-994b-b04ed2848922.PNG)

**Comment by poudink** [comment]
Fixed by https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344.
