### ISSUE TITLE
De-emphasized screen size inconsistent between fullscreen and windowed.

### ISSUE THREAD

**Issue by Nixel1324** [Arisotura/melonDS#906]
In windowed, the non-emphasized screen will be the largest size that still fits, but in the new fullscreen mode it's always 1x internal resolution.
This happens with either screen emphasized, including emphasis auto. Even screen sizing works fine.

EDIT: This doesn't happen when "Force integer scaling" is deselected.

Windowed:
![Windowed](https://user-images.githubusercontent.com/39053484/103155543-3afe8e80-47a1-11eb-868b-5c62f0933306.png)

Fullscreen:
![Fullscreen](https://user-images.githubusercontent.com/39053484/103155546-4487f680-47a1-11eb-82cd-fc1299e20748.png)

**Comment by RSDuck** [comment]
I can't reproduce

**Comment by Nixel1324** [comment]
I kinda forgot about this (I've been playing with "even" screen sizing), but this still happens for me on 9.2.
