### ISSUE TITLE
Final Fantasy 4 Heroes of Light OpenGL Graphics Broken

### ISSUE THREAD

**Issue by Peduls** [Arisotura/melonDS#907]
The shadows and floor in some areas of Final Fantasy 4 Heroes of Light appear very broken. Only happens in OpenGL.

Software
![Software](https://user-images.githubusercontent.com/34750422/103159092-7047b400-4782-11eb-84b3-40c9ae2a8da7.PNG)

OpenGL
![OpenGL](https://user-images.githubusercontent.com/34750422/103159094-776ec200-4782-11eb-9994-420d6cd7d724.PNG)

**Comment by Peduls** [comment]
Forgot to mention this issue first showed up in 0.9.1

**Comment by RSDuck** [comment]
seems to broken since https://github.com/Arisotura/melonDS/commit/aac843c7deddae52ce46275f8c828bcac42b4693

**Comment by RSDuck** [comment]
fixed in https://github.com/Arisotura/melonDS/commit/8a068c22947163d98b78645d5604efb20f6a3241
