### ISSUE TITLE
Dr. Mario Express (USA) errors as soon as it starts

### ISSUE THREAD

**Issue by Tiberius1437** [Arisotura/melonDS#917]
First of all MelonDS doesn't even recognize it as a dsi ROM. I have to set it to "any file"

![Capture](https://user-images.githubusercontent.com/68873449/103351559-ba6cc480-4af7-11eb-907f-d61c492b3e3f.PNG)

![Capture2](https://user-images.githubusercontent.com/68873449/103351565-c193d280-4af7-11eb-8642-6050b63afb40.PNG)

The menu recognizes the rom

![Capture3](https://user-images.githubusercontent.com/68873449/103351581-d07a8500-4af7-11eb-9a6a-30c0b56620d7.PNG)

But it crashes right after I start it.

![Capture4](https://user-images.githubusercontent.com/68873449/103351615-dff9ce00-4af7-11eb-802a-065430989d8d.PNG)

**Comment by WaluigiWare64** [comment]
The ROM has to be installed on the NAND as it is a DSiWare, or you can run it through TWiLight Menu++ or Unlaunch.

**Comment by Tiberius1437** [comment]
>The ROM has to be installed on the NAND
How do I do that?

**Comment by WaluigiWare64** [comment]
You can do the alternative I mentioned.

**Comment by Tiberius1437** [comment]
Can you walk me through the process? How do I use TWiLight Menu++ to play dsi games in MelonDS?

**Comment by WaluigiWare64** [comment]
Follow [the DSi CFW Guide](https://dsi.cfw.guide).
You can configure the SD card in melonDS by using a FAT image.

**Comment by Tiberius1437** [comment]
What a ridiculous and arduous process. I'll just take this to mean MelonDS can't play dsi games.

**Comment by WaluigiWare64** [comment]
You can't run DSiWare through the cart slot anyway since it tries to load in stuff from the NAND.
We are just being hardware accurate.
