### ISSUE TITLE
I think that a pixel line is misplaced on the horizontal screen layout

### ISSUE THREAD

**Issue by LOuroboros** [Arisotura/melonDS#920]
Title.
I noticed there was something going on as I was playing Pokémon Ranger Shadows of Almia, but I understood what it was just now due to the colors of it that seem to complement the content of the other screen.
There's a line of pixels that is left behind on the first screen of the emulated Nintendo DS when you set the screen layout to horizontal. That's what I think it's happening, at least. Look at these 2 pics, mainly the second one:
![Untitled2562](https://user-images.githubusercontent.com/4485172/103450948-87176a80-4c9c-11eb-97a6-5ab1f3a515bd.png)
![Untitled2563](https://user-images.githubusercontent.com/4485172/103450949-88489780-4c9c-11eb-89d9-f842f2f3d91e.png)

I marked it with a circle to make it easier to spot.

**Comment by RSDuck** [comment]
Do you use the OpenGL display option or the OGL renderer?

That looks like texture bleeding. We need to enable clamp to edge for the screen texture.

**Comment by LOuroboros** [comment]
> 
> 
> Do you use the OpenGL display option or the OGL renderer?
> 
> That looks like texture bleeding. We need to enable clamp to edge for the screen texture.

Oh, I do. I had the OGL Display option enabled. Disabling it seemingly solved the problem.

Should I leave this issue opened? :eyes:

**Comment by RSDuck** [comment]
yes, as it still happens with it enabled. It's an easy fix I'll do it right away.

**Comment by LOuroboros** [comment]
I know this is a bit late, but thank you for fixing this!
I was tired yesterday, but now I'm noticing that without using the OGL Driver there's screen tearing happening, so I'm glad the next release of the emulator will have the problem addressed!

**Comment by WaluigiWare64** [comment]
Yep.
You can test it out by trying the builds on the CI, which are the latest builds from master.
