### ISSUE TITLE
Cant open melonds 0.9.1

### ISSUE THREAD

**Issue by Algamerthetruealbanian** [Arisotura/melonDS#927]
As said previus version where usabel on linux ex 0.9
i cant run this version as an executabel as its a shared library 
can anyone help me open this version

**Comment by WaluigiWare64** [comment]
What error do you get upon launch?

**Comment by nadiaholmquist** [comment]
For some reason the file manager in GNOME doesn't let you run PIE executables, instead i would suggest installing it from flatpak, you can see how in the blog post about 0.9.1.

**Comment by CatGreen90** [comment]
It's apparently an issue with libmagic and shared-mime-info misidentifying PIE executables as shared libraries: https://gitlab.freedesktop.org/xdg/shared-mime-info/-/issues/11

They should run if launched from the command line, though.

**Comment by Algamerthetruealbanian** [comment]
SOLVEd 
thnx to nadiaholquist for helping me out 
a question i have will that version be up to date with the github version?

**Comment by Algamerthetruealbanian** [comment]
SOLVEd 
thnx to nadiaholquist for helping me out 
a question i have will that version be up to date with the github version?

**Comment by WaluigiWare64** [comment]
Yep.
@nadiaholmquist maintains it herself.

**Comment by Algamerthetruealbanian** [comment]
thx for leeting me know

**Comment by Algamerthetruealbanian** [comment]
Probelm solved evryone thnx to evryone answering my questions

**Comment by nadiaholmquist** [comment]
Just to add, the initial issue you had should be fixed now as long as you have the latest updates installed.
