### ISSUE TITLE
Pokemon Diamond freezes after swapping between clocks on Pokétch

### ISSUE THREAD

**Issue by Ironcanon** [Arisotura/melonDS#928]
As title says when swapping between apps on the pokétch (the equivalent to C-gear for Diamond) when I swapped onto the analog clock the game freezes.

![PokemonCrash](https://user-images.githubusercontent.com/24834993/103679724-e1127b80-4f8d-11eb-8f52-39cba496313d.png)

After testing it seems that the game freezes when viewing the the second clock in the same run (you can view either clock perfectly fine but when swapping to the other clock the game freezes). As the clocks aren't 'next' to each other (you can't go from one clock straight to another) you can save and reload the game in-between the clocks to access the rest of the pokétch apps.

Unfortunately I'm quite far into the game and so I'm not sure when this started to occur but obviously the user would have to access both clocks before it can happen.

**Comment by RSDuck** [comment]
can you give us a savefile?

**Comment by Ironcanon** [comment]
How would I be able to do that?

**Comment by RSDuck** [comment]
it doesn't crash for me. Cycling through the Poketch apps works fine.

**Comment by Ironcanon** [comment]
Weird, anything you suggest I try settings wise?

**Comment by RSDuck** [comment]
ah I didn't try it with JIT enabled, I got the crash now too ;)
