### ISSUE TITLE
Metal Max 2 Reloaded Open GL issue

### ISSUE THREAD

**Issue by MetalFan1988** [Arisotura/melonDS#929]
Some objects are not shown in the scenarios using OpenGl in software rendering works very well. If it could be fixed it would be wonderful.:)
![Captura de pantalla (158)](https://user-images.githubusercontent.com/29298680/103975705-d1886380-5142-11eb-983b-f4ee9b6770fe.png)

![Captura de pantalla (159)](https://user-images.githubusercontent.com/29298680/103975756-f2e94f80-5142-11eb-958e-c36bd131633d.png)

**Comment by poudink** [comment]
https://github.com/Arisotura/melonDS/commit/8a3a8b7c684996d2ea72a95e5abd62b1e763f344 seems to have fixed this.
