### ISSUE TITLE
Pokemon Black Poké Transfer Lab Softlock

### ISSUE THREAD

**Issue by KostaSaizo7** [Arisotura/melonDS#931]
In Pokemon Black, I tried to use the [Poké Transfer](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9_Transfer) feature (where you transfer Pokemon from a Gen4 game to a Gen5 game) and I found a softlock in version 0.9.1.  I remembered that I have tried this in the past and I could successfully connect 2 instances of melonDS and that softock never happened. So I tried version 0.4 and this doesn't happen. After you talk to a character and save the game in the Poké Transfer Lab, the game transitions to the screen below .

melonDS 0.4
![2](https://user-images.githubusercontent.com/39852873/104043699-daca0c80-51e4-11eb-9da8-fee1e95f1d6a.jpg)

But in version 0.9.1 the games gets stuck, the message doesn't show up in the bottom screen and you can't go back. 

![1](https://user-images.githubusercontent.com/39852873/104044206-a440c180-51e5-11eb-9df5-356af73a644b.jpg)

I have tried enabling and disabling various settings (frame limiter, audio sync, jit recompiler) but the game always softlocks.

**Comment by RSDuck** [comment]
If you want to help further figuring this regression, you can try finding out which version broke it. Also can you give us a savefile to reproduce the issue?

**Comment by RSDuck** [comment]
ah before I forget it, do you have mac randomisation enabled?

**Comment by KostaSaizo7** [comment]
Yes it is enabled. But I should clarify that this also happens with just one melonds instance, so I think mac randomisation is irrelevant.

**Comment by KostaSaizo7** [comment]
Well, that was faster than I expected. The lock doesn't happen in version 0.9 so I guess the regression happened in 0.9.1. I have also DM you a save file through the forum. I hope it helps.
![3](https://user-images.githubusercontent.com/39852873/104055794-030f3680-51f8-11eb-9537-5f0437750e13.jpg)

**Comment by RSDuck** [comment]
thank you for the savefile. Weirdly it seems to work fine in debug builds, which points into the direction of some kind of undefined behaviour. Tomorrow I'll look into it with ubsan and asan.
