### ISSUE TITLE
[FEATURE REQUEST] Hide mouse cursor when not in use.

### ISSUE THREAD

**Issue by Metamoran** [Arisotura/melonDS#935]
Can we have a toggleable option to choose between (current) **'Mouse cursor always visible'** and **'Auto-hide mouse cursor after X seconds of mouse inactivity'** behaviour, please? Thanks.

**Comment by WaluigiWare64** [comment]
Added in https://github.com/Arisotura/melonDS/commit/bf0ea26596251d3a1af536b8dfe5f9c9d98d0cd9
