### ISSUE TITLE
Frequent Save File corruption on Shiren the Wanderer

### ISSUE THREAD

**Issue by AlexWongF** [Arisotura/melonDS#940]
I have been playing Shiren the Wanderer ( Mystery Dungeon Series ) on melonDS and it seems that my save file frequently gets corrupted and I lose all progress. I don't know why this is happening.

I used melonDS 0.9.1 for Windows x64

**Comment by RSDuck** [comment]
hm, maybe the save type in your data base in wrong. Could you tell us the size of the savefile?

**Comment by AlexWongF** [comment]
![image](https://user-images.githubusercontent.com/6776230/104477921-70c4b500-55a0-11eb-9774-8cf46e0e45ca.png)

**Comment by RSDuck** [comment]
https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=2154

that seems to be the right size

**Comment by AlexWongF** [comment]
I am using the USA Version.

**Comment by AlexWongF** [comment]
I would be thankful if someone could test if it's something that only happens on my end or something.
Maybe I am using a bad firmware, I don't know, I changed some wi-fi settings since the game has a rescue connect thing.

My save got corrupted at least 4-5 times on around 5-6 hours of gameplay.

**Comment by AlexWongF** [comment]
I was playing on another emulator and the save got corrupted too. I think it's because of the rom.

**Comment by AlexWongF** [comment]
Sorry about this issue, I discovered the reason, this game doesn't like if you turn it off while not on the main menu and corrupts your save on purpose so you don't try to cheat death.

**Comment by RSDuck** [comment]
great you got this resolved, don't worry, maybe it will help somebody else.
