### ISSUE TITLE
Recent macOS build dynamically links to libslirp without including it.

### ISSUE THREAD

**Issue by emctague** [Arisotura/melonDS#945]
The macOS build for v0.9.1 looks for a copy of libslirp *already installed* on the user's system under /usr/local/opt.... rather than statically linking to it or including a dylib in the app. This means users downloading melonDS builds for macOS from the website will most likely not be able to run it unless they happen to have libslirp installed for some reason - and depending on their level of technical understanding they might not know that they can fix that by installing the package via homebrew.

Could you consider making the macOS app builds statically link or include a copy of the library?

**Comment by WaluigiWare64** [comment]
Yep we know this - I couldn't find a way to bundle the libraries for a macOS version less than it was building on. For example, if I built on macOS 10.15, someone with macOS 10.13 couldn't load the app.
Regarding non technical users not understanding how to install the libraries, melonDS now has a Homebrew Cask package. We are planning to add this to the Downloads page.

**Comment by emctague** [comment]
Awesome, sorry to make a redundant issue, then!
