### ISSUE TITLE
Unlaunch complains about low battery and refuses to save settings

### ISSUE THREAD

**Issue by windwakr** [Arisotura/melonDS#956]
If you have Unlaunch installed and make a change in the settings and press save, it gives this error about the battery being low. JIT on/off makes no difference.
![unlaunchsettings](https://user-images.githubusercontent.com/284886/105401904-b3b40780-5bf4-11eb-9267-d8331876ddff.png)

**Comment by Arisotura** [comment]
try with latest revisions? the battery level register used to be erroneously set to 0x83, but it's been changed to 0x8F a while ago

**Comment by windwakr** [comment]
Sorry, I should have mentioned but that was tested with the latest master as of today.

**Comment by Arisotura** [comment]
o. then I need to look deeper into this.

I think I have a unlaunch'd NAND laying around. how do you get to the settings menu?

**Comment by windwakr** [comment]
If it's not booting up directly into the unlaunch menu for you, I think you can hold a+b while booting to get to it. Then just choose options.

**Comment by Arisotura** [comment]
tried that, it always takes me to the DSi menu regardless... I'll look into it.

**Comment by Arisotura** [comment]
I just gave this a try on latest revision and it's working fine
