### ISSUE TITLE
Mario Kart DS doesn't crash when turning on the spot on Luigi's Mansion steps

### ISSUE THREAD

**Issue by mariomadproductions** [Arisotura/melonDS#96]
On a real console (any) with _Mario Kart DS (Europe)_ (and maybe other versions), if you turn on the spot on the Luigi's Mansion entrance stairs the game crashes (the graphics stop changing and the sound repeats itself). This doesn't happen in melonDS - the game acts like you turned on the spot on any other slope in the game. You can quickly get reproduce the glitch by doing the following: select Time Trials -> [choose character/kart] -> Mushroom Cup -> Luigi's Mansion -> [drive forward to the steps in front of the mansion] -> [press A+B and turn]

**Comment by StapleButter** [comment]
er https://github.com/StapleButter/melonDS/issues/81

so, does it crash, or does it not crash?

anyway, the lack of crash might be because the MPU isn't emulated

**Comment by mariomadproductions** [comment]
It doesn't crash with melonds, and that is inaccurate, because it crashes on console

**Comment by StapleButter** [comment]
does it crash in desmume or NO$GBA?

**Comment by mariomadproductions** [comment]
No.

**Comment by Nadia-h** [comment]
Can't seem to reproduce this on real hardware with the European version of Mario Kart DS.

Could you upload a video of this happening?

**Comment by mariomadproductions** [comment]
I will, but first - are you holding A+B and pressing left or right on the d-pad? I did it on the Time Trial, but I think it works in other modes.

**Comment by Brian151** [comment]
If I may just say, LOL!
Usually bug reports are BECAUSE something crashed, not because it WORKED

lol

sry if it seems an inappropriate place to say that!

**Comment by mariogamer2** [comment]
@Brian151 emulator are designed to be bug compatible with the original system.

**Comment by Brian151** [comment]
I probably should've been more clear that I'm aware of said fact

I was just pointing-out a bug like this is rare, usually the goal is to reduce crashes, not intentionally cause one.

**Comment by Nadia-h** [comment]
Tried again holding A+B on the stairs to turn, the game does indeed crash when doing that.

**Comment by Gericom** [comment]
I confirmed on IS-NITRO that it's a data abort (reading from 0). Which is invoked by the pu (memory protection unit). It seems to be related to some sound that does not exist or something, but I'm not entirely sure why it doesn't crash on nds-bootstrap.

Anyway, this is probably something that would be much slower to emulate, but still would be a nice feature if you could enable it.

**Comment by JMC47** [comment]
Could we please get better steps toward reproducing this?  This is absolutely the kind of issue that I love to harp on.

**Comment by mariomadproductions** [comment]
> Could we please get better steps toward reproducing this? This is absolutely the kind of issue that I love to harp on.

I've updated the first post with more detailed instructions.

**Comment by Arisotura** [comment]
so this is the first case of 'needs PU emulation', I guess

**Comment by mariomadproductions** [comment]
As the [blogpost](https://melonds.kuribo64.net/comments.php?id=158) says, this was fixed in v0.9.4.
