### ISSUE TITLE
[Feature Request] Toggle to hide menu bar

### ISSUE THREAD

**Issue by phallusferrus** [Arisotura/melonDS#961]
It would be nice if the menu bar along the top could be hidden by a hotkey or a right-click menu alternative of some kind were added

**Comment by WaluigiWare64** [comment]
There is a fullscreen option, but no option to hide the menu bar. Config -> Input and Hotkeys -> General Hotkeys.
This is a duplicate of #417.

**Comment by phallusferrus** [comment]
Duplicate of #417
