### ISSUE TITLE
Bugged Nintendo Wifi Menu

### ISSUE THREAD

**Issue by shaz01** [Arisotura/melonDS#966]
https://imgur.com/DGitgFP

Can reproduce it on every try I do. 
Reproduced on M1 Apple Silicon Mac mini. MacOS 11.1. Compiled from source code

**Comment by WaluigiWare64** [comment]
I think this is issue #944 .
Also, I'm still working on ARM64 Mac support, and there are still some issues to address.

**Comment by WaluigiWare64** [comment]
@shaz01, could you try building off latest master?

**Comment by shaz01** [comment]
@WaluigiWare64 It's working perfectly. Thanks for your hard work!

**Comment by WaluigiWare64** [comment]
> @WaluigiWare64 It's working perfectly. Thanks for your hard work! 

It was actually @RSDuck who fixed this.
