### ISSUE TITLE
Regression: Screen flickering and output freezing.

### ISSUE THREAD

**Issue by nathanielcwm** [Arisotura/melonDS#971]
On b75b3f6, not present on 0.9.1
OpenGL with 10x and improved polygon splitting enabled.
Flickering is also present on firmware and flickering has the exact same behavior:
Bottom right corner of screen goes black in a backwards L shape.

I'll attach a video later.

**Comment by RSDuck** [comment]
I could reproduce the issue and and https://github.com/Arisotura/melonDS/commit/a3f4aaf50314f6ab528afb8dbcef88cfb012e765 fixed it for me. Since this is… well the weird the kind of issue, can you tell me whether it worked for you too?

**Comment by nathanielcwm** [comment]
Seems to greatly reduce the issue but I still got the issue on the firmware.

**Comment by nathanielcwm** [comment]
Oh ye forgot to mention that occasionally when the issue presents itself the screen becomes frozen but sounds still seem to work fine.

**Comment by nathanielcwm** [comment]
I think i've narrowed the commit that lead to this regression down to b78bc4c. @RSDuck

**Comment by RSDuck** [comment]
yes I know. Though the issue seems to lie somewhere deeper, that commit only brought it to day light.

**Comment by RSDuck** [comment]
can you try again with the latest revision?

**Comment by nathanielcwm** [comment]
Yep fixes this issue. Doesn't fix #972
