### ISSUE TITLE
Regression: blank screen after stopping the emulator on OpenGL renderer

### ISSUE THREAD

**Issue by gal20** [Arisotura/melonDS#972]
Bug introduced in b78bc4cb66d29019119349ef31cb4cbadf870cfe.
When stopping the emulator using the OpenGL renderer, the entire window turns black, including the menu bar, and never recovers. The emulator is still responsive and can load roms, but the screen will stay completely blank for the rest of the run
![melon2](https://user-images.githubusercontent.com/71563441/106040537-47993e00-60e3-11eb-9757-48da3b7433c2.png)

**Comment by RSDuck** [comment]
this is related to #971

there seems to be something seriously wrong. Though I have no idea what it could be. First of all we have a lot of glFlush calls in the code, which seem to be necessary (which as far as I know shouldn't be the case). Then also things work perfectly fine once you add glFinish in certain places or use RenderDoc to debug the issues. I also encountered some other weird behaviour while implementing https://github.com/Arisotura/melonDS/commit/b78bc4cb66d29019119349ef31cb4cbadf870cfe . Clears just didn't want to work, except with glFinish or RenderDoc…

It sounds like some kind of race condition, but that's also only a guess.

**Comment by RSDuck** [comment]
https://github.com/Arisotura/melonDS/commit/a3f4aaf50314f6ab528afb8dbcef88cfb012e765 fixed https://github.com/Arisotura/melonDS/issues/971 for me which was introduced with the same commit. Did the last commit fix this issue for you?

**Comment by gal20** [comment]
Issue still exists in a3f4aaf50314f6ab528afb8dbcef88cfb012e765

**Comment by WaluigiWare64** [comment]
I experience the same issue in Windows.
The menu bar also goes black.

**Comment by RSDuck** [comment]
can you try again

**Comment by nathanielcwm** [comment]
Still experience this specific issue on 40aae154cf77e0611057a05702f28d9cf17b08f4.

When the emulator is stopped then restarted output is completely frozen and menu bar also becomes frozen.
But on Windows the menu can still be used despite being frozen, this explanation is bad so imma just put a screenshot.

![image](https://user-images.githubusercontent.com/22572406/106617865-f1783f00-65a9-11eb-97ad-e45a8c64b735.png)

**Comment by WaluigiWare64** [comment]
@nathanielcwm this is odd, the menu bar hides for me (i can still interact with it).

**Comment by RSDuck** [comment]
how is it now?

**Comment by nathanielcwm** [comment]
That commit seems to fix it for me.

Also fixes #981

**Comment by WaluigiWare64** [comment]
Can we close this?

**Comment by gal20** [comment]
Looks like 40aae154cf77e0611057a05702f28d9cf17b08f4 fixes this. Not sure if 2e999ae1b8e88e41fce3b2289372b44344cc79b0 was necessary.

**Comment by nathanielcwm** [comment]
hmm I now keep on experiencing random freezing and crashes
so the issue might not have been entirely fixed.

**Comment by RSDuck** [comment]
> 
> 
> hmm I now keep on experiencing random freezing and crashes
> so the issue might not have been entirely fixed.
> 
> ```
> - <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
> - <System>
>   <Provider Name="Application Hang" /> 
>   <EventID Qualifiers="0">1002</EventID> 
>   <Version>0</Version> 
>   <Level>2</Level> 
>   <Task>101</Task> 
>   <Opcode>0</Opcode> 
>   <Keywords>0x80000000000000</Keywords> 
>   <TimeCreated SystemTime="2021-02-04T11:24:31.1281763Z" /> 
>   <EventRecordID>1687195</EventRecordID> 
>   <Correlation /> 
>   <Execution ProcessID="0" ThreadID="0" /> 
>   <Channel>Application</Channel> 
>   <Computer>LAPTOP-N0VH03O2</Computer> 
>   <Security /> 
>   </System>
> - <EventData>
>   <Data>melonDS.exe</Data> 
>   <Data>0.9.1.0</Data> 
>   <Data>43a4</Data> 
>   <Data>01d6fae68a23f455</Data> 
>   <Data>4294967295</Data> 
>   <Data>C:\Users\nat-tigerlake\Documents\Emulators\Programs\Melon DS\melonDS.exe</Data> 
>   <Data>161d5e99-b538-4991-b756-ad6ea8ca844c</Data> 
>   <Data /> 
>   <Data /> 
>   <Data>Unknown</Data> 
>   <Binary>55006E006B006E006F0077006E0000000000</Binary> 
>   </EventData>
>   </Event>```
> 
> Not rlly sure how to accurately reproduce the issue as of right now tho...
> ```

with OpenGL or software?

**Comment by nathanielcwm** [comment]
opengl no crashing with software

**Comment by RSDuck** [comment]
ok great atleast it works with sw

**Comment by nathanielcwm** [comment]
@RSDuck so it seems like it doesn't crash with opengl display in software mode too

I believe it's hardware dependent as it only seems to crash on my laptop so here's the specs:
i5-1135g7 running on iGPU.

Something about the opengl mode after the fixes seems to conflict with the driver of my iGPU as a driver crash always accompanies the crashing that I was experiencing, it doesn't crash in stress tests or benchmarks so I think it's unlikely that my actual hardware is faulty however... Sorry for not mentioning this as I wanted to confirm with stress tests and benchmarks first before writing about it.

I did not experience any of this crashing before b78bc4c

**Comment by nathanielcwm** [comment]
```Source
DS emulator, sorta. also 1st quality melon.

Summary
Stopped working

Date
‎4/‎2/‎2021 6:24 pm

Status
Report sent

Description
Faulting Application Path:	C:\Users\nat-tigerlake\Documents\Emulators\Programs\Melon DS\melonDS.exe

Problem signature
Problem Event Name:	BEX64
Application Name:	melonDS.exe
Application Version:	0.9.1.0
Application Timestamp:	601ad07c
Fault Module Name:	StackHash_1b28
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	00000000
Exception Offset:	PCH_A8_FROM_ntdll+0x000000000009CB04
Exception Code:	c0000005
Exception Data:	0000000000000008
OS Version:	10.0.19042.2.0.0.256.161
Locale ID:	18441
Additional Information 1:	1b28
Additional Information 2:	1b285f915f4c0d2d38392026b4cfb083
Additional Information 3:	2ab3
Additional Information 4:	2ab3e5e1cff8ab67e96d6473bb970a87

Extra information about the problem
Bucket ID:	6c1cb8770ecab8b9c5744c2d65f84f67 (1545944329962934119)
```

Here's another error log from reliability monitor
looks like the other crash entries got wiped

**Comment by nathanielcwm** [comment]
hmmm @RSDuck with 6256a42e0099cef9f567148083c55bbb798d8184 I can't even use melonDS with software anymore...
either crashes immediately on firmware bootup or it freezes on a white screen with no audio anymore too.
![image](https://user-images.githubusercontent.com/22572406/107424952-43483880-6b59-11eb-9230-e3200951ebfc.png)

**Comment by RSDuck** [comment]
@nathanielcwm that's probably #994

**Comment by nathanielcwm** [comment]
oh yep on d63f797 issue is no longer present
