### ISSUE TITLE
glitch in "Fushigi no Dungeon - Fuurai no Shiren DS 2 - Sabaku no Majou (J)"

### ISSUE THREAD

**Issue by harlayzhou** [Arisotura/melonDS#978]
both in software and opengl.

![Fushigi no Dungeon - Fuurai no Shiren DS](https://user-images.githubusercontent.com/8403754/106602542-1cf22e00-6598-11eb-953c-e9fefef51f7d.jpg)

**Comment by RSDuck** [comment]
how do I get to this title screen? I only get a different one where it's day not night.

**Comment by harlayzhou** [comment]
1. run the game
2. dont push any button or just fast forward
3. until the logo shows.

**Comment by RSDuck** [comment]
I did just that. Could it be possible that you need to advance in the game to get that title screen?

**Comment by harlayzhou** [comment]
I'm sure, not in game.
PS: It's correct in Desmume.

**Comment by RSDuck** [comment]
![grafik](https://user-images.githubusercontent.com/9352526/106618371-accfb200-656f-11eb-8a36-11aa579399e3.png)
this is the screen I'm getting

**Comment by harlayzhou** [comment]
I know, it's according to the system time.
just set you pc time to night.

**Comment by RSDuck** [comment]
well that would have been helpful to know from the start
