### ISSUE TITLE
Please, I beg you, add "LCD SWAP" Hotkey like exist in Desmume

### ISSUE THREAD

**Issue by FabioManoel1977** [Arisotura/melonDS#980]
Sorry bad english

For some unknown reason, OBS can capture nicely the gameplay of  melonDS but can not capture screen of Desmume, then I gave up about Desmume and begin to use melonDS, however, the feature that exist in Desmume that is awesome is the fact that we can choose a key on our gamepad to change (swap) the lcd screen of botton to top and vice versa, but, melonDS lacks this feature. Is terrible to play without this feature, specially because I like to play one BIG screen one LCD and put the other LCD a small screen, like the screenshot:

![2021-02-02 10_45_37- 60_60  melonDS 0 9 1](https://user-images.githubusercontent.com/41028393/106609000-db379800-6543-11eb-9e2f-ab62e5328186.jpg)

I beg you, add this feature in the next release

**Comment by RSDuck** [comment]
you don't need to beg

**Comment by troywweber7** [comment]
There's an option in the menu that says "toggle" or "hold". Does this mean this feature works now?

**Comment by Brankale** [comment]
In newer builds there's an option to Swap Screen "permanently" in the Screen Layout section but there's also a hotkey added with cd6859ef6f449f3f61db312addea9d656069736e, so I think this issue can be closed. The only thing is that this feature it's not included in a "stable" release yet.

**Comment by Codex-** [comment]
Checked this today, hotkey is assignable and works great

**Comment by FabioManoel1977** [comment]
Yes, thank you very much, it is working perfect fine. Desmume is now unnecessary and I already deleted it. thank you very much, melonDS develops.
