### ISSUE TITLE
OpenGL: OSD isn't displayed when in OpenGL

### ISSUE THREAD

**Issue by nathanielcwm** [Arisotura/melonDS#981]
Tested on 40aae154cf77e0611057a05702f28d9cf17b08f4 on Windows.

Behaviour not exhibited on software renderer.

Appears to be related to #972 as it's completely fine in ab222ab.

**Comment by RSDuck** [comment]
I can't reproduce

**Comment by RSDuck** [comment]
the weirdness continues…

**Comment by nathanielcwm** [comment]
Fixed by 2e999ae
