### ISSUE TITLE
[0.9.1] - Dragon Quest IX - OpenGL General Glitchness

### ISSUE THREAD

**Issue by MasterNaxum** [Arisotura/melonDS#987]
Regarding Dragon Quest IX: When using OpenGL Renderer instead of the Software Render, visual glitches such as the disapperance/flickering of some overworld textures are present, as well as some wrong rendering order for actors such as beds. The first noticeable instance of these issues happens at the Observatory while going up towards the world tree, with grass disappearing from the ledges as you walk by.

Even on x1 resolution the issue will still happen on the OpenGL Renderer.

**Comment by RSDuck** [comment]
did you try a build from latest revision? I'm sure there will still be some issues with the OpenGL renderer, but we recently fixed some regressions with it.

**Comment by MasterNaxum** [comment]
> did you try a build from latest revision? I'm sure there will still be some issues with the OpenGL renderer, but we recently fixed some regressions with it.

After a few days of personal troubles regarding msys2 packaging shenanigans I built it myself and confirmed that the opengl glitches are gone as of the latest revision.

**Comment by poudink** [comment]
you don't need to build it yourself. there are pre-built downloads in the actions tab.
