### ISSUE TITLE
Mic function doesn't work in melonDS

### ISSUE THREAD

**Issue by HilbertIdeals5** [Arisotura/melonDS#995]
I tried playing Pokémon White to test out the mic function, but it never works. I've set it to "External microphone" and "Blow noise", and neither make the Jigglypuff sing.

<img width="624" alt="Screen Shot 2021-02-07 at 5 05 59 PM" src="https://user-images.githubusercontent.com/63978875/107160874-eedd6700-6966-11eb-9286-81f822b1476e.png">

I'm using the melonDS 0.9 beta binary from here: http://melonds.kuribo64.net/comments.php?id=129

So there's two things:

1. Why isn't the microphone function working?
2. Will you be adding support for internal microphones anytime soon?

**Comment by Arisotura** [comment]
why are you using that beta? we released 0.9.1 a while ago.

**Comment by HilbertIdeals5** [comment]
I went back to 0.9 because on 0.9.1 for Mac, the top screen is always blank.

**Comment by WaluigiWare64** [comment]
Is this in DS mode or DSi mode?

**Comment by HilbertIdeals5** [comment]
This is DS mode.

**Comment by WaluigiWare64** [comment]
Could you try with the latest builds off GitHub? The graphical issues should be fixed.

To get them, you can go to the Readme and click the badge that says "macOS x86-64". You can then click the most recent commit in the list. Then, you can download the most recent build under "Artifacts".

**Comment by NicknineTheEagle** [comment]
I have the same issue on the latest build, tried different microphone options and none of them work. Mic test in DSi menu shows no reaction, too.

**Comment by WaluigiWare64** [comment]
> I have the same issue on the latest master build, tried different microphone options and none of them work. Mic test in DSi menu shows no reaction, too.

@NicknineTheEagle what platform are you on?

**Comment by NicknineTheEagle** [comment]
> 
> 
> > I have the same issue on the latest master build, tried different microphone options and none of them work. Mic test in DSi menu shows no reaction, too.
> 
> @NicknineTheEagle what platform are you on?

Windows.

**Comment by WaluigiWare64** [comment]
@NicknineTheEagle Microsphone isn't supported yet in DSi mode. Try using DS mode.

**Comment by NicknineTheEagle** [comment]
Okay, I've tested with the homebrew app (http://kuribo64.net/get.php?id=jZk9MPy4NUiyevy9) and it seems to be working. I guess I need to adjust my sound sample because the one I have doesn't seem to work in Ace Attorney.

**Comment by NicknineTheEagle** [comment]
I think melonDS is clamping input volume somehow because making the microphone sample ear splittingly loud doesn't make it sound loud on playback.
Ace Attorney is still not reacting to the sample even though I'm literally using Phoenix's voice clip ripped from the game files. Not sure if it's the game being picky or the sample being too quiet.

**Comment by RSDuck** [comment]
does the integrated blow noise really not work for you? It has been tested to work well in a lot of games.

**Comment by WaluigiWare64** [comment]
> does the integrated blow noise really not work for you? It has been tested to work well in a lot of games.

They seem to be using their own sample.

> I'm literally using Phoenix's voice clip ripped from the game files.

**Comment by RSDuck** [comment]
the game will likely just look out for any very loud sound (as in almost constantly reaching the peek) which the integrated blow sound provides.

**Comment by NicknineTheEagle** [comment]
@WaluigiWare64 @RSDuck Nope, no reaction to integrated blow noise.

**Comment by WaluigiWare64** [comment]
Could you test a different game?

**Comment by NicknineTheEagle** [comment]
Yes, I'm aware there's a hotkey and I am pressing it. As I said above, the microphone does work, it's clear from homebrew test app results, I think it's just this game being picky about the audio.

**Comment by WaluigiWare64** [comment]
@StLouisCPhT could you test it out natively and see if it's something to do with Rosetta 2?

**Comment by StLouisCPhT** [comment]
Might take a while. I don't think I have any games that use the mic

**Comment by StLouisCPhT** [comment]
Tested on Mario Party DS, Big Blowout. Doesn't work natively either.

**Comment by StLouisCPhT** [comment]
I can't believe I forgot about this:
Starting in macOS 10.14, applications have to specifically request access to the camera and microphone.

I tested this by starting melonDS in terminal (which already had been granted access to the mic) and playing Mario Party DS. The mic works fine.

**Comment by WaluigiWare64** [comment]
@HilbertIdeals5 could you try using the builds from GitHub actions?

**Comment by dylndreams** [comment]
> @NicknineTheEagle Microphone isn't supported yet in DSi mode. Try using DS mode.

will there be a time for it? i just wanna make flipnotes

**Comment by dylndreams** [comment]
have u tested? for me, the only thing it cant do is record sounds.

**Comment by Vinfinity-Gaming** [comment]
Flipnotes work all except for the audio. Mic isnt implemented in DSi mode (which i do darn well want it to be..)
