### ISSUE TITLE
Firmwares problems

### ISSUE THREAD

**Issue by Griffin260** [Arisotura/melonDS#997]
Hello, I'm actually using Retroarch app and I can't use the melonDS cuz it have problems with firmwares, specifically bio7.bin, bio9.bin & firmware.bin; Is there any possibility to solve this? Thank you very much in advance.

**Comment by WaluigiWare64** [comment]
You need to dump the bios and firmware files from your DS and then configure them in RetroArch,

**Comment by WaluigiWare64** [comment]
@Griffin260 did you get RetroArch to detect your firmware?
